### ISSUE TITLE
[Domino Visual Editor] Subform Support

### ISSUE THREAD

**Issue by JoelProminic** [Moonshine-IDE/Moonshine-IDE#1015]
We would like to add support for Subforms in the Form editor, so that blocks of form mockups can be shared between multiple forms.

UPDATE: 
Branch: features/issue_1015_subform_support
Bamboo Builds: https://static.moonshine-ide.com/downloads/releases/dev/macos/branches/features/issue_1015_subform_support
Test Databases available here:  https://static.moonshine-ide.com/downloads/releases/dev/macos/branches/features/issue_1015_subform_support/

**Comment by JoelProminic** [comment]
You can see an example of a subform with ODP with File > New > Domino On Disk Project:

`nsfs/nsf-moonshine/odp/Forms/Greeting.form`
```
<item name='$SubForms'><text>Footer</text></item>
<item name='$SubForm_RepIDs' sign='true'><text>0000000000000000</text></item>
```

`nsfs/nsf-moonshine/odp/SharedElements/Subforms/Footer.subform`
```
<?xml version='1.0' encoding='utf-8'?>
<note class='form' xmlns='http://www.lotus.com/dxl' version='9.0' maintenanceversion='1.10'
 replicaid='052585270065DAC7'>
<updatedby><name>...</name></updatedby>
<wassignedby><name>...</name></wassignedby>
<item name='$HTMLCode' sign='true'>
<rawitemdata type='1'>
X/8QAAIADwAHAAAAAAAAAA==
</rawitemdata></item>
<item name='$TITLE'><text>Footer</text></item>
<item name='$Comment' sign='true'><text/></item>
<item name='$Info' sign='true'>
<rawitemdata type='1'>
hhgBAIAAAAAAgAAAAQABAP///wAQAAAA
</rawitemdata></item>
<item name='$Flags'><text>CUAx3</text></item>
<item name='$DesignerVersion'><text>8.5.3</text></item>
<item name='$$ScriptName' summary='false' sign='true'><text>Footer</text></item>
<item name='$Body' sign='true'>
<rawitemdata type='1'>
gQKC/1oAAQAAAAAAAAAAAKAFAACgBQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAABAAAAAJSHAAAAAAAAAAAAAAAAAQAAAAQAAACDBAEAhf9XAAECAApUaGlzIGlzIGFu
IGV4YW1wbGUgZm9ybSBwcm92aWRlZCBpbiB0aGUgTW9vbnNoaW5lLUlERSBPbiBEaXNrIFByb2pl
Y3QgVGVtcGxhdGUuAA==
</rawitemdata></item></note>
```

I see a bunch of Base64-encoded binary data here that we would like to strip out (#1013)

**Comment by feather812002** [comment]
Hello, @JoelProminic 
I done some basic function for this task, 
Now , user can create a new form file into sub form list , then user can select it in other form .

![image](https://user-images.githubusercontent.com/8543391/182142579-8393e5a3-9de7-4dea-b0a1-7368836ad23c.png)

**Comment by JoelProminic** [comment]
I ran a test today with the latest changes on the main NSFConverter branch, and I am missing the subforms in the converted database:

   : Unable to access file:/Users/-user-/Downloads/xmlPrj_1982659315736852497/visualeditor-src/main/webapp/subforms

I confirmed that I was on the latest revision and that I built the code and reloaded the server, so I'm not seeing how it could be a problem on my side.   I ran out of time to debug this further today, so we can discuss it tomorrow.

**Comment by JoelProminic** [comment]
@feather812002, I created a new test database called [TestSubform.nsf](https://static.moonshine-ide.com/downloads/releases/dev/macos/branches/features/issue_1015_subform_support/TestSubform.nsf) to test nesting and other functionality in subforms.  This includes:
- Three levels of nested subforms
- Examples of each component time in subforms, along with other recently added properties

I did a test, and I found that the "TestSubformNesting" form worked properly.  However, the TestMultipleSubforms form is blank when I open it in Moonshine.  I don't see any column errors, and the .xml file seems to be populated.  Please take a look when you have a chance.

**Comment by JoelProminic** [comment]
I did some more testing with subfroms in the mockup editor, and I found some minor issues:
- Subform combobox should be sorted alphabetically
- "Example Subrom.subform" should be "Example Subform.subform".  Do we use this at all in the current database?  We didn't include the corresponding forms.  If not, we should exclude this completely to avoid confusion.
- The "New > Domino Visual Editor Sub Form" action in the File and right-click menu should use "Subform" instead of "Sub Form".  This should also be updated in the "New Domino Sub Form File" dialog header.

Otherwise, this seems to be working well.  We should be ready for a merge after we fix these issues.

**Comment by feather812002** [comment]
@JoelProminic 
I already fix these all small issue
Just except the second point , because ,I can't find the "Example Subrom.subfrom" from Moonshine-IDE and MockupVisualEditor.
I memory I add this file into NSFConvertProtal , rather than in the Moonshine-IDE
So, if I miss on this , and you find it on other same place,let  me know.

Now, I am testing it , if all work fine ,I will commit it in after some mins.

**Comment by JoelProminic** [comment]
I confirmed the menu actions were updated. This looks more consistent with the rest of the interface.

I confirmed the subform combobox is sorted now.

For `Example Subrom.subform", I do not see this file in FormBuilder (this has `footer.notimportant` instead) or Domino Visual Editor.  I see the example subform in three places in NSFConverterPortal, and I'd like to get these cleaned up:
- https://github.com/Moonshine-IDE/NSFConverterPortalProject/blob/main/nsf-converter-portal/src/main/resources/NsfConverterBlankProject/visualeditor-src/main/webapp/subforms/Example%20Subform.subfrom - this name is valid, but the file is empty
- https://github.com/Moonshine-IDE/NSFConverterPortalProject/blob/main/dxl-to-visual-editor-converter/src/main/resources/src_domino_nsfs/nsf-moonshine/odp/SharedElements/Subforms/Example%20sub%20form.subform - "sub form" should be "Subform"
- https://github.com/Moonshine-IDE/NSFConverterPortalProject/blob/main/nsf-converter-portal/src/main/resources/NsfConverterBlankProject/nsfs/nsf-moonshine/odp/SharedElements/Subforms/Example%20Subrom.subform - mispelled name - this is the case from above.

I would eventually like to refactor the embedded [NSFConverterPortalProject.zip](https://github.com/Moonshine-IDE/NSFConverterPortalProject/blob/main/nsf-converter-portal/src/main/resources/NsfConverterBlankProject.zip), but this may be a separate task.

**Comment by JoelProminic** [comment]
@JesseProminic did some tests today and reported that the nsfs/nsf-moonshine/odp/SharedElements/Subforms directory did not exist for new Domino Visual Editor projects.  If the user tries to create a subform, they get a popup with error:

![image](https://user-images.githubusercontent.com/24532731/186254344-87c3a2e8-7bd1-4cf7-bb23-63035f6ecb72.png)

We need to get this directory added automatically.  Some options:
- Add it to the Domino Visual Editor template.  This won't help for older Domino Visual Editor projects, though.
- Automatically create the directory when the New Subform prompt is opened.  This could trigger an error if the prompt is opened in a project that is not Domino Visual Editor, but this should not appen with the action filters.

If we do keep the prompt, we should change the prompt like this:

> Missing required folder:
> 
> %relative-or-full-path%

**Comment by JoelProminic** [comment]
We also need support for renaming subforms.  This will need to:
- rename the .subform file
- rename the corresponding .xml file.  Note the recent work in #1067
- update any subform components that reference this subform in .form or .subform files.

```
    : Error #1009
    : TypeError: Error #1009
    : 	at actionScripts.plugins.ui.editor::VisualEditorViewer/updateChangeStatus()
    : 	at actionScripts.ui.editor::BasicTextEditor/openHandler()
    : 	at actionScripts.plugins.ui.editor::VisualEditorViewer/openHandler()
    :
    : Click here to Report a Bug
```

**Comment by feather812002** [comment]
@Joel @JesseProminic 
I create a new Domino Visual project from :
File->New->Visual Edtior Project
and select the "Domino NSF Database Visual Editor"

After I create the project, I can get the nsfs/nsf-moonshine/odp/SharedElements/Subforms directory in correct place:
![image](https://user-images.githubusercontent.com/8543391/186411285-f8456a1e-36f7-4995-b608-a0173c01086e.png)

So, as you see, the folder in correct location .
I can't repeat this bug ,so I can't address it and try to fix it  ,please details the test steps ,if you get the bug again .

Thanks.

**Comment by feather812002** [comment]
@JoelProminic 
I fix the rename bug , it look like relate the code not consider the subfrom and pages
It only consider how to rename file from Froms with domino form file.
So, I update it in today , and test it make sure it work fine .
In my test, I can confirm it can success rename the  subfrom file and xml file in same time , you don't need rename the corresponding .xml file by manual.

And you need close other form or subfrom that already reference this rename subfrom ,
the updated rename subfrom should display correct in the subform list .

But as you know , the subfrom name write into the form file that already reference this subfrom .
So, the old form maybe still show the old name of the subfrom .
You need manual update it at now .

If we want dynamically update it in real time, it will be a very complex problem, because it means that we have to search all form files and subform files to determine whether it contains this renamed file , then we can update these .

**Comment by JoelProminic** [comment]
I did a test exporting a database with underscores in the form and view names.  I see that the underscore was not encoded:
![image](https://user-images.githubusercontent.com/24532731/188244763-8247d8ee-7ebc-4b49-90c0-e59046fb9658.png)

I also tried calling the view and form from agents/formulas, and I found that the names with underscores worked properly.  

I think this is just a display issue for the form names in the Notes client.  Since it doesn't affect the code behavior, we don't need to do any special encoding for the underscores for now.

**Comment by feather812002** [comment]
@JoelProminic 
Hello, Joel, I found a strange error, it look like not relate the subfrom update.
The bug trigger for remove all other element .

After I press the "delete" key ,remove the element from visual editor, the visual editor show correct display as empty , but after I click the element tree on the left, it show it still contain the element ,but it become invisible:
![image](https://user-images.githubusercontent.com/8543391/192283804-02fb3ce9-8967-4d90-95fe-e4ff42c38de1.png)

I think this is why you get the the bug about the subfrom remove on last weekend.
I still investigate this.

**Comment by feather812002** [comment]
And if I save this form , the intermiddle xml will show as follow:

`<mockup>
  <MainApplication title="" width="700" height="450" class="flexVerticalLayout flexVerticalLayoutLeft flexVerticalLayoutTop" wrap="false" direction="Vertical" vpostion="left">
    <Label size="12" color="system" fontStyle="normal" fontName="serif">Label</Label>
    <Subformref subFormName="tesstBusform22222" percentWidth="50" class="flexHorizontalLayoutWrap flexHorizontalLayoutLeft flexHorizontalLayoutTop" wrap="true">
      <Label size="12" color="system" fontStyle="normal" fontName="serif">tesstBusform22222</Label>
    </Subformref>
  </MainApplication>
  <MainApplication title="" width="700" height="450" class="flexVerticalLayout flexVerticalLayoutLeft flexVerticalLayoutTop" wrap="false" direction="Vertical" vpostion="left"/>
</mockup>`

**Comment by feather812002** [comment]
OKay. final , I understand why we got this error, 
In our design , you point out : after we rename the subfrom , we should change the name from intermiddle xml file,
But we forget one thing,: if we only change the intermiddle xml file, but not change the visual components on the surface editor, after we save it , it will write the other xml into the xml.

So, in this case, if we close all form tab , then we change the name of the subfrom , then we open the form again all will work fine .

Because when we open the form again , the visual editor will initialize the components from xml again.

**Comment by feather812002** [comment]
Other solution is remove the old file when we save the intermiddle xml , but I think it must increase so much I/O write for disk in the Moonshine-IDE, so maybe this is not a good idea.

**Comment by JoelProminic** [comment]
I did some quick tests today with @feather812002's updates, and I don't see any immediate problems

Type | Open | DXL | IntermediateXML | Editor | Delete
-----|------|-----|-----------------|--------|-------
Form | Yes  | Updated | Updated | Updated (including subform list combobox) | Works
Form | No  | Updated | Updated | N/A | N/A
Subform | Yes  | Updated | Updated | Updated (including subform list combobox) | Works
Subform | No  | Updated | Updated | N/A | N/A
