### ISSUE TITLE
[Domino Visual Editor] View Support

### ISSUE THREAD

**Issue by JoelProminic** [Moonshine-IDE/Moonshine-IDE#1016]
We would like to add support for building Views in Domino Visual Editor.  This will require a significantly different editor than the Form editor, but it is a critical tool for building Domino databases.

@JustinProminic wants to put an emphasis on using shared actions (#1014) and shared columns (#1017) with views instead of creating columns and actions directly in the view.  If we don't have good support for shared designs, we could end up with databases that are difficult to maintain.   If we want to be really serious about this, we could commit to making all columns and view actions shared, but we'll need to review the DXL structure to determine if this will be practical.

UPDATE:
Branch:  features/issue_1016_view_support 
Build:  TODO

**Comment by JoelProminic** [comment]
Some screenshots of the Domino View interface.  I'll put the column properties in #1017.

![image](https://user-images.githubusercontent.com/24532731/235004860-d4ffddec-7d42-4eff-8586-d071d44aa83c.png)
![image](https://user-images.githubusercontent.com/24532731/235005383-0e4023e7-62c7-4fa7-bd4d-e9ecf020b082.png)
![image](https://user-images.githubusercontent.com/24532731/235005178-1a1348ba-5a4c-48d9-ad45-d9e62049e51d.png)

I rarely change anything besides the View Selection formula in the view properties

**Comment by JoelProminic** [comment]
As discussed yesterday, here is the behavior I expect for the initial View GUI:
- Clicking in the body of the window should show the View properties only
- Clicking on a column should show the column properties only and allow you to make edits
- Add columns from a right-click context menu or a button in the UI
- Remove columns from a right-click context menu or a button in the column properties 
- Allow columns to be dragged to reorder.

**Comment by JoelProminic** [comment]
I confirmed that Domino does not restrict columns from having the same name.  I tested using the same formula and different formulas as well:

![image](https://github.com/Moonshine-IDE/Moonshine-IDE/assets/24532731/503d0a84-64db-4325-aed1-8cd88a8eb8bc)

**Comment by JoelProminic** [comment]
I haven't been able to reproduce the issue with column properties not saving after the last update.

When I tried to use the Remove Column button (note that the label is cut off with the current button width), I got this error:

    : Error #1063
    : ArgumentError: Error #1063
    : 	at flash.events::EventDispatcher/dispatchEvent()
    : 	at mx.core::UIComponent/dispatchEvent()
    : 	at view.domino.propertyEditors::DominoViewColumnPropertyEditor/startRemoveColumn()
    : 	at view.domino.propertyEditors::DominoViewColumnPropertyEditor/__newColumnBtn_click()
    :
    : Click here to Report a Bug

**Comment by JoelProminic** [comment]
I see these column properties were added:
![image](https://github.com/Moonshine-IDE/Moonshine-IDE/assets/24532731/3ebfe0b4-04cd-4df4-8f87-ba3137879a59)

Note that Descending is cut off, and resizing the sidebar does not make it visible.

@feather812002 mentioned that there were problems with the property initialization, and I noticed that the property values were not saving properly as I switched between columns.

I tried changing the UNID column to Descending and adding an extra column, and it crashed every time I tested it with Project > Build with Apache Maven.  The DXL looks like this:

```
<?xml version="1.0" encoding="utf-8"?>
<view name="TestView" showinmenu="false" noreplace="true" unreadmarks="none" publicaccess="false" onopengoto="lastopened" onrefresh="displayindicator" opencollapsed="false" showresponsehierarchy="true" showmargin="true" shrinkrows="false" extendlastcolumn="false" showhierarchies="false" unreadcolor="black" rowlinecount="1" rowspacing="1" bgcolor="white" totalscolor="black" headerbgcolor="white">
  <code event="selection">
    <formula/>
  </code>
  <column sort="descending" categorized="false" hidedetailrows="false" width="27" resizable="true" separatemultiplevalues="true" sortnoaccent="true" sortnocase="true" showaslinks="false" itemname="$0">
    <columnheader title="UNID">
      <font size="9" style="blod"/>
    </columnheader>
    <code event="value">
      <formula>@Text(@DocumentUniqueID)</formula>
    </code>
  </column>
  <column sort="none" categorized="false" hidedetailrows="false" width="9" resizable="true" separatemultiplevalues="true" sortnoaccent="true" sortnocase="true" showaslinks="false" itemname="TestID">
    <columnheader title="TestID">
      <font size="9" style="blod"/>
    </columnheader>
  </column>
</view>
```

I can test more with building in Vagrant tomorrow.

**Comment by JoelProminic** [comment]
Here are some ideas for column drag/drop from @rat-moonshine
- https://stackoverflow.com/questions/10044885/move-reorder-columns-in-a-spark-datagrid-adobe-flex
- Third-party example - we should be careful with this, but I don't see a license: https://github.com/rbrn/apache-flex-drag-drop-columndatagrid/tree/master

Note that we aren't really using the datagrid features here, except to show the column lines.  We could simulate this with a component that does support drag-and-drop instead.

Another idea that I think I mentioned previously is to have a separate display for the columns that is a datagrid showing the columns as rows.  For example:

Label | Value | Width
-- | -- | --
Column1 | Formula | 216
Column2 | Field:  Field1 | 216

Then the columns could be dragged/dropped using the row logic.  The user could switch to a different tab to see the columns arranged as in the current interface, and to see the relative widths (though this also still needs work).

This would be an overkill solution just for column sorting, but we could use it to display some summary information for the columns (Field/Formula, sorting, etc).

**Comment by feather812002** [comment]
@JoelProminic  I got the datecolumn work with drag&drop at now, follow this project:  columndatagrid [(https://github.com/rbrn/apache-flex-drag-drop-columndatagrid/tree/master)].
I no see a license about this . So I think we use this in our code is fine.

I still think we try to keep the dataGrid components is more better in here.
Because, from the design of Moonshine-IDE, it's goal is let user can convert the Domino NSF database to other UI with other database, so the view must should list data in later, like the Domino Designer view work with NSF database, 
Then I think it more make sence for Domino View Edtior of  Moonshine-IDE.

**Comment by JoelProminic** [comment]
From my discussion with @feather812002, we are moving to using character width as the unit of measurement for columns.  The label should be updated to "Width (characters):" to clarify this.  Actionscript needs the column width is pixels, so we are converting this using a ratio computed from `https://help.adobe.com/en_US/FlashPlatform/reference/actionscript/3/flash/text/TextField.html#textWidth`:
1. Create a new TextField with the same font as the datagrid header
2. Set the text to "XXXXXXXX"
3. Read the textWidth property and divide by 8

If we start applying the Title font options to the datagrid, we could do more advanced logic like this:
1. Create a new TextField
2. Set text to "XXXXXXXX"
3. Set size to configured value
4. Set font based on the configured font (needs to be mapped to local fonts)
5. Read the textWidth property to get the actual width, and divide by 8

The column width updates are looking good so far.

**Comment by JoelProminic** [comment]
I noticed a bug today related to drag and drop.   I found that if I clicked a row and dragged it slightly in the row area, it triggered a "onRowDragAndDropped" popup and a console error
```
: Error #1009
: TypeError: Error #1009
: 	at spark.components::DataGrid/dragDropHandler()
: 	at flash.events::EventDispatcher/dispatchEvent()
: 	at mx.core::UIComponent/dispatchEvent()
: 	at mx.managers::NativeDragManagerImpl/_dispatchDragEvent()
: 	at mx.managers::NativeDragManagerImpl/nativeDragEventHandler()
:
: Click here to Report a Bug
```

This is a problem because I was triggering it accidentally when clicking to focus the Moonshine window or when trying to see the View properties.

Looking deeper, I see that I can drag from a row to the column bar to move a column.  This is not necessarily a bad feature, but we need to be careful that this doesn't accidentally reorder columns when the user is trying to see the view properties.

**Comment by JoelProminic** [comment]
The view editor is working pretty well, so I think I'd like to merge this to master before we start another big change for this.  I'll do some more testing to look for polish issues before we merge.

@piotrzarzycki21, you can check this branch if you want to preview the changes.  This branch isn't too old, and we haven't been making many changes to Moonshine-IDE recently, so I'm hopeful that this will be an easy merge.
Branch: features/issue_1016_view_support

**Comment by JoelProminic** [comment]
@feather812002, I did a final review for this today, and this can be merged to master.

**Comment by JoelProminic** [comment]
I confirmed this is merged
