### ISSUE TITLE
New Workspace Does Not Show Up in Workspace List

### ISSUE THREAD

**Issue by JoelProminic** [Moonshine-IDE/Moonshine-IDE#1021]
We saw this issue today during testing:
1. Open MoonshineDevelopment
2. File > Workspace > Create Workspace
3. Select a name and create the workspace.  I chose "zzzTestWorkspace"
4. The workspace opens properly
5. File > Workspace > Switch Workspace.  BUG:  The selection is blank, and the new workspace is not in the list.
6. Select the IDE-Default workspace and click Load Workspace
7. File > Workspace > Switch Workspace.  BUG:  The new workspace is not in the list.
8. Restart Moonshine
7. File > Workspace > Switch Workspace.  Now the new workspace is in the list.

I didn't see any errors on the console, so this seems different than #760.

**Comment by rat-moonshine** [comment]
This should be fixed now. Please, check.

Scenario | "Load Workspace" generates with new Workspace
-------------|-----------------------
Fresh start | Yes
Create new Workspace | Yes
Duplicate Workspace | Yes

**Comment by JoelProminic** [comment]
I confirmed that this is working for macOS and Windows.  I also tested File > Workspace > Save as New Workspace for the duplicate logic.
