### ISSUE TITLE
[Domino Visual Editor] Cannot Select Components in Reopened Form

### ISSUE THREAD

**Issue by JoelProminic** [Moonshine-IDE/Moonshine-IDE#1022]
When I tried to test today's updates, I found that I couldn't select any components from the editor in a reopened form.
1. Create a new form
2. Add a Label
3. Select the Main Application panel, and then the Label.  This works
4. Save and close the form
5. Open the form
6. Try to select the Label.  BUG:  I can only select the Main Application panel
7. Switch to the Organizer tab and select the Label.  This works

So, I can still test with this, but the bug will slow down my testing.  I probably won't do too much more testing with this today, but I may work on a test database for the round-trip instead.

_Originally posted by @JoelProminic in https://github.com/Moonshine-IDE/Moonshine-IDE/issues/1001#issuecomment-1092008514_

I originally saw this in the #1001 branch, but I confirmed this issue in master as well.

**Comment by piotrzarzycki21** [comment]
I have started working on fix today and I hope to have it tomorrow. It is more extensive fix. Issue has been exposed after some refactoring when I was preparing Visual Editor libraries for Royale output.

**Comment by piotrzarzycki21** [comment]
Issue should be fixed on master. @feather812002 please update your branches having in mind latest email from @Aszusz - you may experience some conflicts.

**Comment by JoelProminic** [comment]
I confirmed this was fixed and working in @feather812002's branch. Thanks!
