### ISSUE TITLE
[Domino Visual Editor] Error on Intermediate XML Conversion

### ISSUE THREAD

**Issue by JoelProminic** [Moonshine-IDE/Moonshine-IDE#1023]
When testing #1001 today, I found that the intermediate XML conversion (#968) failed.  I confirmed the problem on master.  @feather812002 reported that this stated failing for him after he merged master into his branches for MockupVisualEditor and VisualEditorConverterLib:
1. Update MoonshineDevelopment
2. Unzip the attached project:  [xmlPrj_8188391235052749449_TestHideOption2.zip](https://github.com/Moonshine-IDE/Moonshine-IDE/files/8466226/xmlPrj_8188391235052749449_TestHideOption2.zip)
3. Open the extractd project in MoonshineDevelopment with Project > Open/Import Project. BUG:  this error triggers before the project opens (# removed to avoid markdown issues).

    : Error 1009
    : TypeError: Error 1009
    : 	at converter::DominoConverter$/itemFromXML()
    : 	at components.common::Div/fromXML()
    : 	at components.domino::DominoTable/fromXML()
    : 	at converter::DominoConverter$/itemFromXML()
    : 	at components.domino::Body/fromXML()
    : 	at converter::DominoConverter$/itemFromXML()
    : 	at converter::DominoConverter$/fromXML()
    : 	at converter::DominoConverter$/fromXMLOnly()
    : 	at utils::EditingSurfaceReader$/fromXMLAutoConvert()
    : 	at actionScripts.plugins.as3project.importer::FlashDevelopImporter$/convertDomino()
    : 	at actionScripts.impls::IFlexCoreBridgeImp/convertFlashDevelopToDomino()
    : 	at actionScripts.plugin.actionscript.as3project::AS3ProjectPlugin/autoConvertXmlToDominoForm()
    : 	at actionScripts.plugin.actionscript.as3project::AS3ProjectPlugin/importFDProject()
    : 	at actionScripts.plugin.actionscript.as3project::AS3ProjectPlugin/openProjectByDirectory()
    : 	at actionScripts.plugin.actionscript.as3project::AS3ProjectPlugin/importProjectWithoutDialog()
    : 	at flash.events::EventDispatcher/dispatchEvent()
    : 	at actionScripts.plugins.nativeFiles::FileAssociationPlugin/openFilesByPath()
    : 	at actionScripts.plugins.nativeFiles::FileAssociationPlugin/onAppInvokeEvent()
    : 	at flash.events::EventDispatcher/dispatchEvent()
    : 	at flash.desktop::NativeApplication/dispatchEvent()
    :
    : Click here to Report a Bug

The attached project could convert when I originally tested it a couple weeks ago.  I used this as my example rather than the latest XML to confirm that this wasn't an issue with the recent updates for #1001.

This is blocking testing for #1001 at the moment.  @piotrzarzycki21, do you see something that could cause this in your recent updates?  @feather812002, if you find a simple fix for this, go ahead and fix it in master.  If it is more complicated (i.e. related to some refactoring), we can discuss it with @piotrzarzycki21.

**Comment by piotrzarzycki21** [comment]
I'm on it!

**Comment by piotrzarzycki21** [comment]
I have pushed changes to master which fixes issue caused by my changes. Error which above is not caused by my changes - they are exposes a bug which I'm not sure how to resolve. @feather812002 or you @JoelProminic need to provide me some information. 

During conversion element called "Paragraph" is missing from known elements stored in our internal object. When we are in the UI layer we are using [DominoParagraph](https://github.com/Moonshine-IDE/MockupVisualEditor/blob/7285feb8ad617938e709505fea7bee1420d0e6e4/src/view/domino/surfaceComponents/components/DominoParagraph.as#L99) where ELEMENT_NAME is "Paragraph" - this class is strictly UI.

However when we are converting XML without UI interaction we are using non-UI components - this is our case here. In our library we have two similar classes [DominoPar](https://github.com/Moonshine-IDE/VisualEditorConverterLib/blob/master/src/components/domino/DominoPar.as) and [DominoParagraph](https://github.com/Moonshine-IDE/VisualEditorConverterLib/blob/master/src/components/domino/DominoParagraph.as) - Which one is correct ? Does value of ELEMENT_NAME should be changed in correct classes ? Let me know and I will remove unused class and fix the right one.

**Comment by feather812002** [comment]
I also got the error after I merge the update from master in today .
![image](https://user-images.githubusercontent.com/8543391/162948161-23c65f18-82e1-4e4b-b1fd-9266da925ed5.png)
About the [DominoParagraph](https://github.com/Moonshine-IDE/MockupVisualEditor/blob/7285feb8ad617938e709505fea7bee1420d0e6e4/src/view/domino/surfaceComponents/components/DominoParagraph.as#L99) , we should work with DominoParagraph when we work with convert or other some UI convert or action , the [DominoPar](https://github.com/Moonshine-IDE/VisualEditorConverterLib/blob/master/src/components/domino/DominoPar.as) only work for other domino class,  it just a part of other Domino non-UI components, some times, one Domino components component is composed of other components, so DominoPar only work for this .

**Comment by piotrzarzycki21** [comment]
> About the [DominoParagraph](https://github.com/Moonshine-IDE/MockupVisualEditor/blob/7285feb8ad617938e709505fea7bee1420d0e6e4/src/view/domino/surfaceComponents/components/DominoParagraph.as#L99) , we should work with DominoParagraph when we work with convert or other some UI convert or action , the [DominoPar](https://github.com/Moonshine-IDE/VisualEditorConverterLib/blob/master/src/components/domino/DominoPar.as) only work for other domino class, it just a part of other Domino non-UI components, some times, one Domino components component is composed of other components, so DominoPar only work for this .

Please provide me project where you are using DominoPar ? You are not right saying that we should work only with DominoParagraph. We should work with DominoParagraph only if you are manipulating things on the UI - if not - there should be equivalent which is non UI, so my question stands - which non UI component should be used to fix that issue ? 

This case is non-UI case.

**Comment by feather812002** [comment]
@piotrzarzycki21 I also check the DominoPar , it only exist in the VisualEditorConverterLib.
https://github.com/Moonshine-IDE/VisualEditorConverterLib/blob/d79e1931bc581dac9e44738f507df240dd98b8e6/src/components/domino/DominoLabel.as#L398

Yes, maybe I not type it clear,  my mean is DominoParagraph only work with UI ,and convert something into UI , for convert the UI into middle xml.

Let me clear the DominoPar again , it not a UI components, it also not work with other UI components , it only work in the VisualEditorConverterLib and work with other non-UI domino class.

**Comment by piotrzarzycki21** [comment]
@feather812002 In above conversion you are using non-UI components and it looks like you are not aware of that. Here is 3 classes

**UI:** https://github.com/Moonshine-IDE/MockupVisualEditor/blob/master/src/view/domino/surfaceComponents/components/DominoParagraph.as

**non-UI Class 1:** https://github.com/Moonshine-IDE/VisualEditorConverterLib/blob/master/src/components/domino/DominoParagraph.as
**non-UI Class 2:** https://github.com/Moonshine-IDE/VisualEditorConverterLib/blob/master/src/components/domino/DominoPar.as

Which one out of that should be used **Class 1** or **Class 2** ? - UI is not used in that case at all.

**Comment by feather812002** [comment]
**UI:**https://github.com/Moonshine-IDE/MockupVisualEditor/blob/master/src/view/domino/surfaceComponents/components/DominoParagraph.as 
should work with  : 
**non-UI Class 1:** https://github.com/Moonshine-IDE/VisualEditorConverterLib/blob/master/src/components/domino/DominoParagraph.as
non-UI Class 2 work with other non-UI Class , we don't need change it at now .

**Comment by piotrzarzycki21** [comment]
> non-UI Class 2 work with other non-UI Class , we don't need change it at now .

Would it be possible to provide me where DominoPar class is being used ? What cases ?

**Comment by piotrzarzycki21** [comment]
> **non-UI Class 1:** https://github.com/Moonshine-IDE/VisualEditorConverterLib/blob/master/src/components/domino/DominoParagraph.as

Understand, so now moving forward [ELEMENT_NAME](https://github.com/Moonshine-IDE/VisualEditorConverterLib/blob/master/src/components/domino/DominoParagraph.as#L54) in above class should be changed to ELEMENT_NAME = "Paragraph" as I understand, not "Par" ?

**Comment by feather812002** [comment]
https://github.com/Moonshine-IDE/VisualEditorConverterLib/blob/d79e1931bc581dac9e44738f507df240dd98b8e6/src/components/domino/DominoLabel.as#L398
For now , only the DominoLabel, work with the DominoPar.
But it still maybe possible work with other Domino non-UI class in later.

No, just keep the [ELEMENT_NAME](https://github.com/Moonshine-IDE/VisualEditorConverterLib/blob/master/src/components/domino/DominoParagraph.as#L54)  as "Par".
Because the Domino not exist the Paragraph element , the Paragraph element add by require from Justin and @JoelProminic , so I use the Par as the Paragraph element , but in Domino , the Par also work for other domino class. 
So, the DominoParagraph non-UI class should defined the element name as "par", because no tag name "Paragraph" in Domino dxl .

**Comment by piotrzarzycki21** [comment]
> No, just keep the [ELEMENT_NAME](https://github.com/Moonshine-IDE/VisualEditorConverterLib/blob/master/src/components/domino/DominoParagraph.as#L54) as "Par".
> Because the Domino not exist the Paragraph element , the Paragraph element add by require from Justin and @JoelProminic , so I use the Par as the Paragraph element , but in Domino , the Par also work for other domino class.
> So, the DominoParagraph non-UI class should defined the element name as "par", because no tag name "Paragraph" in Domino dxl .

I have pushed fixes it should work now. 

However some explanation - non-UI classes which resides in [VisualEditorConverterLib](https://github.com/Moonshine-IDE/VisualEditorConverterLib) should be used only for conversion xml which resides in visualeditor-src folder. In this case ELEMENT_NAME should be "Paragraph" - Inside visualeditor-src folder xml can contains "Paragraph" and in fact it contains - once it's being read and translated into our internal objects UI or non-UI method toCode can translate it to whatever is needed.

**Comment by feather812002** [comment]
Sorry ,maybe I misunderstand , but from my read the code from [VisualEditorConverterLib](https://github.com/Moonshine-IDE/VisualEditorConverterLib)  and MockupVisualEditor, the conversion xml into  visualeditor-src folder should work with [toXML](https://github.com/Moonshine-IDE/MockupVisualEditor/blob/3a26d54d8e98878225fbbc7a3ba13c25d4a390e2/src/utils/EditingSurfaceWriter.as#L15)
As you see the code 

`var xml:XML = <mockup/>;`

So , it must generate the middle xml from here , rather than from [VisualEditorConverterLib](https://github.com/Moonshine-IDE/VisualEditorConverterLib).

VisualEditorConverterLib  only work for target UI genearte format, 
For primeface , it should be primeface format
For Domino , it should convert to Domino dxl format.

So , in this case, the ELEMENT_NAME should be "Par", rather than "Paragraph"

**Comment by piotrzarzycki21** [comment]
> The error was resolved for the database I am using to test #1001, but I found in my test today that it failed when opening the converted project for the PerformanceStats database (@feather812002 has access to this).
> 
> ```
> : Error #1009
> : TypeError: Error #1009
> : 	at converter::DominoConverter$/getNewInstanceOfComponent()
> : 	at components.domino::DominoTabView/tabFromXML()
> : 	at components.domino::DominoTabView/fromXML()
> : 	at converter::DominoConverter$/itemFromXML()
> : 	at components.domino::Body/fromXML()
> : 	at converter::DominoConverter$/itemFromXML()
> : 	at converter::DominoConverter$/fromXML()
> : 	at converter::DominoConverter$/fromXMLOnly()
> : 	at utils::EditingSurfaceReader$/fromXMLAutoConvert()
> : 	at actionScripts.plugins.as3project.importer::FlashDevelopImporter$/convertDomino()
> : 	at actionScripts.impls::IFlexCoreBridgeImp/convertFlashDevelopToDomino()
> : 	at actionScripts.plugin.actionscript.as3project::AS3ProjectPlugin/autoConvertXmlToDominoForm()
> : 	at actionScripts.plugin.actionscript.as3project::AS3ProjectPlugin/importFDProject()
> : 	at actionScripts.plugin.actionscript.as3project::AS3ProjectPlugin/openProjectByDirectory()
> : 	at actionScripts.plugin.actionscript.as3project::AS3ProjectPlugin/importProjectWithoutDialog()
> : 	at flash.events::EventDispatcher/dispatchEvent()
> : 	at actionScripts.plugins.nativeFiles::FileAssociationPlugin/openFilesByPath()
> : 	at actionScripts.plugins.nativeFiles::FileAssociationPlugin/onAppInvokeEvent()
> : 	at flash.events::EventDispatcher/dispatchEvent()
> : 	at flash.desktop::NativeApplication/dispatchEvent()
> :
> : Click here to Report a Bug
> ```
@JoelProminic this is on master ?

**Comment by piotrzarzycki21** [comment]
> The error was resolved for the database I am using to test #1001, but I found in my test today that it failed when opening the converted project for the PerformanceStats database (@feather812002 has access to this).
> 
> ```
> : Error #1009
> : TypeError: Error #1009
> : 	at converter::DominoConverter$/getNewInstanceOfComponent()
> : 	at components.domino::DominoTabView/tabFromXML()
> : 	at components.domino::DominoTabView/fromXML()
> : 	at converter::DominoConverter$/itemFromXML()
> : 	at components.domino::Body/fromXML()
> : 	at converter::DominoConverter$/itemFromXML()
> : 	at converter::DominoConverter$/fromXML()
> : 	at converter::DominoConverter$/fromXMLOnly()
> : 	at utils::EditingSurfaceReader$/fromXMLAutoConvert()
> : 	at actionScripts.plugins.as3project.importer::FlashDevelopImporter$/convertDomino()
> : 	at actionScripts.impls::IFlexCoreBridgeImp/convertFlashDevelopToDomino()
> : 	at actionScripts.plugin.actionscript.as3project::AS3ProjectPlugin/autoConvertXmlToDominoForm()
> : 	at actionScripts.plugin.actionscript.as3project::AS3ProjectPlugin/importFDProject()
> : 	at actionScripts.plugin.actionscript.as3project::AS3ProjectPlugin/openProjectByDirectory()
> : 	at actionScripts.plugin.actionscript.as3project::AS3ProjectPlugin/importProjectWithoutDialog()
> : 	at flash.events::EventDispatcher/dispatchEvent()
> : 	at actionScripts.plugins.nativeFiles::FileAssociationPlugin/openFilesByPath()
> : 	at actionScripts.plugins.nativeFiles::FileAssociationPlugin/onAppInvokeEvent()
> : 	at flash.events::EventDispatcher/dispatchEvent()
> : 	at flash.desktop::NativeApplication/dispatchEvent()
> :
> : Click here to Report a Bug
> ```

I have pushed some changes which may fix that issue - check next build.

**Comment by JoelProminic** [comment]
I don't see any more errors like this with my test database.
