### ISSUE TITLE
Duplicate Extensions in Recent Files

### ISSUE THREAD

**Issue by JoelProminic** [Moonshine-IDE/Moonshine-IDE#1027]
While testing #700 today, I noticed that the RECENT files section on the Home page had duplicate extensions for each file.

![image](https://user-images.githubusercontent.com/24532731/167029196-004ac626-190f-43ac-9e70-b76e9e261e8e.png)

I saw the same behavior for File > Recent Files, and I confirmed the behavior in the master build.

I can still open the recent files, so this is just a cosmetic issue.

**Comment by rat-moonshine** [comment]
This problem is now rectified. However, the fix is currently part of #700 branch, I'm hopeful we soon have a merge of the branch into `master`. If the merge would take more time then I shall apply the fixes in `master` separately.

**Comment by JoelProminic** [comment]
I confirmed that the duplicate extensions are removed, and I can still open the files from Recents. This should be fine for a merge.
