### ISSUE TITLE
Copy/Paste for Domino Visual Editor Components

### ISSUE THREAD

**Issue by JoelProminic** [Moonshine-IDE/Moonshine-IDE#1032]
I remember that we had Copy/Paste working for Flex or Primefaces Visual Editor.  I'd like to have something similar for Domino Visual Editor so that we can quickly duplicate components when building a larger form.

For now, I have flagged this as a long-term task, but we can bump this up if it would be relatively easy to implement (i.e. copy from another Visual Editor).

UPDATE:  In progress
Branch: features/issue-1082_IMOS_Convert
Builds: https://static.moonshine-ide.com/downloads/releases/dev/macos/branches/features/issue-1082_IMOS_Convert

**Comment by JoelProminic** [comment]
While testing I found this behavior confusing:
1. Add a new Label and set some text
2. Select the Label and press CTRL-C then CTRL-V.  Nothing happens
3. Select a container and press CTRL-V.  This works

So, a container must be selected when pasting.  I think this could cause confusion, so I'd like to use one of these options instead:
- Write an error to the console like:  "Pasting is only allowed in a container."  This is not a very helpful solution, but it would be a quick fix that would at least give feedback on why it didn't work.
- Paste the component into the parent container of the selected component, so that it will be a sibling.  Ideally this would be pasted immediately after the selected component, but adding it to the end of the container would be consistent with the current drag and drop behavior.

**Comment by JoelProminic** [comment]
I see that copy-pasting a field does not update the name for the new field, which will cause a compliation error if the user does not change it manually.  Some possible solutions:
- Keep the current behavior, and expect the user to change the name.  We could add a feature to alert on duplicate field names to support this case.
- Match the Domino logic by appending "_1" to the name.  Increment the number until it the field name is unique, for cases where the field is pasted multiple times.  This method is safer, but it can make more work for the user when renaming if they were planning to use a similar name.

**Comment by JoelProminic** [comment]
The save flag currently does not update when pasting a component.

**Comment by feather812002** [comment]
- Copy-pasting a field should auto  update the name to source_name+"{Counter}", the Counter initial value is "1"
-  The save flag currently should update after pasting a component to editor at now.

**Comment by JesseProminic** [comment]
- "Copy" means testing that a component can be copied and pasted. 
- "Target" means testing that the component can be selected for a paste.


Component | Copy | Target | Notes
-- | -- | -- | --
Button | ✅ | ✅  | The color of the buttons are different (1)
Input | ✅ | ✅  | It copies the value but the font does not match (2)
Label | ✅  | ✅  | 
Table | ❗ | ✅  |(3)
Div | ✅  | ✅    |  
ComputedText | ✅    | ✅   |  
Paragraph | ✅ | ✅   |  
Section |✅ | ✅   |  
TabView | ❗  |✅   |(4)
Calendar |✅    | ✅  |  
Subform |✅    | ✅   |
ShareField |✅    | ✅   | 

(1) Button
![Screenshot 2023-03-23 at 11 40 49 AM](https://user-images.githubusercontent.com/96078188/227274322-d8694610-5ebb-46ae-8b11-1f50a162cc8f.png)

(2) Input 
![Screenshot 2023-03-23 at 11 31 19 AM](https://user-images.githubusercontent.com/96078188/227271547-ddaa3f05-93e3-412e-976e-270339c197e6.png)

(3) Table
![Screenshot 2023-03-23 at 11 35 49 AM](https://user-images.githubusercontent.com/96078188/227272797-616b7bef-4654-4021-b3fb-97dc7f352e44.png)

(4) Tab
![Screenshot 2023-03-23 at 11 45 30 AM](https://user-images.githubusercontent.com/96078188/227275365-c2ab05ed-8ee1-485e-b9e9-3c8beb73fe1b.png)

**Comment by JoelProminic** [comment]
The field name incrementation is not working like I expect.  It looks like this is based on a single counter in memory rather than checking the form, so it doesn't necessarily resolve the duplicate field cases:
1. Restart Moonshine
2. Create a new Form
3. Create two fields, Foo and Bar
4. Duplicate Foo.  It is created as Foo1
5. Duplicate Foo again.  It is created as Foo2
6. Duplicate Bar.  It is created as Bar3, rather than Bar1.  This is unexpected, but does not break anything
7. Rename Foo2 to Foo4
8. Duplicate Foo. BUG:  it is created as Foo4, a duplicate
9. Restart Moonshine
10. Duplicate Foo.  BUG:  it is created as Foo1, a duplicate

**Comment by JoelProminic** [comment]
Component | Copy | Target | Notes
-- | -- | -- | --
Button | Works | Sibling | Appearance changes after paste
Input | Works | Sibing | Name updated with incrementing number
Label | Works | Works | 
Table | Works, children also pasted | Child, determined by selected cell | 
Div | N/A | N/A | Removed in #1198
ComputedText | Works | Sibling | 
Paragraph | Works, but triggers Error #1034 on console | Child | 
Section | Works | Works | Nested components overlap each other
TabView | Works, children duplicated as well | Child, based on selected tab | 
Calendar | Works but triggers Error #1009 | Sibling | 
Subform | Works.  BUG:  Label duplicated | BUG:  Child | The user is expected to change to a new subform in this case
SharedField | Works.  BUG:  Label duplicated | BUG:  Child | The user is expected to change to a new shared field in this case
MainApplication | Error:  "Unknown item null" |  | We should not be able to copy paste this component, since there should be only one instance


Here is the error when pasting a paragraph:

    : Error #1034
    : TypeError: Error #1034
    : 	at components.domino::DominoParagraph/fromXML()
    : 	at view.domino.surfaceComponents.components::DominoParagraph/fromXML()
    : 	at utils::CopyPasteVisualEditorManager/pasteItemFromXML()
    : 	at utils::CopyPasteVisualEditorManager/paste()
    : 	at utils::CopyPasteVisualEditorManager/onUiListenerKeyDown()
    :
    : Click here to Report a Bug


Here is the error for pasting a Calendar component.  Is this component supported for Domino Visual Editor?

    : Error #1009
    : TypeError: Error #1009
    : 	at Function/<anonymous>()
    : 	at mx.core::UIComponent/callLaterDispatcher2()
    : 	at mx.core::UIComponent/callLaterDispatcher()
    :
    : Click here to Report a Bug

**Comment by JoelProminic** [comment]
Testing with the update today, I can no longer reproduce the duplicate label.

I still see that I can past a subform inside a subform component, though:
1. Open a form with a subform
2. Select a subform and copy
3. Select the subform and paste.  The subform is pasted inside the same UI element, rather than in the parent.
![image](https://user-images.githubusercontent.com/24532731/229592887-389fb27f-af54-4ae2-9972-39250f6fc5c9.png)

**Comment by JoelProminic** [comment]
I confirmed that Paragraph is working as I expect now, and Shared Field is hidden again.

I also did a build test and confirmed that the copy-pasted components worked properly.

I am closing the issue, and we can proceed with the next steps for the #1200 merge.
