### ISSUE TITLE
Ant Errors for Flex Desktop Template

### ISSUE THREAD

**Issue by JoelProminic** [Moonshine-IDE/Moonshine-IDE#1034]
I did a test with a fresh Flex Desktop project today, and saw problems with the Ant build.  I tested on Development Version 3.3.3, Build 2568:
1. Restart Moonshine
2. Create a new Fled Desktop project
3. Project > Build with Apache Ant.  BUG:  it uses Desktop for the Ant path instead of the configuredd path

    : Ant build Running
    : SDK path: /Users/-user-/Downloads/MoonshineSDKs/Flex_SDK/Flex_4.16.1_AIR_32.0
    : /Users/-user-/Downloads/MoonshineSDKs/Ant/apache-ant-1.10.1/bin/ant -file /Users/-user-/Desktop
    : What? Buildfile: /Users/-user-/Desktop is a dir!
    : Build failed
    : FSCH exit code: 1

4. Check the `.as3proj` file.  The Ant path is relative:

    <option antBuildPath="build/build.xml"/>

5. Project > Open/Import Project and select the same project.  This will update the last selected file-chooser directory
6. Project > Build with Apache Ant.  BUG:  now it gives an error on the project path

    : Ant build Running
    : SDK path: /Users/-user-/Downloads/MoonshineSDKs/Flex_SDK/Flex_4.16.1_AIR_32.0
    : /Users/-user-/Downloads/MoonshineSDKs/Ant/apache-ant-1.10.1/bin/ant -file /Users/-user-/Documents/Flex/temp_workspace/TestFlexDesktop_0520
    : What? Buildfile: /Users/-user-/Documents/Flex/temp_workspace/TestFlexDesktop_0520 is a dir!
    : Build failed
    : FSCH exit code: 1

7. Open the project settings
8. In the Ant Build tab, browse to the project Ant script and save the settings
9. Project > Build with Apache Ant.  BUG:  this fails with a timestamp error

    : compileAIR:
    :      [echo] AIR build process
    :      [java] Timestamp response not valid

10. Project > Open/Import Project and select the project again
11. Project > Build with Apache Ant.  The script fails with the timestamp error.  So, the first bug doens't seem to trigger when an absolute path is set

For the timestamp issue, I see the Ant script uses this server:  http://timestamp.comodoca.com/rfc3161

We saw similar errors for the Moonshine (and other project) builds, so we [switched](https://github.com/Moonshine-IDE/Moonshine-IDE/blob/815df7ac8c8732d2e904f156c5a877967031ebdf/ide/MoonshineSharedCore/build/build-lib.xml#L308) to:  http://timestamp.digicert.com

The timestamp server will need to be updated for each project template that uses it:

    % grep -l -ri "http://timestamp.comodoca.com/rfc3161" . | grep src   
    ./ide/MoonshineSharedCore/src/elements/templates/projects/ActionScript Desktop Project/build_air/build.xml.template
    ./ide/MoonshineSharedCore/src/elements/templates/projects/Flex Desktop Project (MacOS, Windows)/build_air/build.xml.template
    ./ide/MoonshineSharedCore/src/elements/templates/projects/ActionScript Mobile Project/build_air/build.xml.template
    ./ide/MoonshineSharedCore/src/elements/templates/projects/Feathers SDK Desktop Project (MacOS, Windows)/build_air/build.xml.template

The Ant build isn't really a critical feature, so we can leave this a lower priority and bump it to a later release if it will be time consuming.

**Comment by rat-moonshine** [comment]
`What? Buildfile: $antPath is a dir!` possibly introduced since https://github.com/Moonshine-IDE/Moonshine-IDE/issues/700#issuecomment-1132720311 updates. 

I fixed this. Following was my local test results:

Action | Project | Ant Build Run
-------|----------|-----------------
Open/Import | Generic Project without configuration file | Worked
Open/Import | Generic Project with configuration file | Worked
Create | Project supplied with Ant build file | Worked
Open/import | Project with Ant build file | Worked

I also replaced templates' Ant file-timestamps from `http://timestamp.comodoca.com/rfc3161` to `http://timestamp.digicert.com`. I confirm this worked locally.

**Comment by JoelProminic** [comment]
@JesseProminic, can you test this?   Let me know if you need any clarification.
