### ISSUE TITLE
Open Path in Terminal

### ISSUE THREAD

**Issue by JoelProminic** [Moonshine-IDE/Moonshine-IDE#1038]
From @JustinProminic

>Similar to how Moonshine IDE has "Show in Finder", please add "Open in Terminal" and have a menu of terminal profiles available like Finder has:
>
> ![image](https://user-images.githubusercontent.com/24532731/171281993-5af40d2b-29e0-459f-b5ee-90045d9a6bb6.png)
>
>Along with some less elegant Windows equivalent for just opening a PowerShell or DOS prompt (both options please).

For opening Terminal or the Windows command line, we can reuse logic from #989.

For the Profile selection, see some examples [here](https://apple.stackexchange.com/questions/122875/opening-new-terminal-app-window-tab-with-a-certain-profile-from-command-line-or):  `set current settings of selected tab of window 1 to settings set "Grass"`.  Don't change `default settings`.

Do we really want the option to select a profile?  This is an extra nested menu that the user needs to navigate each time, so it is only really useful if the user wants to open different  color Terminals for each action.  We could streamline this somewhat by having the first entry be "Default" or "System Default", which would just use the default profile configured for Terminal.

UPDATE:  Branch:  features/issue_1038_openpath_in_terminal
macOS:  https://static.moonshine-ide.com/downloads/releases/dev/macos/branches/features/issue_1038_openpath_in_terminal
Windows:  https://static.moonshine-ide.com/downloads/releases/dev/windows/branches/features/issue_1038_openpath_in_terminal

**Comment by JustinProminic** [comment]
If we are going to do this, I definitely want the ability to select the color as I showed in the above screen shot please.  Having said that, this is not a high priority issue.

**Comment by JustinProminic** [comment]
And to further clarify, I would want the ability with the sub-menu to select colors such that I do not get stuck with only one color.  I'd prefer the flexibility to select colors on a per-project basis as the screen shot showed.

**Comment by rat-moonshine** [comment]
> Some notes from today's discussion:

I think this observation was for #914 . I have copied @JoelProminic observation at [here](https://github.com/Moonshine-IDE/Moonshine-IDE/issues/914#issuecomment-1168201516).

**Comment by rat-moonshine** [comment]
The initial implementation now can be tested with branch build plans at Bamboo, for both Windows and macOS. Please, check.

**Comment by rat-moonshine** [comment]
Example codes:

```
tell application "Terminal"
	set win to do script
	set win's current settings to settings set "Grass"
end tell
```

**Comment by JoelProminic** [comment]
**The theme should be supported for macOS Terminal only.**   There may be a similar Windows feature, but we don't need to spend time on this for now.

I see some suggests to [set the Terminal theme here](https://stackoverflow.com/questions/7807962/applescript-to-open-specific-terminal-style-windows).   In particular, this looks promising:

```
tell application "Terminal"
    set win to do script
    set win's current settings to settings set "Basic"
end tell
```

The submenu should have a "Default" option which won't set any theme, and then a list of other themese.  Ideally this list should be populated automatically from a command, but I haven't found a command yet

    Open in Terminal
        Default
        -------
        Basic
        Grass
        Homebrew
        ...

**Comment by rat-moonshine** [comment]
> Ideally this list should be populated automatically from a command, but I haven't found a command yet

I posted in StackOverflow.

**Comment by rat-moonshine** [comment]
Unfortunately, I couldn't found much of a help to get a list of the system available Terminal theme-list except running the following command:

`defaults read com.apple.Terminal "Window Settings"`

This returns a user readable format. Unfortunately, parsing the format took me long time than anticipated. 

The command returns a JSON like format "NeXTSTEP" but not JSON. There also not much help to convert the format into JSON easily, except using "plutil" command on Terminal. But "plutil" does not available pre-installed into macOS. I finally come up of using Regex to string search and populate the list. The list seems to be populate correctly now:

![image](https://user-images.githubusercontent.com/24370870/200302672-5d8d113b-af02-48ad-9cdf-e1968b79c353.png)

I also added an AppleScript file with necessary changes that trigger the Terminal with appropriate theme. 

I still needs to give some tests on Windows.

**Comment by rat-moonshine** [comment]
Tested on Windows, all seems to be good.

**Comment by JoelProminic** [comment]
This is working well for me on macOS.  I still want to test with a custom theme, though.

However, we are missing the separated "Default" entry that I requested.  This is not a specific theme, but it will use the default the user selected in the Terminal application.   From the Moonshine side, this option means that you will skip this line:

```
    set win's current settings to settings set "Basic"
 ```   
 
This is intended to be a quick option if the user doesn't care about selecting a specific theme.

**Comment by rat-moonshine** [comment]
Added. 
![image](https://user-images.githubusercontent.com/24370870/200495798-d480a32a-a881-42ba-ad56-4dc1bc8b1578.png)

**Comment by JoelProminic** [comment]
This is working great for the basic tests on macOS.  There is some more testing to do:

Test | Result | Notes
-- | -- | --
macOS Default | Works | 
macOS with Theme | Works | 
macOS with Custom Theme |  | Make sure it shows up in list and works.   We could also think about character escaping, but I don't want to spend too long on this
Windows Command Line |  | 
Windows Powershell |  |

**Comment by rat-moonshine** [comment]
This issue is now merged into `master`.

**Comment by JoelProminic** [comment]
On Windows we should have two options:
- Open in Command Line
- Open in PowerShell (may be replaced by Windows Terminal in near future)

**Comment by JoelProminic** [comment]
We also need to support populating the Terminal/Command Line/PowerShell window with the correct environment variables for the project.  This should use the same environment for the project build commands.   Remember that Java, Flex, and Royale projects can have custom SDKs.

**Comment by JoelProminic** [comment]
I did a test where I selected a file instead of a directory and chose Open in Terminal.   This properly opened the parent directory instead.

**Comment by JoelProminic** [comment]
Another, hopefully minor,  update is that we should run the clear command after running the other commands for the directory and environment setup.  This will let the user work from a clean window.

**Comment by rat-moonshine** [comment]
- New open in PowerShell option now added in Windows

It appears the existing environment-setup logic already adds the Moonshine-environments in opening/running shell-instance. I tested different environments in opening CMD/PowerShell which have added through Moonshine Settings, when the environments not available in regular CMD/PowerShell prompts. 

Example, in regular PowerShell:
![image](https://user-images.githubusercontent.com/24370870/204220700-965568f6-632a-4d1d-bc65-3011d5f156a3.png)

In `Open in PowerShell` PowerShell window:
![image](https://user-images.githubusercontent.com/24370870/204220542-5592382a-cd75-4208-89a2-b5a2044fcdae.png)

Please, check.

**Comment by piotrzarzycki21** [comment]
@rat-moonshine I believe we are still building and commiting MoonshineGUICore.swc, so you need to build and commit that as well. My local build fail initially.

**Comment by rat-moonshine** [comment]
Okay, @piotrzarzycki21 . I thought opposite since last discussed on building SWCs. I shall plan to commit re-compiled one from next time.

**Comment by rat-moonshine** [comment]
Updates:

- Terminal now opens with environment auto-setup from Moonshine
- Clear command added in opening Terminal, CMD and PowerShell

**Comment by JoelProminic** [comment]
While testing today's updates on Catalina, I found that the environment command was cut off after 1024 characters:

![image](https://user-images.githubusercontent.com/24532731/204640307-49c4af72-09e7-46b6-b392-1402c446d914.png)

    cd '/Users/joelanderson/Documents/Flex/workspace/FormBuilder-Contact-API/ContactsDatabase';export FLEX_HOME="/Users/joelanderson/Downloads/MoonshineSDKs/Flex_SDK/Flex_4.16.1_AIR_33.1";export AIR_SDK_HOME="/Users/joelanderson/Downloads/MoonshineSDKs/Flex_SDK/Flex_4.16.1_AIR_33.1";export JAVA_HOME="/Users/joelanderson/Downloads/MoonshineSDKs/Java/openjdk-1.8.0";export ANT_HOME="/Users/joelanderson/Downloads/MoonshineSDKs/Ant/apache-ant-1.10.1";export MAVEN_HOME="/Users/joelanderson/Downloads/MoonshineSDKs/Maven/apache-maven-3.6.0";export GRADLE_HOME="/Users/joelanderson/Downloads/MoonshineSDKs/Gradle/gradle-7.5.1";export GRAILS_HOME="/Users/joelanderson/Downloads/MoonshineSDKs/Grails/grails-3.3.10";export HAXE_HOME="/Users/joelanderson/Downloads/MoonshineSDKs/Haxe/haxe-4.2.4";export NEKO_HOME="/Users/joelanderson/Downloads/MoonshineSDKs/Haxe/neko-2.3.0";export VIRTUALBOX_HOME="/usr/local/bin";export DYLD_LIBRARY_PATH="/Users/joelanderson/Downloads/MoonshineSDKs/Haxe/neko-2.3.0:/Applications/HCL Notes.app/Conten

This error didn't reproduce on Mojave.

Checking the [Apple documentation](https://developer.apple.com/library/archive/technotes/tn2065/_index.html#//apple_ref/doc/uid/DTS10003093-CH1-TNTAG1-HOW_LONG_CAN_MY_COMMAND_BE_), the limit is ~260,000 bytes, so we shouldn't be hitting a hard limit.

After some experimentation, @rat-moonshine found that adding a short delay (0.5 seconds) we were able to avoid this issue.  I did some updates and found this was working consistently.  I suspect that the 1024 number comes from a buffer, and the original code was interrupting the transmission before it finished.

**Comment by JoelProminic** [comment]
Here are some tests to run with the current build (on master):

Project | Custom SDKs | Selection | Expected | macOS
--------|-------------|-----------|----------|------
Flex Desktop | None | Project root | Open to project root, environment matches global SDK | 
Flex Desktop | None | Subdirectory | Open to selected directory, environment matches global SDK | 
Flex Desktop | None | Not the first open project | Open to selected project, environment matches selected project | 
Flex Desktop | Custom Flex SDK | Project root | Open to project root, environment uses custom SDK | 
Java Gradle | Default JDK | \- | Open to selected directory, use JDK 17 | 
Java Gradle | JDK 8 | \- | Open to selected directory, use JDK 8 | 
Java Maven | Default JDK | \- | Open to selected directory, use JDK 17 | 
Java Maven | JDK 8 | \- | Open to selected directory, use JDK 8 | 
Form Builder | N/A | \- | Open selected directory, use JDK 8 | 
Domino Visual Editor | N/A | \- | Open selected directory, use JDK 8 | 
Royale | None | \- | Open selected directory, environment matches global SDK | 
Royale | Custom SDK | \- | Open selected directory, environment matches global SDK | 
Other project | N/A | \- | Open selected directory, use selected environment | 

We'll need some coverage on Windows Command Line and Powershell  as well, but we probably don't need to duplicate all the above tests.

I'm tagging @JesseProminic to help with testing.  I'll update the test matrix if I have a chance to do more testing today.

**Comment by rat-moonshine** [comment]
> After some experimentation, @rat-moonshine found that adding a short delay (0.5 seconds) we were able to avoid this issue.

I gave some more tests to this today, and it appears that breaking the command in multi-execution do the tricks and it's do not requires the delay. I tested removing the 0.5 seconds delay and things are functioning as expected. 

Please, check this at some time.

**Comment by JesseProminic** [comment]
Project | Custom SDKs | Selection | Expected | macOS
-- | -- | -- | -- | --
Flex Desktop | None | Project root | Open to project root, environment matches global SDK |  :white_check_mark:  |
Flex Desktop | None | Subdirectory | Open to selected directory, environment matches global SDK |  :white_check_mark:  |
Flex Desktop | None | Not the first open project | Open to selected project, environment matches selected project |  :white_check_mark:  |
Flex Desktop | Custom Flex SDK | Project root | Open to project root, environment uses custom SDK |  :white_check_mark:  |
Java Gradle | Default JDK | - | Open to selected directory, use JDK 17 |  :white_check_mark:  |
Java Gradle | JDK 8 | - | Open to selected directory, use JDK 8 |  :white_check_mark:  |
Java Maven | Default JDK | - | Open to selected directory, use JDK 17 |  :white_check_mark:  |
Java Maven | JDK 8 | - | Open to selected directory, use JDK 8 |  :white_check_mark:  |
Form Builder | N/A | - | Open selected directory, use JDK 8 |  :white_check_mark:  |
Domino Visual Editor | N/A | - | Open selected directory, use JDK 8 |  :white_check_mark:  |
Royale | None | - | Open selected directory, environment matches global SDK |  :white_check_mark:  |
Royale | Custom SDK | - | Open selected directory, environment matches global SDK| :white_check_mark:  |

**Comment by rat-moonshine** [comment]
> With the latest build (2931), I got another cutoff error on macOS Catalina:

I re-introduced the delay for 0.5 seconds. Please, try once.

**Comment by JoelProminic** [comment]
This is working properly again on macOS Catalina.

@JesseProminic, please do some tests for the environments in Windows Command Line and Powershell .

**Comment by JesseProminic** [comment]
<!DOCTYPE html>

Project | Custom SDKs | Selection | Expected | Windows Command Line | Windows PowerShell |
-- | -- | -- | -- | -- | --
Flex Desktop | None | Project root | Open to project root, environment matches global SDK | ✅ | ✅ |
Flex Desktop | None | Subdirectory | Open to selected directory, environment matches global SDK | ✅| ✅ |
Flex Desktop | None | Not the first open project | Open to selected project, environment matches selected project | ✅| ✅ |
Flex Desktop | Custom Flex SDK | Project root | Open to project root, environment uses custom SDK | ✅| ✅ |
Java Gradle | Default JDK | - | Open to selected directory, use JDK 17 | ✅| ✅ |
Java Gradle | JDK 8 | - | Open to selected directory, use JDK 8 | ✅| ✅ |
Java Maven | Default JDK | - | Open to selected directory, use JDK 17 | ✅| ✅ |
Java Maven | JDK 8 | - | Open to selected directory, use JDK 8 | ✅| ✅ |
Form Builder | N/A | - | Open selected directory, use JDK 8 | ✅| ✅ |
Domino Visual Editor | N/A | - | Open selected directory, use JDK 8 | ✅| ✅ |
Royale | None | - | Open selected directory, environment matches global SDK | ✅| ✅ |
Royale | Custom SDK | - | Open selected directory, environment matches global SDK| ✅ | ✅ |

**Comment by JesseProminic** [comment]
![Screenshot 2022-12-12 at 10 48 01 AM](https://user-images.githubusercontent.com/96078188/207104195-4fa8da49-1f79-4c0b-b39e-25658644a75e.png)
 I still get this error and had to click 'OK' 16 times to get to the project (Windows).

**Comment by JoelProminic** [comment]
@JesseProminic, the svn.exe error is a [known issue](https://github.com/Moonshine-IDE/Moonshine-SDK-Installer/issues/3).  I recommend that you delete C:\MoonshineSDKs\SVN to clear these errors for now.

**Comment by JoelProminic** [comment]
The test coverage looks good on this, so I am closing the issue.
