### ISSUE TITLE
Updates for DominoParagraph

### ISSUE THREAD

**Issue by JoelProminic** [Moonshine-IDE/Moonshine-IDE#1041]
While discussing #675 with @piotrzarzycki21, there was some confusion about the meaning of DominoParagraph controls in Domino Visual Editor.  

The purpose of this control is to separate a group of components as a separate line or paragraph.  This is more like an HTML `<p>` than a `<div>`.  In Domino, the designer adds line breaks to handle this separation, but Visual Editor is based on layouts instead.

To clarify this behavior, I want to make the following changes:

The DominoParagraph control should have fixed values for the properties indicated below.  The properties should still be displayed for clarity, but they should not be editable.

Property | Editable | Value
---------|----------|------
Width | No | 100% (fill parent)
Height | No | Size to fit (checkbox disabled)
Direction | No | Horizontal
Wrap | No | True (Note that this may be affected by [alignment=none](https://github.com/Moonshine-IDE/Moonshine-IDE/issues/1008#issuecomment-1143839280))
Horizontal Align | Yes | Any option.  See the Alignment discussion in #1008.
Vertical Align | No | top
Hide Options | Yes | this may be changed freely

![image](https://user-images.githubusercontent.com/24532731/171509443-d0a096df-c0af-4547-9679-0aeed3ed03a0.png)

The other containers should default to Direction=Vertical, so that it is clear that the paragraphs will be arranged vertically.  We can cosider whether we want disable this option entirely for containsers - This could simplify the generation code, but it may be inconvenient for simple cases.  This should include:
- MainApplication
- Table cells
- Section
- TabView

NSFConverter may need to be updated to set the layout properties as discussed above.  This shouldn't change the resulting layout - the options above are meant to match the way DominoParagraph is used by NSFConverter and the Domino generation logic currently.

**Comment by piotrzarzycki21** [comment]
I have made an update to Paragraph properties. I need to still figure out why width is being displayed as value instead 100%. I didn't take care yet the other containers.

**Comment by piotrzarzycki21** [comment]
I have figure out how to display percentage values for Paragraph - it's been committed. I have also setup vertical layout for MainApplication and TabView - In order to do that for TableCells and Section I need a bit more investigation.

**Comment by piotrzarzycki21** [comment]
I think I'm done with this task. Just a notice to the wrap - I do select wrap property default, but always precedence have what is coming from intermediate XML, so you may notice that in opened project unselected. When you drag and drop new paragraph in Visual Editor it will be selected.

**Comment by JoelProminic** [comment]
Checking the Paragraph in the latest build (2604), it looks like the height is fixed to 40px, rather than sized to fit.  Also Hide options was removed - was this intentional?  Otherwise, this looks like I expect:
![image](https://user-images.githubusercontent.com/24532731/172471701-e9bbd4a3-efc4-4ce4-868d-6258f3964aec.png)

Once we have this working as expected I would like @feather812002 to update the defaults in NSFConverter, so we should be able to avoid the problem with unexpected values in the intermediate XML.

I checked the other containers

Container | Direction
----------|----------
Main Application | Vertical
Table (Cell Details | PROBLEM:  Horizontal 
Section | PROBLEM:  I do not see the layout fields here.  This may need to be a separte issue if we never had this layout.   I found in another test today that Section doesn't work well in general.
TabView | Vertical

**Comment by piotrzarzycki21** [comment]
> Also Hide options was removed - was this intentional?

Hide options wasn't merged to master as far as I know.

**Comment by piotrzarzycki21** [comment]
I have fixed Table Cell to make it Vertical. Let's leave section for separate issue if it is needed.

**Comment by piotrzarzycki21** [comment]
I have made changes where checkbox is unselected and component trying to fit to size. There is still number displayed in that box, but I don't want to change it for now.

**Comment by JoelProminic** [comment]
@feather812002, we need to update the default settings for components generated by NSFConverterPortalProject as described in the description above.   This is is needed to properly clear the unexpected behavior for #1033.   The default settings above should match how NSFConverter is using the components currently, but we'll need to retest database conversion to confirm it still generates the database correctly.

**Comment by feather812002** [comment]
@JoelProminic I already done the setting default for "MainApplication" and "TabView"
But TableCell and Section, I can't found the correct potion place the default direction .

And I see you add these as "PROBLEM", so maybe we need check this more in here ?

**Comment by JoelProminic** [comment]
TableCell (`<Column>` in the intermediate XML) has a nested Div to handle the layout, similar to how we handled TabView.

Section doesn't have the nested Div, though, so this will [take more work](https://github.com/Moonshine-IDE/Moonshine-IDE/issues/1041#issuecomment-1149698349).  I'm fine with revisiting this later.

The DominoParagraph options look good except for the Wrap checkbox.  This should be defaulted in `nsf-converter-portal` so that it is checked.
![image](https://user-images.githubusercontent.com/24532731/186018098-d7de5b98-e952-45f8-b8de-965b5757f93d.png)

**Comment by JoelProminic** [comment]
I moved the remaining issues to [NSFConverterPortalProject](https://github.com/Moonshine-IDE/NSFConverterPortalProject/issues/20) (private) so that we can close this issue for the release.
