### ISSUE TITLE
Sorting Mange Repository > Browse Entries

### ISSUE THREAD

**Issue by rat-moonshine** [Moonshine-IDE/Moonshine-IDE#1044]
From @JustinProminic 

--------------------------------

On the one hand, maybe it is useful to allow the project browser to define the order things appear.

On the other hand, it seems like the result is an unsorted list that is hard to read.

My vote is to auto-sort the list automatically.

In generally, whenever anything is found in an unsorted fashion, I will at some point ask that it be sorted once I realize it is happening.

![image](https://user-images.githubusercontent.com/24370870/172115156-48166e09-bde5-4c8d-804a-d0a2d9a3a1ce.png)

**Comment by rat-moonshine** [comment]
From @JoelProminic 

-----------------------------

Our strategy was to preserve the sorting from moonshine-dependencies.xml:
https://github.com/Moonshine-IDE/Moonshine-IDE/issues/503#issuecomment-504095503

This seems to be the current behavior.  For example:
![image](https://user-images.githubusercontent.com/24370870/172342639-d295b29c-49cf-47fd-895f-8e0e2df96f97.png)

The idea was that the project developer would have control for an appropriate ordering for the project.  In this case, you can see I had some grouping in the XML, but this grouping is not represented in the XML.

That said, the ordering does not look very intentional for this project currently - I also initially assumed from your screenshot that the entries were unsorted.  This could make more sense as we add othe prrojects to this list (i.e. Flex Input Agents and Flex Bugs Agents), but I'm not sure how much benefit we are getting with the current logic.

I think we have discussed adding subdirectories for this feature.  This would allow us to group the projects logically, and then each directory could be sorted alphabetically if desired.

**Comment by JoelProminic** [comment]
@JustinProminic confirmed that we should sort this alphabetically.  If we really want to sort the entries in the file instead, we can prefix numbers.

**Comment by rat-moonshine** [comment]
I'm unclear how we wants to approach this. Are you planning to change the ordering from XML side, or Moonshine requires to order alphabetically at UI side?

**Comment by rat-moonshine** [comment]
Auto-sort items now being added to the children in `Tree` component. Please, check.

**Comment by JoelProminic** [comment]
I tested with a couple projects, and the sorting looks good.
