### ISSUE TITLE
UI Error Texts Unable To Read

### ISSUE THREAD

**Issue by rat-moonshine** [Moonshine-IDE/Moonshine-IDE#1045]
From @JustinProminic 

------------------------------

I have a very hard time reading the "Destination path is already exists."

Also, that is not proper English.  It should state "Destination path already exists.".

Can you please change the color scheme?

For some reason, the screen shot below is easier to read than in Moonshine, but it is still really difficult to read.

I think it should be yellow or something.

It really strains my eyes reading it and I have a very hard time seeing it for some reason.

Please look for other examples like this and also change them.

![image](https://user-images.githubusercontent.com/24370870/172115710-b7f39a35-4f77-4f80-a8cc-66843c2ba78e.png)

**Comment by rat-moonshine** [comment]
Usually, I would expect an error text label in red. I added a background colour to increase readability while keeping the text colour in red, please give this a test if this feels more easier (to read).

![image](https://user-images.githubusercontent.com/24370870/172346483-293bb923-17cf-4d09-9566-0474f7fa1797.png)

**Comment by JoelProminic** [comment]
This is easier to read, but it looks very out of place to me.  Maybe it would look better with a bit more padding and a thin border?

As I looked at this more while writing my comment, it began to feel more unpleasant.  It is still much better than the original, but maybe we need a darker shade of red.

Did you find any other examples of the red text on a grey background.  Was the previous CSS class shared elsewhere?

**Comment by rat-moonshine** [comment]
At this point this is the most easiest approach to handle error-text-label. We're only using available CSS styling to `Label` component where `backgroundColor` is available. I can try to add paddings but there is not border property available to `Label` CSS. Having border may require more complicated approach, like a separately created background element behind the `Label`, i.e. `Rect` etc. Although, using a `styleName=$StyleName` approach to any `Label` is more easiest, which we currently using.

**Comment by rat-moonshine** [comment]
![image](https://user-images.githubusercontent.com/24370870/172565733-29ac8798-22b3-43eb-8de5-ebda1983e451.png)

I made some alteration in colours, padding. Hopefully, this looks more proper than the previous version.

**Comment by JoelProminic** [comment]
I think this looks a better, but it still looks out of place in the interface.  We can discuss this in the meeting.

Also, the text is still wrong.  @JustinProminic requested we change this to "Destination path already exists."

**Comment by JoelProminic** [comment]
Some other interfaces that may need this format:
- SVN/Git Authentication errors
- Duplicates in Git > New Branch
- Duplicates in File > Workspace > Create Workspace - I see this uses a different format (Also, this should be "Workspace already exists.":

![image](https://user-images.githubusercontent.com/24532731/172660913-1b647971-a9bb-459c-8c72-51b0b8dffc23.png)


I expect that there are other cases I am forgetting here, but hopefully this will give us ideas for finding similar cases.

**Comment by JoelProminic** [comment]
We discussed this in the meeting today, and we would like to use the format from New Workspace for all of these errors.

**Comment by rat-moonshine** [comment]
I have updated error display styling in following popups for now:
- Repository clone
- Add repository
- New branch
- Switch branch

**Comment by JoelProminic** [comment]
Action | Update
-------|-------
Repository clone | Confirmed
Add repository | Can't reproduce - duplicates here trigger a popup instead
New branch | Wrong color - see below
Switch branch | Can't reproduce - how do I trigger an error with this format in this interface?


For New Branch, I see that the format for the Loading status was also updated, with a different text color (note that this is a strange project with a local configuration as the "remote", so don't worry to much about why this failed for now)

![image](https://user-images.githubusercontent.com/24532731/176552491-9ad7523f-ceda-406f-8464-d087210c0dbe.png)

For the actual error message, the color was also wrong:

![image](https://user-images.githubusercontent.com/24532731/176552549-1bd64beb-a0bb-4aa2-946d-897c4e011bdb.png)

**Comment by rat-moonshine** [comment]
Following are the scenario when a message appears in respective popups:
- Add Repository: SVN/Git is not present
- Switch Branch: Git is not present

I have updated text colouring in New Branch window.

**Comment by JoelProminic** [comment]
Action | Update
-------|-------
Repository clone | Confirmed
Add repository | Confirmed
New branch | Colors fixed
Switch branch | Still can't test - Git > Switch Branch is disabled if Git is not configured.  This may be a legacy error
