### ISSUE TITLE
ArgumentError: Cannot open branch because it is not in the data provider - TreeView/toggleBranch()

### ISSUE THREAD

**Issue by piotrzarzycki21** [Moonshine-IDE/Moonshine-IDE#1051]
I'm getting following error in console after launching Moonshine:

```
Cannot open branch because it is not in the data provider.
: ArgumentError: Cannot open branch because it is not in the data provider.
: 	at feathers.controls::TreeView/toggleBranch()
: 	at moonshine.plugin.problems.view::ProblemsView/problemsView_problems_addItemHandler()
: 	at flash.events::EventDispatcher/dispatchEvent()
: 	at moonshine.plugin.problems.data::DiagnosticHierarchicalCollection/setDiagnostics()
: 	at actionScripts.plugin.problems::ProblemsPlugin/handleShowDiagnostics()
: 	at flash.events::EventDispatcher/dispatchEvent()
: 	at actionScripts.languageServer::ActionScriptLanguageServerManager/languageClient_publishDiagnosticsHandler()
: 	at flash.events::EventDispatcher/dispatchEvent()
: 	at moonshine.lsp::LanguageClient/textDocument__publishDiagnostics()
: 	at moonshine.lsp::LanguageClient/parseNotificationMessage()
: 	at moonshine.lsp::LanguageClient/parseMessage()
: 	at moonshine.lsp::LanguageClient/parseMessageBuffer()
: 	at moonshine.lsp::LanguageClient/parseMessageBuffer()
: 	at moonshine.lsp::LanguageClient/languageClient_input_onData()
```

**Comment by joshtynjala** [comment]
I can reproduce this issue if I close my Problems view and restart Moonshine (so that the Problems view is not already open at startup). Thanks!

**Comment by piotrzarzycki21** [comment]
@joshtynjala when you push fix for some view to Haxe lib without actually that swc - I need in my dev environment build it yourself probably. Is it not suppose to be pushed as well ?

**Comment by joshtynjala** [comment]
I usually push the .swc when there are new/changed classes referenced from the .as/.mxml files. I tend to skip it for bug fixes that don't affect the public API, to avoid making our Git repo ridiculously huge with binaries. It's already a surprisingly long download when someone clones the repo for the first time (as I recall, Git downloads the entire history). I prefer not to make that significantly worse by pushing every minor .swc change.

I could probably be convinced to always commit the .swc, though, if you think it's really important.

**Comment by piotrzarzycki21** [comment]
> I usually push the .swc when there are new/changed classes referenced from the .as/.mxml files. I tend to skip it for bug fixes that don't affect the public API, to avoid making our Git repo ridiculously huge with binaries. It's already a surprisingly long download when someone clones the repo for the first time (as I recall, Git downloads the entire history). I prefer not to make that significantly worse by pushing every minor .swc change.
> 
> I could probably be convinced to always commit the .swc, though, if you think it's really important.

It is very rare when bug do not allow me even use Moonshine trough my IDE and this is the case which I believe would be worth to have it pushed. I just build swc on my own locally so I will be good.
