### ISSUE TITLE
Ant Build Does Not Fail on Apple Signing Command Errors

### ISSUE THREAD

**Issue by JoelProminic** [Moonshine-IDE/Moonshine-IDE#1052]
We recently saw a Moonshine build (2587) where [these exec tasks](https://github.com/Moonshine-IDE/Moonshine-IDE/blob/c3cd6d11ccc520287c27491939dc1dc76bd4ac06/ide/MoonshineSharedCore/build/build-lib.xml#L680-L688) on the Bamboo server.  However, the build was considered successful, and we saw [many problems and odd behaviors](https://github.com/Moonshine-IDE/Moonshine-IDE/commit/5c8fa20505f8e2f9df156e98a64afd07ef799383#commitcomment-75401910) while testing.   We are not sure why this error caused so many errors, but we need to make sure it fails the build in the future.

    build	TIMESTAMP	     [exec] DEPLOY/MoonshineDevelopment.app: replacing existing signature
    error	TIMESTAMP	     [exec] Result: 139
    build	TIMESTAMP	     [echo] Signing checks on Non-Sandbox APP: spctl -vvv --assess --type exec DEPLOY/MoonshineDevelopment.app
    build	TIMESTAMP	     [exec] DEPLOY/MoonshineDevelopment.app: invalid resource directory (directory or signature have been modified)
    error	TIMESTAMP	     [exec] Result: 1

Exit code 139 seems to indicate an [error with the timestamp server](https://developer.apple.com/forums/thread/680876).

I see many `<exec>` tasks in this `buildAppStorePKG` target.  To make these trigger an error, we can use the `failonerror="true"` attribute ([example](https://github.com/Moonshine-IDE/Moonshine-IDE/blob/c3cd6d11ccc520287c27491939dc1dc76bd4ac06/ide/MoonshineSharedCore/build/build-lib.xml#L662)) to make it fail the Ant script on an error.  

I am mainly interested in alerting on the above signing commands, but it may be worth doing a full review.  However, some `exec` commands may be allowed/expected to fail, like `rm` commands that are just needed to ensure that the file doesn't exist.  (These should probably use the [delete task with failonerror="false"](https://ant.apache.org/manual/Tasks/delete.html) instead, but we don't necessarily need to change this now).  [Example](https://github.com/Moonshine-IDE/Moonshine-IDE/blob/c3cd6d11ccc520287c27491939dc1dc76bd4ac06/ide/MoonshineSharedCore/build/build-lib.xml#L615-L618)

    build	TIMESTAMP	     [exec] rm: DEPLOY/MoonshineDevelopment.app/Contents/Frameworks/Adobe AIR.framework/Versions/1.0/Adobe AIR_64 Helper: No such file or directory
    error	TIMESTAMP	     [exec] Result: 1

**Comment by rat-moonshine** [comment]
I did some updates to Ant build script. I mainly concentrated in `buildAppStorePKG` and `signItemsBeforePackaging` targets. 

I worked on mostly `replace` and `exec` tasks along with a few others. In above two targets if any task do not has fail-error property then that is either intentional or doesn't available. 

I tested locally and this is all good so far. I'm committing the changes.

**Comment by JoelProminic** [comment]
The Bamboo builds are still working after your updates, which is a good sign that you didn't add the `failonerror` attribute to the wrong task.

Remaining tests:
- I should review the script briefly
- We can test `buildAppStorePKG` with a disabled network connection to trigger the timestamp server error.

**Comment by rat-moonshine** [comment]
I gave some tests by triggering network off during Ant builds, and they seems to be working expected way.

Based on my time to attempt (network off) it hits both the time at following line.

```
[exec] DEPLOY/MoonshineDevelopment.app/Contents/Resources/META-INF/AIR/extensions/karar.santanu.SecurityScopeBookmark/META-INF/ANE/MacOS-x86-64/SecurityScopeBookmark.framework/Versions/A: signed bundle with Mach-O thin (x86_64) [karar.santanu.SecurityScopeBookmark]
     [exec] DEPLOY/MoonshineDevelopment.app: replacing existing signature

BUILD FAILED
/Users/devseba/Documents/ProminicGITBranch/Moonshine-IDE/ide/MoonshineSharedCore/build/build-lib.xml:254: The following error occurred while executing this line:
/Users/devsena/Documents/ProminicGITBranch/Moonshine-IDE/ide/MoonshineSharedCore/build/build-lib.xml:639: exec returned: 139

Total time: 5 minutes 47 seconds
```
Above thrown on [line](https://github.com/Moonshine-IDE/Moonshine-IDE/blob/master/ide/MoonshineSharedCore/build/build-lib.xml#L639) as soon network turned off.

**Comment by JoelProminic** [comment]
Great!  I did a quick review of the changes, and they look reasonable to me.  I think this should be what we need.
