### ISSUE TITLE
Variables Entries in Debug is Un-selectable 

### ISSUE THREAD

**Issue by rat-moonshine** [Moonshine-IDE/Moonshine-IDE#1054]
While I was debugging a Royale application using Moonshine Development v3.3.3 Build 2641 on macOS, 
![image](https://user-images.githubusercontent.com/24370870/174768477-25db4d13-c88e-4852-908e-1d917ce4b9b9.png)

I noticed that the "Variables" section items are un-selectable thus un-expandable:

![image](https://user-images.githubusercontent.com/24370870/174768572-691f4f37-5fa4-4486-af8f-c88b43d5f3a0.png)

**Comment by joshtynjala** [comment]
Confirmed. I can reproduce with Feathers UI rc.2, but it works correctly with rc.1.

Interestingly, selection is still working correctly for the TreeView instances inside OutlineView and ProblemsView. Hopefully, this means that I simply need to tweak the custom collection used by the variables tree, and that it doesn't require a new release of Feathers uI.
