### ISSUE TITLE
[Domino Visual Editor] Paragraph Alignment Options

### ISSUE THREAD

**Issue by JoelProminic** [Moonshine-IDE/Moonshine-IDE#1055]
This issue has been extracted from #1008.  We want to convert these options from Domino Designer:

![image](https://user-images.githubusercontent.com/24532731/160937146-ab1f75ce-3253-42b1-9989-0a97f3436c5a.png)

@feather812002 has already started working on this, but we wanted to stop the updates so that we could merge.  The interface currently looks like this:

![image](https://user-images.githubusercontent.com/24532731/176019807-91f87b7e-fe05-498f-bfbc-0cf343a68944.png)

Remaining problems:
- The horizontal alignment selection does not match the actual field value.
- The other options use the "default" value, ignoring the actual field/paragraph settings
- The icons are all the same for First Line.  If we need to create new icons for this, @rat-moonshine may be able to help

Note that the First Line options are actually applied to the `<pardef>` in the DXL, so the same options need to be used for the entire Paragraph.  Also, since these options are implemented using the margin settings, they can be affected by changes in the margins (a Text/paragraph property).

Branch:  features/issue_1055_paragraph_alignment_options
Bamboo Builds:  https://static.moonshine-ide.com/downloads/releases/dev/macos/branches/features/issue_1055_paragraph_alignment_options
Test Database:  https://moonshine-ide.com/downloads/releases/dev/macos/branches/features/issue_1008_add_addtional_field_properties/TestFieldOptions_1008_4.nsf

**Comment by feather812002** [comment]
I already create 3 branch for  and MockupVisualEditor and VisualEditorConverterLib for this .
[Moonshine-IDE](https://github.com/Moonshine-IDE/Moonshine-IDE/tree/features/issue_1055_paragraph_alignment_options)

**Comment by JoelProminic** [comment]
I ran some tests on today's updates (new Moonshine build, fresh TestFieldOptions_1008_4.nsf export from latest NSFConverter).  I got this error when first opening a field with FirstLine properties set (TestIndent):

    : Error #1009
    : TypeError: Error #1009
    : 	at view.domino.propertyEditors::InputTextPropertyEditor/initializeAlign()
    : 	at view.domino.propertyEditors::InputTextPropertyEditor/onInputCreationComplete()
    : 	at view.domino.propertyEditors::InputTextPropertyEditor/___InputTextPropertyEditor_BasePropertyEditor1_creationComplete()
    : 	at flash.events::EventDispatcher/dispatchEvent()
    : 	at mx.core::UIComponent/dispatchEvent()
    : 	at mx.core::UIComponent/set initialized()
    : 	at mx.managers::LayoutManager/doPhasedInstantiation()
    : 	at mx.managers::LayoutManager/doPhasedInstantiationCallback()
    :
    : Click here to Report a Bug

I see that the alignment option was not displayed properly.

![image](https://user-images.githubusercontent.com/24532731/177396482-2ffe47f7-7fb1-42e6-8e98-d52cfc0cf30c.png)

I continued getting this error for each field I checked, even if they didn't have First Line properties:

I tried adding a new field, but I got the same error.   I updated the settings manually, but they were not displayed when I reopened the form.  I do see the options in the generated DXL, though:

```
![image](https://user-images.githubusercontent.com/24532731/177396643-86a09567-0597-42a7-b90b-78147ec919ea.png)
```

Note that Indent should be {{0.25}} by default in the UI.


I tried building the database anyway, but I found that the indent settings (and alignment) did not seem to have any effect:
![image](https://user-images.githubusercontent.com/24532731/177396771-182b81c3-9181-499f-827f-aefbaec4be7c.png)

**Comment by JoelProminic** [comment]
I did some tests with today's Moonshine build.

First Line option is displaying properly now in Moonshine, without errors.  However, I'm seeing that the editor tab is flagged as modified when I select any field, so I can't explore the design without triggering "modifications".  I'm not sure what is actually changing here, if anything.


Checking the generated database, I see that Alignment is working like I expect now.   Indent also looks good, but the outdent is indenting the entire field

![image](https://user-images.githubusercontent.com/24532731/178042775-0b1cde6e-965a-4452-8dcb-2b1b6fbd2f72.png)

I see the outdent is working properly for the extended margin, though:

![image](https://user-images.githubusercontent.com/24532731/178042800-1ffce28d-a16e-4f0f-aebf-ee95957fda47.png)

**Comment by JoelProminic** [comment]
I tested the Spacing property updates.   I tested with the TestAlignment form in TestFieldOptions_1008_4.nsf.  Expected format:

![image](https://user-images.githubusercontent.com/24532731/178355645-7bb57a79-40a5-45cf-a742-e69b54a67c6e.png)

I found that the spacing fields are only set to "single", even for fields with custom settings like TestInterline and TestAbove.

I generated the database, and I found that it did not match the original properties

![image](https://user-images.githubusercontent.com/24532731/178355660-31103139-de53-4235-9cb8-1fa0f9ef555c.png)

I'm still seeing that the editor is flagged as modified any time I select a DominoInputText.  I also noticed this error when closing the unsaved tab:

    : Error #1009
    : TypeError: Error #1009
    : 	at mx.containers::Accordion/focusInHandler()
    : 	at mx.core::UIComponent/setFocus()
    : 	at mx.managers::FocusManager/setFocus()
    : 	at mx.managers::FocusManager/activate()
    : 	at mx.managers.systemClasses::ActiveWindowManager/deactivateForm()
    : 	at mx.managers.systemClasses::ActiveWindowManager/deactivate()
    : 	at mx.managers.systemClasses::ActiveWindowManager/removeFocusManager()
    : 	at mx.managers::PopUpManagerImpl/popupRemovedHandler()
    : 	at mx.managers::SystemManager/http://www.adobe.com/2006/flex/mx/internal::rawChildren_removeChild()
    : 	at mx.managers::SystemManager/removeChild()
    : 	at mx.managers::PopUpManagerImpl/removePopUp()
    : 	at mx.managers::PopUpManager$/removePopUp()
    : 	at actionScripts.controllers::CloseTabCommand/cleanUp()
    : 	at actionScripts.controllers::CloseTabCommand/closeTab()
    :
    : Click here to Report a Bug

**Comment by feather812002** [comment]
Report from @JoelProminic 
1. Create a new Domino Visual Editor project
2. Click the target icon to open the project tree to the file.  Note that nsfs/nsf-moonshine/target is not visible
3. Add a label and save
4. Project > Build with Apache Maven
5. The build completed.  BUG:  nsfs/nsf-moonshine/target does not appear in the project tree, but I confirmed it is on the filesystem


I test this in latest version from branch :
![image](https://user-images.githubusercontent.com/8543391/178969061-463a5c9d-71f3-4007-ba48-7ad57088aa98.png)


As you see , in  the latest version of branch ,it work fine , I can get the target folder 

So, you got this maybe just cause I not merge the latest version into branch on your test time .

**Comment by JoelProminic** [comment]
Thanks for testing the file update issue.  I couldn't reproduce this either since yesterday's update.   I figure that the filewatcher updates were in an incomplete state the last time you merged master into this branch.

I'm still seeing the issue with the edited flag in the tab:
1. Export a fresh project zip with NSFConverter (I didn't see any updates here today)
2. Unzip and open in Moonshine
3. Open TestAlignment.form
4. Click TestLeft. BUG:  the tab shows as edited.

I'm testing with [build 580](https://bamboo.prominic.net/chain/result/viewChainResult.action?planKey=MS-BMOB&buildNumber=580), triggered by commit `983c1029d...` on MockupVisualEditor.  I tried to build this directly from the source, but I got stuck on some configuration issues.

**Comment by JoelProminic** [comment]
Revisiting the other updates:

#### Alignment

I see that "Justified" behaves the same as "Left" in this test form, but this consistent with the behavior of the original form.   Otherwise, these look good.
![image](https://user-images.githubusercontent.com/24532731/179079508-636f055b-560a-4cd7-bf6a-7f81d4b03b66.png)


#### Indent

There is a problem with Outdent - the first line has the same indent/margin as the rest of the paragraph.

#### Line Spacing

There is an extra line above each of the fields used to test line spacing.  I see there is an empty Label between the `-----` paragraph and the field.  Otherwise this looks good.

#### List

The bullets look like what I see in the original database.

**Comment by JoelProminic** [comment]
@JesseProminic, when you have a chance please do some tests with this update.   You can get the latest build and test database (TestFieldOptions_1008_4.nsf) with the links in the description.  In particular:
- Do some tests with other test databases, and check for new discrepancies.
- Check the behavior of the options in the Paragraph Alignment tab from the editor to make sure they are working well for manual updates.

**Comment by feather812002** [comment]
@JoelProminic , I confirm this "firstlineleftmargin" is empty error , it cause latest update.

I confirm I can build success at now .

**Comment by JoelProminic** [comment]
I see some remaining edit issues with the First Line property.
- If I select a field with no configured indent, the tab is flagged as edited.  We think this is because the indent value is being set
- If I select Indent or Outdent, the text field gets set to 0.  Instead, I expect this to be set to `0.25` to match Domino Designer.

I reminded @rat-moonshine that we need updated icons for First Line.  See the description for the example from Domino.  This is not an urgent priority, so we can move this to a new issue if it will take longer to fix.

**Comment by rat-moonshine** [comment]
> I reminded @rat-moonshine that we need updated icons for First Line. See the description for the example from Domino. This is not an urgent priority, so we can move this to a new issue if it will take longer to fix.

I added three icons, but I don't have a good way to test this. Please, check.

**Comment by JoelProminic** [comment]
The updated First Line logic looks good:

Test | Flagged as edited | Indent Value
-----|-------------------|-------------
Open field with no indent | No | Hidden
Change from no indent to indent | Yes | 0.25
Change from no indent to outdent | Yes | 0.25
Change from indent to outdent | Yes | 0.25
Change from indent to no indent | Yes | Hidden
Change from outdent to indent | Yes | 0.25
Change from outdent to no indent | Yes | Hidden
Custom indent, click indent again | Yes | Resets to 0.25

**Comment by JoelProminic** [comment]
@rat-moonshine, I confirmed the new icons.  This should work:

![image](https://user-images.githubusercontent.com/24532731/180565264-8722bcac-a6c2-4265-a847-79903345f052.png)

**Comment by JoelProminic** [comment]
I retested the TestAlignment form in the [example database](https://moonshine-ide.com/downloads/releases/dev/macos/branches/features/issue_1008_add_addtional_field_properties/TestFieldOptions_1008_4.nsf), and it worked like I expected:
![image](https://user-images.githubusercontent.com/24532731/194671137-92a175e1-a2e6-4029-b52d-2420c9b353d2.png)

However, @JesseProminic saw strange behavior with a manual example on the HostMyApple machine (Notes 12).  The bullets are cut off, and they extend to the following labels:
![image](https://user-images.githubusercontent.com/24532731/194671304-1c614824-7c93-44ad-9e3a-b95d41d535b5.png)

I checked the configuration and DXL and I didn't see an obvious problem.

**Comment by JoelProminic** [comment]
I rebuilt the project locally, and I did not get any list bullets:
![image](https://user-images.githubusercontent.com/24532731/194672396-e6698fce-9cbb-404f-b6ec-2d4922920df3.png)

For reference, here is the test project.  I confirmed that the List settings were all reset to "none" in this copy, but I'm not sure when this happened.:  
[paragraphListSpacingOct7_clean.zip](https://github.com/Moonshine-IDE/Moonshine-IDE/files/9737773/paragraphListSpacingOct7_clean.zip)

**Comment by feather812002** [comment]
@JoelProminic  I build this on local machine and open it with Notes 12.
It look like fine , and I not get the bullets cut off:
![image](https://user-images.githubusercontent.com/8543391/195100483-3e5c3c64-1da9-4d8e-918c-87f23e8cb447.png)

**Comment by JoelProminic** [comment]
@JesseProminic couldn't reproduce this behavior in her latest tests either.  The other behavior looks good, so I'm going to close this for the 3.3.3 release.  If we find more trouble with the List properties (or the edit flag logic on these fields), we can create a new issue.
