### ISSUE TITLE
[Domino Visual Editor] Help and Hint Properties Broken

### ISSUE THREAD

**Issue by JoelProminic** [Moonshine-IDE/Moonshine-IDE#1056]
While testing Domino Visual Editor before the #1008 merge today, I noticed that the Help Description and Field Hint properties in the DominoInputText Advanced tab are not working properly.  I'm pretty sure these were working at some point while testing #1008.   For today's test, I used the TestHelpAndHint form in [TestFieldOptions_1008_4.nsf](https://moonshine-ide.com/downloads/releases/dev/macos/branches/features/issue_1008_add_addtional_field_properties/TestFieldOptions_1008_4.nsf).

![image](https://user-images.githubusercontent.com/24532731/176318774-d293ea49-ea1e-40a6-8fc4-d3d7c1defa21.png)

The converted database looks like this:

![image](https://user-images.githubusercontent.com/24532731/176318803-96c1343e-0f88-4f6c-b839-c6154e740eb3.png)

I checked the properties in Moonshine, and the Help Description and Field Hint were not set for any of the fields in this form.

![image](https://user-images.githubusercontent.com/24532731/176318820-56b67768-1c12-417c-8032-f2f18df382b3.png)

I tried setting the properties from within Moonshine to confirm if there was a problem on the Moonshine side.  I found that only the Description showed up in the generated database.

**Comment by feather812002** [comment]
I found this issue cause the NSFConvet not export the "Help" and "Hint" properties.
So I to do some fix on this , and test it again : 
- TestHelpOnly 
   
![image](https://user-images.githubusercontent.com/8543391/176427111-5faee43b-7354-4ee6-91b0-e3950fa80ed7.png)

- TestHintOnly
![image](https://user-images.githubusercontent.com/8543391/176427151-745f3600-e772-434e-a879-8e2fd1468133.png)

- TestBoth
   
![image](https://user-images.githubusercontent.com/8543391/176427214-7b39c72d-45de-49c8-8853-0ff7c44fcf42.png)

- TestSpecial
![image](https://user-images.githubusercontent.com/8543391/176427258-2cc98ba8-8ce2-47da-9433-322320cc9451.png)


After some test for generate NSF database with ODP , I got follow UI:
![image](https://user-images.githubusercontent.com/8543391/176432172-89bcc63c-34af-4e01-ac03-5de09beac6df.png)

**Comment by JoelProminic** [comment]
I confirmed that the Help and Hint options are working properly now.  This will be merged along with #1056.
