### ISSUE TITLE
Importing Generated CRUD Agents to Domino Database

### ISSUE THREAD

**Issue by JoelProminic** [Moonshine-IDE/Moonshine-IDE#1062]
Now that we have generated code for the Java agents (#978), we need a way to import them into a Domino database so that they can be called by the application.  I have a couple ideas for this:

### DXL Importer

DXL Importer (#668, #935) should be able to handle this.  I have some examples to run DXL Importer from Gradle, but this will need more work to support multiple agents.

I envision this workflow:
1. Generate a separate Java project with agentProperties files.
2. Generate the NSF and deploy it to a server
3. Run DXL Importer to build the agent to the target server and database.

Advantages:
- Existing, tested tool
- Can be used in future development
- Works with Gradle - this will make it easier to add more logic.

Disadvantages:
- Messy configuration files. This can be improved with some cleanup and comments in the short term, and with a custom editor in the future
- DXL Importer code is not in GitHub yet
- Dependencies on other third-party libraries (needs cleanup)

### NSFODP

I checked some NSFODP examples with NSFConverterPortalProject/nsf-to-odp-exporter.  I can call it from the command line like this:

    java -cp target/nsf-to-odp-exporter-1.0.2-jar-with-dependencies.jar:../domino-nsf-converter-jars/lib/domino-notes-9.0.1.8.1.jar:../domino-nsf-converter-jars/lib/lwpd-commons-9.0.1.10.jar:../domino-nsf-converter-jars/lib/lwpd-domino-napi-9.0.1.10.jar:../domino-nsf-converter-jars/lib/websvc-9.0.1.10.jar net.prominic.Exporter <database> <target_directory>
    # Example:
    java -cp target/nsf-to-odp-exporter-1.0.2-jar-with-dependencies.jar:../domino-nsf-converter-jars/lib/domino-notes-9.0.1.8.1.jar:../domino-nsf-converter-jars/lib/lwpd-commons-9.0.1.10.jar:../domino-nsf-converter-jars/lib/lwpd-domino-napi-9.0.1.10.jar:../domino-nsf-converter-jars/lib/websvc-9.0.1.10.jar net.prominic.Exporter ../TestFieldOptions_1008_4.nsf tmp_odp

I see agents exported to odp/Code/Agents/*.ja.  For non-imported agents, .ja files contain the source code.  Here is an example fo the agent format:
```
<?xml version="1.0" encoding="utf-8"?>
<!-- For the attributes, we need at least name, hide, publicaccess, and restrictions-->
<agent xmlns="http://www.lotus.com/dxl" name="CorrectVMHost" version="11.0" replicaid="8625888000684D9E" hide="notes web v3" publicaccess="false" designerversion="8.5.3" restrictions="unrestricted" activatable="false">
  <!-- skip noteinfo through designchange - don't make sense locally -->
  <noteinfo noteid="4fe" unid="-snip-" sequence="8">
    <created>
      <datetime>20210107T121829,59-06</datetime>
    </created>
    <modified>
      <datetime dst="true">20220715T135932,75-05</datetime>
    </modified>
    <revised>
      <datetime dst="true">20220527T123745,54-05</datetime>
    </revised>
    <lastaccessed>
      <datetime dst="true">20220715T135932,74-05</datetime>
    </lastaccessed>
    <addedtofile>
      <datetime dst="true">20220715T135932,74-05</datetime>
    </addedtofile>
  </noteinfo>
  <updatedby>
    <name>CN=Joel ...</name>
  </updatedby>
  <wassignedby>
    <name>CN=Joel ...</name>
  </wassignedby>
  <designchange>
    <datetime dst="true">20220527T123746,61-05</datetime>
  </designchange>
  <!-- This "trigger" section is also important.  This should be simpler for unscheduled agents -->
  <trigger type="scheduled">
    <schedule type="daily" runlocation="specific" runserver="CN=domino-49.prominic.net/O=PNI">
      <starttime>
        <datetime>T024500,00</datetime>
      </starttime>
    </schedule>
  </trigger>
  <code event="action">
    <!-- make sure javaproject.class matches java.name
    <javaproject class="com.Prominic.sh.populate.CorrectZoneHost.class" codepath="H:\HCL\Notes\Data" compiledebug="true">
      <!-- the <java> tag can contain raw source code.  Would it be easier to include the binaries here? -->
      <java name="com/Prominic/sh/populate/CorrectZoneHost.java">package com.Prominic.sh.populate;
...
</java>
      <!-- The script libraries are added like this -->
      <sharedlibraryref name="StringUtils"/>
      <sharedlibraryref name="PopulateAgentBase"/>
      <sharedlibraryref name="EmailAlert"/>
    </javaproject>
  </code>
  <!-- ignore rundata -->
  <rundata processeddocs="0" exitcode="0" agentdata="A0CB8310A3A3270A8625884F0060E36F">
    <agentmodified>
      <datetime dst="true">20220527T123745,55-05</datetime>
    </agentmodified>
    <agentrun>
      <datetime dst="true">20220715T024607,56-05</datetime>
    </agentrun>
    <runlog>Started running agent 'CorrectVMHost' on 07/15/2022 02:45:38 AM
Found 0 document(s) that match search criteria
Ran Java Agent Class
Done running agent 'CorrectVMHost' on 07/15/2022 02:46:07 AM
</runlog>
  </rundata>
  <!-- the compiler levels may be relevant -->
  <item name="$JavaCompilerSource">
    <text>1.3</text>
  </item>
  <item name="$JavaCompilerTarget">
    <text>1.2</text>
  </item>
</agent>
```

This doesn't look too hard to generate.  The workflow for this solution would be like:
1. Generate the agent source to `src/main/java` (or `nsfs/nsf-moonshine/odp/Code/Java`
2. Add new template files for the agents under visualeditor-src.  This will contain:
    - settings for the agent properties
    - a definition of the Java or JAR that should be included.  We could simplify this to always include the full JAR for the Java source
3. Also define a script library to include at least the Moonshine-Domino-CRUD JAR
4. When building the nsfodp project:
    - Compile the Java code
    - Generate the .ja files and script libraries with the configuration properties and compiled/source code
    - run normal nsfodp compilation

Advantages: 
- Don't need a separate step to import and sign the agents

Disadvantages
- In some ways, this is like a fresh implementation of DXL Importer.  Hopefully we can reuse the code, but we'll need to work at a lower level than if we reuse DXL Importer.
- We would need another method to update agents after the database design is "finallized" and the user begines making customizations.  DXL Importer could be used for both cases
- We would need more work with Maven to get the agent generation integrated into the build (if this is not already configured in nsfodp compiler).  Perhaps we could move the configuration files to Gradle to make this easier, but that could be a big task

DXL Importer should have code to generate the agent DXL.  We should also consult the [DTD for <agent>](https://help.hcltechsw.com/dom_designer/11.0.1/basic/H_AGENT_ELEMENT_XML.html)

**Comment by JoelProminic** [comment]
I released the new Moonshine-Domino-CRUD template (0.2) with DXL Importer scripts (and also JSON and API documentation).

@rat-moonshine, I tested the new template, and I see that Moonshine failed to convert the new `%eachform%` directories:
- `agentProperties/agentbuild/%eachform%Scripts` - this is for DXL Importer.  You won't have permissions to run these script for a real database, but I'll run them once they are generated
- `docs/%eachform%Docs` - API documentation for each form.  This is a more specialized version fo the [API-README.md](https://github.com/Moonshine-IDE/Moonshine-Domino-CRUD/blob/v0.2/API_README.md).  

Also, the DXL Importer scripts require the [project properties](https://github.com/Moonshine-IDE/Moonshine-Domino-CRUD/blob/v0.2/template/TemplateREADME.md#project-level-population) (specifically `%project%`), so this is a minor update from the original template logic.

**Comment by JoelProminic** [comment]
Once we have the DXL Importer scripts working, my plan is to run them against this example FormBuilder project (I may put this in a repository later): [2022_07_20__AuthorBookFan.zip](https://github.com/Moonshine-IDE/Moonshine-IDE/files/9172611/2022_07_20__AuthorBookFan.zip)

I'll import the generated agents and do some quick tests - it will be easier for me to test and generate the agents if I can generate them with Moonshine.

Then, I'll give you the details you need to access the imported agents, so that you can integrate them into the generated Royale projects.  I'll probably create a separate issue for this.  The Domino server and dbName will need to be configured in the project - I'll give you more information about this in the other issue.

**Comment by rat-moonshine** [comment]
Following path generations now included with module generation:

- `agentProperties/agentbuild/%eachform%Scripts`
- `docs/%eachform%Docs`

Please, check.

**Comment by JoelProminic** [comment]
I confirmed the updates for %eachform% processing.

However, I see that "%project%" is not populated in the `%eachform%` files.  For example, in `agentProperties/agentbuild/AuthorScript/AuthorCreate.properties` from the AuthorBookFan example database, the insertion parameter was not updated on this line:

    $$jarSourceFile=./build/libs/%project%.jar

I breifly mentioned this in my [comment](https://github.com/Moonshine-IDE/Moonshine-IDE/issues/1062#issuecomment-1192989046), but it seems this got lost with the bigger update.  I don't see any other insertion parameters that were missed.

**Comment by rat-moonshine** [comment]
> I breifly mentioned this in my https://github.com/Moonshine-IDE/Moonshine-IDE/issues/1062#issuecomment-1192989046, but it seems this got lost with the bigger update. I don't see any other insertion parameters that were missed.

This should be fixed now. Please, check.

**Comment by JoelProminic** [comment]
The generated agents look good after the last update.

I imported the agents to this URL (access is restricted by the Firewall).  I may find a more public location for this later:
BaseURL:  https://domino-49.prominic.net/A55606/Joel/Test-Moonshine-Domino-CRUD.nsf/
Example:  https://domino-49.prominic.net/A55606/Joel/Test-Moonshine-Domino-CRUD.nsf/AuthorRead?OpenAgent

I may move the agents to a more public or specialized database later.

We can discuss the next steps for FormBuilder integration with the agents tomorrow.  If you want to play with the API, you can follow generated documentation in `docs/AuthorDocs/Author_API.md` or the [generic documentation](https://github.com/Moonshine-IDE/Moonshine-Domino-CRUD/blob/main/API_README.md).

**Comment by rat-moonshine** [comment]
Thanks for the early access to `AuthorRead` agent, @JoelProminic . I can access this as this way:

`{"documents":[{"AuthorID":"AUTHOR-001","NameLast":"Doe","NameFirst":"John","Age":"25"}],"errorMessage":"","state":"authenticated","username":"Anonymous"}`

Is `AuthorID:"AUTHOR-001"` an auto-generated identifier to the record? I was wondering what key is to provide in case of deleting an entry as documented [here](https://github.com/Moonshine-IDE/Moonshine-Domino-CRUD/blob/main/API_README.md).

**Comment by JoelProminic** [comment]
I confirmed that the DXL Importer scripts work with the [DominoVagrant/demo](https://github.com/DominoVagrant/demo) Domino server.   I need a couple updates to the JavaAgents template to integrate better with the new settings defined in https://github.com/Moonshine-IDE/Moonshine-IDE/issues/1077#issuecomment-1221063516 .
- Change the default action to "clean importAll"
- Update gradle.properties to work with the default Domino server.  This will require some additional project-level insertion parameters

**Comment by JoelProminic** [comment]
I'd also like to make some other DXL Importer updates while I'm updating the template:
- Linux support - I had to work with this while debugging other issues, and it is pretty straightforward:  https://github.com/Moonshine-IDE/DXLImporter-Gradle-Demo/issues/5
- Add option to treat STDERR as STDOUT for DXL Importer, to improve how the output appears in the console:  https://docs.gradle.org/current/dsl/org.gradle.api.tasks.JavaExec.html#org.gradle.api.tasks.JavaExec:errorOutput

**Comment by JoelProminic** [comment]
Unfortunately, the local Notes API applications were failing on your workstation for compiling the database (NSFODP).  I expect similar errors for the agent deployment (DXL Importer) step.

We have plans to move NSFODP (#1007) and DXL Importer (#1062) to run in the Domino Vagrant instance.   I'm planing to focus on getting these tasks moving, and I'll send you instructions when it is ready (or early access).  I'd like to get the Vagrant and REST interface updates ready by the end of the week, but the Moonshine updates will take a little longer.

**Comment by JoelProminic** [comment]
@rat-moonshine, To avoid the Domino API errors we have been seeing on the local machine (they were especially bad in my tests on Wednesday with @piotrzarzycki21), I added a REST-Interface script to [DominoVagrant/demo](https://github.com/DominoVagrant/demo)
- Menu Action:   `Project > Run on Vagrant` (put this just below `Run Gradle Command`)
- Project Types:  Java projects with `projectType=java-domino`
- Required Vagrant instance capability:  java-domino-gradle

The action will work like this:
1. ZIP the project.  This zip should not include the parent project directory - build.gradle should be at the top level in the file.  This is required so that the script doesn't need to compute the extracted project name.
2. Upload the ZIP using `/file/upload` and save the `path` response
3. Run the `/opt/domino/scripts/run_dxl_importer.sh` script using `/task`.  The only parameter should be the uploaded file path collected above
4. Check the task status with `/task/$id` until it finishes.  The output should be displayed on the console to check for errors, but no further actions are required.

Example:

    cd ~/Documents/Flex/temp_workspace/GenesisCatalog_JavaAgents
    zip -r /tmp/GenesisCatalog_JavaAgents.zip *

    curl -X "POST" "http://localhost:8096/file/upload" \
         -H "Content-Type: multipart/form-data" \
         -F "file=@/tmp/GenesisCatalog_JavaAgents.zip"

    {"path":"/tmp/restinterface/upload/GenesisCatalog_JavaAgents.zip","size":182069}

    curl -X "POST" "http://localhost:8096/task" \
         -H "Accept: application/json" \
         -H "Content-Type: application/x-www-form-urlencoded" \
         --data-urlencode "command=/bin/bash /opt/domino/scripts/run_dxl_importer.sh /tmp/restinterface/upload/GenesisCatalog_JavaAgents.zip"

    {"id":4,"startDate":"2022-09-16T22:14:03Z","workingDir":"/tmp/restinterface/working","command":"/bin/bash /opt/domino/scripts/run_dxl_importer.sh /tmp/restinterface/upload/GenesisCatalog_JavaAgents.zip","errorMessage":null,"timeout":null,"output":null,"taskStatus":"EXECUTING","exitStatus":null}


    curl "http://localhost:8096/task/4"

NOTES:
- Since the DominoVagrant/demo server does not have access to other servers by default, these DXL Importer requests will be limited to the `demo/DEMO` server for now.
- The `projectType` option is not visible in the project settings, so we can't update a setting to flag a new project to have this feature.  That said, even if we had this, the current script expects a specific convention for the DXL Importer scripts.

**Comment by rat-moonshine** [comment]
I have committed a first version of the "Run on Vagrant" functionality.

- A new menu option is available for Java-Domino type of project
- A popup appears to select Vagrant instance (Note: I didn't found any reference of the `capability` filtering in above details, thus all the instance currently displaying in the dropdown for now)
- Starting the job based

However, I couldn't able to complete the job successfully in my tests:

- Created a new Domino Java project
- Starts the new process
- Eventually returned following error from server:

```
: Zipping files from: /Users/--/Desktop/NewJavaDominoProject
:   adding: NewJavaDominoProject.javaproj (deflated 63%)
:   adding: RunJar.sh (deflated 20%)
:   adding: build.gradle (deflated 56%)
:   adding: src/ (stored 0%)
:   adding: src/main/ (stored 0%)
:   adding: src/main/java/ (stored 0%)
:   adding: src/main/java/NewJavaDominoProject.java (deflated 62%)
: Trying to upload request to: http://localhost:8096/file/upload. This may take some time..
: Requesting conversion job to: http://localhost:8096/task
: Re-try conversion(#2) check: 1
: Conversion failed with exit code: 2
: sed: can't read gradle.properties: No such file or directory
```

I noticed I don't have any `gradle.properties` file in my Domino Java project's root, if that causing the problem.

Also, the codes are not in its final state, I shall still tune a few things. Furthermore, I shall do some re-structuring in all the database-job functionalities that we were working on some time. A re-test shall be requested when this changes done.

You can test the "Run on Server" functionality with branch build macOS. Please, check.

**Comment by JoelProminic** [comment]
There were some issues with the menu filter and capabilities check during the meeting this morning, but this has been resolved.

However, I started getting errors on the script.  I think the Domino server ended up in a bad state after on of my tests, and I'm trying to figure out how to recover from this.

When the error triggered, Moonshine reported this output:

    : Requesting conversion job to: http://127.0.0.1:8096/task
    : Re-try conversion(#7) check: 1
    : Re-try conversion(#7) check: 2
    : Conversion failed with exit code: 1
    : FAILURE: Build failed with an exception.
    : * Where:
    : Build file '/tmp/dxlimporter/20220919190858/build.gradle' line: 186
    : * What went wrong:
    : Execution failed for task ':importMoonshine-Domino-CRUD'.
    : > Process 'command '/home/vagrant/.sdkman/candidates/java/8.0.345-zulu/bin/java'' finished with non-zero exit value 4
    : * Try:
    : Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.
    : * Get more help at https://help.gradle.org
    : BUILD FAILED in 7s

However, this does not show the actual output from the action, which is important for debugging the process.  This should also display the `output` from the `/task/%id%` response, followed by the `errorMessage`.

**Comment by JoelProminic** [comment]
The current Java Domino template won't work, since the `notesInstallation` path is hard-coded in `build.gradle` rather than defined in `gradle.properties`.  TODO:  I think the best solution will be to revisit the Java Domino template to make it consistent with my updated Gradle configuration for DXL Importer.  I'll need to add a workaround for the ID password as well

You can run a test like this.
1. Create/open a Form Builder project
2. Build the database:  Project > Build with Apache Maven
3. Project > Deploy Database
4. Project > Generate Java Agents
5. Project > Run on Vagrant

I noticed in today's testing that the `Moonshine-Domino-CRUD` template had `projectType=java-gradle`.  I updated this to `projectType=java-domino`

The action is working well in my tests.  TODO:
- Show action output on error
- Update Java Domino template
- Add script support for specifying Gradle actions (currently hard-coded to `clean importAll`)
- Retrieve data from the built project.  This is not necessary for DXL Importer, but it could be needed to get the generated JARs for projects like `Moonshine-Domino-CRUD`.

**Comment by rat-moonshine** [comment]
- `output` should be displaying now in case of `executing`, `completed` and `failed/error` returns
- I did structural changes that I mentioned [earlier](https://github.com/Moonshine-IDE/Moonshine-IDE/issues/1062#issuecomment-1250974253) in database-job procedures affecting all four database-job sections - Convert Database, Deploy Database, Deploy Royale and Run on Vagrant. Some tests are requested.

**Comment by JoelProminic** [comment]
The error handling logic is working like I expect.

Feature | Error Handling | Notes
--------|----------------|------
Run on Vagrant (Java Domino) | Works | Change the server or databaseName in gradle.properties
NSFODP | Not yet available | Modify DXL file to make XML invalid
NSF Converter | Works | Modify script
Deploy Database | Works | Modify script
Deploy Royale | Works | Modify Script

We reviewed the code today, and noticed an odd check for the ["error" property](https://github.com/Moonshine-IDE/Moonshine-IDE/blob/f3df219b2aa6094b7df3198b5deee9b28891103e/ide/MoonshineDESKTOPevolved/src/actionScripts/plugins/vagrant/utils/DatabaseJobBase.as#L88).  I don't think this property should ever appear with the current REST-Interface behavior.

**Comment by JoelProminic** [comment]
Hmm, in my testing today I was regularly seeing cases where the script hung in Vagrant, even though it ran cleanly when I tried manually.   This behavior makes me thing that the output streams for STDERR or STDOUT are getting full.   I thought I saw code to consume this output, but I only see this in the REST interface source:  https://github.com/Moonshine-IDE/REST-Interface/blob/235cacd82fbeabc6ab1463bc5f5fb887e06014a5/grails-app/services/restinterface/TaskService.groovy#L61-L62

This is a Vagrant-side problem.  The Moonshine behavior seems good for now.

**Comment by JoelProminic** [comment]
The [consumeProcessOutput](http://docs.groovy-lang.org/docs/groovy-1.7.2/html/groovy-jdk/java/lang/Process.html#consumeProcessOutput(java.lang.StringBuffer,%20java.lang.StringBuffer)) method should be what we need.  I see this was commented out in the code at some point in relation to the timeout changes.  We can discuss this tomorrow.

**Comment by rat-moonshine** [comment]
This issue is now merged into `master`.

**Comment by JoelProminic** [comment]
This has been working reliably for me on macOS.
