### ISSUE TITLE
[Domino Visual Editor] Trouble with Edit Flag on Field Properties

### ISSUE THREAD

**Issue by JoelProminic** [Moonshine-IDE/Moonshine-IDE#1064]
While testing #1055 I have been seeing some trouble with the way the edit flag is being set for the recently added field properties (#1001, #1008, #1055).
- The edit flag gets set immediately when a field is selected.  @feather812002 traced this to the combobox fields, and this behavior is not triggering with the latest updates
- The edit flag does not get set on a field change.  In this case, I need to make other changes to the field properties before I can save.

I see that we have the edit flag behavior working like I expect for the Type and Kind comboboxes in the Field Info tab.  The other comboboxes should behave like this.

We'll need some new logic for the special controls like Color, Alignment, and First Line

I also noticed that the Client Objects combobox in the Field Info tab sets the edit flag when it is changed.  However, this is just a selector for the different Formula field types.  The edit flag shoudl be set when the Formula is updated instead.

@JesseProminic, I'll probably need your help testing the different properties as we make updates.  In general, watch for problems like this in your Domino Visual Editor testing.

**Comment by JoelProminic** [comment]
@JesseProminic, I think this is ready for some more thorough testing.

Bamboo Builds: https://static.moonshine-ide.com/downloads/releases/dev/macos/branches/features/issue_1055_paragraph_alignment_options
Test Database: https://moonshine-ide.com/downloads/releases/dev/macos/branches/features/issue_1008_add_addtional_field_properties/TestFieldOptions_1008_4.nsf

Basically, I want you to go through the field properties and test this:
1. Select a field.  This should not flag the tab as edited.
2. Browse to the property and make a change.  The tab should now be flagged as edited.
3. If the tab is flagged as edited, reopen the form to reset the flag.

Let me know if you find any fields that behave unexpectedly.  Watch for more complex property edit logic like [this](https://github.com/Moonshine-IDE/Moonshine-IDE/issues/1055#issuecomment-1192921945)

While you are at it, please check that the new properties (i.e. #1055) make reasonable sense to you from a fresh perspective.   I have been reviewing these properties through many incremental changes, and with some preconceptions from years of using Domino Designer, so I have probably overlooked some things.

**Comment by JesseProminic** [comment]
The edit flag on field properties is working fine, although every time I tried to save after my action, "v outden:0" keeps popping up. 
![Screen Shot 2022-08-01 at 9 09 58 AM](https://user-images.githubusercontent.com/96078188/182166792-a4e6b8b3-fca1-4290-a3e7-e1dc21936d57.png)

A new field box would not show the italic and grey 'input text' after I save, but it will show up after I close the window and reopen the file. 
![Screen Shot 2022-08-01 at 9 10 47 AM](https://user-images.githubusercontent.com/96078188/182166945-4f3e07dc-f286-485c-8e22-aec005bfa352.png)
![Screen Shot 2022-08-01 at 9 11 25 AM](https://user-images.githubusercontent.com/96078188/182167045-e9c90f67-c31c-4472-b479-dd7925a1bda7.png)

**Comment by feather812002** [comment]
@JesseProminic 
Hello, I already fix the "v outden:0" alert poping error on the latest update, 
but for the show the italic and grey "input text ",let me clear it .
the input default text is "Input Text" and it is grey show in the input component , 
If we input any other text ,it will only be display as Flex Default font and color always is black.
We not found a way dynamically display font style and color, changing it in real time based on user selections in the properties panel.
So, it not show the italic and grey after you save is correct action at now , 
We can discuss this with @JoelProminic  to tonight daily meeting .

Thanks.

**Comment by JoelProminic** [comment]
I didn't see the popup in my tests today.  Note that the update was on the #1015 branch:
Branch:  features/issue_1015_subform_support
Bamboo build:  https://static.moonshine-ide.com/downloads/releases/dev/macos/branches/features/issue_1015_subform_support/

For the "Input Text" issue, I clarified for @feather812002 that this was an issue with the hint text on the field rather than with how the formatting is displayed.  This is strange behavior, but not a priority to fix (and not directly related to this issue).

@feather812002 confirmed that this hint text can be overwritten by setting the Value property, which may be removed soon.  See [this comment](https://github.com/Moonshine-IDE/Moonshine-IDE/issues/1069#issuecomment-1203268708) for more information.

**Comment by JoelProminic** [comment]
Revisiting this after the merge to master, I see that the edit flag is not being updated when I set options from these tabs:
- Font
- Paragraph Hide When
- HTML Tags

The options in these tabs seem fine, though:
- Paragraph Alignment
- Advanced

I didn't test everything carefully in my review, but this is the general behavior I am seeing.

**Comment by JesseProminic** [comment]
I tested that the edit flag for **Input** is being updated in the options from _all_ of the tabs:

- Field Info
- Advanced
- Font
- Paragraph Alignment
- Paragraph Hide When
- HTML Tags
