### ISSUE TITLE
Rename Bug for Domino Visual Editor

### ISSUE THREAD

**Issue by JoelProminic** [Moonshine-IDE/Moonshine-IDE#1067]
I noticed this during other testing today:
1. Create a new Domino Visual Editor project called "TestPerformance".
2. Right-click on `nsfs/nsf-moonshine/odp/TestPerformance.form` and choose Rename
3. Update the name to TestPerformance2 and click Rename.  The file is renamed.  BUG:  Error appears on the console:  `: Unable to access file:/Users/joelanderson/Documents/Flex/temp_workspace/TestPe.xmlance/visualeditor-src/main/webapp/TestPerformance.form`
4. Enable "Show hidden files/folders" in Moonshine > Settings > General if you haven't already (may require restart)
5. Browse to `visualeditor-src/main/webapp/TestPerformance.xml`.  BUG:  this has not been renamed
6. Right-click > Rename
7. Rename the file to TestPerformance2.  The file is renamed.  BUG:  this error shows on the console:  `: Unable to access file:/Users/joelanderson/Documents/Flex/temp_workspace/TestPe.xmlance/visualeditor-src/main/webapp/TestPerformance.xml`

The problem seems to be that the code is doing a regular expression replace for ".form", which matches unexpected text.  To fix this, change the find string to `.form$` so that it only matches the end of the string.  

Also note that with the second rename, it is trying to rename the XML file again, instead of renaming the corresponding Form file.  This could cause problems for any project, but these files will be hidden from most users.

Neither issue is high priority, but it triggered for me on the converted `PerformanceStats_BingTest.nsf` database.

**Comment by piotrzarzycki21** [comment]
I have spent some time on this one and I have found that [this replace](https://github.com/Moonshine-IDE/Moonshine-IDE/blob/7fee9f83221612089ee71f1e9d3a4162819c26dd/ide/MoonshineSharedCore/src/actionScripts/utils/UtilsCore.as#L1698) mess up with path for some reason.

**Comment by piotrzarzycki21** [comment]
@Aszusz will take care of this issue.

**Comment by JoelProminic** [comment]
I confirmed that this clears the error for `.form` files.  However, as @joshtynjala noted on the commit, the `.` should be escaped (`\.`) in the regular expression, or it is just a wildcard.  This could become a problem when we add support for `.subform` files with #1015.

https://github.com/Moonshine-IDE/Moonshine-IDE/blob/fe5bb7ed909a256a9f6f05d3929425972ded39e2/ide/MoonshineSharedCore/src/actionScripts/utils/UtilsCore.as#L1698

I still see an error for the rename on `visualeditor-src/main/webapp/TestPerformance.xml` but this is a different issue.  Looking at the code, I see it is trying to rename a corresponding XML file in `visualeditor-src` file when renaming any file in a Visual Editor project. However, the `visualeditor-src` files are only linked to files like `.form`, `.mxml`, or `.xhtml`.  (As we continue development, we'll need to support renames for other files like `.subform` (#1015) and `.view` (or similar, #1057)).  There may be other file types that need this rename that I am forgetting.  We may want to move this to a separate issue.

**Comment by Aszusz** [comment]
@JoelProminic 
> `.` should be escaped 

Fixed

> I still see an error for the rename on visualeditor-src/main/webapp/TestPerformance.xml but this is a different issue.

I think this kind of rename can only be unidirectional and this is not an issue. Correct me if this is wrong.

> As we continue development, we'll need to support renames for other files like .subform (https://github.com/Moonshine-IDE/Moonshine-IDE/issues/1015) and .view (or similar, https://github.com/Moonshine-IDE/Moonshine-IDE/issues/1057)

If you'd like I'll add `.subform` and `.view` right here to future-proof before we forget.

**Comment by Aszusz** [comment]
Fixed the bug when trying to rename/delete any random file in the Visual Editor project would print an error to the console:
```
: Unable to access file:C:\Users\Adrian\Documents\xmlPrj_PerformanceStats_BingTest\nsfs\nsf-moonshine\some.txt
```
The logic is now narrowed down to .mxml .xhtml and .form files. I put no folder limitation for now as this may be subject to change.

**Comment by JoelProminic** [comment]
We had similar errors for #1015 and #1079, which have been resolved.
