### ISSUE TITLE
[DominoVisualEditor] Spaces in Form Name

### ISSUE THREAD

**Issue by JoelProminic** [Moonshine-IDE/Moonshine-IDE#1071]
I updated MoonshineDevelopment and ran a test for generating a Royale project for PerformanceStats_BingTest, and I got this error:

    : /Users/-user-/Documents/Flex/temp_workspace/PerformanceStats_BingTest_Royale/src/PerformanceStats_BingTest_Royale.mxml(72): col: 5 Error: This tag is unexpected. It will be ignored.
    :     <view:ConfigValue xmlns:view="view.*"/>
    :     ^

Checking the code, I see whitespace in the class and field names:

src/view/Config Value.mxml:
```
  <fx:Script><![CDATA[
	import org.apache.royale.jewel.Alert;
	import vo.Config ValueVO;
	[Bindable] private var config valueVO:Config ValueVO;
	[Bindable] private var config valueVOItems:Array = [new Config ValueVO()];
```

So the problem is that we have a form with a space in the name ("Config Value.form").   This is converted from the original database, so we want to preserve it for converting back to the original database.  If we decide to rename it on the NSFConverter side later, we'll need to update the name in other locations as well:
- View selection formulas
- Actions (shared, view, and form)
- Formulas in views

Checking other databases we want to convert, I see we have other forms like this:
- "(Grails4NotesWorkaround_FirewallForm_pfSense)" - Parenthesis indicate hidden forms on the Domino side, but I think we still need to convert these for Royale
- "Site Serial Server Misc Device Form - Remote Access Only"

My suggestion would be to remove all non-alphanumeric characters from the form name when generating the class and variable names.  In theory this could cause duplicates in the class names, but this will be a less common case than whitespace or other special characters in the form name.  We could also keep the underscores - I don't have a strong perference either way for this.

I would like to preserve the case of the Form name for the class and variable names.  Variables should change only the first character to lowercase (camel case), so that we have "siteSerialServerMiscDeviceFormRemoteAccessOnly" instead of "siteserialservermiscdeviceformremoteaccessonly" (both are excessively long, but the camel case version is a easier to read).

**Comment by piotrzarzycki21** [comment]
This issue need to be discussed, cause from ActionScript point of view spaces in the name of classes are not allowed - unless I'm not aware of something.

**Comment by piotrzarzycki21** [comment]
I have started to remove spaces, underscores and parenthesis from file names. Maybe we should stop here with that and see what kind of names we will get in real life examples.

**Comment by JoelProminic** [comment]
I'm still seeing issues with the "Config Value" form in PerformanceStats_BingTest.nsf.

**Comment by JoelProminic** [comment]
I'm moving this to 3.3.4.   We can work on this as we revisit the PerformanceStats_BingTest.nsf conversion tests.

**Comment by piotrzarzycki21** [comment]
I have fixed that issue. Performance stats project after conversion to Royale is building correctly now.

**Comment by JoelProminic** [comment]
This is working with my latest test.   We made updates on the [NSFConverter side as well](https://github.com/Moonshine-IDE/NSFConverterPortalProject/issues/21)

**Comment by piotrzarzycki21** [comment]
I'm reopening this one for farther investigation. I did tests Mumble database and white spaces in files are not handled correctly.

**Comment by piotrzarzycki21** [comment]
@Aszusz Please take a look into that line https://github.com/Moonshine-IDE/Moonshine-IDE/blob/84cd90167ebc7076109bf8aaefe12091a78be260/ide/MoonshineDESKTOPevolved/src/actionScripts/plugins/visualEditor/domino/ExportDominoToRoyalePlugin.as#L208

**Comment by piotrzarzycki21** [comment]
It is fixed now. Thanks @Aszusz !

**Comment by JoelProminic** [comment]
Will this regular expressions clear characters in the parent directory?  For example:  `/Users/test user/test-workspace/Project/...`

**Comment by piotrzarzycki21** [comment]
Please @Aszusz check this one.

**Comment by Aszusz** [comment]
> Will this regular expression clear characters in the parent directory? For example: /Users/test user/test-workspace/Project/...

No, it only contains the file name. I refactored the variable name to reflect the intent better.

**Comment by JoelProminic** [comment]
I am seeing similar issues with the generated Java projects.  In this case, the first space is being removed, but not other spaces or special characters.  For example, here are some problematic cases withi ` ` and `-` in the converted Mumble Meeting project:

![image](https://user-images.githubusercontent.com/24532731/233140915-297d40a1-988f-4845-8865-130d017421f9.png)

**Comment by piotrzarzycki21** [comment]
> @JoelProminic I can't understand this , it look like you have the name trouble from Java agent and in the src/main/java folder. But obviously , the java agent still not work for NSFConverProtal and Moonshine-IDE side, so I don't know how do you get the agent into the src/main/java folder, and what project generate it ? So, I don't know how to fix it .
> 
> Thanks.

This is something which I should be able to fix.

**Comment by piotrzarzycki21** [comment]
@JoelProminic I have pushed some changes for this issue in java agent exports. Please give it a try and let's see if it's enough.

**Comment by JoelProminic** [comment]
I confirmed this was a known issue with NSFConverterPortal and form generation:  #1098.

The current generated agents use the names I expect.  I added some notes to #1098, and I'm closing this issue.
