### ISSUE TITLE
Generate Java Agents for Domino Visual Editor

### ISSUE THREAD

**Issue by JoelProminic** [Moonshine-IDE/Moonshine-IDE#1072]
We would like to generate Java agents for Domino Visual Editor, similar to what we did for Form Builder in #978.

The agent template was designed to work with the FormBuilder properties, but we should be able to generate the insertion parameters based on the Domino Visual Editor properties instead.  I'll create some guidance for this when I have a chance.

Note that once we add support for subforms (#1015), we'll need to search through the subforms recursively to build the full list of fields.

UPDATE:  I added a [test project](https://static.moonshine-ide.com/downloads/releases/dev/macos/branches/features/issue_978_CRUD_agents_integration/2022_08_12__FormBuilder_Example_AuthorBookFan_DVE.zip).  I created this by generating a database for the example in #978 and then converting it with NSF Converter.   I manually added the views from #1073 for this test.
UPDATE2:  I created an updated [test project](https://static.moonshine-ide.com/downloads/releases/dev/macos/branches/features/issue_978_CRUD_agents_integration/2022_09_01__FormBuilder_Example_AuthorBookFan_DVE.zip) for the generated view name updates

**Comment by piotrzarzycki21** [comment]
@rat-moonshine Can you point me to some classes which generates for you these agents stuff on your sight ? I would like to look into that as a first step.

**Comment by JoelProminic** [comment]
It looks like @rat-moonshine's last comment is for the logic to connect Royale to the agents, rather than generating the agents.  I'm planning to create an issue for connecting to the agents soon.

**Comment by JoelProminic** [comment]
See https://github.com/Moonshine-IDE/Moonshine-Domino-CRUD/blob/main/template/TemplateREADME.md for the template instructions.   Here is some clarification for the insertion parameters:

### Project-Level

Parameter | Description
----------|------------
`%project%` | The name of the project
`%NotesExecutablePath%` | The Notes path from the Domino settings
`%eachform%` | Strip out any whitespace or special characters in the name, as with #1071

### %eachform%

Parameter | Description
----------|------------
`%form%` | Strip out any whitespace or special characters in the name, as with #1071
`%formRaw%` | The original Form Name
`%view%`| "All By UNID_5c%formRaw%".  The view is added with #1073.  

### Elements

Category | Definition
---------|-----------
all | All fields
key | This category should be empty for Domino Visual Editor, at least for now.  Intead, we are using the DominoUniversalID as the key (no configuration required on Moonshine side)
editable | `field.kind` == "editable"
required | Currently not used.  I see we have `field.required` in the intermediate XML, but this is not populated by NSFConverter


Parameter | Description
----------|------------
`%name%` | `field.name`
`%label%` | Use `field.name` for this as well.  We don't have a direct link to the label
`%description%` | "" - not defined in Domino Visual Editor
`%type%` | `field.type`
`%typeupper%` | `%type%` in uppercase
`%multivalue%` | `field.allowmultivalues` == "true"

**Comment by JoelProminic** [comment]
This issue should be ready for implementation.  Let me know if you have any more questions about the template or the process.  Note that you won't be able to test importing and running these agents until we get a full Domino Vagrant server working, so you'll need my help to finish the testing.

**Comment by piotrzarzycki21** [comment]
@rat-moonshine, @JoelProminic where should I click in application in order to generate Java Agents out of example from #1074?

**Comment by rat-moonshine** [comment]
@piotrzarzycki21 when you have the OnDisk project selected you'll have the option `Project > Generate Java Agents`.

**Comment by piotrzarzycki21** [comment]
> @piotrzarzycki21 when you have the OnDisk project selected you'll have the option `Project > Generate Java Agents`.

@rat-moonshine I don't see this, unless what Joel provide is not ondisk project. 

<img width="1168" alt="Screenshot 2022-08-15 at 10 17 28" src="https://user-images.githubusercontent.com/24554795/184601582-04e97d35-9dea-466c-a0b9-ab1d12f5574d.png">

**Comment by rat-moonshine** [comment]
Hm.. Perhaps that is part of #978 updates on branch. I see @JoelProminic mentioned that it's [ready](https://github.com/Moonshine-IDE/Moonshine-IDE/issues/978#issuecomment-1213515779) for a merge, I shall do that once confirmed.

**Comment by piotrzarzycki21** [comment]
> Hm.. Perhaps that is part of #978 updates on branch. I see @JoelProminic mentioned that it's [ready](https://github.com/Moonshine-IDE/Moonshine-IDE/issues/978#issuecomment-1213515779) for a merge, I shall do that once confirmed.

Not sure what do you wanted to confirm. It's stated clearly that is ready to merge. I will switch to that branch. Please merge this today if possible.

**Comment by piotrzarzycki21** [comment]
I have just switched ot branch and I still don't see options in menu to generate agents - @rat-moonshine can you check using Joel's project ?

**Comment by rat-moonshine** [comment]
I discussed with @JoelProminic and it's now merged into the `master`.

**Comment by piotrzarzycki21** [comment]
> I discussed with @JoelProminic and it's now merged into the `master`.

Thanks. Did you try it ? Do you experience same issue as me ?

**Comment by JoelProminic** [comment]
@piotrzarzycki21, I provided a Domino Visual Editor project in the description instead of an On Disk Project.

 I updated MoonshineDevelopment to the latest version and did this test on macOS Catalina:
1. Create a new Domino On Disk Project.  Alternatively, clone [the Form Builder test project](https://github.com/Moonshine-IDE/FormBuilder-Example-AuthorBookFan) and jump to step 4
2. Open `src/main/formbuilder/%project%.dfb`
3. Populate the form and save
4. (Optional) Set Base Agent URL in Project Settings > Domino:  https://rest-swf.prominic.net/A55D78/Test-Moonshine-Domino-CRUD.nsf
5. Project > Generate Java Agents
6. Select a parent directory
7. The Java project opens after a couple seconds
8. Reselect the Domino On Disk Project and run Project > Generate Apache Royale Project
9. Select a parent directory
10. The Royale project opens after a couple seconds

Does this work for you?

**Comment by piotrzarzycki21** [comment]
> 4\. https://rest-swf.prominic.net/A55D78/Test-Moonshine-Domino-CRUD.nsf

I was interested only in generating Java Agents to see how to implement that on my sight. Thanks. It's working now.

**Comment by piotrzarzycki21** [comment]
> @piotrzarzycki21 an amount of agent communication is already comes from the `.template` files (https://github.com/Moonshine-IDE/Moonshine-IDE/tree/features/issue_978_CRUD_agents_integration/ide/MoonshineSharedCore/src/elements/templates/royaleTabularCRUD/module/$moduleName/$moduleNameServices) - `$moduleNameServices.as` holds the module-specific named agent references from Form Builder:
> 
> ```
> public static const LISTING_AGENT:String = "/$moduleNameRead?OpenAgent";
> public static const ADD_AGENT:String = "/$moduleNameCreate?OpenAgent";
> public static const EDIT_AGENT:String = "/$moduleNameUpdate?OpenAgent";
> public static const REMOVE_AGENT:String = "/$moduleNameDelete?OpenAgent";
> ```
> 
> The base-URL is placed somewhere in the application as static URL. Rest is standard proxy/services communication to get/send data between the application and server.

@rat-moonshine Out of this one once I choose from in menu Project -> Generate Java Agents is being created new java project am I right ?

**Comment by piotrzarzycki21** [comment]
I see you are downloading template. What's the reason to do that instead of having it as part of Moonshine sources ?

**Comment by piotrzarzycki21** [comment]
After analysis of @rat-moonshine's code I think I should reuses this two classes [CRUDJavaAgentsExporter](https://github.com/Moonshine-IDE/Moonshine-IDE/blob/master/ide/MoonshineDESKTOPevolved/src/actionScripts/plugins/ondiskproj/crud/exporter/CRUDJavaAgentsExporter.as) and [CRUDJavaAgentsModuleExporter](https://github.com/Moonshine-IDE/Moonshine-IDE/blob/master/ide/MoonshineDESKTOPevolved/src/actionScripts/plugins/ondiskproj/crud/exporter/CRUDJavaAgentsModuleExporter.as). However based on what I should generate these agents ?

I do understand that I should generate agent 1:1 - One form = one agent class, but what should be inside ? In intermittent xml I have Fields, but somehow going trough xml in search of fields maybe too much ? 

Should I rather look into DXL, where I see I have following tag:
```
<item name="$Fields">
    <textlist>
      <text>SourceField</text>
      <text>SourcePattern</text>
      <text>OutputExpression</text>
      <text>OutputField</text>
    </textlist>
  </item> 
```

Above seems to be list of fields which should be part of each agent - Am I right ?

**Comment by piotrzarzycki21** [comment]
@JoelProminic It would be really easier for me if you could get from Bing's example project one form - and create based on that JavaAgent project - I could see what actually should be part of it.

**Comment by rat-moonshine** [comment]
> > @piotrzarzycki21 an amount of agent communication is already comes from the `.template` files (https://github.com/Moonshine-IDE/Moonshine-IDE/tree/features/issue_978_CRUD_agents_integration/ide/MoonshineSharedCore/src/elements/templates/royaleTabularCRUD/module/$moduleName/$moduleNameServices) - `$moduleNameServices.as` holds the module-specific named agent references from Form Builder:
> > ```
> > public static const LISTING_AGENT:String = "/$moduleNameRead?OpenAgent";
> > public static const ADD_AGENT:String = "/$moduleNameCreate?OpenAgent";
> > public static const EDIT_AGENT:String = "/$moduleNameUpdate?OpenAgent";
> > public static const REMOVE_AGENT:String = "/$moduleNameDelete?OpenAgent";
> > ```
> > The base-URL is placed somewhere in the application as static URL. Rest is standard proxy/services communication to get/send data between the application and server.
> 
> @rat-moonshine Out of this one once I choose from in menu Project -> Generate Java Agents is being created new java project am I right ?

The above code snippets is actually part of the generated Royale project, from its service-delegate class. But yes, `Project > Generate Java Agents` is suppose to generate the Java project.

**Comment by JoelProminic** [comment]
> I see you are downloading template. What's the reason to do that instead of having it as part of Moonshine sources ?

@piotrzarzycki21, I wrote up my reasoning for this template strategy [here](https://github.com/Moonshine-IDE/Moonshine-IDE/issues/978#issuecomment-1151692385).  We can revisit this design if you have concerns, but it has been convenient so far.

**Comment by JoelProminic** [comment]
@piotrzarzycki21, the example database I sent should generate basically the same agents as the FormBuilder-Demo-AuthorBookFan project.  The only differences I expect are:
- The lookup view - FormBuilder already generates a view
- The keys - Domino Visual Editor doesn't have a way to track these yet.

The `$Fields` item should be a complete list of fields (This may include the subform fields as well - we will revisit this later).   However, it doesn't contain the type information that is required from the templates, so you'll need to parse the fields from the `visualeditor-src` XML files.

I went through the example Domino Visual Editor project and generated the insertion parameters based on the logic described in my [earlier comment](https://github.com/Moonshine-IDE/Moonshine-IDE/issues/1072#issuecomment-1213510914).  Then these insertion parameters will need to be plugged into the [algorithm](https://github.com/Moonshine-IDE/Moonshine-Domino-CRUD/blob/main/template/TemplateREADME.md) that I created ([Groovy Example](https://github.com/Moonshine-IDE/Moonshine-Domino-CRUD/blob/main/src/test/groovy/helper/GenerateTemplate.groovy)).  Hopefully you can use the algorithm implementation that @rat-moonshine created.

### %eachform%

%form% | %formRaw% | %view%
-------|-----------|-------
Author | Author | All By UNID_5cAuthor
Book | Book | All By UNID_5cBook

### Fields

#### Author

To populate the fields, I checked the `visualeditor-src` XML files and searched for `<field`.  You are doing something similar already to generate the value objects, but I expect that is integrated with the rest of the code generation logic.

%name% | %label% | %descrlption% | %type% | %typeupper% | %multivalue%
-------|---------|---------------|--------|-------------|-------------
AuthorID | AuthorID | "" | text | TEXT | false (allowMultivalue not set)
NameFirst | NameFirst | "" | text | TEXT | false
NameLast | NameLast | "" | text | TEXT | false
NameLast | NameLast | "" | text | TEXT | false
Age | Age | "" | number | NUMBER | false
DateOfBirth | DateOfBirth | "" | datetime | DATETIME | false
Biography | Biography | "" | richtext | RICHTEXT | false
UpdateHistory | UpdateHistory | "" | datetime | DATETIME | true


#### Book

%name% | %label% | %descrlption% | %type% | %typeupper% | %multivalue%
-------|---------|---------------|--------|-------------|-------------
BookID | BookID | "" | text | TEXT | false
Title | Title | "" | text | TEXT | false
Authors | Authors | "" | text | TEXT | true
PageCount | PageCount | "" | number | NUMBER | false
PublishYears | PublishYears | "" | number | NUMBER | true

### Categories

The "all" and "editable" categories should contain all fields here, while "key" and "required" should be empty.   I'll need to add come computecd field examples at some point.

**Comment by piotrzarzycki21** [comment]
I have moved farther with implementation. I belive I have something, but I will test if it's really working tomorrow and hopefully push first version.

**Comment by piotrzarzycki21** [comment]
@JoelProminic I have pushed first version of generation java project. Generation has been implemented based on Bing's example. I didn't test it too much farther. Comments are welcome based on what you are see in generated project. New build of Moonshine should have all my changes.

**Comment by JoelProminic** [comment]
I see the latest Bamboo build failed:

    19-Aug-2022 09:48:21 	CompileWeb:
    19-Aug-2022 09:48:21 	     [copy] Copying 6712 files to -snip-/Moonshine-IDE/ide/MoonshineWEBevolved/build/bin-debug/elements
    19-Aug-2022 09:48:26 	     [echo] /Users/mmb/SDKs/Flex_4.16.1_AIR_33.1
    19-Aug-2022 09:48:26 	     [echo] ../../MoonshineSharedCore
    19-Aug-2022 09:48:26 	     [echo] ../../MoonshineSharedCore/src/locale/{locale}
    19-Aug-2022 09:48:26 	     [echo] ../src
    19-Aug-2022 09:48:27 	    [mxmlc] Loading configuration file /Users/mmb/SDKs/Flex_4.16.1_AIR_33.1/frameworks/flex-config.xml
    19-Aug-2022 09:48:40 	    [mxmlc] -snip-/Moonshine-IDE/ide/MoonshineWEBevolved/src/actionScripts/impls/IFlexCoreBridgeImp.as(85): col: 15 Error: Interface method generateJavaAgentsVisualEditor in namespace actionScripts.interfaces:IFlexCoreBridge not implemented by class actionScripts.impls:IFlexCoreBridgeImp.
    19-Aug-2022 09:48:40 	    [mxmlc] 
    19-Aug-2022 09:48:40 	    [mxmlc]         public class IFlexCoreBridgeImp implements IFlexCoreBridge
    19-Aug-2022 09:48:40 	    [mxmlc]                      ^
    19-Aug-2022 09:48:40 	    [mxmlc] 

The installer was generated, though, so I can start testing with that.

**Comment by JoelProminic** [comment]
I generated the project, and it compiled properly (this is a good sanity test that you can use).

I see the Author field list looks like this:

```
		Collection<FieldDefinition> fields = new ArrayList<FieldDefinition>();
		fields.add(new FieldDefinition("AuthorID", FieldType.TEXT, false));
		fields.add(new FieldDefinition("NameFirst", FieldType.TEXT, false));
		fields.add(new FieldDefinition("NameLast", FieldType.TEXT, false));
		fields.add(new FieldDefinition("Age", FieldType.TEXT, false));
		fields.add(new FieldDefinition("DateOfBirth", FieldType.TEXT, false));
		fields.add(new FieldDefinition("Biography", FieldType.TEXT, false));
		fields.add(new FieldDefinition("UpdateHistory", FieldType.TEXT, false));
		fields.add(new FieldDefinition("null", FieldType.TEXT, false));
```


And Book looks like this:

```
		Collection<FieldDefinition> fields = new ArrayList<FieldDefinition>();
		fields.add(new FieldDefinition("BookID", FieldType.TEXT, false));
		fields.add(new FieldDefinition("Title", FieldType.TEXT, false));
		fields.add(new FieldDefinition("Authors", FieldType.TEXT, false));
		fields.add(new FieldDefinition("PageCount", FieldType.TEXT, false));
		fields.add(new FieldDefinition("PublishYears", FieldType.TEXT, false));
		fields.add(new FieldDefinition("null", FieldType.TEXT, false));
```

So both of these have an extra "null" field. It looks like this is an extra field entry, rather than an incomplete definition for one of the actual fields.

I see that all of the types are set to "TEXT" currently.

In addition, this does not set the multivalue option correctly for UpdateHistory, Authors, or PublishYears.   I confirmed these were set as multivalue in the FormBuilder_Example_AuthorBookFan_DVE project.

I also see that `%view%` is passed as "null" instead of "All By UNID_5cAuthor" in AuthorRead (and similarly in BookRead):

```
	protected View getLookupView() throws NotesException {
		return agentDatabase.getView("null");
	}
```

**Comment by piotrzarzycki21** [comment]
> generateJavaAgentsVisualEditor

I don't understand what is happening here. That method is implemented.

**Comment by piotrzarzycki21** [comment]
> So both of these have an extra "null" field. It looks like this is an extra field entry, rather than an incomplete definition for one of the actual fields.
> 
> I see that all of the types are set to "TEXT" currently.

I have fixed that null pointer, FieldType issue and multi values. I still need to work on view name. Please pay attention to the github hash in build cause there was also some commits in VisualEditorConveretLib

**Comment by piotrzarzycki21** [comment]
> I also see that `%view%` is passed as "null" instead of "All By UNID_5cAuthor" in AuthorRead (and similarly in BookRead):
> 
> ```
> 	protected View getLookupView() throws NotesException {
> 		return agentDatabase.getView("null");
> 	}
> ```

@JoelProminic I looked into that and it looks like there simply no viewName either in your example which you have provided me or Bing's one. DXL nor our intermediate xml format doesn't contains viewName. Is it something which was missed on Bing's sight ? 

Temporary I have assigne viewName same as formName.

**Comment by JoelProminic** [comment]
Right, the view will be defined by convention.  I have some details in my writeup [here](https://github.com/Moonshine-IDE/Moonshine-IDE/issues/1072#issuecomment-1213510914):
![image](https://user-images.githubusercontent.com/24532731/185974318-964de969-3bce-4dd2-bc8d-8d4f7a2d8576.png)

The `generateJavaAgentsVisualEditor` error is still triggering in Bamboo.  Note that this error is triggering on the Web build.

**Comment by piotrzarzycki21** [comment]
@JoelProminic I have pushed changes to have view ready, but I'm really not sure if this how it should be. Let me know.

**Comment by JoelProminic** [comment]
@piotrzarzycki21, I checked the agents and they look correct from a manual review.  

I tried to do a test with running them on the Vagrant Domino server, but I ran into issues on the server side.  If I can't fix this quickly, I'll do a test against an existing database.

I already have example agents deployed for #1074, so you can continue with that for now.

**Comment by piotrzarzycki21** [comment]
@rat-moonshine I have used Joel's [test project](https://static.moonshine-ide.com/downloads/releases/dev/macos/branches/features/issue_978_CRUD_agents_integration/2022_08_12__FormBuilder_Example_AuthorBookFan_DVE.zip) to generate Java agents using your `OnDiskRoyaleCRUDModuleExporter` I have created my own [DominoRoyaleModuleExporter](https://github.com/Moonshine-IDE/Moonshine-IDE/blob/master/ide/MoonshineDESKTOPevolved/src/actionScripts/plugins/visualEditor/domino/DominoRoyaleModuleExporter.as). I'm interested in generation *.Proxy and *.Service classes - I'm not interested into VO or Views. I have override some methods and in theory [omitted generation VO and views](https://github.com/Moonshine-IDE/Moonshine-IDE/blob/b09ca3ed1697876654c4964822b61097b3365cf0/ide/MoonshineDESKTOPevolved/src/actionScripts/plugins/visualEditor/domino/DominoRoyaleModuleExporter.as#L61) - however in the Royale project result I still see them generated. Can you look into that tomorrow and check what am I missing here ?

**Comment by rat-moonshine** [comment]
Just to ensure I understood, are you seeing VO and Views generated with all its values and not any raw template files?

On a separate note, [recently we noticed](https://github.com/Moonshine-IDE/Moonshine-IDE/issues/1077#issuecomment-1228076349) that during Royale CRUD or Java Agents generation Moonshine generates modules from other opened projects.

This has been fixed and currently as part of the ongoing branch development. I just wanted you to know since you're also working on this generation.

**Comment by rat-moonshine** [comment]
@piotrzarzycki21 I confirm your scenario while doing a test comparison by commenting off the same lines. I see VO and view-classes being generated, however the critical content in them not being generated. i.e. 

```
public class AuthorVO  
{
    public var DominoUniversalID:String;
    %PropertyStatements%

    public function AuthorVO()
    {
    }
		
    public function toRequestObject():Object
    {
	%ToRequestObjectStatements%
    }

    public static function getAuthorVO(value:Object):AuthorVO
    {
        var tmpVO:AuthorVO = new AuthorVO();
        %GetNewVOStatements%
        return tmpVO;
    }
```
This looks like while commenting-off `VOClassGenerator` you only stopped generating the content in those files when the files itself created much earlier.

From preventing those files being created, you also need to override [this](https://github.com/Moonshine-IDE/Moonshine-IDE/blob/b09ca3ed1697876654c4964822b61097b3365cf0/ide/MoonshineDESKTOPevolved/src/actionScripts/plugins/ondiskproj/crud/exporter/OnDiskRoyaleCRUDModuleExporter.as#L139) method and line with this:

`th.projectTemplate(TEMPLATE_MODULE_PATH, targetPath, ["$moduleNameVO", "$moduleNameViews"]);`

But I see this affect in other way in `RoyalePageGeneratorBase.startReferenceCollecting().onImportCompletes()` method. The codes perhaps somewhere trying to retain different other references for elsewhere. This might require investigating to prevent from triggering exception.

**Comment by JoelProminic** [comment]
I did some tests with the Java agents on the [DominoVagrant/demo](https://github.com/DominoVagrant/demo) Domino instance, and the agents mostly worked

View should be "All By UNID/Author" instead of "All By UNID_5c%form%.view". The latter is the format for the file name, but the former is the corresponding view name.  I see I did not have this correct in my writeup - I will fix this.

I see that the Read agent gives errors when there are no keys defined.  This could be resolved by either:
- Adding a DocumentUniversalID field (type=text, multivalue=false, label=, description=).
- Updating the template to allow empty keys, like other agents in the template.  I think we'll want this anyway, so I'll plan to make this update tomorrow.

The other agents seem to be working well.  I will do more tests once the Royale server is working.

**Comment by JoelProminic** [comment]
@feather812002 started working on #1073, and I was reminded that we wanted to add a subdirectory to the generated views.   The new view name format is:  `All By UNID/CRUD/%formRaw%`

I updated the test project [here](https://static.moonshine-ide.com/downloads/releases/dev/macos/branches/features/issue_978_CRUD_agents_integration/2022_09_01__FormBuilder_Example_AuthorBookFan_DVE.zip).

**Comment by JoelProminic** [comment]
I confirmed that the `%view%` is fixed.  I can DXL Import the agents without making any modifications to the generated project.
