### ISSUE TITLE
Royale Compilation Breaks When Output Path Has Space

### ISSUE THREAD

**Issue by rat-moonshine** [Moonshine-IDE/Moonshine-IDE#1075]
I recently noticed that while compiling a Royale application having its "Javascript Output Path" with space value, compilation terminates with following error:

```
: -theme=/Users/devsena/Downloads/MoonshineSDKs/Royale_SDK/apache-royale-0.9.9-bin-js/royale-asjs/frameworks/themes/JewelTheme/src/main/resources/defaults.css
: -html-template=src/resources/jewel-index-template.html
: -js-dynamic-access-unknown-members=true
: -debug=true
: -compiler.targets=JSRoyale
: -js-output=/Users/devsena/Desktop/Path
: With
: Space
: Error: unable to open 'Space'.
: 36.757155521 seconds
```

![image](https://user-images.githubusercontent.com/24370870/185303059-1c4ba8fa-2908-4d58-9346-76f3904b6951.png)

I don't remember I had seen this break in past, though.

**Comment by JoelProminic** [comment]
I confirmed this on macOS and Windows
