### ISSUE TITLE
Getting Started Download Link Opens Broken Page

### ISSUE THREAD

**Issue by rat-moonshine** [Moonshine-IDE/Moonshine-IDE#1076]
Moonshine opens broken link to download Moonshine SDK Installer from Getting Started:

https://moonshine-ide.com/moonshine-app-store-helper/

This needs to be rectified with:

https://moonshine-ide.com/download-sdk-installer/

**Comment by JoelProminic** [comment]
I see the Getting Started page was updated, but there is another link in the menu:
1. File > Launch Moonshine SDK Installer
2. Click Go to Download Page.  BUG:  this opens the old page
3. Click "Click here".  BUG:  this opens the old page

@Aszusz, did you remove the original link recently?  Or perhaps it was lost in the move to GitHub pages?  I would be nice to have a redirect until we can get this release out.

**Comment by Aszusz** [comment]
I moved the redirects but they had a bug and stopped working when I disabled old content.
I made a fix and now all the links should go to the installer page:
- https://moonshine-ide.com/download-sdk-installer/
- https://moonshine-ide.com/moonshine-app-store-helper/
- https://moonshine-ide.com/download/
(and main downloads directory is https://static.moonshine-ide.com/downloads/)

**Comment by JoelProminic** [comment]
I confirmed the download links I mentioned above are working properly now.  I'm closing the issue.
