### ISSUE TITLE
Deploy Database to Vagrant Domino Server

### ISSUE THREAD

**Issue by JoelProminic** [Moonshine-IDE/Moonshine-IDE#1077]
We are working on setting up a [Domino server on a Vagrant instance](https://github.com/DominoVagrant/demo) so that we can test the converted database in a safe sandbox environment.

The deployment will be handled by the REST interface, similar to what we did in #979.  I will create a script and capability for this and provide a wirteup when it is ready.

Some related updates I need to consider:
- Moonshine needs to know where to find the database to deploy
    - currently this is at `nsfs/nsf-moonshine/target/nsf-moonshine-domino-1.0.0.nsf`. Do I want ot update this to a user defined name, probably based on the project name?
    - instead, we could have the user select the database in the project tree.  This would be more flexible, but would require the user to have more knowledge of the structure
- We need to configure the target path and database name for the server
    - This will probably be added to the Domino settings so that we can use if for the DXL Import as well
    - If we support database selection in the project tree, we would probably want to request this in a prompt
- We need to add some guidance on how to get started with the VagrantDomino instance.

UPDATE:
Branch:  features/issue_1077_deploy_database
Build:  https://static.moonshine-ide.com/downloads/releases/dev/macos/branches/features/issue_1077_deploy_database

**Comment by JoelProminic** [comment]
I have created a script for the database deployment.  @rat-moonshine, you can review this for now and I can answer your questions/concerns.  I'll need to send you some instructions for setting up the Vagrant instance before you can test, though, and there are decisions I need to make on the UI side as well (see above).

The process will work the same as what we did [here](https://github.com/Moonshine-IDE/Moonshine-IDE/issues/979#issuecomment-1171640477).  The main differences are:
- For the `file/upload` action, the file will be the local database (.nsf)
- The `/task` action will use a different script and parameters:

```
# URL:  /task
# Content-Type:  application/x-www-form-urlencoded
# Parameter:  command (the command to run
#   - "/opt/domino/scripts/deploy_database.sh".  This is a hard-coded path to the script.  Vagrant will enforce this location.
#   - "%nsf-path%" - collected from the file/upload response
#   - "%dbname%" - the name and path of the target database

curl -X "POST" "http://localhost:8096/task" \
     -H "Accept: application/json" \
     -H "Content-Type: application/x-www-form-urlencoded" \
     --data-urlencode "command=/bin/bash /opt/domino/scripts/deploy_database.sh '%nsf-path%' '%dbname%'"
```

You will then check the status normally.

The capability required to use this feature is:  "upload-database".  For now, this is not available on the NSFConverter Vagrant instance, but we may revisit this later.

**Comment by rat-moonshine** [comment]
> The process will work the same as what we did https://github.com/Moonshine-IDE/Moonshine-IDE/issues/979#issuecomment-1171640477. The main differences are:
> 
> - For the file/upload action, the file will be the local database (.nsf)

Isn't that we were uploading `.nsf` file only in earlier implementation?

**Comment by JoelProminic** [comment]
I would like to add the following properties to the Domino Settings for Form Builder  (and Domino Visual Editor, in the long term):

Property | Default Value | Display Description | Notes
---------|---------------|---------------------|------
Local Database | `nsfs/nsf-moonshine/target/nsf-moonshine-domino-1.0.0.nsf` | Path to generated database. | This will be used as the default for database deployment, and we may also use it to automate opening the database
Target Server | `demo/DEMO` | The target Domino server | Will be passed to DXL Importer in a future update | `demo/DEMO` is the default for DominoVagran/demo.  We may change this later
Target Database  | `%CleanProjectName%.nsf` | The database name and path on the target server, relative to the data directory | Remove any characters from the project name except alphanumeric and '_'.  Used for Database Deployment and DXL Importer
Base Agent URL | `https://127.0.0.1:8080/%CleanProjectName%.nsf` | The base database URL to use for the generated agents | Used for Royale Agent interaction.  Note that the name could be generated based on the target database, but the agent database and target database don't necessarily need to be the same.  This property already exists, but included it to add ordering, a description, and a default.

Then add a new menu action called Project > Deploy Domino Database.  Put this above "Generate Java Agents".  When the user clicks the prompt, they will get a dialog showing these properties.  The properties will be defaulted based on the above settings, but they should be editable.

Property | Default Value | Notes
---------|---------------|------
Database to Deploy | Local Database | This should have a filechooser
Target Server |  | This should be a Vagrant instance combobox, similar to "NSF Converter" from Others > Convert Domino Database (#979).  In this case, the filter capability is "upload-database"
Target Location | Target Database | Don't include a filechooser here, since it is a remote, relative path.  If no value is set, show a hint like `path/to/database.nsf`

![image](https://user-images.githubusercontent.com/24532731/185700897-153873ec-c7b5-4d83-930c-8317c9c50eea.png)

On submit, you should go through the REST API process as described above.  When the upload is done, write a message to the console.  TODO:  do we need to keep the prompt open to show the progress, or show a prompt on completion?

I'll review this process with @JustinProminic next week, and we may need to make some changes.  We may also want an option to trigger this prompt from the right-click menu on a .nsf file (which may change the defaults).

**Comment by rat-moonshine** [comment]
While starting the Vagrant/Domino server today I encountered with following error:

> : Bringing machine 'domino-vm' up with 'virtualbox' provider...
> : There are errors in the configuration of this machine. Please fix
> : the following errors and try again:
> : vm:
> : * The host path of the shared folder is missing: ./dist-id-files

Without having an idea, I tried this to start several times but it continues to return the same error, while the server did worked last night. Having not much of an option in mind, I tried to destroy the earlier instance and `up` again. Incidentally, I noticed following notes/instruction in https://github.com/DominoVagrant/demo page:

> Copy this ID to ./dist-id-files/safe.ids (or update SAFE_NOTES_ID in Vagrantfile), and run vagrant up.

With some speculation I created a blank directory named "dist-id-files" under root repository, and that did worked this time. Unfortunately by that time I already destroyed the earlier created Vagrant instance, so it took me another hour to re-create. 

The functionality is ready for an initial tests. You can download a build of macOS branch build from Bamboo to test.

**NOTE** on `Local Database`. For the time being I keep the field blank and not default populated. The field-property holds a `FileReference` object to use its `FileReference.upload()` method, unfortunately I found a `FileReference` object can be created through file browsing, generating a `FileReference` from a `File` object manually is difficult (or, I didn't found a way). A user needs to browse a file to access its `FileReference` object and then use its `upload` functionality. 

Please, check.

**Comment by JoelProminic** [comment]
I did a test and confirmed that the upload worked.

We discussed the FileChooser in the meeting today. We may be able to open the `File` directly and upload the binary data directory.   If we do need the user to create the FileReference from the filechooser, then we should make sure that the file chooser opens to the expected location by default - in my test it opened to a different directory, and I needed to find my project and the full path manually.

**Comment by rat-moonshine** [comment]
I re-tested `URLLoader` against my [earlier tests](https://github.com/Moonshine-IDE/Moonshine-IDE/issues/979#issuecomment-1174978023) to use this for an upload, I noticed that I was having a separate error that I believe was due to non-passing of upload-field name. 

I confirm I successfully able to upload a file using `URLLoader` this time, providing correct upload-field name. This will enable us to upload a file without going through a file-browser (unlike `FileReference`) and the way we wants this. We can also use this against a file-browsing event.

I'm adjusting my codes to fit these.

**Comment by rat-moonshine** [comment]
@JoelProminic pointed that `Project > Generate Java Agents` populates non-existing modules in generated project, as in following example "Author" and "Book" modules doesn't exists in parent OnDisk project:

![image](https://user-images.githubusercontent.com/24370870/186829035-4c24a34b-d33c-44ad-ad39-e7098701e575.png)

During our investigation we found that Moonshine generates modules from other currently opening OnDisk projects, too - into the generated Java agents project.

This problem should be fixed now. Please, check.

**Comment by JoelProminic** [comment]
I have been seeing an issue where deploying `nsf-moonshine-domino-1.0.0.nsf` from a new project, it instead deploys a previous copy from another project.   After some investigation with @rat-moonshine (thanks for your help!), it looks like this is actually triggering on the Vagrant side.  My current theory is that Domino is using a cache when opening the database as a template, so it won't get a fresh copy if I am using the same source name and path.   I'm working on fixing this in:  https://github.com/DominoVagrant/demo/issues/4

**Comment by JoelProminic** [comment]
The cache issue should be resolved now.   You should see the update if you pull `DominoVagrant/demo` and run `vagrant reload`.

One remaining issue I noticed while testing this is that I gave a bad default value for "Base Agent URL".  This should use "http://" instead of "https://".  I updated the [original comment](https://github.com/Moonshine-IDE/Moonshine-IDE/issues/1077#issuecomment-1221063516) to reflect this.

We could generate an SSL certificate for the Vagrant Domino server, but it would give errors unless it was generated by a proper certificate authority and we added a domain mapping in `/etc/hosts`.

**Comment by JoelProminic** [comment]
Also, the "NSF Converter" label in the prompt should be "Vagrant Instance" instead.   This was copied from a previous mockup.

**Comment by rat-moonshine** [comment]
- Protocol label updated
- Form label and title updated

**Comment by JoelProminic** [comment]
This action is working well with DominoVagrant/demo.

One remaining issue is that we need to get this added to Domino Visual Editor projects as well, along with the supporting settings.  These settings will also be used by #1072 and #1074, with @piotrzarzycki21 is working on currently.

**Comment by rat-moonshine** [comment]
This issue is now merged into `master`.

**Comment by JoelProminic** [comment]
I confirmed this feature on master.   We still need this added to Domino Visual Editor when you have a chance.  In the meantime, I can deploy it manually.

**Comment by rat-moonshine** [comment]
> We still need this added to Domino Visual Editor when you have a chance.

Does this means that the menu-option needs to be available for Domino Visual Editor project, and needs to trigger the same popup?

**Comment by rat-moonshine** [comment]
I updated the Domino Visual Editor project to properly opens the Deploy Database popup. 

However, I couldn't able to test an upload (although, it's the same popup/upload script) due to Vagrant error during running DominoVagrant/demo:

```
==> domino-vm: Running provisioner: file...
    domino-vm: dist => /home/vagrant/dist
==> domino-vm: Running provisioner: file...
    domino-vm: dist-support => /home/vagrant/dist-support
==> domino-vm: Running provisioner: Copy dist JARs to NotesJava (shell)...
    domino-vm: Running: script: Copy dist JARs to NotesJava
==> domino-vm: Running provisioner: Copy dist JARs to NotesJava (shell)...
    domino-vm: Running: script: Copy dist JARs to NotesJava
    domino-vm: cp: cannot stat ‘/vagrant/build/libs/*.jar’: No such file or directory
The SSH command responded with a non-zero exit status. Vagrant
assumes that this means the command failed. The output for this command
should be in the log above. Please read the output to determine what
went wrong.
```
Please, check.

**Comment by piotrzarzycki21** [comment]
Guys so what's the story with that ? Should I be able my export to Royale deploy on Vagrant and run actually ?

**Comment by JoelProminic** [comment]
@piotrzarzycki21, yes you should be able to export any Royale project to a compatible Vagrant server if you use the `Project > Deploy to Vagrant Instance` action.   This has been deployed to the master branch already.

For now, the only "compatible" Vagrant instance is [DominoVagrant/demo](https://github.com/DominoVagrant/demo).  You can try this yourself if your workstation supports Vagrant, but you'll need the Domino server.  I'll send a link by email.

We can add more compatible Vagrant servers later.  (Thinking about this, though, I regret putting the script in `/opt/domino`)

**Comment by JoelProminic** [comment]
A prompt is needed to select the Vagrant instance.  I created a generic prompt mockup:
![image](https://user-images.githubusercontent.com/24532731/190829386-9e42fe0a-2a7c-4863-8a91-cd756c7910df.png)
