### ISSUE TITLE
Deploy Royale Application to Vagrant Instance

### ISSUE THREAD

**Issue by JoelProminic** [Moonshine-IDE/Moonshine-IDE#1080]
I have added a new script to deploy Royale applications to the `DominoVagrant/demo` Vagrant instance.  This will be used to clear the CORS errors without the need to start a local server and set headers on the Domino server.

Script:  `/opt/domino/scripts/deploy_html.sh`
Capability:  `upload-html`
Parameters:
- The path to an uploaded ZIP file containing the compiled files
- The name of the target directory for the application.  Use the project name as the default

The zip file should be relative to the `bin` directory, so that it will contain the `js-debug` directory by default.  This is not a requirement of the script or server, so we can change this convention if you have a better idea.  Would it be better to include `bin/` in the zip to mirror the project structure?

The target directory will be (re)created in the base web directory, and then the zip file will be expanded into the directory.  So, the application should then be available at http://127.0.0.1:8080/%ProjectName%/js-debug/index.html

Command-line Example:

    # ZIP
    cd bin
    zip -r ../test.zip *

    # Upload ZIP
    curl -X "POST" "http://localhost:8096/file/upload" \
         -H "Content-Type: multipart/form-data" \
         -F "file=@/Users/-user-/Documents/Flex/temp_workspace/TestOldFormsRoyaleApplication/test.zip"

    # Run task.  First parameter comes from response of upload
    curl -X "POST" "http://localhost:8096/task" \
         -H "Accept: application/json" \
         -H "Content-Type: application/x-www-form-urlencoded" \
         --data-urlencode "command=/bin/bash /opt/domino/scripts/deploy_html.sh '/tmp/restinterface/upload/test.zip' 'TestOldFormsRoyaleApplication'"

    # Check the status - use the ID from the response to the `/task` command
    curl "http://localhost:8096/task/1"

    # Application available at:  http://127.0.0.1:8080/%ProjectName%/js-debug/index.html

In Moonshine, the action should be triggered from the Project menu for Royale projects:  `Project > Deploy to Vagrant Server`.  (An alternative would be to bundle it with the build action and call it something like `Project > Build & Run on Vagrant`.  I think it makes more sense to keep it separate for now, though).

The action should open a prompt like this:
![image](https://user-images.githubusercontent.com/24532731/187000209-ba58b029-f2f4-4173-ad8e-f0096e1eb21c.png)

Once the deployment task finishes, launch the expected URL in a browser.  In the long term, we may wan to make the base URL configurable based on the Vagrant `/info` response, but we can hard-code thsi for now.

**Comment by rat-moonshine** [comment]
This is now ready for a test with macOS branch build on Bamboo. Please, check.

**Comment by JoelProminic** [comment]
This is working well for me with the DominoVagrant instance. 

I see a couple cosmetic issues:
- The URL label looks awkward on a separate line, though I get that it is consistent with the rest of the labels.  Maybe italics or some other formatting on computed URL will look better?
![image](https://user-images.githubusercontent.com/24532731/187718826-ca116d9e-276c-4e9c-9e44-5dc979a1ac98.png)

Otherwise, I'd like to get this merged to master soon so that we can use it to test @piotrzarzycki21's updates for #1074.

**Comment by rat-moonshine** [comment]
I have replaced "URL" to "Possible URL". My reasoning was that `bin` could hold only `js-release` at a certain time and still able to be accessed as 12.0.0.1:8080/$projectName/js-release/index.html. We can still change the label to something more meaningful if we want.

I have adjusted the UI. However, for some unknown reason I see url-address not accepting _italic_ style. Possibly, because many of its embedding style usages in the application.

![image](https://user-images.githubusercontent.com/24370870/187855991-ee6591dd-1726-4aa9-a5f5-8c3bfc1f9383.png)

**Comment by rat-moonshine** [comment]
This issue is now merged into `master`.

**Comment by JoelProminic** [comment]
The URL display is still not great, but I can see that the URL will not fit on the same line with a long project name.

I think "Possible URL" sounds too uncertain.  If we keep this solution, I think "Example URL" would be better (though it still seems a bit misleading when Moonshine will automatically open that URL later).  "Target URL" would be consistent with the "Target Directory" parameter.  I think I like "Target Directory" the best, but other users may find this unclear.

I still see the "Project does not contains ..." typo (should be "Project does not contain..."

**Comment by rat-moonshine** [comment]
I did textual changes:
- "Possible URL" replaced with "Example URL"
- "Project does not contains ..." replaced with "Project does not contain..."

**Comment by JoelProminic** [comment]
I confirmed the prompt updates:
![image](https://user-images.githubusercontent.com/24532731/191379123-6473b903-eb6c-4e11-ad14-028e22b127a5.png)

Overall this is working well for me.  I may revisit this at some point to change the location for the `deploy_html.sh` script.
