### ISSUE TITLE
New DXL Importer Insertion Parameters for Generated Java Agent Projects

### ISSUE THREAD

**Issue by JoelProminic** [Moonshine-IDE/Moonshine-IDE#1083]
Now that we have the `DominoVagrant/demo` template mostly working, we like to populate the DXL Importer parameters in the generated Java projects for FormBuilder (#978) and DominoVisualEditor (#1072).

I made [some updates to the template](https://github.com/Moonshine-IDE/Moonshine-Domino-CRUD/issues/25), but there are a couple new project-level insertion parameters.  These can be populated with the [additional Domino settings added as part of database deployment](https://github.com/Moonshine-IDE/Moonshine-IDE/issues/1077#issuecomment-1221063516).

Parameter | Moonshine Setting | Description
----------|-------------------|------------
`%server%` | Target Server | The Domino server to use for DXL Imports.  This may be blank
`%databaseName%` | Target Database | The name of the agent database on the Domino server, including the path relative to the Domino Directory.

I updated the [template README](https://github.com/Moonshine-IDE/Moonshine-Domino-CRUD/blob/main/template/TemplateREADME.md) and example template code to include these new parameters.

**Comment by rat-moonshine** [comment]
I have added two new properties during generation https://github.com/Moonshine-IDE/Moonshine-IDE/commit/aa2cbefa61ab7283caaf3fa060bf2bbd1440d7da. However, I'm not clear on "including the path relative to the Domino Directory" against `%databaseName%` population. The "Target Database" from settings holds name-only `.nsf` file, where I should acquire the relative path to Domino server?

I assume the ordering of the process is:
1. Generate Java Agents
2. Deploy Java Agents (in this step however agent returns us the `.nsf` path in Domino)

**Comment by piotrzarzycki21** [comment]
@rat-moonshine I just looked into that and my [DominoJavaAgentsExporter](https://github.com/Moonshine-IDE/Moonshine-IDE/blob/master/ide/MoonshineDESKTOPevolved/src/actionScripts/plugins/visualEditor/domino/DominoJavaAgentsExporter.as) extends your [CRUDJavaAgentsExporter](https://github.com/Moonshine-IDE/Moonshine-IDE/blob/master/ide/MoonshineDESKTOPevolved/src/actionScripts/plugins/ondiskproj/crud/exporter/CRUDJavaAgentsExporter.as). Your latest changes are being used by me automatically - however you are casting over activeProject to force specific type of project - I don't think my logic is using [IDeployDominoDatabaseProject](https://github.com/Moonshine-IDE/Moonshine-IDE/blob/master/ide/MoonshineSharedCore/src/actionScripts/interfaces/IDeployDominoDatabaseProject.as) - in that case my generation will fail using method [createFileSystemBeforeSave ](https://github.com/Moonshine-IDE/Moonshine-IDE/blob/bdb91ecd989700b0e98d0af88ef713d844862064/ide/MoonshineDESKTOPevolved/src/actionScripts/plugins/ondiskproj/crud/exporter/CRUDJavaAgentsExporter.as#L243) - Can you make les strongly typed in that case ?

**Comment by rat-moonshine** [comment]
Isn't that Visual Editor Project creates `AS3ProjectVO`.. In that case `AS3ProjectVO` is already [implements](https://github.com/Moonshine-IDE/Moonshine-IDE/blob/master/ide/MoonshineSharedCore/src/actionScripts/plugin/actionscript/as3project/vo/AS3ProjectVO.as#L57) `IDeployDominoDatabaseProject` and populates the fields in project's settings in case of `AS3ProjectVO.[isDominoVisualEditorProject](https://github.com/Moonshine-IDE/Moonshine-IDE/blob/master/ide/MoonshineSharedCore/src/actionScripts/plugin/actionscript/as3project/vo/AS3ProjectVO.as#L258)`. I think the generate/deploy Java agents are available in case of Domino Visual Editor project only, let me know if I'm missing something, @piotrzarzycki21 .

**Comment by JoelProminic** [comment]
I did a test with Project > Generate Java Project for FormBuilder, and this worked like I expected.

I tried a test with Domino Visual Editor, and this also worked.  I haven't noticed any problems so far related the concerns reported by @piotrzarzycki21.

**Comment by JoelProminic** [comment]
@piotrzarzycki21, did you have any remaining concerns for this?  If not, we can close the issue.

**Comment by piotrzarzycki21** [comment]
> @piotrzarzycki21, did you have any remaining concerns for this? If not, we can close the issue.

No. I'm good here.
