### ISSUE TITLE
Parse Error When Opening Domino On Disk Project

### ISSUE THREAD

**Issue by JoelProminic** [Moonshine-IDE/Moonshine-IDE#1084]
@JesseProminic and I revisited the [test FormBuilder project](https://github.com/Moonshine-IDE/FormBuilder-Example-AuthorBookFan) for #978, and we found we couldn't open the project in Moonshine:

    : Error #1009
    : TypeError: Error #1009
    : 	at actionScripts.plugin.ondiskproj.importer::OnDiskImporter$/parse()
    : 	at actionScripts.impls::IOnDiskBridgeImpl/parseOnDisk()
    : 	at actionScripts.plugin.actionscript.as3project::AS3ProjectPlugin/openProjectByDirectory()
    : 	at actionScripts.plugin.actionscript.as3project::AS3ProjectPlugin/importProjectWithoutDialog()
    : 	at flash.events::EventDispatcher/dispatchEvent()
    : 	at actionScripts.plugins.nativeFiles::FileAssociationPlugin/openFilesByPath()
    : 	at actionScripts.plugins.nativeFiles::FileAssociationPlugin/onAppInvokeEvent()
    : 	at flash.events::EventDispatcher/dispatchEvent()
    : 	at flash.desktop::NativeApplication/dispatchEvent()
    :
    : Click here to Report a Bug

I got some inconsistent results when debugging this, but I found some possible causes:
- The project directory does not match the .ondiskproj file (depending on how the repository was cloned or downloaded)
- The project name and directory contains dashes
- Missing `src/main/visualeditor` directory - this empty directory was excluded from Git

**Comment by rat-moonshine** [comment]
I noticed some variations in project opening/parsing steps between different project types, OnDisk was one of them. 

I made some requisite changes and that fix the said project opening. Please, check.

**Comment by JoelProminic** [comment]
I ran this test on macOS Catalina:
1. Download `FormBuilder-Example-AuthorBookFan` [as a zip](https://github.com/Moonshine-IDE/FormBuilder-Example-AuthorBookFan/archive/refs/heads/main.zip)
2. Unzip the directory.  It should appear as `FormBuilder-Example-AuthorBookFan-main`
3. Open the `FormBuilder-Example-AuthorBookFan.ondiskproj` file from Finder
4. The project opens as `FormBuilder-Example-AuthorBookFan-main` (using the directory name)

For comparison, if I try opening a Domino Visual Editor project generated by NSFConverterPortalProject, I see the project name based on the configuration file.  This discrepancy is odd, but not necessarily a problem.
![image](https://user-images.githubusercontent.com/24532731/189743660-2b41e1d7-8e66-4ea9-894d-8866f7a9a640.png)


I tried some variations on my above test case, and I got the same behavior for the project name.
- Open the project with `Project > Open Project`.
- Open the project with `Project > Import Project Archive`
- Open the project with `Git > Clone`.  Choose a target directory that doesn't match the `.ondiskproj` file in this case.

**Comment by rat-moonshine** [comment]
In above screenshot I see project name is different than then configuration file name. However, Moonshine do not stores project name explicitly in any of its configuration files. If any project-name populates based on reading _from_ configuration file, then it could have being done from reading some path value for the particular project type. 

The closest thing we probably can fix in OnDisk project is to populated based on the configuration file name. I see that is happening in Visual Editor Domino project case, too.

**Comment by rat-moonshine** [comment]
I have adjusted project parsing for OnDisk and Generic projects, and a project name should populate based on its configuration file now.

![image](https://user-images.githubusercontent.com/24370870/189846385-23bf4d91-68b3-4238-bde3-fac66007039c.png)

**Comment by JoelProminic** [comment]
I confirmed the updated behavior for OnDiskProject and GenericProject.  @rat-moonshine reported that these projects were updated to match the logic of the other project types, but I confirmed the behavior with some quick tests for DominoVisualEditor and FlexDesktop.
