### ISSUE TITLE
BUILD FAILED

### ISSUE THREAD

**Issue by godolsoft** [Moonshine-IDE/Moonshine-IDE#1085]
Hello everyone, does anyone know how to solve this error?,

compileAPKProject:
:      [java] C:\Users\TICS\Documents\vericono\build\build-debug\vericono-app.xml: error 303: Icon assets/icon_48.png is missing from package
:      [java] C:\Users\TICS\Documents\vericono\build\build-debug\vericono-app.xml: error 303: Icon assets/icon_72.png is missing from package
: 
: BUILD FAILED
: C:\Users\TICS\Documents\vericono\build\build.xml:145: Java returned: 12

**Comment by piotrzarzycki21** [comment]
@godolsoft This is unrelated to Moonshine. You have probably in your build.xml file incorrect path to your assets icon.
