### ISSUE TITLE
Import Genesis Catalog Project

### ISSUE THREAD

**Issue by JoelProminic** [Moonshine-IDE/Moonshine-IDE#1089]
We would like to add a way to open a project from Genesis Catalog in Moonshine.   We'll add this as a `Project > Import from Genesis Catalog` menu action.

The basic logic is close to `Project > Import Project Archive`, but we will have an extra download step:
1. `Project > Import from Genesis Catalog`
2. Show prompt for "Download URL"
3. Moonshine downloads the file
4. Moonshine unzips the file
5. Moonshine opens the directory as a project in Moonshine, using the current logic.

In the long term, we'd like to add a [custom URL protocol handler](https://stackoverflow.com/questions/80650/how-do-i-register-a-custom-url-protocol-in-windows) to Moonshine to allow us to trigger this directly from the GenesisCatalog website.   We tried something similar for [Prominic Native](https://github.com/prominic/AIR-Prominic-Native/issues/78#issuecomment-993455143) (private project).

**Comment by rat-moonshine** [comment]
Updates:
- Menu
- Poupup
- Job class

Todo:
- Upload a project Zip somewhere
- Test everything

**Comment by rat-moonshine** [comment]
This seems to be working now. I have merged this into `master` for easy in our tests. Any further change/fix can applied there.

**Comment by rat-moonshine** [comment]
My note:
For testing with a quick remote zip:

> https://github.com/Moonshine-IDE/Vagrant-REST-Interface/archive/refs/heads/master.zip

**Comment by rat-moonshine** [comment]
I have adjusted the codes to manage in following scenarios:

- If target project directory already exists, Moonshine will prompt with a re-browse option
- If the downloaded zip doesn't has a nested root directory, it'll shown an error on console `Zip archive do not contains a nested root. Project fails to open.` and terminates

Please, check.

**Comment by JoelProminic** [comment]
I created some zip files with multiple files at the base level for testing:
[2022_09_26__DependenciesTest1.zip](https://github.com/Moonshine-IDE/Moonshine-IDE/files/9647951/2022_09_26__DependenciesTest1.zip)
[2022_09_26__test_java_dependencies.zip](https://github.com/Moonshine-IDE/Moonshine-IDE/files/9647952/2022_09_26__test_java_dependencies.zip)

**Comment by rat-moonshine** [comment]
Updates:

- Updated support to check and notify if a zip contains root directory or not, more properly
- Added support to find and prompt if multiple projects found within the target directory

Please, check.

**Comment by JoelProminic** [comment]
This worked as expected for each of the example projects above.  The first two failed with:

    : Unsupported zip file: multiple files at base level.

And the third one opened the standard prompt for multiple projects.

We will review this issue in the meeting tomorrow to plan the next step.

**Comment by rat-moonshine** [comment]
- URL protocols added for both macOS and Windows(through NSIS) 
- Running address on a browser with `moonshine://hello` or `moonshinedevelopment://hello` shall trigger the respective applications

**Comment by rat-moonshine** [comment]
URL protocol is ready for a test in Moonshine now:

1. Install Moonshine/Development
2. Open a browser and enter the URL scheme in its address-bar: `moonshine://gencaturl=https://github.com/Moonshine-IDE/Vagrant-REST-Interface/archive/refs/heads/master.zip` - modify the protocol between `moonshine://..` and `moonshinedevelopment://..` based on the target application you wants to trigger
3. Hit `Enter`
4. On macOS browser, choose `Allow` in the standard opening dialog to confirm the browser opens the application
5. Moonshine application should start (if not running already) and opens the Import Genesis Catalog popup with the query value from `gencaturl=`

I set the query variable as `gencaturl` for now, we can change this if requires.

**Comment by JoelProminic** [comment]
This is working for me on macOS Firefox and Windows Edge.  We should probably check other browsers for compatibility.   

I notice that Edge prompted me to allow the page to access Moonshine, but Firefox did not have a security prompt:
![image](https://user-images.githubusercontent.com/24532731/193094527-e153b732-462f-434d-b291-3c0b1073c881.png)

**Comment by JoelProminic** [comment]
We will need to add [URL encoding](https://www.w3schools.com/tags/ref_urlencode.ASP) for the gencaturl parameter (an future parameters).  For example, if I test this URL:

moonshinedevelopment://gencaturl=https://test.com?p1=foo&p2=bar

Then Moonshine currently treats `p2=bar` as a separate parameter:

![image](https://user-images.githubusercontent.com/24532731/193096077-a3edac17-7202-407a-bb51-29db7143c0c4.png)

We'll need to encode the `gencaturl` URLs on the Genesis Catalog website, and decode the value on the Monshine side.

**Comment by Igazine** [comment]
@Team please note that application InvokeEvent is not available in OpenFL. So this is once again a feature that we need to implement as a native extension

**Comment by rat-moonshine** [comment]
> @Team please note that application InvokeEvent is not available in OpenFL. So this is once again a feature that we need to implement as a native extension

@joshtynjala do you see a possibility we can have `InvokeEvent` in a future Openfl release (?) I think this a standard CLI feature that could available to any desktop applications.

**Comment by rat-moonshine** [comment]
URL decoding added for the _URL_ part from `gencaturl=$url`. 

An example of fully encoded URL parameter:
`moonshine://gencaturl=https%3A%2F%2Fgithub.com%2FMoonshine-IDE%2FVagrant-REST-Interface%2Farchive%2Fref%2Fheads%2Fmaster.zip&foo=bar`

We need to ensure that `=` and `&` continue to use as separator and not be encoded.

**Comment by joshtynjala** [comment]
> @joshtynjala do you see a possibility we can have InvokeEvent in a future Openfl release (?) I think this a standard CLI feature that could available to any desktop applications.

If there's a way to do it in Haxe, we can add that to OpenFL. I'm not actually sure whether Haxe can do it or not. A quick Google search didn't bring up much, but I can try to do some deeper research next month.

**Comment by rat-moonshine** [comment]
Thank you @joshtynjala , that would be very helpful. Since this a very internal-in-nature logic to an application shell, maybe it'd be better if we can have the functionality available by the application itself, rather than helping through an extension, although that option we continue to have to investigate.

**Comment by Igazine** [comment]
> I think this a standard CLI feature that could available to any desktop applications.

Starting an app with command line parameters, and registering URL handlers and handling app invocation (even in already running apps) are two very different things. The former is naturally available in all known frameworks, the latter is an OS-specific feature set that's seemingly working entirely differently on different platforms. On macOS the protocol registration is being done in info.plist, on Windows it's registry-based, while Linux store this stuff in files on disk. And then comes the actual implementation of the protocol/invocation handler code which is again different on each targeted platform.

Let's hope Josh finds something useful, but I highly doubt there would be a cross-platform solution that's easy to implement (although I'm not an expert in Haxe/Lime's low-level stuff)

**Comment by rat-moonshine** [comment]
You're right @Igazine , they are different thing. My reference to the term CLI was because in both the cases we're using the CLI way to catch/read application arguments. So far the `InvokeEvent` provides us both the world to work with, I didn't tested with Linux, though. 

We have URL protocol works in both macOS and Windows using with `InvokeEvent`. I don't know of Linux at this moment.

**Comment by JoelProminic** [comment]
We can test the decoding using [online encoders](https://www.urlencoder.org/).

Original URL:  https://test.com/testdownload.zip?p1=foo&p2=bar
Encoded (with extra parameter):  `moonshinedevelopment://gencaturl=https%3A%2F%2Ftest.com%2Ftestdownload.zip%3Fp1%3Dfoo%26p2%3Dbar&p3=DONOTINCLUDE`

The URL displayed in Import from Genesis Catalog should match the original URL.


I asked @JesseProminic to help test more browser support.

**Comment by JesseProminic** [comment]
The test link works both in Safari and Chrome on macOS.

**Comment by JesseProminic** [comment]
On Widow 11, the test link does open in Edge and Google Chrome but I got a message on Console:

Unable to access file:moonshinedevelopment://gencaturl=https%3A%2F%2Ftest.com%2Ftestdownload.zip%3Fp1%3Dfoo%26p2%3Dbar&p3=DONOTINCLUDE

![Screen Shot 2022-09-30 at 1 20 51 PM](https://user-images.githubusercontent.com/96078188/193333755-7d6b9fb3-af02-4696-93ab-167c6ec8f03b.png)

**Comment by rat-moonshine** [comment]
> I got a message on console:
> 
> Unable to access file:moonshinedevelopment://gencaturl=https%3A%2F%2Ftest.com%2Ftestdownload.zip%3Fp1%3Dfoo%26p2%3Dbar&p3=DONOTINCLUDE

This message could be a side-effect from other plugin class also listens to `InvokeEvent`. I shall check and see what I can do.

**Comment by rat-moonshine** [comment]
> moonshinedevelopment://gencaturl=https%3A%2F%2Ftest.com%2Ftestdownload.zip%3Fp1%3Dfoo%26p2%3Dbar&p3=DONOTINCLUDE

This problem should have resolved now. Please, check.

**Comment by rat-moonshine** [comment]
> > I got a message on console:
> > Unable to access file:moonshinedevelopment://gencaturl=https%3A%2F%2Ftest.com%2Ftestdownload.zip%3Fp1%3Dfoo%26p2%3Dbar&p3=DONOTINCLUDE
> 
> This message could be a side-effect from other plugin class also listens to `InvokeEvent`. I shall check and see what I can do.

This problem should have resolved now. Please, check.

**Comment by JesseProminic** [comment]
> > > I got a message on console:
> > > Unable to access file:moonshinedevelopment://gencaturl=https%3A%2F%2Ftest.com%2Ftestdownload.zip%3Fp1%3Dfoo%26p2%3Dbar&p3=DONOTINCLUDE
> > 
> > 
> > This message could be a side-effect from other plugin class also listens to `InvokeEvent`. I shall check and see what I can do.
> 
> This problem should have resolved now. Please, check.

Yes the message is no longer showing up.

**Comment by joshtynjala** [comment]
> @joshtynjala do you see a possibility we can have InvokeEvent in a future Openfl release (?) I think this a standard CLI feature that could available to any desktop applications.

In the 9.3.0-Dev branch of OpenFL, I have implemented `InvokeEvent.INVOKE` for the initial set of command line options passed to the app on launch.

AIR also supports `InvokeEvent.INVOKE` for an app that is already open. This is **not** yet supported in my new implementation for OpenFL. In fact, I'm not sure that I have enough knowledge of C++ and native macOS/Windows APIs to further implement this on my own.

Implementing it on macOS actually looks to be relatively straightforward. There's an `application:openFile:` method in Objective-C that gets called when an associated file is double-clicked in Finder (and also if the user drags and drops a file onto the app). Under the hood, OpenFL uses SDL, which already provides an `application:openFile:` implementation that was added to handle dragging and dropping files (and it basically gets the non-dragdrop part for free). OpenFL can listen for the existing event from SDL and use that to dispatch `InvokeEvent.INVOKE`... but only on macOS.

On Windows, it seems to be much more complicated. SDL on Windows handles only dragging and dropping files, but not double-clicking files from Explorer. Seemingly because these actions aren't unified in a single API on Windows, like they are on macOS. As best I can tell, opening an associated file from Explorer on Windows always results in launching a new instance of the .exe. I've read that a new instance is supposed to detect if an older instance of the same .exe is already open. If there's an older instance, the new instance should pass a message to the older instance, and then exit. Then, the older instance will handle it from there. That's way to much low-level stuff for me to figure out in a reasonable timeframe.

**Comment by rat-moonshine** [comment]
That was indeed a bit critical in implementation, thank you @joshtynjala, for the details. 

While you referred to file-type-association, I remember this another area we might requires your guidance. 

Currently, file-type-association we declares through project's `*-app.xml` file. We saw this is sufficient for Windows, however we required to do some additional handling for macOS which we does through [manipulating](https://github.com/Moonshine-IDE/Moonshine-IDE/blob/master/ide/MoonshineSharedCore/build/build-lib.xml#L464) info.plist file through our Ant build-script.

I was wondering what was the mechanism for these in Openfl project? How we'll going to declare the file-type-association or is their any such configuration file where we can write these?

**Comment by Igazine** [comment]
@rat-moonshine It's somewhat the same/easier to add info.plist and entitlements.plist additions in OpenFL apps.

- First you have to create a local directory in the OpenFL project root (but can be anywhere accessible to the compiler). e.g. `{root}/Templates`
- Then you have to copy the [macOS templates](https://github.com/openfl/lime/tree/develop/templates/mac) directory from Lime's installation directory into your app's newly created directory (so you have something like `{root}/Templates/mac` with 2 plist files in it). Lime resides in {haxelibroot}/lime/{currentversion} on your system, this `haxelib libpath lime` console command will print the actual path
- You can extend or modify the contents of the these newly created plist files depending on your needs
- Lastly you have to define the template path in the OpenFL [project.xml](https://lime.openfl.org/docs/project-files/xml-format/) file. e.g. `<template path="Templates" />`. This template path can be configured for different build scenarios, just like any other value in the project.xml file
- The compiler will pick these templates up and use them instead of Lime's defaults (btw editing [these templates](https://github.com/openfl/lime/tree/develop/templates) is how you define a lot of stuff for all supported platforms)

**Comment by Igazine** [comment]
On Windows the file associations (and the majority of these kind of things) are defined in the Registry. I believe the installer engine can be configured to add/modify Registry values, but I also have a working C++ code to manipulate (read/write) Registry entries and values.

**Comment by rat-moonshine** [comment]
https://lime.openfl.org/docs/project-files/xml-format/ this is even more broad than I imagined. Thanks for the links and details @Igazine . I can imagine I need some time and hand-on experience to digest all these details, though ) But it is good that we have mechanism to do these in Haxe/Openfl.

Regarding Windows' registry-edit, we generally does this through our NSIS installer, as we did for URL protocol needs.

**Comment by rat-moonshine** [comment]
@dpastov I'm not sure if this already implemented/added at genesis.directory website side, but URL-protocol is available at Moonshine side now. An URL with given format should able to trigger Moonshine to prompt with Genesis Catalog Import. More details are at [here](https://github.com/Moonshine-IDE/Moonshine-IDE/issues/1089#issuecomment-1263800148).

Just to note, there are two protocol services currently available to Moonshine-IDE: `moonshine://$arg` and `moonshinedevelopment://$arg`, while we probably wants to call the former from genesis.directory website.

**Comment by JoelProminic** [comment]
@dpastov, here is an example:

For a download URL like this:  https://github.com/prominic/DbSigner/archive/refs/heads/main.zip

The Genesis URL looks like this:
moonshine://gencaturl=https://github.com/prominic/DbSigner/archive/refs/heads/main.zip

Until Moonshine is released, you'll want to use moonshinedevelopment://:
moonshinedevelopment://gencaturl=https://github.com/prominic/DbSigner/archive/refs/heads/main.zip

**Comment by dpastov** [comment]
@JoelProminic when I tried to open project in Moonshine it did not work and in the browser it throws such an error (see it below). 
Could you please explain what I need to do in order to resolve it?

> Failed to launch 'moonshine://gencaturl=https%3A%2F%2Fgithub.com%2Fprominic%2FDbSigner%2Farchive%2Frefs%2Fheads%2Fmain.zip' because the scheme does not have a registered handler.

**Comment by JoelProminic** [comment]
This is because the new handlers are only configured in Moonshine Development for now.  This will be available in Moonshine once we release 3.3.3.

You can use the moonshinedevelopment:// URL for testing, for now.  Note that you will see a similar error if you don't have a recent version of MoonshineDevelopment installed.  We may want to move the Moonshine download link or other text  in the pages to make it more clear that the user needs to install Moonshine first.  We can brainstorm more on this tomorrow.

**Comment by JoelProminic** [comment]
I reviewed this with Justin and Dmytro today.

Justin asked about when Moonshine registers the URI handlers.  On installation?  On startup?

The `moonshinedevelopment://` links do not work for Dmytro on Windows.  This worked for Jesse and me, so this needs more investigation.

We'd like to change "Genesis Catalog" to "Genesis Directory Catalog" to match the website domain (I see it at least in the menu action and panel title).

I see that the Project > Import from Genesis Catalog now fails for URLs ("Invalid URL format"):
- Previous test example:  https://github.com/Moonshine-IDE/Vagrant-REST-Interface/archive/refs/heads/master.zip
- Example from Genesis website:  https://genesis.directory/files/c746859f68e114c6c12588d9007c4816/dbsigner.zip 

![image](https://user-images.githubusercontent.com/24532731/195706162-76b832a6-d201-4a37-bfc6-476cd3934579.png)

**Comment by JoelProminic** [comment]
@JustinProminic wants to move away from using the ZIP download URL directly in the moonshine links.  Instead we should use an ID for the appication.

Proposed URI format:  `moonshine://project/%id%`
Example:  `moonshine://project/iMessageSMS`

Note that the body of the URI is not in the query string format (i.e. `project=iMessageSMS`).  If we can't make this work with the proposed format above, we can use the query string format.

Once Moonshine gets the app ID, it will need to lookup the download URL.  We'll do this through the api.genesis.catalog like we do for MyAccount, but this requires updates from @dpastov.

Proposed URL:  https://api.genesis.directory/v1/apps/%id
Example:  https://api.genesis.directory/v1/apps/iMessageSMS

Proposed output:

```
{
  "app":{
      "install": "install imessagesms",
      "id": "imessagesms",
      "title": "iMessageSMS - Send an SMS",
      "url": "https://genesis.directory/apps/iMessageSMS",
      "downloadURL": "https://genesis.directory/source/imessagesms.zip"
    }
}
```

Moonshine should use the `downloadURL` as the current zip URL.  @dpastov, note that `downloadURL` is a new property - feel free to change the name or URL format to match your needs or preferences.

If `downloadURL` is missing, `null` or `""`, then report an error (this will let us disable the download for a project if we haven't set it up yet):

> Project download is not currently available for this application.

@rat-moonshine, we would like to support the format `moonshine://project/%id%` in the `Project > Import from Genesis Directory Catalog` prompt.  This is the primary use case that Justin wants to support, but we could support other formats later.

**Comment by JoelProminic** [comment]
We would also like to have a new menu item underneath `Project > Import from Genesis Directory Catalog`:   `Project > Open Genesis Directory Catalog in Browser`.  This should open [https://genesis.directory/apps](https://genesis.directory/apps) in the default browser.

**Comment by JoelProminic** [comment]
Justin also requested that we add the Parent Directory field to the `Project > Import from Genesis Directory Catalog` dialog.  Ideally, we would reuse the logic from New Project so that we have a history of previously used directories, but we can simplify this to a simple filechooser for now if needed.

Note that we won't be able to check for project directory existance until we download and open the zip, so this could fail if the project is already downloaded.

**Comment by rat-moonshine** [comment]
> Justin asked about when Moonshine registers the URI handlers. On installation? On startup?

It writes to registry during the installation.

**Comment by rat-moonshine** [comment]
> Note that the body of the URI is not in the query string format (i.e. project=iMessageSMS). If we can't make this work with the proposed format above, we can use the query string format.

My recommendation is we should use query string format to distinguish from other values we might send to Moonshine in this way. This pass through the `InvokeEvent` - when a file double-clicked or drop-inside, that also doesn't has a query string but we have a mechanism to determine if it's a file anyway. But I don't wants to make these mixed up between different sections' logic and keep the needs specific to different plugin classes determining by their respective query string. 

The query string suggestion `project=iMessageSMS` is vague in overall Moonshine perspective. I'd recommend using more specific string that determines the string is for Genesis Catalogue section, i.e. `genproject=iMessageSMS`. For now I'm going to use this term but we can adjust the wording always.

**Comment by rat-moonshine** [comment]
https://github.com/Moonshine-IDE/Moonshine-IDE/commit/9594af5188cdeb3a33331f99b0ca0baf53ef88da

> I see that the Project > Import from Genesis Catalog now fails for URLs ("Invalid URL format"):

I couldn't able to reproduce this during my tests, unfortunately. Both the URLs properly tested and download started therefore.

> Note that the body of the URI is not in the query string format (i.e. project=iMessageSMS). If we can't make this work with the proposed format above, we can use the query string format.

For the time being, I set the query requirement as `moonshine://genproject=%id%`. I still do not recommend a format like `moonshine://project/%id%` to support further implementation on this area in future, and reduce complexity/confusion. We can talk on this more if requires, though.

Following the updates:

- Query changed from `gencaturl=$url` to `genproject=%id`
- Popup title updated
- Web-service call added to fetch genesis.directory website data based on the `%id%` - currently, https://api.genesis.directory/v1/apps/iMessageSMS returns 404 thus no further handling added in Moonshine now, once I shall have some data I shall parse and populates the input-field based on the `downloadURL`
- Necessary UI handling added to support above case
- Parent directory selection field added in the popup
- New menu option "Open Genesis Directory Catalog in Browser" added

**Comment by dpastov** [comment]
@rat-moonshine @JoelProminic 

I have extended the API so we can lookup for App by ID

`https://api.genesis.directory/v1/apps/%id`

Example (success):

https://api.genesis.directory/v1/apps/iMessageSMS

```
{
 app: {
  install: "install imessagesms",
  downloadurl: "https://genesis.directory/files/c746859f68e114c6c12588d9007c4816/dbsigner.zip",
  id: "imessagesms",
  title: "iMessageSMS - Send an SMS",
  url: "https://genesis.directory/apps/iMessageSMS"
 }
}
```

Example (error)

https://api.genesis.directory/v1/apps/qwerty

`{ }`

**Comment by rat-moonshine** [comment]
Thank you @dpastov , I'm adding the handlers now.

**Comment by rat-moonshine** [comment]
> The moonshinedevelopment:// links do not work for Dmytro on Windows. This worked for Jesse and me, so this needs more investigation.

@dpastov please make sure you install with newer installer. Also, make sure you have single `Moonshine.exe` or `MoonshineDevelopment.exe` in your system - although this is unlike scenario, but we've seen such strange things in macOS, at least.

**Comment by rat-moonshine** [comment]
[Web-service](https://github.com/Moonshine-IDE/Moonshine-IDE/issues/1089#issuecomment-1278703772) handling now added into Moonshine. Please, check.

**Comment by dpastov** [comment]
@rat-moonshine 

> @dpastov please make sure you install with newer installer.

I have installed 3.3.3 (development version) now and after that protocol: "moonshinedevelopment://" started to work.
When I run moonshine.exe it switch somehow to moonshinedevelopment.exe (I can see that in taskmanager/process). It's fine, just wanted to inform about that.

My steps:

1. Click on link: moonshinedevelopment://genproject=dbsigner
2. That runs Moonshine and popup me with a dialog with prefilled url to zip file.
![image](https://user-images.githubusercontent.com/844872/195850043-0edac543-ef1e-435c-adad-9f1f03a5ac99.png)
3. After I specify location and [Submit] it successfully downloaded the project on my disk and added it to Moonshine IDE.
![image](https://user-images.githubusercontent.com/844872/195850245-8f8de002-c0c3-4592-9f7d-0d6e18ee0c3f.png)

So things work well as expected in main scenario (I have not tested scenarios with improper gebproject or if project URL is not valid etc).

**Comment by JoelProminic** [comment]
After some refeactoring during today's meeting, the prompt looks like this:

![image](https://user-images.githubusercontent.com/24532731/195943197-0da42bf8-6f0b-4128-b9c3-53324faea029.png)

The URL format has been changed to Justin's original request:  `moonshine://project/dbsigner`

Test | Status | Notes
-- | -- | --
Test from browser (macOS) | Works | 
Test from browser (Windows) | Works | 
Test from prompt (macOS) | Works | 
Test from prompt (Windows) | Works | 
Prompt test | Updated as requested | Changes were made during meeting
Menu Item to open prompt | Updated | `Project > Import from Genesis Directory Catalog`
Menu Item to open genesis.directory | Works | 
Invalid application ID  | Triggers error on submit | "Not a valid application at https://api.genesis.directory/v1/apps/dbsigner
Pass ZIP URL | Works | This was not part of the updated requirements, but it is still supported from the old logic.

There are still some remaining changes on the genesis.catalog website, but I think the URI handler and Moonshine logic are working well.  I'll review this with Justin later today if we have time.

**Comment by JoelProminic** [comment]
We don't need any other immediate Moonshine-side changes before the release, so I am closing this issue.
