### ISSUE TITLE
Add "dark" Theme to code editor

### ISSUE THREAD

**Issue by piotrzarzycki21** [Moonshine-IDE/Moonshine-IDE#109]
Adding dark theme to code editor should be configurable from the settings. Suggestion where we should put that option most welcome.

**Comment by rat-moonshine** [comment]
I think #108 is a related issue. We can manage one (issue) for this.

**Comment by piotrzarzycki21** [comment]
Yes I would like to change existing colors for code in case of white theme. - It is also an exercise whether we can do this. Then jump to the dark theme.

**Comment by blackjyn** [comment]
Does this dark theme feature already been implemented?

**Comment by piotrzarzycki21** [comment]
Hi @blackjyn,

Unfortunately not. It is still in our long task queue. 

Thanks for asking!
Piotr

**Comment by joshtynjala** [comment]
Open Moonshine settings, and go to the Text Editor page. There are now new options for syntax color scheme and font size.

**Comment by JoelProminic** [comment]
We missed this in the 3.3.3 Milestone, but it has been working well.  We'll create separate issues if we find problems.
