### ISSUE TITLE
Project > Clean Fails for Domino Visual Editor or Domino On Disk Project

### ISSUE THREAD

**Issue by JoelProminic** [Moonshine-IDE/Moonshine-IDE#1090]
I'm seeing this behavior in my tests for the Database Conversion demo.
1. Create a new Visual Editor Project (Domino type) or Domino On Disk Project (FormBuilder)
2. Project > Build with Apache Maven.  Note that the `nsfs/nsf-moonshine/target` directory is created
3. Project > Clean.  BUG:  There is no message on the console, and `nsfs/nsf-moonshine/target` is not deleted
4. Right-click on the project and choose Copy Path
5. Open a Terminal and navigate to the path
6. Run `mvn clean` (you may need to setup environment variables for Maven and Java).  
7. Note that the `nsfs/nsf-moonshine/target` directory is removed.

**Comment by rat-moonshine** [comment]
I was unaware on what to do in case of OnDisk project, thus no command was added in `clean` handler. 

I have added `mvn clean` command in case of OnDisk and Domino Visual Editor projects now, if Maven is unavailable it'll terminate with necessary error.

**Comment by JoelProminic** [comment]
I did some testing and confirmed that this works.

Project | OS | Test Result
--------|----|------------
Form Builder | macOS | Works
Form Builder | Windows | Works
Domino Visual Editor | macOS | Works
Domino Visual Editor | Windows | Works

If Maven is missing, I see this error:

I did some testing and confirmed that this works.

    : Unable to find Maven to run a clean.

I think it would be better to use the same behavior as Project > Build with Apache Maven
1. Display "Specify path to Maven folder"
2. Open Maven Settings page.

**Comment by JoelProminic** [comment]
I see this is opening the Maven settings now, but it is using the ": Unable to find Maven to run a clean.".  This message feels a bit awkward to me, so I'd rather use the message from Build with Apache Maven.   On further review, I'd like to change that message to just "Specify path to Maven" - "folder" feels redundant here.

**Comment by rat-moonshine** [comment]
Message is being updated, please check.

**Comment by JoelProminic** [comment]
I confirmed the message is updated for DominoVisualEditor and FormBuilder, and for both Clean Project and Build with Apache Maven.  This looks good to me.
