### ISSUE TITLE
Haxe/Openfl Project Failed to Re-Build Following A Compilation Error

### ISSUE THREAD

**Issue by rat-moonshine** [Moonshine-IDE/Moonshine-IDE#1093]
While working on Haxe/Openfl project targeting MacOS platform, I noticed that once a `Build & Run` process failed because of any compilation error, next time trying `Build & Run` throws following error on console and refused to build:

`Build is running. Wait for finish...`

A restart to Moonshine eliminates the problem, though.

I also noticed that there was no build-notification or build-termination button in Moonshine status bar, during a build.

- [x] Fix run-compilation problem
- [x] Add build-notification/termination to its status bar

**Comment by JoelProminic** [comment]
This update works for the original topic, but it made me look into how we are handling concurrent builds for other projects.  This is outside of the scope for this issue, so I'll create a separate issue if we want to investigate it.
