### ISSUE TITLE
Vagrant Exception When Killing Non-Vagrant Action

### ISSUE THREAD

**Issue by JoelProminic** [Moonshine-IDE/Moonshine-IDE#1095]
1. Restart Moonshine
2. Open a Royale Project
3. Project > Ruild
4. Project > Deploy to Vagrant - let this finish
5. Open another project. I confirmed this for Haxe OpenFL and Flex Desktop
6. Cancel the action with the button in the bottom-right.  BUG:  Moonshine shows an error for a Vagrant action

    : Error #1009
    : TypeError: Error #1009
    : 	at actionScripts.plugins.vagrant::VagrantPlugin/onTerminateDeployRoyaleVagrantRequest()
    : 	at flash.events::EventDispatcher/dispatchEvent()
    : 	at components.views.other::MoonshineStatusBar/onTerminateBuild()
    : 	at components.views.other::MoonshineStatusBar/__btnStop_click()
    :
    : Click here to Report a Bug

I repeated the test without running the `Deploy to Vagrant` action, and the error did not trigger.  I expect this is caused by an event listener that was not removed properly.

Watch for similar problems on other Vagrant actions.

If this issue is difficult to fix, we can save it for a later release - it seems to only be a cosmetic error.

**Comment by rat-moonshine** [comment]
Please, check.

**Comment by JoelProminic** [comment]
I can't reproduce this after the update.
