### ISSUE TITLE
Wrong Parent Directory for Convert Domino Database

### ISSUE THREAD

**Issue by JoelProminic** [Moonshine-IDE/Moonshine-IDE#1096]
I revisited #979 as part of other tests, and I found that the converted project is being created in the wrong directory:

![image](https://user-images.githubusercontent.com/24532731/195461909-8b983ad9-9a31-4790-88b7-667e116b9a56.png)

The "Select Parent Directory" path is not used by either the existance check or the actual created project.

I didn't see this problem in the original implementation of #979.

**Comment by rat-moonshine** [comment]
This should be fixed now, please check.

**Comment by JoelProminic** [comment]
The update works well for me.   I tested setting the fields in both orders (to make sure Moonshine wasn't using the last selected directory for the parent directory).

@rat-moonshine reported that it wasn't clear how this code was ever working properly, so we should watch for other related problems.

We should also return to this at some point to use the Parent Directory control from New Project, which will allow the user to select recently used parent directories.
