### ISSUE TITLE
Update Moonshine-Domino-CRUD Template URL

### ISSUE THREAD

**Issue by JoelProminic** [Moonshine-IDE/Moonshine-IDE#1097]
I used a temporary URL when we were originally setting up the `Moonshine-Domino-CRUD` template for FormBuilder and DominoVisualEditor:   

> https://moonshine-ide.com/downloads/Moonshine-Domino-CRUD/dev/template.zip

I would like to change this before the release (I confirmed this is working now):

> https://moonshine-ide.com/downloads/Moonshine-Domino-CRUD/prod/template.zip

It would be nice if we could automatically use the first URL for the Development build, but this should wait until after the 3.3.3 release.

I'll also need to update this production path with an official version of the zip.  I have been doing some test updates for quick fixes.

**Comment by rat-moonshine** [comment]
Done.

**Comment by JoelProminic** [comment]
I confirmed this was update.
