### ISSUE TITLE
Add DominoVagrant/demo To Default Repository List

### ISSUE THREAD

**Issue by JoelProminic** [Moonshine-IDE/Moonshine-IDE#1104]
@JustinProminic requested that we add the [DominoVagrant/demo] project to the default repository list in Moonshine.  This can be used for many of the new Vagrant actions (`Other > Convert Domino Database` requires a different Vagrant instance, which is private for now.  We may add this as an entry later).
- Repository:  https://github.com/DominoVagrant/demo
- Type:  GIT
- Notes:  Setup a test HCL Domino server

I should review the Notes message with @JustinProminic

**Comment by rat-moonshine** [comment]
Updates:
- Moved default repositories list to external [file](https://github.com/Moonshine-IDE/Moonshine-IDE/blob/848e965935e407d9142636da012ff63f093a1b91/ide/MoonshineSharedCore/src/elements/data/DefaultRepositories.xml)
- Added DominoVagrant in default list

**Comment by JoelProminic** [comment]
@JustinProminic confirmed that we should keep the XML file as part of the Moonshine build rather than putting it on the website.

Tests:
- Fresh install (cleared settings)
- Existing install (DominoVagrant should get added)
- macOS/Windows

**Comment by JesseProminic** [comment]
| | Fresh install (cleared settings)  |  Existing install (DominoVagrant) |
| --- | --- | --- |
macOS |:white_check_mark: | :white_check_mark: |
Windows | |
