### ISSUE TITLE
Select/Deselect All Broken in Multi-Project Prompt

### ISSUE THREAD

**Issue by JoelProminic** [Moonshine-IDE/Moonshine-IDE#1108]
After the Haxe merge (#1102), I found a problem in the multi-project open:
1. Project > Open/Import Project
2. Select the Moonshine-IDE directory
3. A prompt opens with the available projects
4. Disable the Select/Deselect All button.  BUG:  Nothing happens

![image](https://user-images.githubusercontent.com/24532731/198079762-cf9a9171-ec59-4f28-8185-2a0bd0355242.png)

**Comment by Igazine** [comment]
This issue has been fixed. Please wait for the master merge before testing

**Comment by Igazine** [comment]
Changes have been merged into master

**Comment by JoelProminic** [comment]
I confirmed this is fixed on the macOS development build.
