### ISSUE TITLE
Toggle Edit Mode in Generated Royale Forms

### ISSUE THREAD

**Issue by JoelProminic** [Moonshine-IDE/Moonshine-IDE#1110]
@JustinProminic requested that we have the generated forms open in read-only mode by default, and then add a button to toggle Edit Mode.  This will mimic the behavior of the Notes client.   

I'll update this issue with more details later.

**Comment by piotrzarzycki21** [comment]
If we will have "Edit" button in form what is happening with our list? The first thing which user sees when he enter specific option is list with Add, Remove option - I know you have stated @JoelProminic https://github.com/Moonshine-IDE/Moonshine-IDE/issues/1039#issuecomment-1292307553 that we should hide them, but it would be extremely unusual for the user have "Edit" mode ON inside form and make visible Add, Remove trough that.

In my opinion when user enters list - he should have option - checkbox or toggle button where he can switch between Edit/Non-Edit option for all. Next when he enter form he will see form in applied mode. Thoughts ?

**Comment by JoelProminic** [comment]
To clarify, this is different from #1039.  It is intended to be used even if not running in read-only mode.  The use case is:
1. The user clicks Add.  The form opens in write mode, and the user can create and submit the form
2. The user double-clicks an entry in the data grid/view.  In this case, the form opens in "read-only" mode so that the user can view the document without fear of accidentally making changes.  The Save button should be hidden or disabled.
3. The user decides to edit the open document, so they click an Edit button to switch to edit mode.   Ideally this button will be always visible so that the user doesn't have to scroll and lose their place in a large form to enable edit mode.   In Notes, we can enter edit mode by double-clicking on a field, but I'm not sure this would make sense for the Royale application.

Having a method to cancel edit mode may be desirable, but then we have to deal with incomplete changes.   I know Notes has an option for this, but most applications I use don't make this available.  Instead, I save and reopen the document.

**Comment by piotrzarzycki21** [comment]
> * The user clicks Add.  The form opens in write mode, and the user can create and submit the form
> * The user double-clicks an entry in the data grid/view.  In this case, the form opens in "read-only" mode so that the user can view the document without fear of accidentally making changes.  The Save button should be hidden or disabled.

This two scenarios has been implemented. I'ms till thinking how to resolve third option - I hope I will come up with something soon.

**Comment by piotrzarzycki21** [comment]
> Having a method to cancel edit mode may be desirable, but then we have to deal with incomplete changes. I know Notes has an option for this, but most applications I use don't make this available. Instead, I save and reopen the document.

We have working Cancel mode. When you enter to Edit/Read only mode for document - I'm doing a copy of object - if you cancel operation that copy is being removed.

**Comment by piotrzarzycki21** [comment]
Actions Save, Cancel and Edit Mode should be in the top.

**Comment by piotrzarzycki21** [comment]
Add, Cancel and Edit buttons are in place. This issue is ready for tests.

**Comment by piotrzarzycki21** [comment]
- Add Close button - should discard changes
- Cancel should get back to Readonly mode and revert changes - ideally we should get prompt with question whether we would like to discard changes

**Comment by JoelProminic** [comment]
The remaining issue is the background color for Jodit Editor.  Otherwise, this should be ready for a final review.

**Comment by piotrzarzycki21** [comment]
This feature seems to be implemented. Remaining issue has been raised separately and please raise new issues if needed.
