### ISSUE TITLE
Vagrant Select Prompt Disabled

### ISSUE THREAD

**Issue by JoelProminic** [Moonshine-IDE/Moonshine-IDE#1111]
I first noticed this issue before the Haxe Merge (#1102):
1. Make sure you have [DominoVagrant/demo]() running and configured in the settings.
2. Open a FormBuilder project (also triggers for other Vagrant actions, but this is an example)
3. Project > Build on Vagrant
4. BUG:   the Vagrant combobox is broken

![image](https://user-images.githubusercontent.com/24532731/198102491-304c488f-a923-4a1d-8e18-90be9977786f.png)

Note that this doesn't match the behavior when there are no applicable Vagrant instances - in this case it shows an empty combobox.

When I test the same Vagrant instance in Moonshine 3.3.3, it works fine.

@piotrzarzycki21 didn't seem to have this problem when testing today.

**Comment by rat-moonshine** [comment]
During my debug tests, I couldn't able to reproduce the problem, unfortunately. 

It does takes a little pause before populating the dropdown (if opens first time after `vagrant up`) between run its command and determine the available instances, but they populates eventually for me. 

I also updated to latest Development installer-build (2851), but it populates there as well. However, for the first time test it didn't populated, later I have found there was no entry in Settings > Vagrant. I couldn't remember if I had nothing there (?)

**Comment by rat-moonshine** [comment]
I have reduced the check-timeout to 3 seconds. Please, give this a try.

**Comment by JoelProminic** [comment]
This is usable now, but the delay is long enough that it is annoying when I need to run 4 REST action to import each generated application.  Try 2 seconds and we'll see if this feels better.

**Comment by rat-moonshine** [comment]
Timeout reduced to 2 seconds. Please, check.

**Comment by piotrzarzycki21** [comment]
I don't have any kind of problems so far with this after your update. Please close the issue.

**Comment by rat-moonshine** [comment]
Yeah, this probably alright for now. We shall have this closed once consult with @JoelProminic .

**Comment by JoelProminic** [comment]
I think the 2 second timeout is reasonable for now.  This has been working well while I have been working with the Vagrant REST.
