### ISSUE TITLE
MoonshineGUICore: Install non existing libs in standard HaxeLib librareis

### ISSUE THREAD

**Issue by piotrzarzycki21** [Moonshine-IDE/Moonshine-IDE#1113]
> The reason of this error is because every haxelib dependency is being installed by a script at startup / project open, and it uses the standard haxelib installation command line. However there are specific haxelibs dependencies for the GUICore that are not available on HaxeLib project yet as standard libraries, and need to be manually installed from GitHub.

I'm not sure how to mark these libraries in Moonshine config/scripts in order to use a different command line for these specific libraries. We need to come up with a more general solution that works in every possible Haxe project

E.g. the current config is trying to execute this:

`haxelib install moonshine-openfl-language-client`

while the moonshine-openfl-language-client is currently only available on GitHub, so it should be installed like this:

`haxelib git moonshine-openfl-language-client https://github.com/Moonshine-IDE/moonshine-openfl-language-client.git`

but the script does not know that, and it fails.

_Originally posted by @Igazine in https://github.com/Moonshine-IDE/Moonshine-IDE/issues/1102#issuecomment-1291868567_

**Comment by piotrzarzycki21** [comment]
Issue which was source of this issue -> https://github.com/Moonshine-IDE/Moonshine-IDE/issues/1102#issuecomment-1291807966

**Comment by piotrzarzycki21** [comment]
If I understand correctly when we launch Moonshine it looks into [project.xml](https://github.com/Moonshine-IDE/Moonshine-IDE/blob/master/ide/MoonshineGUICore/project.xml) file ? If I'm right about that maybe we should remove all non existing libraries in HaxeLib from that file ? User who would like to setup that project in Moonshine need to follow instruction in [README](https://github.com/Moonshine-IDE/Moonshine-IDE/tree/master/ide/MoonshineGUICore#readme) - I don't see anything bad to have some manual steps outside Moonshine to have project working.

However what is happening with running LS - when I do not reference these libraries in project.xml file - would it not show anything in code completion if I wanted to use any API from mentioned libraries ?

**Comment by joshtynjala** [comment]
> After opening in Moonshine IDE MoonshineGUICore and have following error:
> : Installing dependency lime...
> : You already have lime version 8.0.0 installed
> : Installing dependency openfl...
> : You already have openfl version 9.2.0 installed
> : Installing dependency actuate...
> : You already have actuate version 1.8.9 installed
> : Installing dependency feathersui...
> : You already have feathersui version 1.0.0 installed
> : Installing dependency amfio...
> : You already have amfio version 1.0.1 installed
> : Installing dependency format...
> : You already have format version 3.5.0 installed
> : Installing dependency markdown-openfl-textfield...
> : You already have markdown-openfl-textfield version 1.0.2 installed
> : Installing dependency moonshine-openfl-language-client...
> : Error: Failed with error: No such Project : moonshine-openfl-language-client
> : Failed to install dependency: moonshine-openfl-language-client
> I did install things using command from MoonshineGUICore README. Did I miss something ?

Hmmm... I thought that I made Moonshine check whether the library was already installed before trying to install it automatically. If not, then that's a bug. If you had already run the `haxelib git` command for those libraries, it should not be trying to install them.

**Comment by joshtynjala** [comment]
I have just confirmed that Moonshine does, in fact, check whether a library is installed before attempting to install it automatically. If it is installed, the `haxelib install` command will not be run. I cannot reproduce this error when I open the MoonshineGUICore project in Moonshine.

@piotrzarzycki21 Do you have two versions of Haxe installed? One installed by Moonshine's SDK installer, and one installed externally? I think that could explain this behavior. You may have manually installed all dependencies for the external Haxe, but I wonder if Moonshine's Haxe might install libraries somewhere else, and they may not be shared?

**Comment by Igazine** [comment]
This _might_ also be related to the type conversion issues I mentioned in yesterday's meeting. Please hold on with doing anything further regarding this specific issue while I take a deeper look at the relevant code parts.
Thank you

**Comment by piotrzarzycki21** [comment]
> @piotrzarzycki21 Do you have two versions of Haxe installed? One installed by Moonshine's SDK installer, and one installed externally? I think that could explain this behavior. You may have manually installed all dependencies for the external Haxe, but I wonder if Moonshine's Haxe might install libraries somewhere else, and they may not be shared?

I have my Moonshine Haxe directory empty, so it means that I believe I didn't install it trough Moonshine. I think initially I have used your instruction on Feathers documentation to install Haxe. @Aszusz you have as well that issue - do you have Haxe installed using SDK Installer and trough command lines ?

**Comment by Igazine** [comment]
This has been fixed on features/haxeconversion branch, will be available on master after the merge.

**Comment by Igazine** [comment]
Changes have been merged into master

**Comment by Aszusz** [comment]
> @Aszusz you have as well that issue - do you have Haxe installed using SDK Installer and trough command lines ?

When I first reproduced the issue I had just one Haxe install, the default Moonshine-IDE one in /c/Moonshine-SDKs/Haxe/

Right now I'm switching my VM between two snapshots:
- one with haxe only in /c/Moonshine-SDKs/Haxe/
- one with haxe in both /c/Moonshine-SDKs/Haxe/ and /c/HaxeToolkit/ (from latest haxe official installer)

Testing on Windows build 1256 on both environments I get the error:
```
: Installing dependency moonshine-openfl-language-client...
: Error: Failed with error: No such Project : moonshine-openfl-language-client
: Failed to install dependency: moonshine-openfl-language-client
```

**Comment by Igazine** [comment]
Thanks @Aszusz , I'm looking into why is this still happening on Windows

**Comment by Aszusz** [comment]
On macOS I get different error:
```
: Installing dependency markdown-openfl-textfield...
: Moonshine IDE™ 3.3.4
: Copyright © STARTcloud, Inc. 2015-2022. All rights reserved.
: Source code is under Apache License, Version 2.0
: https://github.com/Moonshine-IDE/Moonshine-IDE
: Uses as3abc (LGPL), as3swf (MIT), fzip (ZLIB), asblocks (Apache License 2.0), NativeApplicationUpdater (LGPL)
: Running on Adobe AIR 33.1.1.633
: Error: Failed with error: Failed to connect on lib.haxe.org:443
: Failed to install dependency: markdown-openfl-textfield
```

**Comment by Igazine** [comment]
The Haxelib repo does that occasionally, sometimes it's either unreachable or other issues occur

**Comment by piotrzarzycki21** [comment]
I don't have anymore problems with this.
