### ISSUE TITLE
Project > Recent Actions Do Not Open Project or File

### ISSUE THREAD

**Issue by JoelProminic** [Moonshine-IDE/Moonshine-IDE#1115]
While testing #1109, I noticed that the `File > Recent Project` and `File > Recent File` actions do not work.
1. Close all tabs except the Home tab
2. Open a project from the right side of the screen.  This works
3. Close the project
4. Try to open this project from `File > Recent Project`.  BUG:  Nothing happens.  There is no console error.

I see similar behavior for a recent file.

I couldn't reproduce this on the 3.3.3 production build, so I suspect this broke after the Haxe merge.

(On a side note, the Recent Files and Recent Projects lists get very long when you are working with many files, so it is a pain to scroll through the full list to find a single file.   Sorting by last used might work better, but then it would be almost impossible to find an old file (this may be outside the scope of "Recents" though).   We don't need to change this for this issue, but we may want to revisit this eventually.)

**Comment by Igazine** [comment]
This issue has been fixed and fixes have been merged into master.

**Comment by piotrzarzycki21** [comment]
Remove test ready and close the issue
