### ISSUE TITLE
Windows version reported by Moonshine IDE Help->About is not correct

### ISSUE THREAD

**Issue by solaechea** [Moonshine-IDE/Moonshine-IDE#1118]
## Environment
Moonshine IDE Version 3.3.3, Build 1250, Player: 33.1(Harman) Running On: Windows 10

### Windows Specifications
64 bits
Edition	            Windows 11 Home
Version	            21H2
Installed on	‎5/‎4/‎2022
OS build	22000.1098
Experience	Windows Feature Experience Pack 1000.22000.1098.0

![Captura de pantalla 2022-10-31 120514](https://user-images.githubusercontent.com/1082804/199054453-baf4fd79-f1fe-4e89-a055-ea4cf4247984.png)

**Comment by Igazine** [comment]
Itt happens on the server builds, but does not happen if I locally build and run Moonshine with ADL.
Needs some investigation

**Comment by rat-moonshine** [comment]
Maybe, it's how far the known-system exists to `AS3.Capabilities` to label an Windows OS - https://help.adobe.com/en_US/FlashPlatform/reference/actionscript/3/flash/system/Capabilities.html#os. Unlike macOS, where it parsed based on "Mac OS X.Y.Z" way, the Windows systems (maybe) more strictly specified. 

@Igazine do you see it reports Windows 11 if you build locally?

**Comment by Igazine** [comment]
@rat-moonshine I replaced `MoonshineDevelopment/Adobe AIR/Versions/1.0/Adobe AIR.dll` in the install directory with a newer one (copied from the SDK dir) and Windows version showed up correctly. So I believe this is a framework issue, but I'm not sure what AIR SDK we're using for server builds. Upgrading the AIR SDK on Bamboo will probably fix this if it does not break anything else.

Checking the [Harman AIR release notes](https://airsdk.harman.com/release_notes) shows that Windows 11 version detection has been fixed in AIR 33.1.1.743, so the SDK on Bamboo must be older

**Comment by Igazine** [comment]
@JoelProminic I'm not sure who can take care of the Flex/AIR SDK on Bamboo, so I assigned this task to you. Thank you

**Comment by rat-moonshine** [comment]
I shall look into the updating SDK on build systems, if I have some time by tomorrow.

**Comment by rat-moonshine** [comment]
I have updated Harman SDK with v33.1.1.856 (latest from MSDKI Development) in both the build system (macOS, Windows).

Please, give this a test with newer builds.

**Comment by piotrzarzycki21** [comment]
> I have updated Harman SDK with v33.1.1.856 (latest from MSDKI Development) in both the build system (macOS, Windows).
> 
> Please, give this a test with newer builds.

@rat-moonshine But newest AIR is https://airsdk.harman.com/download/33.1.1.935 - Is it not the one which should be used ?

**Comment by rat-moonshine** [comment]
Yeah, we could have. But 33.1.1.856 is the last update raised in MSDKI and released in Development. I prefer not to update Bamboo system to a version that not being distribute, or at least tested by MSDKI, at this point.

**Comment by solaechea** [comment]
@rat-moonshine This seems to be fixed now! 

![Windows 11](https://user-images.githubusercontent.com/1082804/201099430-16658efe-2e15-4e05-8806-13aee3131868.png)

**Comment by piotrzarzycki21** [comment]
@solaechea If it's working please close the issue.
