### ISSUE TITLE
Project Does Not Open on Startup - JavaImporter$parse() Error

### ISSUE THREAD

**Issue by JoelProminic** [Moonshine-IDE/Moonshine-IDE#1123]
@JustinProminic reported that a Java Gradle project did not open when reopening Moonshine, and this error was displayed on the console;

    : Error #1090
    : TypeError: Error #1090
    : 	at actionScripts.plugin.java.javaproject.importer::JavaImporter$/parse()
    : 	at actionScripts.impls::IJavaBridgeImpl/parseJava()
    : 	at actionScripts.plugin.project::ProjectPlugin/openPreviouslyOpenedProject()
    : 	at actionScripts.plugin.project::ProjectPlugin/handleShowPreviouslyOpenedProjects()
    : 	at flash.events::EventDispatcher/dispatchEvent()
    : 	at actionScripts.plugins.startup::StartupHelperPlugin/onUpdateStageCompletes()
    : 	at flash.events::EventDispatcher/dispatchEvent()
    : 	at components.containers::UpdaterView/remove()
    : 	at components.containers::UpdaterView/set isUpdateAvailable()
    : 	at mx.binding::Binding/defaultDestFunc()
    : 	at mx.binding::Binding/innerExecute()
    : 	at mx.binding::Binding/wrapFunctionCall()
    : 	at mx.binding::Binding/execute()
    : 	at mx.binding::Binding/watcherFired()
    : 	at mx.binding::Watcher/notifyListeners()
    : 	at mx.binding::PropertyWatcher/eventHandler()
    : 	at flash.events::EventDispatcher/dispatchEvent()
    : 	at actionScripts.extResources.riaspace.nativeApplicationUpdater::AutoUpdaterHelper/set isUpdater()
    : 	at actionScripts.extResources.riaspace.nativeApplicationUpdater::AutoUpdaterHelper/updater_updateStatusHandler()
    : 	at MoonshineDESKTOP/__updater_updateStatus()
    : 	at flash.events::EventDispatcher/dispatchEvent()
    : 	at actionScripts.extResources.riaspace.nativeApplicationUpdater::NativeApplicationUpdater/updateDescriptorLoader_completeHandler()
    : 	at flash.events::EventDispatcher/dispatchEvent()
    : 	at flash.net::URLLoader/onComplete()

Environment:

    Moonshine IDE™
    Version 3.3.3, Build 2845, Player: 33.1(Harman) Running On: Mac OS 12.5.1

I have not been able to reproduce this problem yet with Justin's project.

**Comment by JoelProminic** [comment]
@rat-moonshine reported that this exception could indicate a .javaproj error.   We can't share this project, but the .javaproj looks like this:

    <project>
      <gradleBuild>
        <option commandLine="clean build deploy"/>
        <actions>
          <action action="clean" actionName="Clean"/>
          <action action="publishToMavenLocal" actionName="Publish to Maven Local"/>
          <action action="clean run" actionName="Clean and Run"/>
          <action action="clean build" actionName="Clean and Build"/>
          <action action="clean jarIndividual" actionName="JAR Individual"/>
          <action action="clean build deploy" actionName="Clean, Build, and Deploy"/>
        </actions>
      </gradleBuild>
      <classpaths>
        <class path="src/main/java"/>
      </classpaths>
      <build>
        <option mainClassPath=""/>
        <option mainclass="$ProjectName"/>
      </build>
      <options>
        <option projectType="java-gradle"/>
        <option jdkType="jdk-8"/>
      </options>
    </project>


The values for `mainClassPath` and `mainclass` are not populated, and there are additional `gradleBuild` actions defined.

I don't see the parser error with this project on macOS Catalina, though, so this doesn't seem to be the full problem.

**Comment by joshtynjala** [comment]
It looks like this exception can be thrown if the final `>` character is missing from any of the XML elements in the file. This leads me to consider a couple of possibilities:

1) The file being loaded is invalid. Unfortunately, this would mean that we've been looking at the wrong file, and we'd need some way to figure out which one is the right file.
2) The file is loaded incompletely by the `FileStream`, for some reason. This seems unlikely, but even AIR can have bugs sometimes.

I'm leaning towards 1.

**Comment by JoelProminic** [comment]
We have not seen this recently.  We will reopen the issue if @JustinProminic starts seeing the problems again.
