### ISSUE TITLE
JDK 17+ Support

### ISSUE THREAD

**Issue by JoelProminic** [Moonshine-IDE/Moonshine-IDE#1124]
We found in #1120 that the latest JDK language server has a hard dependency on JDK 17 or higher.   We would like to add support for this in Moonshine.  This could include:
- MSDKI Installation (https://github.com/Moonshine-IDE/Moonshine-SDK-Installer/issues/98)
- Confirm the project templates can support JDK 17+.  For example, we have seen errors with Gradle in our initial JDK 19 tests - this could require a Gradle upgrade as well.
- Create a separate JDK option for JDK 11?   I'd prefer to avoid this if possible
- Improve the JDK interface so that it is easier to switch between JDKs, similar to what we do for Flex and Royale?

**Comment by piotrzarzycki21** [comment]
Whoever is going to work on this please move or add that issue to MSDKI repository for adding another entryways  there.

**Comment by rat-moonshine** [comment]
The most latest JDK from AdoptOpenJDK is https://github.com/AdoptOpenJDK/openjdk17-binaries. I can starts testing by this only. However, I'm not sure if we wants to test by >17, where to have the download available since AdoptOpenJDK don't has anything similar.

**Comment by rat-moonshine** [comment]
> Create a separate JDK option for JDK 11? I'd prefer to avoid this if possible

I'm not sure about which interface the above statement is.. but on availing the JDK17 in MSDKI we have some options available:

1. Three individual JDK entries - JDK 8, JDK 11, JDK 17 (this list can go larger with more version additions)
2. Keep "JDK 8" as separate entry. Keep default/generic JDK with version/variant installation option (as we has for Royale)
![image](https://user-images.githubusercontent.com/24370870/199653210-68b17387-db9c-451a-8c6e-88e048e52afc.png)

Let me know what you thought. @piotrzarzycki21 @JoelProminic @Aszusz

**Comment by rat-moonshine** [comment]
Following are my test results with `pre-release` version of JDK17 from AdoptOpenJDK repository.

Tested on: Monterey M2
Dated binary: [Arm64](https://github.com/AdoptOpenJDK/openjdk17-binaries/releases/download/jdk-2021-05-07-13-31/OpenJDK-jdk_arm64_mac_hotspot_2021-05-06-23-30.tar.gz)
Dated binar: [x64](https://github.com/AdoptOpenJDK/openjdk17-binaries/releases/download/jdk-2021-05-07-13-31/OpenJDK-jdk_x64_mac_hotspot_2021-05-06-23-30.tar.gz)

Project Type | Arm64 | x64
------------|----------|---------
Java Gradle | Failed to start language server | Server started
Java Maven | Failed to start language server | Server started

**Comment by piotrzarzycki21** [comment]
> > Create a separate JDK option for JDK 11? I'd prefer to avoid this if possible
> 
> I'm not sure about which interface the above statement is.. but on availing the JDK17 in MSDKI we have some options available:
> 
> 1. Three individual JDK entries - JDK 8, JDK 11, JDK 17 (this list can go longer with more version additions)
> 2. Keep "JDK 8" as separate entry. Keep another default/generic JDK entry with version/variant installation option (as we has for Royale)
>    ![image](https://user-images.githubusercontent.com/24370870/199653210-68b17387-db9c-451a-8c6e-88e048e52afc.png)
> 
> Let me know what you think. @piotrzarzycki21 @JoelProminic @Aszusz

I think JDK 8 should be separated and new entry with more never sdk with drop down list:
- One entry as is with JDK 8
- Second entry with drop down list

**Comment by piotrzarzycki21** [comment]
Wait a second - If I'm correct we need here Open JDK 19 for language server - it won't run without that version for Java project. Please follow discussion in other thread - is it not mentioned somewhere in #1120 ?

**Comment by Igazine** [comment]
Judging from #1120 v17 is the requirement for the language server update. I just tested with v19 because that was the one installed on my macOS, but I think v19 is not mandatory.

**Comment by JoelProminic** [comment]
I see that [AdoptOpenJDK](https://adoptopenjdk.net/) was rebranded as [Adoptium/Temurin](https://adoptium.net/).  I see the latest LTS (long-term-support) version is 17, so I think we should use this version unless we have a need to upgrade higher.  (The LTS vesions are 8, 11, and 17).

**Comment by joshtynjala** [comment]
Yeah, AdoptOpenJDK is no longer active, and it will disappear at some point in the future. We need to move to its successor, Adoptium/Temurin.

https://blog.adoptopenjdk.net/2021/08/goodbye-adoptopenjdk-hello-adoptium/

**Comment by piotrzarzycki21** [comment]
I have downloaded Java 17 provided by @rat-moonshine . Language server seems to be started, but I'm getting following error on console while starting project [DominoVagrant](https://github.com/DominoVagrant/demo) Java project.

```
: Nov 4, 2022, 8:09:27 AM Illegal character in path at index 45: file:/Users/piotrzarzycki/Library/Application Support/com.moonshine-ide.development/Local Store/java/jdt-language-server/config_mac/org.eclipse.osgi/50/0/.cp/gradle/init/init.gradle
: Illegal character in path at index 45: file:/Users/piotrzarzycki/Library/Application Support/com.moonshine-ide.development/Local Store/java/jdt-language-server/config_mac/org.eclipse.osgi/50/0/.cp/gradle/init/init.gradle
: java.net.URISyntaxException: Illegal character in path at index 45: file:/Users/piotrzarzycki/Library/Application Support/com.moonshine-ide.development/Local Store/java/jdt-language-server/config_mac/org.eclipse.osgi/50/0/.cp/gradle/init/init.gradle
: 	at java.base/java.net.URI$Parser.fail(URI.java:2974)
: 	at java.base/java.net.URI$Parser.checkChars(URI.java:3145)
: 	at java.base/java.net.URI$Parser.parseHierarchical(URI.java:3227)
: 	at java.base/java.net.URI$Parser.parse(URI.java:3175)
: 	at java.base/java.net.URI.<init>(URI.java:623)
: 	at java.base/java.net.URL.toURI(URL.java:1054)
: 	at org.eclipse.jdt.ls.core.internal.managers.GradleProjectImporter.getGradleInitScript(GradleProjectImporter.java:601)
: 	at org.eclipse.jdt.ls.core.internal.managers.GradleProjectImporter.getGradleInitScriptArgs(GradleProjectImporter.java:564)
: 	at org.eclipse.jdt.ls.core.internal.managers.GradleProjectImporter.getBuildConfiguration(GradleProjectImporter.java:443)
: 	at org.eclipse.jdt.ls.core.internal.managers.GradleProjectImporter.startSynchronization(GradleProjectImporter.java:405)
: 	at org.eclipse.jdt.ls.core.internal.managers.GradleProjectImporter.importDir(GradleProjectImporter.java:295)
: 	at org.eclipse.jdt.ls.core.internal.managers.GradleProjectImporter.importToWorkspace(GradleProjectImporter.java:211)
: 	at org.eclipse.jdt.ls.core.internal.managers.ProjectsManager.importProjects(ProjectsManager.java:149)
: 	at org.eclipse.jdt.ls.core.internal.managers.ProjectsManager.initializeProjects(ProjectsManager.java:111)
: 	at org.eclipse.jdt.ls.core.internal.handlers.InitHandler$1.runInWorkspace(InitHandler.java:244)
: 	at org.eclipse.core.internal.resources.InternalWorkspaceJob.run(InternalWorkspaceJob.java:43)
: 	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:63)
```

**Comment by rat-moonshine** [comment]
![image](https://user-images.githubusercontent.com/24370870/199926847-fa8b1994-2861-4465-8a61-41bcbae6d485.png)

MSDKI now [installs](https://github.com/Moonshine-IDE/Moonshine-SDK-Installer/issues/98) Temurin JDK 17. We can have this tested with the branch builds for now.

**Comment by JoelProminic** [comment]
In my other testing, I haven't seen any major issues with JDK 17.  I'd like to do some documented test for the different projects types for completeness. 

@JesseProminic, please install JDK 17 from MSDKI (if you haven't done so already) and test these items for each project type:
- New Project
- Language server (if applicable)
- Build & Run (Run may not be applicable for some projects)

Project | macOS | Windows | Notes
-- | -- | -- | --
Actionscript |  |  | 
Away3D |  |  | 
Domino On Disk Project |  |  | 
Feathers SDK Deskotp Project |  |  | 
Feathers SDK Mobile Project |  |  | 
Flex Browser Project |  |  | 
Grails Project  |  |  | 
Haxe Feathers UI |  |  | 
Haxe OpenFL |  |  | 
Haxe |  |  | 
Java Domino |  |  | JDK 8 only for build, JDK 17 for language server
Java Gradle |  |  | 
Java Maven |  |  | 
Royale Browser |  |  | 
Visual Editor (Royale Only) |  |  | 

If you find more projects I missed, please add them.

**Comment by JesseProminic** [comment]
| Project | macOS | Windows | Notes
| ------------- | ------------- | ------------- | ------------- |
| Actionscript 	| successful | | |
| Away3D 	| successful | | |
| Domino On Disk | successful | | |
| Feathers SDK Deskotp Project |	successful | | |
| Feathers SDK Mobile Project |	successful | | |
| Flex Browser Project	|	successful | | |
| Flex Desktop Project	|	successful | | |
| Flex Mobile Project	|	successful | | |
| Grails Project	|		successful | | |
| Hexe Feathers UI Project	| successful | | |
| Hexe Open FL Project	|	successful | | |
| Hexe Project (with Java) |	successful | | |
| Java Domino Project	|	successful | | |
| Java Gradle Project	|	failed  |  | 	Could not initialize class org.codehaus.groovy.runtime.InvokerHelper	|	
| Java Maven Project	|	failed |  |		Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.8.1:compile (default-compile) on project NewJavaMavenProject: Compilation failure | 
| Library Project (Flex)	|	built successfully | | |
| Royale Browser Project	|	successful | | |
| Visual Editor Project (Domino) |	built successfully | | |

**Comment by JesseProminic** [comment]
To add, each project I create, I get this error but then I could build the project anyway. This only happened in Windows.

<img width="427" alt="Screenshot 2022-11-18 at 2 32 51 PM" src="https://user-images.githubusercontent.com/96078188/202798296-866fdf7c-689c-4742-949e-cfebccddb881.png">

**Comment by JoelProminic** [comment]
Checking the [Gradle Compatibility Matrix](https://docs.gradle.org/current/userguide/compatibility.html), it looks like we would need to upgrade Gradle to at least 7.3.  The latest version is 7.5.1.  This could definitely break the Gradle scripts because of changed references, so this will need some investigation.

Java Domino projects need to run with JDK 8, so this should work.  JDK 17 is required for the language server, but this hasn't been causing problems in my practical use.  I see @JesseProminic reported an error for Windows, though, so this will need investigation.

**Comment by JoelProminic** [comment]
I did some tests with Gradle 7.5.1 on macOS Monterey, and so far the Java Gradle and Java Domino projects are working well.  I'm a little surprised there were no errors for changed syntax - this might show up for more complicated projects, but the complicated Gradle scripts I use are all for Domino (and using JDK 8).

**Comment by Igazine** [comment]
@Igazine Check Haxe Java output

**Comment by rat-moonshine** [comment]
ARM based JDK is now available to download where it may needs. https://github.com/Moonshine-IDE/Moonshine-SDK-Installer/issues/98.

**Comment by JoelProminic** [comment]
With the current design, Moonshine 3.3.3 users will need to manually upgrade the JDK and Gradle to clear errors.  The SDKs can be downloaded from MSDKI, but the Settings update is manual.  

So, the use case could be something like this:
1. User creates or opens a Java Gradle project
2. Moonshine reports that the language server won't work without JDK 11
3. User  opens MSDKI - does this update automatically
4. User installs JDK17.  
5. User manually updates Moonshine to JDK 17?
6. User tries to build the Java Gradle project.   This fails if they missed the Gradle SDK update
7. User reopens MSDKI (they may not even realize this is the fix)
8. User installs Gradle
9. User manually updates Gradle.

Fresh users will not be affected, so the initial setup is still easy.

We could upgrade if there is a "newer" version of the SDK in MoonshineSDKs, but this has a couple problems:
- We need to define logic to determine if the version is newer for each SDK.  This would be vulnerable to changes in the version format on different versions of the SDK
- The user might have intentionally reverted to an older SDK.


I was thinking about updating the SDKs automatically only when an install event is triggered from MSDKI.  However, @rat-moonshine clarified that this is not how MSDKI works currently:

>Regarding how MSDKI notifies any update to Moonshine - 
>We wanted to check what content MSDKI generates to its XML that Moonshine loads and update itself..  
>It seems like MSDKI generates full list of available SDKs with their path values only. 
>It is under /Downloads/MoonshineSDKs/.MoonshineHelperNewUpdate.xml 
>When Moonshine loads, the job is simplistic at this side then.. It just checks whether any SDK configured or not, if not configured or has a broken-path, it updates with the valid-available path that generates by MSDKI. 
>At MSDKI side, that is only thing its doing.

So, it would not necessarily be clear which SDK was updated, wo this could override an SDK that the uesr intentionally downgraded.

**Comment by rat-moonshine** [comment]
JDK 11 removed from MSDKI install option.

**Comment by JesseProminic** [comment]
After manually updating Gradle 7.6 and changing the setting to the new version 


Project | macOS | Windows |
-- | -- | -- | 
Java Gradle Project |:white_check_mark: successful | :white_check_mark: successful |

**Comment by JoelProminic** [comment]
@JustinProminic recommended that we automatically update the user to JDK 17 and the latest version of Gradle.  These versions would also be required by Getting Started.  This would override the SDK if users manually downgraded for some reason, but we don't have a specific use case that would require the downgrade.  Upgrades could trigger this as well if we are checking for an exact version - comparing the version could help with this, but it could need SDK-specific logic.

**Comment by Igazine** [comment]
I don't see any errors on Windows with a Haxe project targeting Java.

Moonshine IDE™
Version 3.3.4, Build 1354, Player: 33.1(Harman)
Running on: Windows 11

OpenJDK 19.0.1

Moonshine open/build Haxe project (Java output) successful

Before updating OpenJDK to 19 I tested it with 11.0 as well and it was also successful
