### ISSUE TITLE
Generated Royale Interface Buttons Needs To Be Resize Properly

### ISSUE THREAD

**Issue by rat-moonshine** [Moonshine-IDE/Moonshine-IDE#1128]
@JustinProminic reported that the buttons in generated CRUD Royale interface cropped its texts and not resizes by their default text-widths.

![image](https://user-images.githubusercontent.com/24370870/199906457-19f044e0-32b5-4814-beb1-9c456ea56cfe.png)

**Comment by rat-moonshine** [comment]
This should have fixed now. Please check.

**Comment by JoelProminic** [comment]
@rat-moonshine clarified that this bug triggered when there were less than 3 columns in the generated view.   

With the update, I see the buttons are not aligned with the table, so this should not be a problem.  I confirmed that I don't see this sizing issue until I reduce the browser window to an unreasonable size, so I think this fix is sufficient:
![image](https://user-images.githubusercontent.com/24532731/207667781-2877fa5d-fa00-439a-b243-b3486ed69a09.png)
