### ISSUE TITLE
Manage Workspaces

### ISSUE THREAD

**Issue by JoelProminic** [Moonshine-IDE/Moonshine-IDE#1132]
Currently we are missing some actions for workspaces, like delete and rename.  I think it would make sense to create a Manage interface for this in the Moonshine Settings.  

Some features:
- New
- Delete
- Rename
- Open (switches workspace)

We should have a button to open this interface from the Project sidebar.  This would be next to the controls for #1131 

UPDATE: Branch: features/issue_1038_openpath_in_terminal
macOS: https://static.moonshine-ide.com/downloads/releases/dev/macos/branches/features/issue_1038_openpath_in_terminal
Windows: https://static.moonshine-ide.com/downloads/releases/dev/windows/branches/features/issue_1038_openpath_in_terminal

**Comment by JoelProminic** [comment]
I noticed today that the External Editors feature is not working properly.  Checking Settings > External Editors, I see that the checkbox is not set for any of the editors, and I can't change the checkbox.  I'm currently working in the Master branch, but I'm wondering if the checkboxes got corrupted when I saved the settings after discussing this issue in the meeting this morning.   It is possible that this is an unrelated issue, though.

**Comment by rat-moonshine** [comment]
This is mostly working now, hopefully no big surprise waits there. The only thing that still needs to do is to prevent 'IDE-Default' from deletion.

**Comment by JoelProminic** [comment]
Test | Result | Notes
-- | -- | --
Add | Works, workspace switches | 
Add (already exists) | "Workspace is already exists" | Message should be "Workspace already exists."
Remove | Removed | 
Remove (current workspace) | Deleted, switch to the first workspace | 
Remove (IDE-Default) | TODO | TODO
Rename | BUG:  workspace name updates in Moonshine, but I get error when switching the renamed workspace.  On reload, the workspace is not renamed | Button should be "Rename" instead of "Create"
Rename (current workspace) | BUG:  workspace name updates in Moonshine, but I get error when switching to a different workspac.  On reload, the workspace is not renamede | 
Rename (name matches another worspace) | Workspace is already exists" | Message should be "Workspace already exists.". 
Rename (IDE-Default) | TODO | TODO
Switch | Not implemented as expected.  See below | 
Switch (current workspace) | Not implemented as expected.  See below | 


"Switch" currently opens the "Load Workspace" prompt rather than using the displayed entires.  This should be moved to button/links on the individual entires

For the Rename errors, this is what I can see of the stack trace:

![image](https://user-images.githubusercontent.com/24532731/202510103-e6ddcdcf-4e6b-4a60-b91f-4d0e5eb2456d.png)

**Comment by JoelProminic** [comment]
Test after today's updates:

Test | Result | Notes
-- | -- | --
Add | Works | 
Add (already exists) | BUG: Displays error on prompt submission only | 
Remove | Works | 
Remove, multiple workspaces | Works | 
Remove (current workspace) | Works, opens first workspace | Should this open IDE-Default instead?
Remove (IDE-Default) | Checkbox disabled | 
Rename | Works | Button is "Create" instead of "Rename"
Rename (current workspace) | Works | 
Rename (name matches another worspace) | BUG:  Displays error on prompt submission only | 
Rename (IDE-Default) | Link disabled | 
Switch | Works | Link is now on each entry
Switch (current workspace) | Link Disabled | 

The Add/Rename validation should trigger when typing, similar to what we did for #1137.

After one of my Rename tests, I clicked the "Cancel" button on the Settings page and tried to switch the workspace.  I got FileWatcher errors like this each time I switched the workspace.  However, I coudn't reproduce this with a quick test later:

    : Error #1009
    : TypeError: Error #1009
    : 	at actionScripts.plugins.fswatcher::FSWatcherPlugin/addProject()
    : 	at actionScripts.plugins.fswatcher::FSWatcherPlugin/onAddProject()
    : 	at flash.events::EventDispatcher/dispatchEvent()
    : 	at actionScripts.plugin.actionscript.as3project::AS3ProjectPlugin/openProject()
    : 	at actionScripts.plugin.actionscript.as3project::AS3ProjectPlugin/importFDProject()
    : 	at actionScripts.plugin.actionscript.as3project::AS3ProjectPlugin/openProjectByDirectory()
    : 	at actionScripts.plugin.actionscript.as3project::AS3ProjectPlugin/importProjectWithoutDialog()
    : 	at flash.events::EventDispatcher/dispatchEvent()
    : 	at actionScripts.plugin.workspace::WorkspacePlugin/changeToWorkspace()
    : 	at actionScripts.utils::MethodDescriptor/callMethod()
    : 	at Function/<anonymous>()
    : 	at SetIntervalTimer/onTimer()
    : 	at flash.utils::Timer/tick()
    :
    : Click here to Report a Bug


@rat-moonshine reported that Cancel shouldn't do anything here.  Since the workspaces are updated live, Save and Cancel won't change anything for these updates.

**Comment by rat-moonshine** [comment]
Rename/Add-New prompt updated to display duplicate-name error on key-press.

> After one of my Rename tests, I clicked the "Cancel" button on the Settings page and tried to switch the workspace. I got FileWatcher errors like this each time I switched the workspace. However, I coudn't reproduce this with a quick test later:

However, I couldn't able to reproduce the above error either in my repeated tests. It could have been better if a reproducible steps is there.

**Comment by JoelProminic** [comment]
The updates look good:

Test | Result
-- | --
Rename/Add-New prompt updated to display duplicate-name error on key-press. | Confirmed
Button label toggle between add and rename | Confirmed
IDE-Default auto-selects if a currently selected workspace deletes | Confirmed
Fixed bug where "File > Workspaces > Save As New Workspace" workspace was not appearing in Moonshine Settings immediately |

**Comment by JoelProminic** [comment]
@JustinProminic asked about this feature today.  Go ahead and merge this.   I see there are also updates for #1136 and #1137, but I think it is fine to merge those as well as long as you don't have remaining concerns.  We can finish testing on master.

**Comment by rat-moonshine** [comment]
This issue is now merged into `master`.

**Comment by piotrzarzycki21** [comment]
@rat-moonshine take a look to bamboo if it's successful please.

**Comment by JoelProminic** [comment]
I confirmed this was merged.  I don't see anything else immediate to test for this.
