### ISSUE TITLE
Projects Not Reopened Properly After Switching Workspace

### ISSUE THREAD

**Issue by JoelProminic** [Moonshine-IDE/Moonshine-IDE#1135]
I noticed this issue while testing #1131, but I confirmed it also works with the old Switch Workspace action:
1. Create a new workspace called TestSwitch1
2. Create a new Flex Desktop Project called TestSwitch1A
3. Create a new Flex Desktop Project called TestSwitch1B
4. Close TestSwitch1B
5. Create a new workspace called TestSwitch2
6. Create a new Flex Desktop Project called TestSwitch2A
7. Create a new Flex Desktop Project called TestSwitch2B
8. Close TestSwitch2B
9. Switch between the workspaces.  This works properly
10. In TestSwitch2, open TestSwitch2B
11. Switch to TestSwitch1 and back
12. BUG:  Only TestSwitch2A is open
13. Close TestSwitch2A 
14. Open TestSwitch2B
15. Switch to TestSwitch1 and back
16. This worked for me.  In other cases I saw that it opened a completely different workspace at this step

**Comment by rat-moonshine** [comment]
![image](https://user-images.githubusercontent.com/24370870/201302754-eb257709-416b-4a89-9c54-7d5e7ed3945a.png)

This problem also fixed.

**Comment by rat-moonshine** [comment]
This is ready for test on branch.

**Comment by JoelProminic** [comment]
Note that the last couple commits were for  #1131.

I can't reproduce the workspace switching errors  after the update.   I may reopen this issue if I see more problems.
