### ISSUE TITLE
Open Multiple Projects in Separate Workspace

### ISSUE THREAD

**Issue by JoelProminic** [Moonshine-IDE/Moonshine-IDE#1136]
If we open a directory with multiple projects, Moonshine will display a prompt to let the user choose which project to open.

![image](https://user-images.githubusercontent.com/24532731/198079762-cf9a9171-ec59-4f28-8185-2a0bd0355242.png)

We would like to update this interface to open the projects in a workspace.  The options should be

Option | Notes
-- | --
`-Current (%name%)-` | This should be the default
`-New workspace-` | Allow the user to specify a name
Existing workspace | The user should be able to select the workspace directly without an extra step

The first two options should always be at the top of the selector dropdown.  The existing workspaces should be sorted.

UPDATE: Branch: features/issue_1038_openpath_in_terminal
macOS: https://static.moonshine-ide.com/downloads/releases/dev/macos/branches/features/issue_1038_openpath_in_terminal
Windows: https://static.moonshine-ide.com/downloads/releases/dev/windows/branches/features/issue_1038_openpath_in_terminal

**Comment by rat-moonshine** [comment]
Isn't that `-Current (%name%)-` option is redundant when we're already supplying existing workspace as a dropdown and that comes pre-selected with current workspace-name. 

If we choose to remove `-Current (%name%)-`, then perhaps it makes more sense to have the `-New workspace-` button/option beneath the selector dropdown (?)

**Comment by JoelProminic** [comment]
We discussed this more in the morning chat.  Here is an updated mockup of what I had in mind:
![image](https://user-images.githubusercontent.com/24532731/201435867-393ce2e5-acec-43ea-8098-7c7b9cc4c543.png)

**Comment by rat-moonshine** [comment]
This is ready for a test on branch.

**Comment by JoelProminic** [comment]
The issue with the Current Workspace cases was resolved.

I see that the project list is not sorted.  This is not directly related to this update, but I'd like to get it fixed.

The workspace list sorting is case sensitive.  Is this the same sorting logic used throughout Moonshine?  I'd like to keep this consistent and shared:
![image](https://user-images.githubusercontent.com/24532731/201731037-8d340319-9d90-48f5-ba20-6fdce4ede9ef.png)

**Comment by rat-moonshine** [comment]
Updates:

- New message added in case of duplicate new-workspace, open logic updated
- Sorting fixed in the workspace dropdown
- Added sorting to opening project-list 

Against last update, there are something to note. The label displayed in project-list in a relative-path manner and not in project-name manner. I have added sorting to the label, the string-sort still affect to the whole label (the relative path in this case) and not particularly to the project-name mentioned in that path. Here is an example after the sort applied:

![image](https://user-images.githubusercontent.com/24370870/201875615-536ffda0-bc8b-489e-9af3-dddc57c2780c.png)

**Comment by rat-moonshine** [comment]
While testing this @JoelProminic reported problems in following situation:
![image](https://user-images.githubusercontent.com/24370870/202092248-67bcad01-e437-4f0f-ac87-581e91816b69.png)

Problems:
- Popup not closing
- Selected project(s) not opening to the existing workspace

While testing this, I couldn't able to reproduce the above problem. 

However, I did noticed problem in following scenario

- Selected workspace is A, existing workspace is B
- User tries to create a new workspace named B, from the above popup
- User notifies about duplicate workspace
- User selects projects and submits
- Popup closed
- Workspace do not changed to B with selected project(s) added -- Bug

I shall work on the above fix.

**Comment by rat-moonshine** [comment]
The [above](https://github.com/Moonshine-IDE/Moonshine-IDE/issues/1136#issuecomment-1316389962) problem should resolved now.

**Comment by JoelProminic** [comment]
The update resolves my error case from yesterday.  Here is an updated test matrix.

Test | Open in correct workspace | Workspace Opens | Notes
-- | -- | -- | --
Current | Yes |  | 
Current, projects already open | Yes|  | N
Existing | Yes | Yes | 
Existing entry matching current | Yes | Yes | 
Existing, projects already open | Yes | Yes | 
New | Yes | Yes | 
New, matches existing | Yes | Yes | A warning is displayed in the prompt
New, matches current | Yes | N/A | A warning is displayed in the prompt


@JesseProminic, please go through these cases on Windows when you have a chance.    You can get a test build from the link in the description.
