### ISSUE TITLE
Open Genesis Directory Project in Workspace

### ISSUE THREAD

**Issue by JoelProminic** [Moonshine-IDE/Moonshine-IDE#1137]
@JustinProminic requested that we add a way to open Genesis Directory projects in configured workspaces.  I envision this working as follows:
- We will add an optional metadata file to the base directory of the zip.  This could be XML, JSON, or YAML.  Once we decide which type makes the most sense, we can agree on a format
- Moonshine will always open GenesisDirectory in the multi-project prompt
- Moonshine will display the selected worksapce using the functionality from #1136.  The user can then change this as desired
- If the workspace already exists, show a warning in the UI, but do not block the action.
- If the zip does not contain a metadata file, default to `-Current Workspace-`

UPDATE: Branch: features/issue_1038_openpath_in_terminal
macOS: https://static.moonshine-ide.com/downloads/releases/dev/macos/branches/features/issue_1038_openpath_in_terminal
Windows: https://static.moonshine-ide.com/downloads/releases/dev/windows/branches/features/issue_1038_openpath_in_terminal

**Comment by rat-moonshine** [comment]
Can we have a test-zip containing such a file (either in XML or JSON) having any requisite information to support this issue (?)

**Comment by JoelProminic** [comment]
Here are some test cases.   I'll fill in some example projects when I create them:

Test | Example Project | Expected | Notes
-- | -- | -- | --
Single Project, XML file populated |  | Open multi-project prompt, display suggested workspace | 
Multiple Projects, XML file populated |  | Open multi-project prompt, display suggested workspace | 
Single Project, no XML file |  | Open multi-project prompt, display current workspace | 
Multiple Projects, no XML file |  | Open multi-project prompt, display current workspace | 
Invalid XML |  | Open multi-project prompt, display current workspace | Display warning on console
XML missing property |  | Open multi-project prompt, display current workspace | Display warning on console

**Comment by JoelProminic** [comment]
No one had a strong opinion on the file format, so we'll use XML for consistency with the rest of Moonshine.

We can call the file `config.xml`.  The format would be like:


```
<?xml version="1.0" encoding="UTF-8"?>
<root>
    <SuggestedWorkspace>ExampleWorkspace</SuggestedWorkspace>
    ... future properties here ...
</root>
```

**Comment by JoelProminic** [comment]
We should also test the workspace population logic:

Workspace Status | Expected Result | Notes
-- | -- | --
New Workspace | Select the `-Create-New-Workspace-` option and populate the workspace name. | 
Matches existing workspace | Select the existing workspace, and show a warning that the workspace already exists | This case could happen if the user downloads an updated copy of the catalog entry.

**Comment by rat-moonshine** [comment]
I re-updated the zip files as the files had no root directory.

While working on this, I noticed following point:
![image](https://user-images.githubusercontent.com/24370870/203324583-140f4033-3ae2-4f8a-9f65-4e0a34352a0a.png)

Currently, if a directory-search returns one project it opens to sidebar immediately other than opening multi-project-selection popup. If we want to change this structure then this might affect when browsing a directory using `File > Open/Import Project`, as well. Please suggest.

**Comment by rat-moonshine** [comment]
I'll be needing some more time to this, hopefully we shall have them ready for a test, soon.

**Comment by JoelProminic** [comment]
Yes, my intention is to open the Multiple Project prompt for Genesis Directory Catalog, even if there is only a single project.  This will allow us to use the new workspace selection feature added in #1136.   We could consider only doing this when the ZIP has a config.xml - we can discuss this in the meeting tomorrow.

I don't want to change the current single-project case for Project > Open Import Project, though.   I want to keep this case with minimal clicks for now.

**Comment by rat-moonshine** [comment]
> Sorry, it looks like I misremembered how we did the directory structure for Genesis Directory. To clarify, the expected format is like this, right?

Yes, based on the earlier design (read from [here](https://github.com/Moonshine-IDE/Moonshine-IDE/issues/1089#issuecomment-1258300815)) the Zip must contain one single root directory, other things can contain in that root directory only.

**Comment by rat-moonshine** [comment]
This is mostly ready now, for a test, hopefully. I have updated the [matrix](https://github.com/Moonshine-IDE/Moonshine-IDE/issues/1137#issuecomment-1322359851) with test-results and a few other tests.

Please, check.

**Comment by rat-moonshine** [comment]
I able to reproduce the workspace change bug that @JoelProminic found during Wednesday meeting:

- Select any workspace other than IDE-Default
- Delete the selected workspace in Settings
- Deletion process eventually change to IDE-Default workspace in sidebar
- Create a new workspace
- Select the newly created workspace in Settings and delete
- Sidebar workspace-dropdown changed to first item from in the list (no project opens) and never changed to IDE-Default [Bug]

**Comment by rat-moonshine** [comment]
`[Above](https://github.com/Moonshine-IDE/Moonshine-IDE/issues/1137#issuecomment-1326202368)` problem should be fixed now.

**Comment by JoelProminic** [comment]
This needs more testing, and I should also talk with @dpastov about updating the existing zips on Genesis Directory Catalog.

**Comment by rat-moonshine** [comment]
> We should also test the workspace population logic:
> 
> Workspace Status	Expected Result	Notes
> New Workspace	Select the `-Create-New-Workspace-` option and populate the workspace name.	
> Matches existing workspace	Select the existing workspace, and show a warning that the workspace already exists	This case could happen if the user downloads an updated copy of the catalog entry.

I commit an update, this suppose to display the notes in case a workspace is already exists from dropdown. Please, check.

**Comment by JesseProminic** [comment]
On Windows:

 :eight_spoked_asterisk: I had to open with Windows Explorer to access each zip file first.
 :eight_spoked_asterisk: Used File > Open/Import (A single file does open directly on Moonshine).

Test | Example Project | Expected | Notes | Output
-- | -- | -- | -- | --
Single Project, XML file populated | 2022_11_21__Issue1131_Single_ValidXML.zip | Open multi-project prompt, display suggested workspace |   |  :white_check_mark:
Multiple Projects, XML file populated | 2022_11_21__Issue1131_Multi_ValidXML.zip | Open multi-project prompt, display suggested workspace | Only opens individual file   | :heavy_exclamation_mark: 
Single Project, no XML file | 2022_11_21__Issue1131_Single_NoXML.zip | Open multi-project prompt, display current workspace |   |  :white_check_mark:
Multiple Projects, no XML file | 2022_11_21__Issue1131_Multi_NoXML.zip | Open multi-project prompt, display current workspace |   |  :white_check_mark:
Invalid XML | 2022_11_21__Issue1131_Multi_InvalidXML.zip | Open multi-project prompt, display current workspace |  |  :white_check_mark:
XML missing property | 2022_11_21__Issue1131_Single_MissingXML.zip | Open multi-project prompt, display current workspace |  |  :white_check_mark:
