### ISSUE TITLE
DominoVisualEditor Royale Generation: Export converted project to external application

### ISSUE THREAD

**Issue by piotrzarzycki21** [Moonshine-IDE/Moonshine-IDE#1148]
*UPDATE:  Filling in description*

Some general requirements from our discussion today.  Some of these may be difficult or impractical, so we can discuss these.:
- Automate importing generated Royale projects into an existing project.
- We should support imports from multiple generated projects.  So, the target directory for a project should be unique for the project.
- Generated code can be overwritten, but we want to avoid overwriting code that has been manually modified.  The simplest solution is to keep the generated code separate
- The developer should be reponsible for updating the existing application to reference the generated code (menu entries, panels, etc).  The user should be able to copy short example snippets for this from the generated example.
- We need a way to streamline updating the 'theme" for the generated source to match the target application
- Avoid changing the "theme" of the target application with generated CSS files
- Update the agent URLs to match the target application. For now, this can be done by changing Base Agent URL in the DominoVisualEditor or FormBuilder project.
- Support developer modifications to the generated code for features that are not supported by the generation logic (i.e. special buttons or controls, layout changes to better match the target application, etc).  Ideally these changes will be made outside of the generated source directory, but the developer will probably to do some manual merging.

UPDATE:  Branch:  features/issue_1148_export_to_royale_templating_proj
macOS: https://static.moonshine-ide.com/downloads/releases/dev/macos/branches/features/issue_1148_export_to_royale_templating_proj
Windows: https://static.moonshine-ide.com/downloads/releases/dev/windows/branches/features/issue_1148_export_to_royale_templating_proj

**Comment by piotrzarzycki21** [comment]
`src/generated/<project>/...`

**Comment by piotrzarzycki21** [comment]
[domino_royale_export_v2.txt](https://github.com/Moonshine-IDE/Moonshine-IDE/files/10070026/domino_royale_export_v2.txt)

Adding plan of exporting generated Royale project to external app.

**Comment by JoelProminic** [comment]
For convenience, here is the writeup from this text document:

>Terms:
>RoyaleGEN - project generated out of Domino Visual Editor
>ProjectDEST - project to which we are exporting
>
>Steps:
>1)
>Point to the source code location of ProjectDEST (ex. MyAccount)
>NOTE: ProjectDEST has to contain an /src folder
>
>This step could be accomplished by either clicking on a button in the Project menu and localizing the ProjectDEST directory or
>providing a path to the RoyaleGEN settings file.
>
>2)
>Copy from RoyaleGEN the following folders/files:
>RoyaleGEN/src/views -> ProjectDEST/src/generatedUI/views
>RoyaleGEN/src/classes -> ProjectDEST/src/generatedUI/classes
>RoyaleGEN/src/resources/export-app-styles.css -> ProjectDEST/ src/resources/export-app-styles.css
>NOTE: generatedUI folder has to be created if it doesn't exist
>
>This step can be performed automatically by MoonshineIDE
>
>3)
>The following fragments of code need to be extracted from RoyaleGEN/src/views/MainContent.mxml to ProjectDEST:
>
>a) MainContentManager class:
><fx:Script source="../../../../src/generatedUI/classes/MainContentManager.as"/>
>
>This is a class with global functions used by the views. This logic needs to travel alongside the views.
>
>b) <j:Navigation> component extracted from MainContent into ProjectDEST <j:DrawerContent>
>
>This component contains navigation links and needs to be put in the left menu accordion.
>
>c) All <j:ScrollableSectionContent> from <j:ApplicationMainContent> into ProjectDEST <j:ApplicationMainContent>
>
>Those are the actual views, the content pointed to by links in step b)
>
>We're brainstorming how to automatize this process but for now, our best bet is to do this manually.
>
>4)
>Moving the styles from RoyaleGEN to ProjectDEST:
><fx:Style source="../../resources/export-app-styles.css"/>
>
>This has to be done manually and examined by a developer.
>
>5)
>Adding  ProjectDEST/generatedUI folder to the source-path
>
>This also has to be done manually.

I think at least 3 and 4 are probably steps that should be done manually by the developer, since this could varry a lot based on the application.  2 should be automated, and it would be nice to handle 5 as well.

**Comment by JoelProminic** [comment]
As discussed in the meeting today, @piotrzarzycki21 is planning to deploy the generated code to a separate source directory in the target project.  The new source directory will then be used as a spearate namespace.

The default source directory for the Moonshine Royale templates is `src/`.  However, MyAccount has `src/net/prominic` as the source directory.

Since multiple projects can be imported, we want unique names for each, and they should also be "marked" as generated.  From the meeting our proposed layout was:

    src/
        generated/
            <ProjectName1>
                ...generated source...
            <ProjectName2>
                ...generated source...
            ...

Is it a problem to put the projects at `src/generated/<project>/` when `src/` is a source directory?  If so, we could move this to `generated/<project>` or `generated-src/<project>`.

Would it make sense to update the generated project to use `src/generated/<project>/ as the default source directory for the generated project?  This would make it consistent with the target destination, but I'm not sure it maters for the code.

We should also keep in mind that there will be some duplicate classes between multiple generated source directories (and possibly conflics with the main source directory as well.  We should watch for problems with conflicts.

**Comment by piotrzarzycki21** [comment]
> As discussed in the meeting today, @piotrzarzycki21 is planning to deploy the generated code to a separate source directory in the target project. The new source directory will then be used as a spearate namespace.
> 
> The default source directory for the Moonshine Royale templates is `src/`. However, MyAccount has `src/net/prominic` as the source directory.
> 
> Since multiple projects can be imported, we want unique names for each, and they should also be "marked" as generated. From the meeting our proposed layout was:
> 
> ```
> src/
>     generated/
>         <ProjectName1>
>             ...generated source...
>         <ProjectName2>
>             ...generated source...
>         ...
> ```
> 
> Is it a problem to put the projects at `src/generated/<project>/` when `src/` is a source directory? If so, we could move this to `generated/<project>` or `generated-src/<project>`.
> 
> Would it make sense to update the generated project to use `src/generated// as the default source directory for the generated project? This would make it consistent with the target destination, but I'm not sure it maters for the code.
> 
> We should also keep in mind that there will be some duplicate classes between multiple generated source directories (and possibly conflics with the main source directory as well. We should watch for problems with conflicts.

I have pushed first step towards this part. Changes were quite extensive. Right now exported project to Royale is going to be exported to folder src/ProjectName. I'm starting work for the next stage copying files. 

It is definitely ready to test if you can export project to Royale and you have src/Projectname structure.

**Comment by piotrzarzycki21** [comment]
Branch has been merged to master with following improvements:

- [x] Automate importing generated Royale projects into an existing project.
- [x] We should support imports from multiple generated projects. So, the target directory for a project should be unique for the project.
- [ ] Generated code can be overwritten, but we want to avoid overwriting code that has been manually modified. The simplest solution is to keep the generated code separate
- [ ] ~~The developer should be reponsible for updating the existing application to reference the generated code (menu entries, panels, etc). The user should be able to copy short example snippets for this from the generated example.~~ (**No longer relevant - we have implemented everything automatically almost without ingerention dev**) 
- [x] We need a way to streamline updating the 'theme" for the generated source to match the target application
- [x] Avoid changing the "theme" of the target application with generated CSS files
- [ ] Update the agent URLs to match the target application. For now, this can be done by changing Base Agent URL in the DominoVisualEditor or FormBuilder project.
- [ ] Support developer modifications to the generated code for features that are not supported by the generation logic (i.e. special buttons or controls, layout changes to better match the target application, etc). Ideally these changes will be made outside of the generated source directory, but the developer will probably to do some manual merging. (**This need to be discussed if we actually really want to go into that rabbit hole.**)

Update is ready for some initial tests, so I'm marking this as test ready. I will provide instruction how to test all of that by @JesseProminic

**Comment by piotrzarzycki21** [comment]
Instruction to test:
1. Download PerformanceStats_BingTest (I will send you latest update of that project trough email)
2. Open PerformanceStats_BingTest in Moonshine
3. Select in side bar PerformanceStats_BingTest and choose from menu **Project** -> **Generate Apache Royale project**

_In order to proceed farther you need to have Apache Royale Template application - right now example of that application is MyAccount. You need to checkout using Git MyAccount._

4. Select in side bar generated Royale project and choose from menu **Project** -> **Export to an existing Apache Royale Templated Application**

_Before you jump to the next step familiarise with two MyAccount files. Inside these files you should find xml comments called CURSORS. Once you finish process of exports above those cursors you will have included some portion of code. Inspect if it's really happened after export. 
File 1: **src/net/prominic/ProminicNativeWeb.mxml**
File 2: **src/net/prominic/view/MainContent.mxml**_

5. Point to main application file of Apache Royale templated application - in case of MyAccount it will be `src/net/prominic/ProminicNativeWeb.mxml` and click **Export**

Results to inspect:
 - Inspect files according to above instructions
 - check if inside MyAccount src folder was created folder called "generated" - it should contains source code of exported project
 - add in MyAccount project settings folder "generated" inside "src" folder to source path and build MyAccount. You need to download first Apache Royale 0.9.10-SNAPSHOT using Moonshine SDK Installer.
 
<img width="1256" alt="Screenshot 2022-12-09 at 11 44 56" src="https://user-images.githubusercontent.com/24554795/206685025-fa7c81eb-49a4-4375-8ba0-bb22a875cefa.png">

Note:
In order to reset Royale Template Application (MyAccount) to original state (before export) - use git Discard or something similar on files:
File 1: **src/net/prominic/ProminicNativeWeb.mxml**
File 2: **src/net/prominic/view/MainContent.mxml**_

**Comment by JoelProminic** [comment]
Here is some quick pseudocode from the algorithm discussion today.  The idea is to search and replace individual START_GENERATED blocks rather than trying to make updates by project.  Some potential advantages:


```
class Snippet {
    File file; // relative path
    String keyword;  // i.e. "START_GENERATED_MENU|MyProject|MyForm
    String category; // determines cursor name.  i.e. START_GENERATED_MENU
    int startIndex;
    int endIndex;
    int fullString;  // from start comment through end commment.
}


function pushUpdates(sourceProject, targetProject) {
    snippets = findSnippets(sourceProject); // Search for "START_GENERATED"
    for (snippet : snippets) {
        targetSnippet = findSnippet(snippet.keyword, targetProject);  // support multiple matches for the same snippet?
        if (null == targetSnippet) {
            insertAtCursor(snippet, snippet.fullString, targetProject)
        }
        else {
            replace(targetSnippet, targetProject, snippet)
        }
    }
}
```

**Comment by JesseProminic** [comment]
:white_check_mark: Inside MyAccount src folder was created folder called "generated" - it contains source code of exported project

:white_check_mark: Added  in MyAccount project settings folder "generated" inside "src" folder to source path and build MyAccount.

<img width="601" alt="Screenshot 2022-12-20 at 11 56 17 AM" src="https://user-images.githubusercontent.com/96078188/208734094-7410ba21-262d-4760-b398-f0b1231699af.png">

**Comment by piotrzarzycki21** [comment]
- [ ] Fix button Refresh in exported project
- [ ] Change namespace in Apache Royale Templated App to `src/net/apacheRoyaleTemplatedApp`
- [ ] Change title and add short description to main Hello view
- [ ] Fix issue with white space in src path (@Aszusz ) 
- [ ] Fix export on Windows (@Aszusz )
- [ ] Review links in resources/jewel-index-template.html template and change them if needed

**Comment by JoelProminic** [comment]
@Aszusz and @piotrzarzycki21 reported that the Refresh issue was caused by caching on the agents.  @Aszusz worked around this by adding a `Cache-Control=no-cache` header in the WebRule document.  This should be handled by the agents, though, so I need to revisit this.

**Comment by JoelProminic** [comment]
We are currently storing the template in this repository:  https://github.com/Moonshine-IDE/Apache-Royale-Templated-Application

**Comment by JoelProminic** [comment]
Remaining tasks before release:
- Move Refresh bug (caching) to separate issue
- Do some more robustness testing on update logic.

**Comment by JoelProminic** [comment]
Test | Expected | Actual
-- | -- | -=
Fresh project | All objects imported properly | Confirmed
Change snippet | Snippet is updated properly | Confirmed
Change ordering  | Order preserved after update, no duplicates | Confirmed
Remove entry for a form | Entry added again with update.  We'll need to use a block comment (see below) to handle this case | Confirmed
Hide code snippet with block comment (requires CDATA - [example](https://ar.al/515/)). | Code is updated, but still not visible | Could not test


To hide a block, I tried to use a comment like this.  However, I found it was not allowed at the snippet locations.  We can discuss if there is a similar trick we can use elsewhere:

```
    <mx:Script> <![CDATA[ /*  Hiding block of MXML that includes comments
    ... code ...
    */ ]]> </mx:Script>
```

**Comment by JoelProminic** [comment]
If I open two Export to Royale Templated Application tabs, I get this error if I try to Cancel the first tab.  I can still close the tab:

    : Error #1009
    : TypeError: Error #1009
    : 	at actionScripts.controllers::CloseTabCommand/execute()
    : 	at actionScripts.locator::IDEController/execCommand()
    : 	at flash.events::EventDispatcher/dispatchEvent()
    : 	at actionScripts.plugins.exportToRoyaleTemplatedApp::ExportToRoyaleTemplatedAppPlugin/onCancelReport()
    : 	at flash.events::EventDispatcher/dispatchEvent()
    : 	at mx.core::UIComponent/dispatchEvent()
    : 	at actionScripts.plugin.settings::SettingsView/close()
    : 	at actionScripts.plugin.settings::SettingsView/handleCancelClicked()
    :
    : Click here to Report a Bug
    : Error #1009
    : TypeError: Error #1009
    : 	at actionScripts.plugins.exportToRoyaleTemplatedApp::ExportToRoyaleTemplatedAppPlugin/cleanUp()
    : 	at actionScripts.plugins.exportToRoyaleTemplatedApp::ExportToRoyaleTemplatedAppPlugin/onCancelReport()
    : 	at flash.events::EventDispatcher/dispatchEvent()
    : 	at mx.core::UIComponent/dispatchEvent()
    : 	at actionScripts.plugin.settings::SettingsView/close()
    : 	at actionScripts.plugin.settings::SettingsView/handleCancelClicked()
    :
    : Click here to Report a Bug


I didn't see any problems with Cancel for a single tab at a time.

**Comment by JoelProminic** [comment]
I created [an issue](https://github.com/Moonshine-IDE/Moonshine-Domino-CRUD/issues/34) for the caching update on the agent side.  @Aszusz, if you remember more details about the caching issue, please let me know - we weren't able to reproduce the issue in tests today.

**Comment by JoelProminic** [comment]
I moved the remaing bug to #1191.  Otherwise, this issue looked good in my recent tests.
