### ISSUE TITLE
TypeError: Error #2007 on app start makes Moonshine unusable

### ISSUE THREAD

**Issue by Aszusz** [Moonshine-IDE/Moonshine-IDE#1152]
Recently I did a factory reset on my Mac and I reinstalled Moonshine Development. When I start Moonshine Development this error appears on the console every time. The app launches but is entirely unusable: the app bar doesn't have all menus and I can't start any project.

I retested on BigSur, Monteray and Ventura and got the same results. 

Moonshine SDK Installer works fine though and I used it to download all SDKs. Moonshine stable 3.3.3 also works fine.

```
: Error #2007
: TypeError: Error #2007
: 	at flash.desktop::NativeProcess/start()
: 	at Function/actionScripts.plugins.build:ConsoleBuildPluginBase/start/actionScripts.plugins.build:onEnvironmentPrepared()
: 	at actionScripts.utils::EnvironmentSetupUtils/executeOSX()
: 	at actionScripts.utils::EnvironmentSetupUtils/executeSetCommand()
: 	at actionScripts.utils::EnvironmentSetupUtils/executeCommandWithSetLocalEnvironment()
: 	at actionScripts.utils::EnvironmentSetupUtils/initCommandGenerationToSetLocalEnvironment()
: 	at actionScripts.plugins.build::ConsoleBuildPluginBase/start()
: 	at actionScripts.plugins.menu::OpenInTerminalPlugin/retrieveThemeListOnTerminal()
: 	at actionScripts.plugins.menu::OpenInTerminalPlugin/activate()
: 	at actionScripts.plugin.settings::SettingsPlugin/pluginStateChanged()
: 	at actionScripts.plugin.settings::SettingsPlugin/initializePlugin()
: 	at actionScripts.plugin::PluginManager/registerPlugin()
: 	at actionScripts.plugin::PluginManager/setupPlugins()
: 	at components::MainEntryPoint/onAddedToStage()
: 	at components::MainEntryPoint/___MainEntryPoint_Group1_addedToStage()
: 	at mx.managers::SystemManager/preloader_preloaderDoneHandler()
: 	at flash.events::EventDispatcher/dispatchEvent()
: 	at mx.preloaders::Preloader/displayClassCompleteHandler()
: 	at flash.events::EventDispatcher/dispatchEvent()
: 	at mx.preloaders::SparkDownloadProgressBar/initCompleteHandler()
: 	at flash.events::EventDispatcher/dispatchEvent()
: 	at mx.preloaders::Preloader/dispatchAppEndEvent()
: 	at mx.preloaders::Preloader/appCreationCompleteHandler()
: 	at flash.events::EventDispatcher/dispatchEvent()
: 	at mx.core::UIComponent/dispatchEvent()
: 	at mx.core::UIComponent/set initialized()
: 	at mx.managers::LayoutManager/doPhasedInstantiation()
: 	at mx.managers::LayoutManager/doPhasedInstantiationCallback()
```

**Comment by Aszusz** [comment]
@Igazine assigning to you since it's a TypeError and happens only in Moonshine Development but feel free to reassign if it's not related to haxe conversion. If you need more details let me know.

**Comment by Igazine** [comment]
@Aszusz got it, thank you. it's a null pointer exception, looking into it now

**Comment by Igazine** [comment]
@Aszusz Could you please try again after the build finishes?

**Comment by Aszusz** [comment]
Sure, I'll let you know

**Comment by Aszusz** [comment]
Sorry, same error

**Comment by Aszusz** [comment]
@rat-moonshine If you have a bit of time could you please take a look at it?

**Comment by rat-moonshine** [comment]
Yeah, I'll check this. Thank you for investigating @Igazine .

**Comment by rat-moonshine** [comment]
When there is nothing to set through environment setup (typically when Moonshine installed fresh or its cookie folder being deleted) and trying to set a `null` valued environments through `NativeProcess`, triggers the error. 

I adjusted this slightly so no additional _null_ check or `NativeProcess` handling requires elsewhere. This should be Okay, please give a test.

**Comment by Aszusz** [comment]
@rat-moonshine Thank you so much, this is working now.
