### ISSUE TITLE
Misc. External Editors Update Requirements

### ISSUE THREAD

**Issue by rat-moonshine** [Moonshine-IDE/Moonshine-IDE#1154]
From @JustinProminic 

-----------------------

- [x] Version 15 is now the latest so please adjust as follows the default path:
![image](https://user-images.githubusercontent.com/24370870/204714667-7f3be89c-476e-472b-b5f1-05c6faaae4aa.png)

- [x] The new correct path for Balsamiq is apparently:
![image](https://user-images.githubusercontent.com/24370870/204714732-50de2292-e447-4f8a-bcf8-0cd07a735fd5.png)

- [x] Upon further review, I find it hard to tell which application I am selecting the chekbox on for a wide window.
Please move the enable checkbox to be immediately to the left of the application name.
For example, instead of:
Apache NetBeans [Checkbox]
It would show:
[Checkbox] Apache NetBeans

- [x] **[BUG]** I have been going through to download and test External Editors on an M1 Mac Mini because (as you may have heard last week) my x86 Mac Mini failed.  
I noticed that despite having checked several of the editors, the `About -> External Editors` showed nothing after a restart.
I then checked the Settings->External Editors and discovered that all of the ones I had enabled with the checkmark are now not checked. It seems we have a bug.

- [x] On the external editors, please add Sublime Text for Mac: http://www.sublimetext.com/download_thanks?target=mac. Please also add it to the `About -> External Editors`

**Comment by rat-moonshine** [comment]
There were two bugs with editor checkboxes:

1. In same application session, if an editor installed, re-opening the editors-list in Settings not enables its checkbox
2. Number 4 point reported in the original issue

While the first one from this above list fixed locally, the second one seems to be somewhere messing in the cookie-read/update codes, I needs more time to look into this.

**Comment by rat-moonshine** [comment]
Number 4 from the original issue should also fixed. Please, check.

**Comment by JesseProminic** [comment]
1. The latest version - Version 16 :white_check_mark:
<img width="690" alt="apache" src="https://user-images.githubusercontent.com/96078188/206497755-756618c1-3eab-4bbe-b4e8-5aa424e38ae3.png">

2. Correct path for Balsamiq :white_check_mark:
<img width="448" alt="balsamiq" src="https://user-images.githubusercontent.com/96078188/206497988-bece17fb-d321-4d72-83fb-bee074a7bf3b.png">

3. Check boxes on the left side :white_check_mark:

4. [BUG FIXED] Checkmarks stay checked :white_check_mark:

5. Sublime added :white_check_mark:
<img width="650" alt="sublime" src="https://user-images.githubusercontent.com/96078188/206499359-c03ec801-bf18-404f-94ec-c9e8412d5a98.png">
