### ISSUE TITLE
Getting Started Dialog Shows Git Installed When About Does Not

### ISSUE THREAD

**Issue by rat-moonshine** [Moonshine-IDE/Moonshine-IDE#1155]
As reported by @JustinProminic 

------------------------

I think I have raised this issue before.
The Getting Started page seems to think Git is installed:

![image](https://user-images.githubusercontent.com/24370870/204716830-c3036857-3d92-4d49-b329-39c0d57a0f9b.png)

but the About page does not:

![image](https://user-images.githubusercontent.com/24370870/204716927-bd4523da-b682-4122-8ed4-a8f3abda3417.png)

------------------------------

Briefly, the problem here is Git existence check vs. Git access. 

While the Getting Started sees that Git executables exists and tick the entry as available, About page requires to access the Git executable to do a version test. Unfortunately the executable can't be accessed unless user provides access permission on macOS. In that access restriction case, About shows 'Not Installed'. I understand this could be more meaningful information there instead.

**Comment by rat-moonshine** [comment]
Based on the reasoning of the bug (described in original issue), About screen now shows the solution in better way than earlier "Not Installed" text. With the updates, Git version entry should show now a "Grant permission" link instead:

![image](https://user-images.githubusercontent.com/24370870/205629006-42720c22-6d3e-4c03-8985-21074843bf0e.png)

To test this, please remove/rename the following folder:
/Users/$user/Library/Application Support/com.moonshine-ide

**Comment by rat-moonshine** [comment]
With newer updates, in About section:

Test | Getting Started | About
-- | -- | -- 
Not installed | ---shouldn't show warning but download--- | Showing 'Not installed'
Installed, but needs permission | ---should show warning---- | Shows "Grant Permission", and the link works

**Comment by JoelProminic** [comment]
The Git updates look good:
![image](https://user-images.githubusercontent.com/24532731/205990751-23fcceb6-c302-463f-9494-c16347d77057.png)
![image](https://user-images.githubusercontent.com/24532731/205990853-5a63d3ac-8ac2-4aff-9d62-053060f12430.png)

Test | Getting Started | About
-- | -- | -- 
Not installed | Shows not installed | Shows "Not installed"
Installed, but needs permission | Shows green with a warning.  Clicking Configure opens the Grant Permission prompt | Shows "Grant Permission", and the link works.  NOTE:  The version doesn't load immediately after running through "Grant permission", so this may cause some confusion
Installed with permission | All Green, no Configure button | Shows version.

**Comment by rat-moonshine** [comment]
> I'm also seeing a warning now for Neko, even though the path is populated in the Moonshine settings. I'm wondering if this was affected by your update for the Git warning.

I remember the warning was intentional in case of Neko. If it was disappearing in past, then it is possibly fixed now.
