### ISSUE TITLE
Default Form Name and View Name in FormBuilder

### ISSUE THREAD

**Issue by JoelProminic** [Moonshine-IDE/Moonshine-IDE#1158]
As I do more practical work in Form Builder, I have found it annoying that the Form Name and View Name are not populated by default.  These should be set to match the name of the file:
![image](https://user-images.githubusercontent.com/24532731/204915966-1179977d-c91a-4d75-b6b2-1d020b443a1b.png)

By the original design, these names do not need to match, but this should be the convention.

**Comment by rat-moonshine** [comment]
Thanks to the issue, I found two problems upon investigation:

1. The codes supposed to read from `.dfb` and populate the input-fields accordingly. However, a newly created `.dfb` file didn't had the placeholder where form-name can be updated to - this now added
2. During creation of OnDisk project, `.dfb` file in the corresponding template was wrongly holding format of a `.dve` file - this now fixed

Please, check.

**Comment by JoelProminic** [comment]
This has been working well for me in my development in FormBuilder.
