### ISSUE TITLE
Maven Updates for JDK 17

### ISSUE THREAD

**Issue by JoelProminic** [Moonshine-IDE/Moonshine-IDE#1167]
We are seeing errors with new Java Maven projects after the JDK 17 updates (#1124)

**Comment by JoelProminic** [comment]
I reproduced the error on macOS 12.6.1 (Monterey)

    : [INFO] Compiling 1 source file to /Users/-user-/Documents/TestJavaMaven_12_15/target/classes
    : [INFO] -------------------------------------------------------------
    : [ERROR] COMPILATION ERROR : 
    : [INFO] -------------------------------------------------------------
    : [ERROR] Source option 6 is no longer supported. Use 7 or later.
    : [ERROR] Target option 6 is no longer supported. Use 7 or later.
    : [INFO] 2 errors 

I was able to resolve this by upgrading the plugins in pom.xml (which increases the default Java version to 1.7)

Plugin | Old Version | New Version
-- | -- | --
maven-compiler-plugin |  | 3.10.1
maven-jar-plugin | 3.2.0 | 3.3.0

```
<?xml version="1.0"?>
<project xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd"
  xmlns="http://maven.apache.org/POM/4.0.0"
  xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
  <modelVersion>4.0.0</modelVersion>

  <groupId>local</groupId>
  <artifactId>TestJavaMaven_1215</artifactId>
  <name>TestJavaMaven_1215</name>
  <version>0.1.0-SNAPSHOT</version>
   <build>
        <sourceDirectory>src/main/java</sourceDirectory>
        <plugins>
            <plugin>
                <artifactId>maven-compiler-plugin</artifactId>
                <version>3.10.1</version>
            </plugin>
            <plugin>
                  <groupId>org.apache.maven.plugins</groupId>
                  <artifactId>maven-jar-plugin</artifactId>
                  <version>3.3.0</version>
                  <configuration>
                    <archive>
                      <manifest>
                        <mainClass>TestJavaMaven_1215</mainClass>
                      </manifest>
                    </archive>
                  </configuration>
                </plugin>
        </plugins>
   </build>
</project>
```

Project | Build & Run Test (macOS Monterey x64)
-- | -- 
Java Maven | Requires updates
Royale Browser, Jewel (Build with Apache Maven) | No default build actions or pom.xml.  I though this was supported.
Domino On Disk Project | Blocked by missing update site
Domino Visual Editor |  Blocked by missing update site
Settings > Domino and Notes Client > UpdateSite > Generate | Not enabled on macOS Monterey


@rat-moonshine, the errors I see on other projects may not be directly related to Java and Maven, but they showed up in my tests.  We can create separate issues as needed.

**Comment by rat-moonshine** [comment]
I'm not familiar with Maven/Java. I'm ready to help if anything with basic functioning of Moonshine, though. Please let me know if anything need to be adjust differently or fix at functional level in this case..

**Comment by JoelProminic** [comment]
The updates site generation was disabled because Git wasn't fully configured at the time of my earlier test.  

The update site generation failed with this error on macOS Mojave with JDK 17:

    : [INFO] Copying com.ibm.rcp.toolbox.dashboard_10.0.0.20211117-0921.jar
    : [INFO] ------------------------------------------------------------------------
    : [INFO] BUILD FAILURE
    : [INFO] ------------------------------------------------------------------------
    : [INFO] Total time:  02:02 min
    : [INFO] Finished at: 2023-01-18T18:03:45-06:00
    : [INFO] ------------------------------------------------------------------------
    : [ERROR] Failed to execute goal org.openntf.p2:generate-domino-update-site:5.0.0-SNAPSHOT:generateUpdateSite (default-cli) on project generate-domino-update-site: Execution default-cli of goal org.openntf.p2:generate-domino-update-site:5.0.0-SNAPSHOT:generateUpdateSite failed: java.lang.NullPointerException: entry -> [Help 1]


Most of the actions worked, so this could be an unrelated error.  This will need more investigation.

**Comment by rat-moonshine** [comment]
Java Maven Project [pom.xml](https://github.com/Moonshine-IDE/Moonshine-IDE/blob/master/ide/MoonshineSharedCore/src/elements/templates/projects/Java%20Maven%20Project/pom.xml.template) updated with the versions [specified](https://github.com/Moonshine-IDE/Moonshine-IDE/issues/1167#issuecomment-1353804088). Please, check.

**Comment by JoelProminic** [comment]
I confirmed the updated version, and the Java Maven project builds without modification now.  I'm closing the issue.  Thanks!
