### ISSUE TITLE
Editor Breakpoint Highlight Not Showing During Debug

### ISSUE THREAD

**Issue by rat-moonshine** [Moonshine-IDE/Moonshine-IDE#1170]
Recently, I'm noticing that highlights not showing during a debug in Moonshine. As example, I don't see the breakpoint-highlight in line#60 in following screen:

![image](https://user-images.githubusercontent.com/24370870/207913491-bec3c072-7bcd-4737-89ee-96bdedcad31b.png)

If compared to earlier screen:

![image](https://user-images.githubusercontent.com/24370870/207914665-746f171d-6506-4a24-bf45-5a1138b7dff0.png)

@Aszusz also confirmed the behaviour during his past tests. 
@joshtynjala thinks this could be a bug and its reason may hiding deeper. He suggested to investigate.

**Comment by joshtynjala** [comment]
After some investigation, I can see that it's a bug in the `TextEditor` component. I'll get it fixed later today!

**Comment by joshtynjala** [comment]
I spoke too soon. The `TextEditor` component is working correctly. When I implemented text editor color schemes, I passed the wrong color for the debug highlight from Moonshine to the `TextEditor`. I was incorrectly passing the editor background color, so it looked like there was no highlight.
