### ISSUE TITLE
Import Documents by JSON through Genesis.

### ISSUE THREAD

**Issue by JoelProminic** [Moonshine-IDE/Moonshine-IDE#1171]
We would like an easy way to import documents as JSON for a FormBuilder/DominoVisualEditor database.  This could be used for:
- Populating test data
- Populating default configuration for a database
- Updating databases like names.nsf for specific applications.

I would like a new action for this, `Project > Import Documents` from JSON.  This should be added in the second section, just under `Generate Apache Royale Project`.

This action should open a new prompt with these fields:
- "File to Import:"
    - this should only allow `.json` files for now
    - Populate this with the selected file in the workspace sidebar if the select the file is `.json`
- Vagrant Instance" - Use the same logic as for other Vagrant REST actions.

I created a script at `/opt/domino/scripts/import_json_documents.sh`  This will be available if Vagrant instance has the `import-domino-json` capability.  Currently this is only available for [DominoVagrant/demo-v1.1](https://github.com/DominoVagrant/demo-v1.1) (if you already have an instance, you should just need to run `git pull` then `vagrant reload`) but it will eventually be available in `demo-tasks`

The process will work the same as what we did [here](https://github.com/Moonshine-IDE/Moonshine-IDE/issues/979#issuecomment-1171640477).  The main differences are:
- For the `file/upload` action, the file will be the local database (.nsf)
- The `/task` action will use a different script and parameters:

```
# URL:  /task
# Content-Type:  application/x-www-form-urlencoded
# Parameter:  command (the command to run
#   - "/opt/domino/scripts/import_json_documents.sh".  This is a hard-coded path to the script.  Vagrant will enforce this location.
#   - "%json-path%" - collected from the file/upload response

curl -X "POST" "http://localhost:8096/task" \
     -H "Accept: application/json" \
     -H "Content-Type: application/x-www-form-urlencoded" \
     --data-urlencode "command=/bin/bash /opt/domino/scripts/import_json_documents.sh '%json-path%'"

```

You will then check the status normally.

I added an example file you can use for testing under `ContactsDatabase/data` in [this project](https://github.com/Moonshine-IDE/FormBuilder-Contact-API/).   You will want deploy the database first, or the target will be missing for the document import.

UPDATE:
Branch:  features/issue_1171_import_json
Windows:  https://moonshine-ide.com/downloads/releases/dev/windows/branches/features/issue_1171_import_json
macOS:  https://moonshine-ide.com/downloads/releases/dev/macos/branches/features/issue_1171_import_json

**Comment by rat-moonshine** [comment]
Cover:
- New menu
- Import Document popup
- Database job class

Problem:
During `Project > Build on Vagrant` I'm getting an upload error:
```
: Failed to upload file on server:
: Error #2032: Stream Error. URL: http://192.168.0.103:8096/file/upload?rand=0.4411239163018763
```
Maybe I should try by destroy and re-setup the Vagrant instance.

**Comment by rat-moonshine** [comment]
I required to destroy and start Vagrant to overcome the [earlier](https://github.com/Moonshine-IDE/Moonshine-IDE/issues/1171#issuecomment-1365135414) problem. I can able to pass the `Build on Vagrant` step now. 

Following are my steps in renewed tests:

- Open ContactDatabase application in Moonshine
- Run `Project > Build on Vagrant`
- Run `Project > Deploy Domino Database`
- Run `Project > Import Documents`
- In opening popup I pointed the targeted .json file to `ContactDatabase/data/default_config.json`
- After submission during `/task` operation server returned following error:

```
: Trying to upload request to: http://192.168.0.103:8096/file/upload. This may take some time..
: Requesting conversion job to: http://192.168.0.103:8096/task
: Re-try conversion(#7) check: 1
: Output: jq: error: Could not open file /Users/devsena/Desktop/Running Tasks/FormBuilder-Contact-API-main/ContactsDatabase/data/default_config.json: No such file or directory
: Invalid JSON:  '/Users/devsena/Desktop/Running Tasks/FormBuilder-Contact-API-main/ContactsDatabase/data/default_config.json'
: Conversion failed with exit code: 1
: null
```

I tried following to understand the problem:
- Put the .json file in a directory with no space in its name
- Checked the .json is not broken
- I tried to change quotation between single-quote and double-quote surrounding the path-value, but based on the server output it seems it does understand the full file-path correctly 

Currently, I stuck here.

**Comment by JoelProminic** [comment]
@rat-moonshine, I see you are using the local host path instead of the Vagrant path.  After running `file/upload`, you can get the Vagrant path from the response. You should see similar code in other actions:

```
{
    "path":"/tmp/restinterface/upload/default_config.json",
    "size":524288
}
```

There are no steps required after running the `/task` and polling the status.   At this point, the documents are imported into the database, so there is nothing else to do for the import action.  The imported documents will be available in the Notes client or REST agents.

**Comment by rat-moonshine** [comment]
I'm not sure if I do it right but this returns a success event now from Vagrant. 

Earlier I was uploading the local-database file based on the following instruction from the original issue, which was returning a .nsf file-path post-file/upload event, and eventually it fails with the error as invalid json:

> The process will work the same as what we did https://github.com/Moonshine-IDE/Moonshine-IDE/issues/979#issuecomment-1171640477. The main differences are:
> 
> - For the file/upload action, the file will be the local database (.nsf)
> - The /task action will use a different script and parameters:

Now I'm uploading .json instead of .nsf, and this seems to return similar path-value mentioned [here](https://github.com/Moonshine-IDE/Moonshine-IDE/issues/1171#issuecomment-1366952520).

A build can be tested with branch macOS build from Bamboo.

**Comment by JoelProminic** [comment]
Test | Expected | Result
-- | -- | --
Import valid JSON file | Documents added | Confirmed
Import invalid JSON file | Report error | Confirmed
Run with JSON file selected | Show JSON file in prompt | Confirmed
Run with non-JSON file selected | Prompt is blank, file may be selected | Confirmed
`import-domino-json` capability | Detected properly | TODO

**Comment by JoelProminic** [comment]
@rat-moonshine, please merge this for tomorrow, if it isn't merged already.

**Comment by rat-moonshine** [comment]
It's now merged into `master`.

**Comment by JoelProminic** [comment]
I created [a script](https://github.com/Moonshine-IDE/Moonshine-Domino-CRUD/blob/main/src/main/groovy/com/moonshine/ConvertJSONToGenesis.groovy) to convert agent JSON to a format that works with the feature added in this issue.  The syntax is:

    groovy ConvertJSONToGenesis.groovy <input-file> <output-file>

I'm thinking it will make more sense to handle this conversion as part of the Import Documents action, so that we can store simplified JSON.  However, this would require some messy bash, or a more complicated Groovy or Java code, so we'll stick with this solution for now.

I some practical tests for one of [the Prominic applications](https://github.com/Moonshine-IDE/ZoneMinder-tvOS), and this worked like I expected.  I'm closing this issue for now.

**Comment by JoelProminic** [comment]
I revisited this feature, and I found that the corresponding script and capability are not available in the current provisioner:  https://github.com/STARTcloud/hcl_roles/issues/2

I'm reopening this issue as a reminder before we release Moonshine 3.3.4.  It doesn't necessarily block the release, but the feature will have limited value until we get the capability added to a VM.

**Comment by JoelProminic** [comment]
I added the script to [Super.Human.Installer](https://github.com/Moonshine-IDE/Super.Human.Installer/issues/110) and [hcl_roles(future provisioners)](https://github.com/STARTcloud/hcl_roles/issues/2), so this feature should be available with the next Super.Human.Installer release.
