### ISSUE TITLE
icon is missing from package

### ISSUE THREAD

**Issue by godolsoft** [Moonshine-IDE/Moonshine-IDE#1175]
Hello everybody,
I already configured the paths and that error keeps coming out. Does anyone know how I should configure the folders?

![imagen](https://user-images.githubusercontent.com/47543948/210393012-7fc4cb7e-6260-4354-b590-e1ce58c6081c.png)
![imagen](https://user-images.githubusercontent.com/47543948/210393122-b5d328ad-a984-4373-adf4-d03ec1402298.png)
![imagen](https://user-images.githubusercontent.com/47543948/210393244-ae92eb06-c446-400b-aa09-1c08841e7779.png)
![imagen](https://user-images.githubusercontent.com/47543948/210393371-079cd26c-9b55-4f01-9323-fb1648eef626.png)
 compileAPKProject:
:      [java] C:\Users\TICS\Documents\unos\build\build-debug\unos-app.xml: error 303: Icon icons/icon_114.png is missing from package
:      [java] C:\Users\TICS\Documents\unos\build\build-debug\unos-app.xml: error 303: Icon icons/icon_72.png is missing from package
:      [java] C:\Users\TICS\Documents\unos\build\build-debug\unos-app.xml: error 303: Icon icons/icon_48.png is missing from package
:      [java] C:\Users\TICS\Documents\unos\build\build-debug\unos-app.xml: error 303: Icon icons/icon_128.png is missing from package
: 
: BUILD FAILED
: C:\Users\TICS\Documents\unos\build\build.xml:145: Java returned: 12

**Comment by rat-moonshine** [comment]
If you're using project-supplied Ant build-script to compile the APK, you'll need to add any additional resource folder during your compilation (i.e. `icons`). Try to provide your resource directory in this way:

```
<property name="ICONS_FOLDER" value="../icons" />
<!-- Compile APK -->
<target name="compileAPKProject" depends="compileSWF">
	<java jar="${ADT_PATH}" fork="true" failonerror="true">
		<arg line="-package" />
		<arg line="-target apk-captive-runtime"/>
		<arg line="-storetype pkcs12" />
		<arg line="-keystore '${DESKTOP_SELFSIGNED_CERTIFICATE}' " />
		<arg line="-storepass '${DESKTOP_SELFSIGNED_CERTIFICATE_PASS}'" />
		<arg line="${DESKTOP_PACKAGE_PATH}" />
		<arg line="${DESKTOP_DESCRIPTOR}" />
		<arg line="${SWF_FILE_PATH}" />
		<!-- Add folders to be bundled in the AIR file here -->
		<arg line="${ICONS_FOLDER}" />
	</java>
</target>
```

You need to make sure the path is correct for `ICONS_FOLDER` here.

`$project > Settings > Paths > Resource folders` being use during a "Build & Run" or debug process. It do not modify the Ant build file.

**Comment by godolsoft** [comment]
Excellent answer, I are editing the build.xlm file
I put this 2 lines of code and it worked.
<property name="ICONS_FOLDER" value="../icons" />
<arg line="${ICONS_FOLDER}" />
Thank you rat-moonshine for your very accurate answer
