### ISSUE TITLE
Error: Definition librarie.swc could not be found.

### ISSUE THREAD

**Issue by godolsoft** [Moonshine-IDE/Moonshine-IDE#1178]
hello everybody, It does not compile when I run ant and I get this error:
compileSWF:
:     [mxmlc] Cargando el archivo de configuración C:\MoonshineSDKs\Flex_SDK\Flex_4.16.1_AIR_33.1\frameworks\airmobile-config.xml
:     [mxmlc] C:\Users\TICS\Documents\forlder\src\views\Ventas.mxml(12):  Error: Definition org.alivepdf.data:Grid could not be found.
:     [mxmlc] 
:     [mxmlc] 			import org.alivepdf.data.Grid;

: BUILD FAILED
: C:\Users\TICS\Documents\folder\build\build.xml:126: mxmlc task failed.
: 
: Total time: 9 seconds
: FSCH exit code: 1

I am importing the alivepdf library, but an error appears for the entire library.

![import](https://user-images.githubusercontent.com/47543948/210902767-ce8be3eb-5fb4-47e4-a688-10eca2d52890.JPG)

![lib](https://user-images.githubusercontent.com/47543948/210903764-074a2e09-06f2-494a-b90a-19afc4c2a560.JPG)

What else can I do ? because I already configured the path but the error continues when packaging the apk with Ant.

**Comment by joshtynjala** [comment]
If you're using Ant to build, you probably need to update the build.xml file too. I assume that you should add src/libs/AlivePDF.swc to the mxmlc task's library-path.

**Comment by godolsoft** [comment]
you're great, @joshtynjala. I added the path of the library-path and it was solved.
<compiler.library-path dir="../src" append="true"> 
			   <include name="libs/AlivePDF.swc" />
			</compiler.library-path>
