### ISSUE TITLE
.xml_conversion_required Logic Broken in 3.3.4 Development

### ISSUE THREAD

**Issue by JoelProminic** [Moonshine-IDE/Moonshine-IDE#1181]
I recently noticed that DominoVisualEditor projects generated by NSFConverterPortalProject did not build properly from Moonshine.  The build did not fail on the local machine or on DominoVagrant, but forms were not created properly in theresulting database.  @feather812002 investigated this and noticed that the `.xml_conversion_required` process was no longer triggering (#968).

I see that this issue also prevents population of the Settings > Maven Build > Maven Settings File field.  I set this manually for my local tests.

@rat-moonshine, @piotrzarzycki21, are you aware of any changes in the 3.3.4 milestone that would break this?

Example Project:  
[2023_01_12__NSFConverter_Example.zip](https://github.com/Moonshine-IDE/Moonshine-IDE/files/10405622/2023_01_12__NSFConverter_Example.zip)

**Comment by rat-moonshine** [comment]
The last thing that I worked in OnDisk project was #1171 . This only creates a subset of task and not modifying any existing task. I wonder if that makes any effect to existing workings. Surely that shouldn't affect in Maven settings, either.

**Comment by piotrzarzycki21** [comment]
@JoelProminic What kind of build do we talk about ? Should I run on attached project Project -> Build with Maven ?

**Comment by feather812002** [comment]
@JoelProminic , I almost address this issue. 
[In before , ](https://github.com/Moonshine-IDE/Moonshine-IDE/blob/a51e709aa36472b0195d910c47039a151361fb86/ide/MoonshineSharedCore/src/actionScripts/plugin/actionscript/as3project/AS3ProjectPlugin.as#L162)

```
private function importFDProject(projectFile:FileLocation=null, openWithChoice:Boolean=false, openByProject:ProjectVO=null):void
		{
			// Is file in an already opened project?
			if (checkIfProjectIsAlreadyOpened(projectFile.fileBridge.parent.fileBridge.nativePath)) return;
			
			//check if need auto convert to domino dxl 
			autoConvertXmlToDominoForm(projectFile);

			// Assume user wants to open project by clicking settings file
			openProject(projectFile, openWithChoice, openByProject);

			
		}
```

In this code , before the projectFile pass into the projectName. veditorproj file,
But for now , it pass into is the project root folder ,so this is why it broken at now.

I add some logic code check it , but still have some trouble about the project name .
https://github.com/Moonshine-IDE/Moonshine-IDE/blob/a51e709aa36472b0195d910c47039a151361fb86/ide/MoonshineSharedCore/src/actionScripts/plugin/actionscript/as3project/importer/FlashDevelopImporter.as#L627

I add some code in here to add the setting.xml , so that we can correct build with ODP, but for now , I no way found a project from the project path, I will to do more investigate about this.

**Comment by rat-moonshine** [comment]
@feather812002 There were past adjustment to determine project name during project import. When previously it was determined by project-name = root-directory-name, this logic found often problematic when the containing project may have a different name.

Can you tell me _what_ you're looking for at _which_ point? Maybe we can try look into to help you.

**Comment by JoelProminic** [comment]
@piotrzarzycki21, I see the problematic behavior for both `Project > Build with Apache Maven` and `Project > Build on Vagrant`.

However, the underlying problem is the code that is supposed to trigger when opening the Visual Editor project.  Do you know of a better spot for [this line](https://github.com/Moonshine-IDE/Moonshine-IDE/blob/a51e709aa36472b0195d910c47039a151361fb86/ide/MoonshineSharedCore/src/actionScripts/plugin/actionscript/as3project/AS3ProjectPlugin.as#L162) that will be more specific to Domino Visual Editor?

**Comment by JoelProminic** [comment]
I updated the Bamboo branch plan for branch "bug/issue_1181_xml_conversion_required_logic_broken", but the build failed on a CompileWeb error:

    13-Jan-2023 13:12:52 	CompileWeb:
    13-Jan-2023 13:12:52 	     [copy] Copying 6757 files to .../Moonshine-IDE/ide/MoonshineWEBevolved/build/bin-debug/elements
    13-Jan-2023 13:12:56 	     [echo] /Users/mmb/SDKs/Flex_4.16.1_AIR_33.1
    13-Jan-2023 13:12:56 	     [echo] ../../MoonshineSharedCore
    13-Jan-2023 13:12:56 	     [echo] ../../MoonshineSharedCore/src/locale/{locale}
    13-Jan-2023 13:12:56 	     [echo] ../src
    13-Jan-2023 13:12:57 	    [mxmlc] Loading configuration file /Users/mmb/SDKs/Flex_4.16.1_AIR_33.1/frameworks/flex-config.xml
    13-Jan-2023 13:13:07 	    [mxmlc] .../Moonshine-IDE/ide/MoonshineSharedCore/src/actionScripts/utils/DominoUtils.as(61): col: 54 Error: Access of undefined property File.
    13-Jan-2023 13:13:07 	    [mxmlc] 
    13-Jan-2023 13:13:07 	    [mxmlc]                                         var separatorIndex:int=windowsTitle.lastIndexOf(File.separator);
    13-Jan-2023 13:13:07 	    [mxmlc]                                                                                         ^
    13-Jan-2023 13:13:07 	    [mxmlc] 
    13-Jan-2023 13:13:07 	    [mxmlc] .../Moonshine-IDE/ide/MoonshineSharedCore/src/actionScripts/utils/DominoUtils.as(37): col: 25 Error: Definition flash.filesystem:File could not be found.
    13-Jan-2023 13:13:07 	    [mxmlc] 
    13-Jan-2023 13:13:07 	    [mxmlc]         import flash.filesystem.File;
    13-Jan-2023 13:13:07 	    [mxmlc]                                ^
    13-Jan-2023 13:13:07 	    [mxmlc]

**Comment by feather812002** [comment]
@JoelProminic , I just fix this web build error ,and confirm it build success on the Bamboo at now 
Please check it if you have a free.

**Comment by feather812002** [comment]
> @feather812002 There were past adjustment to determine project name during project import. When previously it was determined by project-name = root-directory-name, this logic found often problematic when the containing project may have a different name.
> 
> Can you tell us _what_ you're looking for at _which_ point? Maybe we can try look into to help you, unless you already handle it.
Hello, @rat-moonshine  , thank you , I already handle it at now .
If it broken again and get some trouble ,I will let you know , thanks.

**Comment by JoelProminic** [comment]
@feather812002, I confirmed that the build completed successfully.  I thought there was some remaining work after the meeting today, but I did some quick test:

Open Action | .form files | Maven Settings File | Compiled Database
-- | -- | -- | --
Double-click .veditorproj | Populated | BUG:  Missing | Works
Project > Open/Import Project | Populated | BUG:  Missing | Works

**Comment by JoelProminic** [comment]
Ah, I forgot that we had added a [special keyword for settings.xml](https://github.com/Moonshine-IDE/Moonshine-IDE/issues/1142#issuecomment-1336769537):

```
<option settingsFilePath="%NSFODP_SETTINGS_FILE%"/>
```

This should be updated in NSFConverterPortalProejct instead of trying to set the full generated path on the Moonshine side.

**Comment by JoelProminic** [comment]
@feather812002,

I no longer see duplicate `settingsFilePath` entries after the project is opened in Moonshine.

Doing some more testing, I found that the .form files were not being populated when I used the `Others > Convert Domino Database` action to convert the database:
1. Make sure the nsf-converter-portal Vagrant instance is running and configured in Moonshine
2. Run `Others > Convert Domino Database` 
3. Select the database and target directory.
4. The Project converts and opens
5. Open the .veditorproj file and confirm that `settingsFilePath` is set
6. Open a .form file in an external editor.  BUG:  the file is empty.


If I convert a database outside of Moonshine and open it, the .form files are populated properly (and I don't see any major changes to the converted forms).

**Comment by JoelProminic** [comment]
The .xml_conversion_required logic is working as expected, and I don't see any obvious regression issues for the database conversion logic.   @feather812002, please merge this branch tomorrow (remember to merge master into the branch first to check for problems).  We can create separate issues for the other conversion issues you started working on.

**Comment by piotrzarzycki21** [comment]
@feather812002 please take a look into failing build after your merge: https://github.com/Moonshine-IDE/Moonshine-IDE/actions/runs/4005945081/jobs/6876903880

**Comment by joshtynjala** [comment]
@feather812002 If you are having trouble fixing the build, please at least update us on your progress. Thanks!

**Comment by JoelProminic** [comment]
@joshtynjala, the build was fixed yesterday.  I confirmed this in both Bamboo and the GitHub actions, but I see I didn't update this issue.

You'll need to update MockupVisualEditor and VisualEditorConverterLib.  Let me know if you are still having problems with the build.

**Comment by JoelProminic** [comment]
I did some quick tests with the database conversion after the merge yesterday, and the original issue is resolved.

**Comment by joshtynjala** [comment]
@JoelProminic Confirmed, updating the dependencies worked. Thanks!
