### ISSUE TITLE
IMOS convert

### ISSUE THREAD

**Issue by feather812002** [Moonshine-IDE/Moonshine-IDE#1182]
We need convert the IMOS core database export from NSFConvertProtal , then import it into Moonshin-IDE.
And build it back to NSF database with ODP.

In this progress , I got so much error, IMOS is a complex database.
So , I create the issue for today's work .

**Comment by piotrzarzycki21** [comment]
@JoelProminic could you maybe edit title of this issue to more appropriate. @feather812002 Please do everything on branch in that regards.

**Comment by JoelProminic** [comment]
I want to keep specific discussion (and screenshots) of IMOS outside of the public GitHub.  Instead, I'd prefer to discuss it in terms of the problems we find while testing conversion of the database.  For example, I have created #1183 and #1184.
