### ISSUE TITLE
Testing Vagrant Actions With demo-tasks Instance

### ISSUE THREAD

**Issue by JoelProminic** [Moonshine-IDE/Moonshine-IDE#1186]
I tried to do some more tests today with the Vagrant features with [demo-tasks](https://github.com/DominoVagrant/demo-tasks) today, and I found that I couldn't configure the application.

The expected URL with the default server name is (not that port 443 is not required in a browser, but we agreed to require it here):  `https://restapi.demo.startcloud.com:443`.  The `restapi` subdomain is redirected to port 8080 with a reverse proxy and this allows the URL to use SSL without configuring a separate certificate.

However, this was rejected despite matching the expected format:

![image](https://user-images.githubusercontent.com/24532731/214706288-cd060059-f771-4a99-84f3-e0589a036bd1.png)

It seems Moonshine requires 4 digits for the port:

![image](https://user-images.githubusercontent.com/24532731/214706271-dd3e1f20-aed6-4241-b00c-45251c09c823.png)

I was able to work around this for now using `http://restapi.demo.startcloud.com:8080`, but I'd like to support the default URL.

**Comment by JoelProminic** [comment]
For other testing I created a fresh FormBuilder application and updated the settings like this:
![image](https://user-images.githubusercontent.com/24532731/214716086-b34aee80-40ec-4453-9953-af50b36fb1b9.png)

Action | Result
-- | --
Others > Convert Domino Database | Not supported by `demo-tasks`
DominoVisualEditor:  Project > Build on Vagrant | Not working because of update site issue.
DominoVisualEditor:  Project > Deploy Domino Database | Working
DominoVisualEditor:  Project > Import Documents | Action not yet available
Java Gradle:  Project > Run on Vagrant | Works.  Note the updated server value above.
Royale:  Deploy to Vagrant Server | Works, but you need to use `https://domino.demo.startcloud.com/` as the Base URL.  I don't see how to update this now, so we'll need to revisit this eventually
Test Application | Works properly

**Comment by rat-moonshine** [comment]
Yes, the port number earlier restricted/limited to 4 digit. 

After looking on this it seems a port number can length between 0-5 [(0 - 65535)](https://stackoverflow.com/questions/38091498/is-default-port-numbers-are-alwasy-4-digit); Based on this I reset the port acceptance between 0-5 digits. This should fix the length problem. 

Please, check.

**Comment by JoelProminic** [comment]
Testing today, I confirmed that the port format was allowed, but Moonshine had trouble reading from the REST interface:
![image](https://user-images.githubusercontent.com/24532731/215187411-ff0d61f5-2463-4f42-b6be-2d3bcdf70996.png)
I confirmed that the test URL (`https://restapi.demo.startcloud.com:443`) works with /info:

![image](https://user-images.githubusercontent.com/24532731/215187471-9d67e0a6-593c-4bdf-98d6-352a371c2ef6.png)

**Comment by rat-moonshine** [comment]
As suggested by @JoelProminic , I tried to setup a local test-server which uses port 443 following the instruction from [here](https://github.com/prominic/MyAccount-Native-on-Royale/wiki/Setup-Local-Test-Server).

While testing the server (i.e. https://localdev.prominic.net:443/info) as new Vagrant instance, I prompted to accept system certificate-warning, but once accepts Moonshine able to access the `info`. 

I also changed the name to `restapi.demo.startcloud.com` to listen to 127.0.0.1, and that also returned similar behaviour as above. 

As it seems that port 443 easily accessible in Moonshine, I wonder what else could cause accessing the URL creates by Super.Human.Installer.

**Comment by rat-moonshine** [comment]
@joshtynjala @Igazine do you have any thoughts what could cause the following (?)

On macOS, https://restapi.demo.startcloud.com:443/info appears to be unreachable while accessing from Moonshine. It always get into `#2032: stream error`. The URL is accessible from browser, though.

Tried to read by different ways:
- `URLLoader` - turns to stream error
- `URLScheme` - turns to stream error
- `SecureSocket` - this seems to trigger `Event.CONNECT`, but I'm not sure how to read from the `info` agent here

I did a test with `Openfl.URLLoader` targeting _cpp_, and that worked without any problem; That at least limit the problem in to AIR application only.

**Comment by JoelProminic** [comment]
To clarify, https://restapi.demo.startcloud.com/info points to a local VM created by Super.Human.Installer.  Tamas, if you want to test this from MoonshineDevelopment:
1. Moonshine > Settings > Vagrant
2. Click the "+" button under Linked Instances
3. Enter a URL in the format `https://restapi.<base-domain-from-SHI>:443` (no `/info`)
4. When you move focus out of the field, Moonshine will try to validate the URL using `/info`


However, I think this problem is probably related to the protocols supported on the server.  It looks like TLS 1.1 and earlier are disabled on the generated server:


    % curl https://restapi.demo.startcloud.com/info --verbose  --tlsv1.1 --tls-max 1.1
    *   Trying 10.0.0.13...
    * TCP_NODELAY set
    * Connected to restapi.demo.startcloud.com (10.0.0.13) port 443 (#0)
    * ALPN, offering h2
    * ALPN, offering http/1.1
    * successfully set certificate verify locations:
    *   CAfile: /etc/ssl/cert.pem
      CApath: none
    * TLSv1.1 (OUT), TLS handshake, Client hello (1):
    * TLSv1.1 (IN), TLS alert, protocol version (582):
    * error:1400442E:SSL routines:CONNECT_CR_SRVR_HELLO:tlsv1 alert protocol version
    * Closing connection 0
    curl: (35) error:1400442E:SSL routines:CONNECT_CR_SRVR_HELLO:tlsv1 alert protocol version
    % curl https://restapi.demo.startcloud.com/info --verbose  --tlsv1.2 --tls-max 1.2 
    ... this works


As @rat-moonshine reported, the open OpenFL API works properly with the newer protocols.

I actually saw a similar problem for this yesterday with the GBAuth project. Is it is psosible to allow TLS 1.2 with the AIR Socket implementation, or do we need to push forward on the Haxe migration for this?

**Comment by JoelProminic** [comment]
I see Adobe AIR reported that they were removing support for [TLS 1.0 and 1.1](https://helpx.adobe.com/x-productkb/multi/eol-tls-support.html).  For Harman, I found [this page](https://help.harmanpro.com/rms-utilizing-smtp-to-o365) about a dependency on TLS 1.0 and 1.1, but I'm not sure that is related.

**Comment by rat-moonshine** [comment]
Point noted (maybe not be related) that Harman jumped version from 33 to 50 - https://airsdk.harman.com/download.

**Comment by Igazine** [comment]
This can be useful:

https://github.com/airsdk/Adobe-Runtime-Support/issues/1781

**Comment by rat-moonshine** [comment]
> This can be useful:
> 
> [airsdk/Adobe-Runtime-Support#1781](https://github.com/airsdk/Adobe-Runtime-Support/issues/1781)

With Harman AIR 33 this works good on Windows but macOS.

**Comment by Igazine** [comment]
If the AIR framework is not compatible with our setup, then not much we can do about it until the pure Haxe C++ target is available. 
Any chance we can upgrade something in our own demo-tasks setup?

**Comment by rat-moonshine** [comment]
This was only a try, in hope to have something a fix, somehow; I downloaded Harman AIR v50.1.12 and tested. When the download/install through MSDKI was easy, the new SDK also didn't shown any trouble running/compiling an application. 

However, I see same `#2032` error while using with the latest SDK. So, there's nothing new with this version of SDK use, either.

**Comment by JoelProminic** [comment]
Okay, it sounds like we don't have an easy fix for this.  We can still use "http://restapi.demo.startcloud.com:8080" to work with demo-tasks in Moonshine, so we'll avoid the https solution for now.

**Comment by piotrzarzycki21** [comment]
> This was only a try, in hope to achieve a fix somehow; I downloaded Harman AIR v50.1.12 and tested. When the download/install through MSDKI was easy, the new SDK didn't shown any trouble running/compiling an application either.
> 
> However, I see same `#2032` error while using with the latest SDK. So, there's nothing new with this version for this particular issue.

@rat-moonshine just an additional question here. How did you build that application? Did you change it's descriptor to make sure that you are using Air 50 ? What was your approach ?

**Comment by rat-moonshine** [comment]
I updated the download-configuration in MSDKI to download Harman AIR 50, did a local build of MSDKI and installed the newer SDK.

Upon installation I see the SDK labeled as AIR 33.1 - I think the `flex-sdk-description.xml` didn't updated in the installation process, but I didn't had time to look into this.

I could build an AIR application by updating its *-app.xml file with namespace value to 50.0 or something - that build the application using the newer SDK. It assures me that I build with newer SDK else it could throw an error saying I'm using an unknown AIR version.
