### ISSUE TITLE
[Domino Visual Editor] Invalid Default Value for $WindowTitle

### ISSUE THREAD

**Issue by JoelProminic** [Moonshine-IDE/Moonshine-IDE#1189]
From https://github.com/Moonshine-IDE/Moonshine-IDE/issues/1183#issuecomment-1405358815 :

>I confirmed that `choicesdialog` is now defaulted to `none` for all the fields.  This seems to compile properly (after fixing the below issue).
>
>However, I found that the `$WindowTitle` was set to the project path instead of the form name, and it was not properly encoded as a string literal, which triggers build errors.
>
>```
>  <item name="$WindowTitle" sign="true">
>    <formula>/path/to/project/</formula>
>  </item>
>```
>
>Previously, it looked like this:
>
>```
>  <item name="$WindowTitle" sign="true">
>    <formula>@Text('projectName')</formula>
>  </item>
>```

After some more testing, I saw the same issue on the latest MoosshineDevelopment (master).
1. Open MoonshineDevelopment.  Make sure you are updated to the latest version
2. Download and unzip [this example project](https://github.com/Moonshine-IDE/Moonshine-IDE/files/10439470/2023_01_17__TestKeywordFields.zip)
3. Open the project in Moonshine
4. Check `TestKeywordFields/nsfs/nsf-moonshine/odp/Forms/TestCheckbox.form`.  BUG: `$WindowTitle` uses the full path (i.e. `/Users/-user-/Downloads/TestKeywordFields`) plus the project name (`TestKeywordFields`) as the formula, and it is not escaped as a formula:

```
  <item name="$WindowTitle" sign="true">
    <formula>/Users/-user-/Downloads/TestKeywordFields/TestKeywordFields</formula>
  </item>
```

While we are revisiting this, I would like to Moonshine use the form name rather than the project name as the `$WindowTitle`, unless there is a different formula defined in the intermediate XML (the NSFConverterPortalProject logic to set this title is a separate issue.  I thought we had this working before...).

Note that the `$WindowTitle` was set properly in my tests earlier this week after the [#1181 merge](https://github.com/Moonshine-IDE/Moonshine-IDE/commit/9277ac053b337c343547e839a9c6485ff0ae67e2), so I think this broke in a recent commit.

UPDATE:  Example database
[2023_01_31__TestWindowTitle.nsf.zip](https://github.com/Moonshine-IDE/Moonshine-IDE/files/10548267/2023_01_31__TestWindowTitle.nsf.zip)

UPDATE:
Branch:  features/issue-1082_IMOS_Convert
Builds:  https://static.moonshine-ide.com/downloads/releases/dev/macos/branches/features/issue-1082_IMOS_Convert

**Comment by JoelProminic** [comment]
I see `$WindowTitle` is set in two locations.  I'm seeing a lot of duplicated methods between these two classes.

https://github.com/Moonshine-IDE/Moonshine-IDE/blob/0aebb05ad16cfedfaf599bfb82972b35405f2b87/ide/MoonshineSharedCore/src/actionScripts/utils/DominoUtils.as#L70
https://github.com/Moonshine-IDE/MockupVisualEditor/blob/0284cccfe8e6c946324efd5ffe921a730f35af8f/src/utils/MainApplicationCodeUtils.as#L660

The second snippet is missing the `@Text` wrapper, so that seems to be the code that is triggering currently.  I'm trying to track where `windowTitle` is generated here, but I'm having trouble with `Edit > Go To References`.

**Comment by feather812002** [comment]
@rat-moonshine 
Hello , I already discuss with Joel and Santanu about this issue in today's daily meeting.
We already address this error and I already fix some issue on the NSFConvertProtal side.
The other part about this issue I will fix in tomorrow.
The projectName path cause the MockupVisualEditor branch not merge into Master,  
and we decide improve it , after I fix in tomorrow , I will details it in here.

**Comment by feather812002** [comment]
Okay , for this issue now it work as follow:

- Import the Visual Editor project from NSFConvertProtal
   The windowsTitle will load from source dxl , if the source dxl not setting the windowsTitle , it will be default as "@Text('form name')"
- Create a new Visual Editor project from Moonshine-DE, the windows title will default as empty , you can free input from property panel of the Mock UI components, after you setting it as open it ,you will get the correct windows title .

**Comment by JoelProminic** [comment]
I attached an example database with some cases to test converting the WindowTitle.
[2023_01_31__TestWindowTitle.nsf.zip](https://github.com/Moonshine-IDE/Moonshine-IDE/files/10548267/2023_01_31__TestWindowTitle.nsf.zip)

Note that I also included some Page cases, which should use the same logic.  We can test opening the forms with [this trick](https://github.com/Moonshine-IDE/Moonshine-IDE/issues/905#issuecomment-963428662).

**Comment by JoelProminic** [comment]
Here are some form test cases.  The pages should have similar behavior.  DEFAULT will be to match the form name.

Case | Resulting Window Title | Test
-- | -- | --
Converted database, no WindowTitle | DEFAULT | 
Converted database, WindowTitle is a string literal | Preserve the title | 
Converted database, WindowTitle is a string literal with special XML characters | Preserve the title | 
Converted database, WindowTitle is a formula | Preserve the title | 
Fresh project, default form | DEFAULT | 
New Form | DEFAULT | 
User enters a new simple window title | Preserve the user value | 
User enters a new window title with special characters | Preserve the user value | 
User enters a new window title with a formula | Preserve the user value | 
User enters an empty string as the formula | Preserve the user value - this is a strange case, but we can allow it | 
User clears the window title | Reset to DEFAULT? | 
Rename, default window title | Update window title to match new form name | 
Rename, custom window title | Preserve original window title |

**Comment by feather812002** [comment]
Case | Resulting Window Title | Test
-- | -- | --
Converted database, no WindowTitle | DEFAULT | :white_check_mark:
Converted database, WindowTitle is a string literal | Preserve the title | :white_check_mark:
Converted database, WindowTitle is a string literal with special XML characters | Preserve the title | :white_check_mark:
Converted database, WindowTitle is a formula | Preserve the title | :white_check_mark:
Fresh project, default form | DEFAULT | :white_check_mark:
New Form | DEFAULT | :white_check_mark:
User enters a new simple window title | Preserve the user value | :white_check_mark:
User enters a new window title with special characters | Preserve the user value | :white_check_mark:
User enters a new window title with a formula | Preserve the user value | :white_check_mark:
User enters an empty string as the formula | Preserve the user value - this is a strange case, but we can allow it | This will also be set an empty string as the title 
User clears the window title | Reset to DEFAULT? | it will be back to empty 
Rename, default window title | Update window title to match new form name | Waiting
Rename, custom window title | Preserve original window title | Waiting

**Comment by JoelProminic** [comment]
Testing today's updates, I see that the default for new forms was `FormName`, but it should be `"FormName"`.  The former is evaluated as a field/item, so the title would be blank unless such a field exists and is populated.

WindowTitle was set properly for the converted forms.

I added some Pages to the test database, but NSFConverter does not convert pages yet (they are only on the Moonshine side.  See #905).  We'll focus on the pages that are created and updated locally instead.

**Comment by JoelProminic** [comment]
The Bamboo build is currently failing on MoonshineWEB:

    build	03-Feb-2023 11:36:50	CompileWeb:
    build	03-Feb-2023 11:36:50	     [copy] Copying 6758 files to .../Moonshine-IDE/ide/MoonshineWEBevolved/build/bin-debug/elements
    build	03-Feb-2023 11:36:54	     [echo] /Users/mmb/SDKs/Flex_4.16.1_AIR_33.1
    build	03-Feb-2023 11:36:54	     [echo] ../../MoonshineSharedCore
    build	03-Feb-2023 11:36:54	     [echo] ../../MoonshineSharedCore/src/locale/{locale}
    build	03-Feb-2023 11:36:54	     [echo] ../src
    build	03-Feb-2023 11:36:55	    [mxmlc] Loading configuration file /Users/mmb/SDKs/Flex_4.16.1_AIR_33.1/frameworks/flex-config.xml
    build	03-Feb-2023 11:37:06	    [mxmlc] .../Moonshine-IDE/ide/MoonshineSharedCore/src/actionScripts/utils/DominoUtils.as(305): col: 23 Error: Access of undefined property StringHelper.
    build	03-Feb-2023 11:37:06	    [mxmlc] 
    build	03-Feb-2023 11:37:06	    [mxmlc] 					windowsTitleName=StringHelper.base64Decode(windowsTitleName);
    build	03-Feb-2023 11:37:06	    [mxmlc] 					                 ^
    build	03-Feb-2023 11:37:06	    [mxmlc] 
    build	03-Feb-2023 11:37:06	    [mxmlc] .../Moonshine-IDE/ide/MoonshineSharedCore/src/actionScripts/utils/DominoUtils.as(316): col: 22 Error: Access of undefined property StringHelper.
    build	03-Feb-2023 11:37:06	    [mxmlc] 
    build	03-Feb-2023 11:37:06	    [mxmlc] 				windowsTitleName=StringHelper.base64Encode(windowsTitleName);
    build	03-Feb-2023 11:37:06	    [mxmlc] 				                 ^
    build	03-Feb-2023 11:37:06	    [mxmlc] 
    build	03-Feb-2023 11:37:06	    [mxmlc] .../Moonshine-IDE/ide/MoonshineSharedCore/src/actionScripts/utils/DominoUtils.as(38): col: 14 Error: Definition utils:StringHelper could not be found.
    build	03-Feb-2023 11:37:06	    [mxmlc] 
    build	03-Feb-2023 11:37:06	    [mxmlc] 	import utils.StringHelper;
    build	03-Feb-2023 11:37:06	    [mxmlc] 	            ^
    build	03-Feb-2023 11:37:06	    [mxmlc]

**Comment by JoelProminic** [comment]
The double-quoting issue from yesterday is resolved.  I ran though the test cases:

Here are some form test cases.  The pages should have similar behavior.  DEFAULT will be to match the form name.

Case | Resulting Window Title | Form | Page
-- | -- | -- | --
Converted database, no WindowTitle | DEFAULT | Confirmed | N/A
Converted database, WindowTitle is a string literal | Preserve the title | Confirmed | N/A
Converted database, WindowTitle is a string literal with special XML characters | Preserve the title | Confirmed | N/A
Converted database, WindowTitle is a formula | Preserve the title | Confirmed | N/A
Fresh project, default form | DEFAULT | Confirmed | N/A
New Form | DEFAULT | Confirmed | 
User enters a new simple window title | Preserve the user value | Confirmed | Page not generated
User enters a new window title with special characters | Preserve the user value | Confirmed | Page not generated
User enters a new window title with a formula | Preserve the user value | Confirmed | Page not generated
User enters an empty string as the formula | Preserve the user value - this is a strange case, but we can allow it | Confirmed | Page not generated
User clears the window title | Reset to DEFAULT | Reset to DEFAULT | Page not generated
Rename, default window title | Update window title to match new form name | Confirmed | FAILED - original name not updated
Rename, custom window title | Preserve original window title | Confirmed | Confirmed

I opened the generated database in Domino Designer, and found that the pages were generated as forms.  I checked, and I see that if I had accidentally created a form instead of a page, it would have been created in the `Forms` directory instead.

My project:  
[2023_02_03__TestWindowTitleManual.zip](https://github.com/Moonshine-IDE/Moonshine-IDE/files/10582092/2023_02_03__TestWindowTitleManual.zip)

**Comment by JoelProminic** [comment]
Case | Resulting Window Title | Page
-- | -- | --
New Page | DEFAULT | Confirmed
User enters a new simple window title | Preserve the user value | BUG:  DEFAULT
User enters a new window title with special characters | Preserve the user value | BUG:  Not preserved `<TestSpecialCharacters>&`
User enters a new window title with a formula | Preserve the user value | BUG:  DEFAULT
User enters an empty string as the formula | Preserve the user value - this is a strange case, but we can allow it | BUG:  DEFAULT
User clears the window title | Reset to DEFAULT | Confirmed
Rename, default window title | Update window title to match new form name | BUG:  could only be oopened by original name, window title not updated
Rename, custom window title | Preserve original window title |

**Comment by JesseProminic** [comment]
Following the procedures from [here](https://github.com/Moonshine-IDE/Moonshine-IDE/issues/1189#issue-1560397795):

| | macOS  |Windows  |
|---|----|-----|
|Window Title | TestCheckbox.form | TestCheckbox.form |

**Comment by JesseProminic** [comment]
:clipboard: **Procedures** (for [this](https://github.com/Moonshine-IDE/Moonshine-IDE/issues/1189#issuecomment-1424831261))

1. Install a development build for Bing's branch
2. Create a new Domino Visual Editor project
3. Create a page Right-Click > New > Domino Visual Editor Page
4. Change the Window Title to an appropriate value
5. Repeat 3 and 4 for the other test cases, with different WindowTitle
6. Unzip and copy this file into nsfs/nsf-moonshine/odp/Code:  https://github.com/Moonshine-IDE/Moonshine-IDE/issues/905#issuecomment-963428662
7. Build the database
8. Open the database in Moonshine
9. Use Actions > Open Page to open each page by name and confirm the window title.


Case | Resulting Window Title | Page
-- | -- | --
New Page | DEFAULT | :white_check_mark:
User enters a new simple window title | Preserve the user value | :heavy_exclamation_mark: Not preserved
User enters a new window title with special characters | Preserve the user value |  :heavy_exclamation_mark: Not preserved 
User enters a new window title with a formula | Preserve the user value |  :heavy_exclamation_mark: Not preserved
User enters an empty string as the formula | Preserve the user value - this is a strange case, but we can allow it |  :heavy_exclamation_mark: Not preserved
User clears the window title | Reset to DEFAULT | :white_check_mark:
Rename, default window title | Update window title to match new form name |  :heavy_exclamation_mark: Only opened by original name, window title not preserved

:memo: **Notes**
- When I created new pages on Moonshine, I could see them there but not on Notes. I was only able to open, Actions > OpenPage, the default page "HelloWorld." 
- When renaming the window titles, the first '_' was not preserved.

**Comment by JoelProminic** [comment]
Revisiting this issue, we found that there are two branches for this:
- `bug/invaild_default_value_for_windowsTitle`
- `features/issue-1082_IMOS_Convert`

The recent updates were made against `features/issue-1082_IMOS_Convert`.  I'm not clear whether the other branch was fully merged into this branch, but I didn't see anything to merge for Moonshine-IDE when I did a quick dry run test:


    % git checkout features/issue-1082_IMOS_Convert
    % git pull
    Already up to date.
    % git merge --no-commit --no-ff  bug/invaild_default_value_for_windowsTitle
    Already up to date.

Once we confirm that `features/issue-1082_IMOS_Convert` is the correct branch, we'll need to rerun some tests (expecially for the recent update for page and WindowTitle), and then merge this branch to `master` in order to close this issue.

**Comment by JoelProminic** [comment]
I noticed that `odp/Code/Agents/OpenPage.fa` was added to the template.   I think this makes sense as a way for the users to test the pages they create without uploading the database to a server.

Case | Resulting Window Title | Page
-- | -- | --
New Page | DEFAULT | Works if saved once.  Note the bug below on the raw template.
User enters a new simple window title | Preserve the user value | Confirmed
User enters a new window title with special characters | Preserve the user value | Confirmed
User enters a new window title with a formula | Preserve the user value | Confirmed
User enters an empty string as the formula | Blank title | BUG: *DEFAULT*
User clears the window title | DEFAULT | Confirmed
Rename, default window title | Update window title to match new form name | BUG:  Had to open page with old name, window title not updated
Rename, custom window title | Preserve original window title | BUG:  Had to open page with old name.

In the rename cases, I did not try to save the editor after the rename.  For the custom case, I had the editor closed during the rename.


For the "New Page" case, I tried this:
1. Create a new Domino Visual Editor project
2. Create a new page called TestDefault
3. Close the page without saving anything
4. Project > Build on Vagrant.  BUG: this fails with the below error

    : [INFO] java.util.concurrent.ExecutionException: java.lang.RuntimeException: Exception while importing element Pages/TestDefault.page
    ...
    : [ERROR] Caused by: java.lang.Exception: Exception importing Basic element Pages/TestDefault.page: An operator or semicolon was expected but none was encountered (line=19, column=6)
    : [ERROR] 	at org.openntf.nsfodp.compiler.ODPCompiler.importDxl(ODPCompiler.java:896)
    : [ERROR] 	at org.openntf.nsfodp.compiler.ODPCompiler.lambda$9(ODPCompiler.java:616)
    : [ERROR] 	... 33 more


The default page looks like this:

```
<?xml version='1.0'?>
<!DOCTYPE page>
<page name='TestDefault' xmlns='http://www.lotus.com/dxl'
 version='9.0' maintenanceversion='1.0' replicaid='85257C8A00383F9C' publicaccess='false'
 designerversion='8.5.3' renderpassthrough='true'>


<body><richtext>
<pardef id='1'/>
<par def='1'/>
<par def='1'>NOTE: This is a template for domino page.  DO NOT MODIFY THIS BY HAND.</par>
<par def='1'/>
<par def='1'/>
<par def='1'>Domino Visual Editor page:</par>
<par def='1'/>
<par def='1'/>
</richtext></body>
<item name="$WindowTitle">
    <formula>Domino Visual Editor Page</formula>
</item>
<item name='$$ScriptName' summary='false' sign='true'><text>TestDefault</text></item>

</page>
```

The default `$WindowTitle` needs to be surrounded by quotes.  I also expect this to match the file name.


```
    <formula>Domino Visual Editor Page</formula>
```

**Comment by feather812002** [comment]
@JoelProminic 
Hello, Joel I fixed the new page not save get compile error bug, and the User enters an empty string as the formula error bug.
But for Rename bug for pages,  I can't repeat your report bug on above,
I get same behavior when I  rename form's windowsTitle.
So ,make sure you work on the correct action , after I rename the page , I click the mainApplication , the windowsTitle get update.

**Comment by JoelProminic** [comment]
Case | Resulting Window Title | Page
-- | -- | --
New Page | DEFAULT | Title is "Domino Visual Editor Page"
User enters a new window title with a formula | Preserve the user value | BUG: the formula shows up in a double-quoted string
User enters an empty string as the formula | Blank title | Title is ""
User clears the window title | DEFAULT | Confirmed
Rename, default window title | Update window title to match new form name | BUG:  page not renamed in NSF
Rename, custom window title | Preserve original window title | 

I see the `$WindowTitle` is wrapped with `@Test('')`, which causes unexpected behavior for proper formulas.  I expect the user to use formulas for WindowTitle.  The problem I reported for the template yesterday should have been fixed in the template only: 

    <formula>@Text('@Text(@Now)')</formula>

For the rename case, the problem is in the compiled NSF.
1. Create a new page
2. Add a label and save
3. Rename the form
4. Check WindowTitle in the Editor - it is set properly
5. Build the database
6. Open the database and open the page with the new name.  BUG:  Page does not exist
7. Open the page with the old name.  BUG:  Page still exists with this name

**Comment by JoelProminic** [comment]
Tests from @JesseProminic 
![image](https://user-images.githubusercontent.com/24532731/223551788-882646d2-7eac-4003-81f8-70a35f2fa68a.png)
[NewVisualEditorProject6.zip](https://github.com/Moonshine-IDE/Moonshine-IDE/files/10913926/NewVisualEditorProject6.zip)

Testing with @JesseProminic's project, I get this error when trying to rename "renameTest1.page" to "renamerenameTest1.page" 

    : TypeError: Error #1089
    : 	at actionScripts.utils::DominoUtils$/dominoWindowTitleUpdate()
    : 	at actionScripts.plugin.rename::RenamePlugin/onFileRenamedRequest()
    : 	at actionScripts.plugin.rename::RenamePlugin/handleRenameFileViewClose()
    : 	at flash.events::EventDispatcher/dispatchEvent()
    : 	at feathers.controls::ScrollContainer/dispatchEvent()
    : 	at moonshine.plugin.rename.view::RenameFileView/submit()
    : 	at moonshine.plugin.rename.view::RenameFileView/renameButton_triggerHandler()
    : 	at flash.events::EventDispatcher/dispatchEvent()
    : 	at feathers.events::TriggerEvent$/dispatchFromMouseEvent()
    : 	at feathers.utils::PointerTrigger/pointerTrigger_target_clickHandler()
    :
    : Click here to Report a Bug


And then this error when trying to close the rename prompt

    : Error #3014
    : Error: Error #3014
    : 	at actionScripts.impls::IFileBridgeImp/moveTo()
    : 	at actionScripts.plugin.rename::RenamePlugin/onFileRenamedRequest()
    : 	at actionScripts.plugin.rename::RenamePlugin/handleRenameFileViewClose()
    : 	at flash.events::EventDispatcher/dispatchEvent()
    : 	at feathers.controls::ScrollContainer/dispatchEvent()
    : 	at moonshine.ui::TitleWindow/closeButton_triggerHandler()
    : 	at flash.events::EventDispatcher/dispatchEvent()
    : 	at feathers.events::TriggerEvent$/dispatchFromMouseEvent()
    : 	at feathers.utils::PointerTrigger/pointerTrigger_target_clickHandler()
    :
    : Click here to Report a Bug

I can't reproduce this with a new page.  @JesseProminic, did you test this on a fresh page today?

The failing page looks like this, which is not what I see for a fresh default Page that I created today:

```
<?xml version="1.0" encoding="utf-8"?>
<page name="renamerenameTest1" version="11.0" maintenanceversion="1.0" replicaid="85257C8A00383F9C" publicaccess="false" renderpassthrough="true" xmlns="http://www.lotus.com/dxl">
  <body>
    <richtext style="width:700px;height:700px;" class="flexVerticalLayout flexVerticalLayoutLeft flexVerticalLayoutTop" direction="Vertical" vdirection="Vertical">
      <pardef id="1016" dominotype="dominoHideDiv" keeptogether="true" keepwithnext="true" hide=""/>
      <par isNewLine="false">
        <run>
          <font color="system" size="12pt" style="normal"/>TestLabel
        </run>
      </par>
    </richtext>
  </body>
  <item name="$WindowTitle" sign="true">
    <formula>@Text('"renamerenameTest1"')</formula>
  </item>
  <item name="$$ScriptName" summary="false" sign="true">
    <text>renamerenameTest1</text>
  </item>
</page>
```

**Comment by JesseProminic** [comment]
@JoelProminic 

> I can't reproduce this with a new page.  Did you test this on a fresh page today?

Yes, I tested on a new project and page yesterday, tried it again this morning, and got the same error.

**Comment by JoelProminic** [comment]
@JesseProminic, I did a test on the HostMyApple machine.   This error just indicates that the build failed:

    : Conversion failed with exit code: 1
    : /opt/nsfodp/run_nsfodp.sh: line 27: [: : integer expression expected

If you scroll up, you can see the actual error:

    : [ERROR] !MESSAGE Application error
    : [ERROR] !STACK 1
    : [ERROR] java.util.concurrent.ExecutionException: java.lang.RuntimeException: Exception while importing element Code/actions/Shared Actions


This is a known issue that I also see on my workstation.  To fix it, delete `nsfs/nsf-moonshine/odp/Code/actions/Shared Actions`

![image](https://user-images.githubusercontent.com/24532731/224111208-5e5e12bb-4241-4650-93e2-bb7f6374d388.png)

**Comment by JesseProminic** [comment]
Case | Resulting Window Title | Page
-- | -- | --
New Page | DEFAULT | ✅ Domino Visual Editor Page
User enters a new window title with a formula | "this is test 1",  thisistest1, this is test 1 | ✅"this is test 1",  thisistest1, this is test 1
User enters an empty string as the formula | "" | ✅ Domino Visual Editor Page
User clears the window title | (The original page name was test1) | ✅ test1
Rename, default window title from Test1.page to renametest1.page|  "renametest1" | ✅ renametest1
Rename, custom window title from Test1.page to renametest1.page | "renametest1" to "rename test 1"|  ✅ rename test 1

<br class="Apple-interchange-newline">

**Comment by JoelProminic** [comment]
In my latest test (build 718), I found that the the `name` attribute was not updated until I saved the page after a rename:

![image](https://user-images.githubusercontent.com/24532731/224189362-560cd8c1-6cf0-4cde-af61-7d9bcdb23f54.png)

**Comment by feather812002** [comment]
@JoelProminic  I test this case again, I confirm it work fine with 
  - New Page without save action.
  - New Page insert a label and save it .
  - New page and rename it ,and save it .
  So, I think this case also is fine can be close and merge to master

**Comment by JoelProminic** [comment]
Revisiting the tests today:
1. Create a new Page - do not save
2. Rename the page.  BUG:  On clicking Rename in the prompt, I get an error on the console:

    : Error # 1009
    : TypeError: Error # 1009
    : 	at components.domino::DominoTable/fromXML()
    : 	at converter::DominoConverter$/itemFromXML()
    : 	at components.domino::Body/fromXML()
    : 	at converter::DominoConverter$/itemFromXML()
    : 	at converter::DominoConverter$/fromXML()
    : 	at converter::DominoConverter$/fromXMLOnly()
    : 	at utils::EditingSurfaceReader$/fromXMLAutoConvert()
    : 	at actionScripts.plugin.actionscript.as3project.importer::FlashDevelopImporter$/convertDomino()
    : 	at actionScripts.plugin.rename::RenamePlugin/onFileRenamedRequest()
    : 	at actionScripts.plugin.rename::RenamePlugin/handleRenameFileViewClose()
    : 	at flash.events::EventDispatcher/dispatchEvent()
    : 	at feathers.controls::ScrollContainer/dispatchEvent()
    : 	at moonshine.plugin.rename.view::RenameFileView/submit()
    : 	at moonshine.plugin.rename.view::RenameFileView/renameButton_triggerHandler()
    : 	at flash.events::EventDispatcher/dispatchEvent()
    : 	at feathers.events::TriggerEvent$/dispatchFromMouseEvent()
    : 	at feathers.utils::PointerTrigger/pointerTrigger_target_clickHandler()
    :
    : Click here to Report a Bug


Clicking the close button triggers a different error.  I have to close the prompt with the Cancel button (I don't see this behavior if I didn't trigger the first error):

    : Error #3014
    : Error: Error #3014
    : 	at actionScripts.impls::IFileBridgeImp/moveTo()
    : 	at actionScripts.plugin.rename::RenamePlugin/onFileRenamedRequest()
    : 	at actionScripts.plugin.rename::RenamePlugin/handleRenameFileViewClose()
    : 	at flash.events::EventDispatcher/dispatchEvent()
    : 	at feathers.controls::ScrollContainer/dispatchEvent()
    : 	at moonshine.ui::TitleWindow/closeButton_triggerHandler()
    : 	at flash.events::EventDispatcher/dispatchEvent()
    : 	at feathers.events::TriggerEvent$/dispatchFromMouseEvent()
    : 	at feathers.utils::PointerTrigger/pointerTrigger_target_clickHandler()
    :
    : Click here to Report a Bug

**Comment by JoelProminic** [comment]
Rerunning the last test, I confirmed:
- Renaming the page works with no error, both by hitting Enter and by clicking Rename
- The Cancel button works
- The close button works
- The $WindowTitle is updated properly
