### ISSUE TITLE
Navigation Between Tabs Broken on macOS Build

### ISSUE THREAD

**Issue by rat-moonshine** [Moonshine-IDE/Moonshine-IDE#1207]
Navigating between tabs by pressing keys seems to be broken in latest Development build on macOS. Windows build however worked in expected manner.

Tested on: macOS Ventura

The hot-keys are:
Ctrl+Tab = To return previously visited tab
Shift+Ctrl+Tab = To open list of opened tabs

**Comment by rat-moonshine** [comment]
Tested with AIR 50.2.2.1 on macOS Ventura - the key-capture still seems to be broken. `CTRL+Tab` not firing at all or captures by the `KeyboardEvent.KEY_DOWN`. In following cases I found the listener fires and don't fires:

Key/combination | Works
-----------------|---------------
CTRL+[non-Tab-key] | Yes
CTRL | Yes
Tab | Yes
CTRL+Tab | No

Since @JoelProminic reported that he found this working on Catalina or in earlier macOS, we might left it this way, or set a new key-combination for this functionality. I propose to shift to using `CTRL+R`, let me know what you think.

**Comment by JoelProminic** [comment]
I would prefer to save the `R` options for something else, if we aren't using them already.

The `ALT` options make more sense, but note that they are used for switching windows on Windows machines.    We could continue using the old shortcut for Windows.

**Comment by rat-moonshine** [comment]
The new key-combination on macOS for jumping between tabs are:

`ALT+Tab` - return to previous tab
`ALT+Shift+Tab` - opens opened tab list

Windows key-combinations did not changed and remains as was in previous. 

I moved this in current milestone as this a small fix.

**Comment by rat-moonshine** [comment]
Using `Tab` key seems to become problematic on macOS; Today, when I tested with the latest build, I see the combination with `Tab` key triggers occasionally in Moonshine. When the last fix applied, it was working appropriately, though.

I'm looking into this again.

**Comment by rat-moonshine** [comment]
We were seeing some problem on _macOS_ recently, here was my observation after some investigation:

- Previous tab toggle keyboard-shortcut do not works (`alt+Tab`)
- Opening tab listing/menu do not works (`alt+Shift+Tab`), opens occasionally 
- Selecting tab-item from opened listing/menu do not correctly selects tab
- Internal exception thrown when listing/menu dismissed with Escape 

Today I worked on this, and here's my test matrix after the fix:

Description | Works
--------------|----------------------
`alt+Tab` works simultaneously | Yes
`alt+Tab+Shift` opens tab-menu every time, when there multiple tabs are opened | Yes
Tab properly selects based on the selection in tab-menu | Yes
Dismissing the tab-menu do not cause any internal exception anymore | Yes

These can be tested in a new Development build.

**Comment by piotrzarzycki21** [comment]
@rat-moonshine Take a look please on bamboo. Build on Actions are failing, so there is good chance it's failing there as well.

**Comment by rat-moonshine** [comment]
Thank you, for mentioning @piotrzarzycki21 . I see a reference left of a non-existing method. This is now fixed, re-build started on Bamboo.

**Comment by rat-moonshine** [comment]
Description | Works (macOS)
----------|-----------------
Opens tab-menu every time, when there multiple tabs are opened | With alt+Shift+Tab  - Yes

I was in impression that it's working correctly, based on my tests earlier; But it appears to be broken probably because latter changes. I commit a fix again, this should work now accordingly, in newer build.

**Comment by JoelProminic** [comment]
When I tested earlier today, I found that if I closed the `Alt-Shift-Tab` menu with `Esc`, the menu temporarily did not open again with `Alt-Shift-Tab` .   This was fixed with the latest build.

I am seeing that `Alt-Tab` fails to work in some edge cases like this:
- Application has just opened, so there is no previous tab
- Closing tabs

This feature seems to be working well with the standard use cases though, so I don't want to spend too much more time on it for this release.

**Comment by rat-moonshine** [comment]
> I am seeing that Alt-Tab fails to work in some edge cases like this:
> 
> Closing tab

While investigating the said scenario, I noticed that selected-tab index incorrectly changed after a tab-close event, i.e. in following screen selected index is 3:

![image](https://github.com/Moonshine-IDE/Moonshine-IDE/assets/24370870/d07a7b22-8172-4170-8cb8-285c98c3e4a9)

When a _previous_ non-selected tab closed, i.e. 1st, it was expected that the tab with title "em202.tph" remain selected, but selected-index changed to:

![image](https://github.com/Moonshine-IDE/Moonshine-IDE/assets/24370870/af5a9831-2c4e-4e1e-8ba6-69509935f678)

This is now fixed. 

However, in similar situation when previous-tab toggle happens, I'm a bit unsure how we wants to handle it. Example, if the last-visited tab is closed, and user tries to jump to previous-tab, what would be preferable?
1. Select next or previous tab of last-visited tab that being closed
2. Do nothing

**Comment by rat-moonshine** [comment]
> However, in similar situation when previous-tab being closed and tab-toggle happens, I'm a bit unsure how we wants to handle it. 

I looked into how other IDEs function in this case, i.e. IntelliJ, FB; and adjusted tab-jump logic to closely match them. This should be good now. 

Please, report any unexpected problem if may erupt.

**Comment by rat-moonshine** [comment]
Hopefully, the only non-working thing, that we found earlier was:
1. Open tab A from sidebar
2. Open tab B from sidebar
3. Try `alt+Tab`
4. Nothing changed (Bug)

This behaviour is now rectified, and previous tab jump works against newly opened tabs.

**Comment by JoelProminic** [comment]
I did some tests with the latest build, and I don't see any problems with opening new tabs now.  I'm closing this issue.
