### ISSUE TITLE
Tibbo Basic Support (Progress Towards LotusScript Support)

### ISSUE THREAD

**Issue by JoelProminic** [Moonshine-IDE/Moonshine-IDE#1211]
@rat-moonshine, we would like to revisit the [Tibbo Basic support](https://github.com/Moonshine-IDE/Moonshine-IDE/tree/tibbo-basic) that @joshtynjala started on back in February 2023.

From @JustinProminic:

>Many Notes/Domino projects depend upon LotusScript, which is a variant of BASIC.
>
>CollabSphere.org 2023 is approaching and I need to submit a session abstract this week.
>
>I think it is due on Friday.
>
>
>Is there any way you can get a working Tibbo Basic project in Moonshine merged to the main Development branch?
>
>Josh I think already has most of this working.
>
>
>If so, then we might be able to get a DXL import or NSFODP working to show a basic LotusScript agent being imported from Moonshine into an NSF.
>
>That would be a nice feature to show off at CollabSphere if we decide to -- although we would of course tag it as very early preview / alpha code quality since we haven't done much with it.

>Lets start with trying to get Tibbo Basic to work, before we worry about LotusScript specifically.
>
>Here is where you can find some Tibbo Basic samples:
>
>https://tibbo.com/support.html
>
>
>https://tibbo.com/programmable/applications.html
>
>
>As for LotusScript, it will be more complex because none of the examples will compile until we can figure out how to capture the definitions of the Notes/Domino core API in LotusScript->Tibbo Basic.
>
>So for LotusScript, we could just focus on editing it and letting the NSFODP compiler report the issues.
>
>
>
>Domino Designer has a lot of example LotusScript code.
>
>Open Domino Designer on Windows, go to Help->Help Contents
>
>Then click on any of these:
>
>
>
>
>
>Then find ones with Examples like this:
>
>
>
>
>The goal should be for  Moonshine IDE to be able to at least edit code like you see on the right.
>
>
>Here are more examples of LotusScript code.
>
>https://www.openntf.org/main.nsf/project.xsp?r=project/LotusScript%20Gold%20Collection
>
>https://genesis.directory/apps/lsgold

The LotusScript documentation is also [available online](https://help.hcltechsw.com/dom_designer/12.0.2/basic/H_4_LOTUSSCRIPT_NOTES_CLASSES_REFERENCE.html) ([example](https://help.hcltechsw.com/dom_designer/12.0.2/basic/H_EXAMPLES_NOTESAGENT_CLASS.html))

**Comment by rat-moonshine** [comment]
The branch is now merged in `master` and can be accessed as v3.3.5.

However, I'm not able to run a Tibbo Basic project language-server during my tests. I knows very little on the current state of this development. 

I saw following error/warning on console, when tried to open a `.tbs` file on editor:

`:  Tibbo Basic language server exited unexpectedly. Close the NewTibboBasicProject project and re-open it to enable code intelligence.`
(https://github.com/Moonshine-IDE/Moonshine-IDE/blob/master/ide/MoonshineDESKTOPevolved/src/actionScripts/plugins/tibbo/TibboBasicLanguageServerManager.as#L277)

@joshtynjala I understand you probably taken by other tasks which are in more priority, can you give some details at least so we can have some idea on current state of this development (?) Or, if the above error was already a known problem, or we can make this work somehow (?) Please, advise.

**Comment by joshtynjala** [comment]
As I recall, everything should have been in a working state when I committed, so I don't know why it would be exiting unexpectedly. Maybe stdout/stderr from Node.js will have some clues.

**Comment by rat-moonshine** [comment]
Thank you, for responding on that @joshtynjala .

I remember I only required to fixed few calls in `TibboBasicLanguageServerPlugin` to make the application compile - it appears that the calling class once a static methods' class, later changed to singleton design. (https://github.com/Moonshine-IDE/Moonshine-IDE/commit/6c1269067f73dc12227df828b5af4fbd760552dd) This should not break the language server working.

As you suggested, I looked into stdError and I see I missed-out these outputs:

```
// first occurrence 

: Tibbo Basic language server workspace root: /Users/devsena/Desktop/Running Tasks/NewTibboBasicProject
: (node:3404) [DEP0128] DeprecationWarning: Invalid 'main' field in '/Users/devsena/Documents/DevareaLocal/ProminicGIT/Moonshine-IDE/ide/MoonshineDESKTOPevolved/bin-debug/elements/tibbo-basic-language-server/node_modules/antlr4/package.json' of 'src/antlr4/index.js'. Please either fix that or report it to the module author
: (Use `node --trace-deprecation ...` to show where the warning was created)
: (node:3404) Warning: Accessing non-existent property 'INVALID_ALT_NUMBER' of module exports inside circular dependency
: (node:3404) Warning: Accessing non-existent property 'INVALID_ALT_NUMBER' of module exports inside circular dependency


// second occurence 

: node:internal/errors:477
:     ErrorCaptureStackTrace(err);
:     ^
: TypeError [ERR_INVALID_ARG_TYPE]: The "path" argument must be of type string. Received undefined
:     at new NodeError (node:internal/errors:387:5)
:     at validateString (node:internal/validators:121:11)
:     at Object.join (node:path:1172:7)
:     at TibboBasicPreprocessor.getFilePath (/Users/devsena/Documents/DevareaLocal/ProminicGIT/Moonshine-IDE/ide/MoonshineDESKTOPevolved/bin-debug/elements/tibbo-basic-language-server/lib/TibboBasicPreprocessor.js:41:33)
:     at TibboBasicPreprocessor.parseFile (/Users/devsena/Documents/DevareaLocal/ProminicGIT/Moonshine-IDE/ide/MoonshineDESKTOPevolved/bin-debug/elements/tibbo-basic-language-server/lib/TibboBasicPreprocessor.js:63:25)
:     at validateTextDocument (/Users/devsena/Documents/DevareaLocal/ProminicGIT/Moonshine-IDE/ide/MoonshineDESKTOPevolved/bin-debug/elements/tibbo-basic-language-server/lib/TibboBasicLanguageServer.js:215:26)
:     at /Users/devsena/Documents/DevareaLocal/ProminicGIT/Moonshine-IDE/ide/MoonshineDESKTOPevolved/bin-debug/elements/tibbo-basic-language-server/lib/TibboBasicLanguageServer.js:86:13
:     at new Promise (<anonymous>)
:     at Timeout._onTimeout (/Users/devsena/Documents/DevareaLocal/ProminicGIT/Moonshine-IDE/ide/MoonshineDESKTOPevolved/bin-debug/elements/tibbo-basic-language-server/lib/TibboBasicLanguageServer.js:85:15)
:     at listOnTimeout (node:internal/timers:559:17) {
:   code: 'ERR_INVALID_ARG_TYPE'
: }
```

**Comment by rat-moonshine** [comment]
Hello @joshtynjala , I was wondering if you had a chance to look into [this](https://github.com/Moonshine-IDE/Moonshine-IDE/issues/1211#issuecomment-1624734863) (?)

**Comment by joshtynjala** [comment]
I found that I was able to open an existing project that I had created previously. I determined that there was one difference between the project template and one of the files in my existing project, so I fixed that, and now the language server launches.

**Comment by rat-moonshine** [comment]
Thank you, for looking into @joshtynjala .

I confirm the tooltip behaviour is showing language-server is working now:

![image](https://github.com/Moonshine-IDE/Moonshine-IDE/assets/24370870/a96fb63d-8f7b-4dec-9816-1e4dcc8bcfdf)

**Comment by JoelProminic** [comment]
This is a cosmetic issue, but I see we have three empty plugins for Tibbo Basic in the Setting page:

![image](https://github.com/Moonshine-IDE/Moonshine-IDE/assets/24532731/1af36b50-bbfa-4433-b349-ed325cd5e051)

Can we hide these from the Settings if they are not needed for now?   If we do need setting for these later, I'd prefer to keep these in a single tab unless we have a reason to handle this differently.

**Comment by joshtynjala** [comment]
These plugins may be added to the result from `IProjectBridgeImpl.getPluginsNotToShowInSettings`.

**Comment by rat-moonshine** [comment]
> These plugins may be added to the result from `IProjectBridgeImpl.getPluginsNotToShowInSettings`.

Done.

**Comment by joshtynjala** [comment]
> The language server doesn't start for me on macOS. 

Is there some kind of error message?

> but I didn't install any of the Tibbo Basic packages

I don't think you need to install any additional packages for the language server to work. I may be mistaken, but I never actually installed anything for Tibbo Basic on my machine.

> There are no build actions.

**Comment by joshtynjala** [comment]
> There are no build actions.

Considering that we're planning to completely replace TibboBasic with LotusScript, including modifying the language server, I didn't think that build actions for Tibbo Basic made much sense to implement.

**Comment by JoelProminic** [comment]
Yeah, if it were a simple command, it would make sense to add Build & Run for completeness.   I don't want to spend a lot of time of build commands or simulators when this is just a stepping stone for LotusScript support, though.   It does feel like this template has limited use for a user that is actually interested in Tibbo Basic, though.  Maybe we'll want to remove this template once we pivot to LotusScript.

Revisiting the language server, I see that it is working for me after I restarted Moonshine.  There were no errors on the console.   Some ideas for what could have caused this:
- I had other projects open before I created the project (FormBuilder, Java, and Royale).   I tried to retest this, though, and I found that the language server is still running
- The main.tbs file was empty when I first created the project.  However, this also did not cause a problem in my later test.
- Perhaps the language server took a long time to start the first time?   I'll see if I can reproduce this on a Windows test machine

**Comment by JoelProminic** [comment]
On a side note, `.tibboproj` files don't have file associations for Moonshine, and I can't open them from File > Open, either.   I can open the project with File > Open Project, though.

@rat-moonshine, is this something we can fix easily.   If it is a difficult/problematic fix, we can consider whether it is worth including.

**Comment by JoelProminic** [comment]
When I tested the Window build, the TibboBasic template was missing.  I checked Bamboo, and found that the Windows build has been failing since July 13 (Build 1404) with this error:

    13-Jul-2023 13:29:00 	CompileSWFWindowsSignedPackage:
    13-Jul-2023 13:29:00 	     [echo] # Signed Process Running - Preparing Bundle
    13-Jul-2023 13:54:29 	     [echo] # Signed Process Running - Signing Executable
    13-Jul-2023 13:54:33 	     [exec] Done Adding Additional Store
    13-Jul-2023 13:54:33 	     [exec] Successfully signed: DEPLOY/MoonshineDevelopmentEXE/MoonshineDevelopment.exe
    13-Jul-2023 13:54:33 	     [echo] # Signed Process Running - Praparing Installer
    13-Jul-2023 13:54:35 	     [exec] Command line defined: "VERSION=3.3.4"
    13-Jul-2023 13:54:35 	     [exec] Command line defined: "INSTALLERNAME=MoonshineDevelopment"
    13-Jul-2023 13:54:35 	     [exec] Command line defined: "APPID=com.moonshine-ide.development"
    13-Jul-2023 13:54:35 	     [exec] Command line defined: "TIMESTAMP=07/13/2023 10:22 AM"
    13-Jul-2023 13:54:35 	     [exec] Processing config: C:\Program Files (x86)\NSIS\nsisconf.nsh
    13-Jul-2023 13:54:35 	     [exec] Processing script file: "nsis-build.nsi" (ACP)
    13-Jul-2023 13:57:56 	     [exec] File: failed opening file "DEPLOY\MoonshineDevelopmentEXE\elements\tibbo-basic-language-server\node_modules\typescript\loc\lcl\CHS\TypeScriptLanguageService\Microsoft.CodeAnalysis.TypeScript.EditorFeatures.dll.lcl"
    13-Jul-2023 13:57:56 	     [exec] Error in script "nsis-build.nsi" on line 218 -- aborting creation process

**Comment by rat-moonshine** [comment]
> Revisiting the language server, I see that it is working for me after I restarted Moonshine.

You can also try closing and re-opening the `.tbs` file only.

> On a side note, .tibboproj files don't have file associations for Moonshine, and I can't open them from File > Open, either. I can open the project with File > Open Project, though.

I have added file-association for `.tbs`, `.tbh` and the `. tibboproj` configuration.

**Comment by rat-moonshine** [comment]
> When I tested the Window build, the TibboBasic template was missing. I checked Bamboo, and found that the Windows build has been failing since July 13 (Build 1404) with this error:

I see the path/file is well exists while I looked into the Bamboo Windows system build directory. 

It breaks on [line-218](https://github.com/Moonshine-IDE/Moonshine-IDE/blob/master/ide/MoonshineDESKTOPevolved/build/nsis-build.nsi#L218). We're not signing any file here so it's not any fail-signing like error as we used to see in macOS.

The command also do not read the files; One thing I suspect though - is it something of Windows path-length problem again (?)

For a comparison, a full Windows path is like this:
`D:\BAH\xml-data\build-dir\MS-MGWS-DJ2\M\ide\MoonshineDESKTOPevolved\build\DEPLOY\MoonshineDevelopmentEXE\elements\tibbo-basic-language-server\node_modules\typescript\loc\lcl\CHS\TypeScriptLanguageService\Microsoft.CodeAnalysis.TypeScript.EditorFeatures.dll.lcl`

**Comment by JoelProminic** [comment]
Yeah, I confirmed that this path was ~269 characters.  The default limit for Windows 10 is 256 (260?) characters.

To avoid this problem, I enabled [Win32 Long Paths in Local Group Policy Editor](https://www.thewindowsclub.com/how-to-enable-or-disable-win32-long-paths-in-windows-11-10) - I didn't see a disadvantage of doing this.   

I see that @joshtynjala also made some changes, so I'll check back on the build to see if it was successful.

**Comment by JoelProminic** [comment]
Unfortunately, I'm still getting the same error after the above update and restarting the server:

    21-Jul-2023 15:36:08 	     [exec] Processing script file: "nsis-build.nsi" (ACP)
    21-Jul-2023 15:39:27 	     [exec] File: failed opening file "DEPLOY\MoonshineDevelopmentEXE\elements\tibbo-basic-language-server\node_modules\typescript\loc\lcl\CHS\TypeScriptLanguageService\Microsoft.CodeAnalysis.TypeScript.EditorFeatures.dll.lcl"
    21-Jul-2023 15:39:27 	     [exec] Error in script "nsis-build.nsi" on line 218 -- aborting creation process
    21-Jul-2023 15:39:27 	
    21-Jul-2023 15:39:27 	BUILD FAILED

I have no problem referencing the full path from the command line, so I'm wondering if this is a different error.

**Comment by rat-moonshine** [comment]
I see a related discussion at [here](https://stackoverflow.com/questions/14202680/error-opening-file-during-installer-compilation). The error is identical to ours. However, the problem appears to have the path length >= 260.

I see an interesting suggestion in the discussion, though:

> Put all the files in C:\Temp or another local directory.

I'm not sure if this logical on Bamboo build system, and this also requires some restructuring in build-scripts.

**Comment by JoelProminic** [comment]
It looks like HCL is working on [VoltScript](https://paulswithers.github.io/blog/2022/06/10/voltscript-a-unique-opportunity) ([more](https://paulswithers.github.io/blog/2022/07/31/ls-classes-1) [links](https://github.com/HCL-TECH-SOFTWARE/volt-mx-ls-toolkit/blob/main/notes/Code/ScriptLibraries/NotesHttpRequestHelper.lss#L142)).  This may also be useful for completing the LotusScript support.  It looks like this is still in development/flux, though.  It may be useful for getting language constants, though.

@JustinProminic suggested using [QB64](https://en.wikipedia.org/wiki/QB64) for the builds.  Make sure to use https://qb64.com/  instead of the `.net` - this was apparently compromised.

**Comment by JoelProminic** [comment]
I don't think Bamboo will let me export the project outside the Bamboo home directory, so I have little control over the Bamboo build directory path.   I had already changed the build directory to `D:\BAH`, and I tried to change this to `D:\B` today (but that hasn't worked so far).   I could also possibly shave a couple characters off with the plan ID.

@joshtynjala, would it be a problem to rename `elements\tibbo-basic-language-server` to something like `elements\tbls`?   We could add a README.md to the directory if we are worried we will not recognize this directory later.

**Comment by joshtynjala** [comment]
Yeah, feel free to rename it. You'll need to change a constant with that path in `TibboBasicLanguageServerManager` too.

**Comment by rat-moonshine** [comment]
Renaming `tibbo-basic-language-server` to `tbls` seems to have fixed the problem. New builds are ready for a test. 

However, I didn't able the language server to work on Windows during my tests. I see I have NodeJS v14.7.0 installed. 

This is working fine on macOS, though. So I don't think there's any referencing problem, either. New directory installed as "elements/tbls".

**Comment by JoelProminic** [comment]
I tested on Windows, and I am seeing this behavior:
1. Create a Tibbo Basic project for the first time.  BUG:  the language server doesn't start
2. Reopen the editor.  Now the language server works
3. Close the editor and restart Moonshine
4. Open the .tbs file.  The language server works.  (NOTE:  the language server does not start for @rat-moonshine in this case)
5. Restart Moonshine without closing the .tbs editor
6. BUG:  When Moonshine reopens, the language server doesn't work.  I left this running for at least a minute in my test, but the language server did not start working.
7. Close and reopen the editor.  Now the language server works.

My theories are:
- For 1, the language needs some extra time to get started the first time.
- For 6, there is some race condition for how soon the editor opens relative to Moonshine starting.

**Comment by JoelProminic** [comment]
This should be good enough for now, so I am closing the issue
