### ISSUE TITLE
Problems with $TITLE After Form Rename

### ISSUE THREAD

**Issue by JoelProminic** [Moonshine-IDE/Moonshine-IDE#1218]
I noticed this problem when renaming the default form:
1. Create a new project
2. Open the default form
3. Add a label:  "TestRename"
4. Close the form
5. Rename the form to "TestRename"
6. Reopen the form
7. Add another label
8. Save
9. Check the Code tab.  BUG: $TITLE is set to the original name
10. Check the intermediate XML file.  BUG:  this also shows title="-originalname-"

The problem seems to be that `title` is not updated in the intermediate XML file.  `$TITLE` is correct until the form is saved again.

I couldn't reproduce this exact behavior on an additional form.  I did see a different problem in one of my tests, but I couldn't reproduce it - I'll update the issue if I can reproduce it later.

**Comment by JoelProminic** [comment]
After today's update, I see that the form name is wrapped in escaped quotes in `MainApplication@title` in the intermediate XML file:

```
  <MainApplication title="&quot;TestForm&quot;" windowsTitle="IlRlc3RGb3JtIg==" width="700" height="450" class="flexVerticalLayout flexVerticalLayoutLeft flexVerticalLayoutTop" wrap="false" direction="Vertical" vpostion="left">
```

So when I update the form editor, I see the `$TITLE` is updated with double-quotes:

```
  <item name="$TITLE">
    <text>"TestForm"</text>
  </item>
```

And then it shows up in the menu like this:
![image](https://github.com/Moonshine-IDE/Moonshine-IDE/assets/24532731/9e4a2b06-a629-4e17-b962-9064c9735246)

**Comment by JoelProminic** [comment]
Testing the merged code in the master branch, I see that the issue with extra double-quotes is fixed. 

However, I'm noticing a new issue where the `All By UNID_5cCRUD_5c...%form%` view is not updated to match the renamed form.  This is needed in order for the generated Java agents to work.    I confirmed this for a couple new projects and also for an additional form.

**Comment by feather812002** [comment]
@JoelProminic I just want to confirm do you want me replace the from name from the view file name ?
please notes, your case only work on the special  file name format of view (All By UNID_5cCRUD_5c...%form%),
 I don't think replace the form name from the view file name is good idea, it maybe cause other some chaos and conflict.
View have a big change contain other form name in product develop env, but it not belong to this form , and it also no any relationship with the rename form . it just maybe the view file name string contain the form name .
so replace it is wrong and not need.
But if you only want replace the  special  file name format (All By UNID_5cCRUD_5c...%form%.view) ,I think this is okay.
I will check the view file name , only the name full match your special format same with on above, it will be replace.
Let me know the details.

**Comment by JoelProminic** [comment]
Right, I only want to update these CRUD views for now - they need to remain linked to the Forms in order for the generated agents to work.  We had this working recently - I'm not sure when it broke.

We could consider doing something similar for other views, but we would need to address problems like:
- More complicated View Selection formulas that include the view name
- Form names that match substrings of view names - these cases could not potentially be related to the form names

**Comment by JoelProminic** [comment]
After testing during the meeting, I found that the additional properties for within the .view file were not updated.  @feather812002 made some fixes, but I am still seeing problems

Property | Updated | Escaped (`\` to `_5c`)
-- | -- | --
The file name | Yes | Yes
view.name  | Yes | BUG:  Yes.  This breaks the view name in HCL Notes
Selection formula | Yes | No (correct)
New action (unescaped) | BUG:  This is updated to the view name instead of the form name | BUG:  Yes.  This breaks the New button

![image](https://github.com/Moonshine-IDE/Moonshine-IDE/assets/24532731/c9468399-f64d-46dc-8b56-7c2ee8853b98)

Example:  Renamed to "TestAnotherRename"
```
<view name="All By UNID_5cCRUD_5cTestAnotherRename" showinmenu="false" noreplace="true" publicaccess="false" designerversion="8.5.3" unreadmarks="none" onopengoto="lastopened" onrefresh="displayindicator" headers="beveled" opencollapsed="false" showresponsehierarchy="true" showmargin="true" shrinkrows="false" extendlastcolumn="false" showhierarchies="false" unreadcolor="black" rowlinecount="1" headerlinecount="1" rowspacing="1" bgcolor="white" totalscolor="black" headerbgcolor="white" boldunreadrows="false" evaluateactions="false" allownewdocuments="false" allowcustomizations="true" hidemarginborder="false" marginwidth="0px" marginbgcolor="white" uniquekeys="false">
  
  <code event="selection">
    
    
    <formula>SELECT "TestAnotherRename" = Form</formula>
  </code>
  
  <actionbar bgcolor="#f0f0f0" bordercolor="black">
    
    <actionbuttonstyle bgcolor="#f0f0f0"/>
    
    <font color="system"/>
    
    <border style="solid" width="0px 0px 1px"/>
    
    <action title="New">
      
      <code event="click">
        
        
        <formula>@Command([Compose]; "All By UNID_5cCRUD_5cTestAnotherRename")</formula>
```

**Comment by feather812002** [comment]
@JoelProminic if my memory is correct , we already restrict the  "/"  and "\" in form name , so in here, why we need test the Escaped (\ to _5c) on form name ?


- I already fix the view name from "_5c" to "\"
- And fix the actionbar formula to form name .

**Comment by feather812002** [comment]
@JoelProminic 
And on the last Test  , I confirm it work fine on your list test case, and please don't forget add at least one field into the form , otherwise, you will got a Document not link or invaild error when you click the "New" action button or Create a new document from the form menu list.

**Comment by JoelProminic** [comment]
I tested the latest build, and this looks good:

Property | Updated | Escaped (`\` to `_5c`)
-- | -- | --
The file name | Yes | Yes
view.name  | Yes | No
Selection formula | Yes | N/A (this is the form name)
New action (unescaped) | Yes | N/A (this is the form name)

**Comment by JoelProminic** [comment]
I confirmed the updates on the master branch with Moonshine Development 3.3.4, build 3085.
