### ISSUE TITLE
Create a New Shared Column from a View

### ISSUE THREAD

**Issue by JoelProminic** [Moonshine-IDE/Moonshine-IDE#1219]
@feather812002 started implementing an option to create a shared column from a view as part of #1216.   There were more design decisions to make for this feature than I expected, so I have moved it to a separate issue.

After our discussion here is the design I would like to go with:
1. User creates a column and edits it as desired
2. Right-Click > Convert to Shared Column.  I would expect this to affect the column that was right-clicked rather than the selected column, but 3c is available if the user gets an unexpected column.
3. Open the New Shared Column prompt.  The name is populated with the Header text
3a.  If the user is satisfied with the name, and there is no duplicate (indicated with a warning in the prompt), they can just click create
3b.  The user can change the name if desired.  Besides the duplicate case, they may want to organize the shared columns more
3c. The user could also cancel the prompt, which would cancel the operation.  This would also help prevent misclicks
4. If the shared column is created, replace the column in the current form.   I'm thinking the shared column editor should *not* be opened automatically in this case.  The user can click the "Edit" button if they do want to make changes, but I would expect the user to be done editing the column in step 1 with this procedure.   I would also suggest that the view be updated in-memory and flagged as edited, rather than updating the files.  The user could then close the tab to "cancel" the local column updates (but the shared column would still exist).

**Comment by JoelProminic** [comment]
Some other designs that we discussed, for reference.

I originally was thinking of this design:
1. Right-Click > New Shared Column
2. Moonshine opens New Shared Column prompt.  User fills this out
3. The Shared Column is created, and is automatically appended to the open view.  The Shared Column editor opens 
4. User can edit the shared column as desired.

This could be a convenient feature, but converting an existing column is more flexible.

@feather812002 originally implemented this design:
1. User creates a column and edits it as desired
2. `Right-Click > Create a new shared column from selected column`
3. The new shared column is created using the Header Text as the file and name.  If the name already exists, show an error.
4. The column still shows up as a normal column in the original view
5. Remove the current column
6. Add the shared column, and move it to the expected solution

Step 3 saves a click for the simplest case, but it also blocks some cases, which would take more clicks to work around.  There may be some cases where the user doesn't want to automatically replace the column in step 4, but the user can do the same thing by closing the view without saving  in the proposed process.

**Comment by feather812002** [comment]
@JoelProminic 
I already done this on the selected column , but it not work to the right click column until now .
because for now we selected column hight light it and all code logic work around the selected column , 
if you want the mouse over and right click target column as the work column , it need more refactory the logic at now 
at least it need detect and calculation the current right click column when you right-click mouse on some column.

and about the 4 step,  the auto updated in-memory and flagged as edited,but please don't click the "Code" tab in the visual editor, because when you click the "Code", the logic will save the update memory column object into local file.
So, if you not save and not click the "Code" tab, the local file will not update for new shared column convert progerss.

**Comment by JoelProminic** [comment]
I created a new issue, #1220 to add a proper warning for duplicate file names.

In addition, I found that the Create button was disabled on in the button initially, even if the name was not a duplicate.   I could fix this by making a change an then reverting to the original name.
![image](https://github.com/Moonshine-IDE/Moonshine-IDE/assets/24532731/6f07da45-cee3-4a37-8200-b1fd1542e6d1)

For the Code tab, @feather812002 confirmed that for Forms, the Code tab is generated in-memory rather than updating the .form or intermediate XML file.   I would like views to work the same way.   The Code tab should not work as a save button.

**Comment by JoelProminic** [comment]
This looks good in my tests:

Case | Shared Column Created | View Updated
-- | -- | --
Simple Column | Confirmed | Confirmed
Duplicate | Confirmed (after different name is selected) | Confirmed
Nested column | Confirmed | Confirmed

Note that there is a major issue with saving the subforms reported [here](https://github.com/Moonshine-IDE/Moonshine-IDE/issues/1216#issuecomment-1738119833)
