### ISSUE TITLE
Selection Discrepancy for Column Delete

### ISSUE THREAD

**Issue by JoelProminic** [Moonshine-IDE/Moonshine-IDE#1221]
I see that when I use the Right-Click > Delete action for a column the selected column is deleted rather than the column I right clicked on:
1. Open/Create a view
2. Add a column
3. Select the first column
4. Right-click > Delete on the last column
5. The first column is deleted instead.

I expect the last column to be deleted in this case.  

Some options if we want to make this more clear:
1. Update the selected column on right-click.  We should consider if this has other effects
2. Show a confirmation prompt with the column title.  This would also add some protection in case th user was trying to click another action.

I also see this behavior
1. Open/create a View
2. Add two columns
3. Select the last column and run Right-click > Delete.  The column is deleted, and the selection moves to the placeholder space to the right.
3. Right-click > Delete the last column without changing the selection.  I get this error:

: Index '-1' specified is out of bounds.
: RangeError: Index '-1' specified is out of bounds.
: 	at mx.collections::ArrayList/removeItemAt()
: 	at view::DominoViewMockVisualEditor/removeColumn()
: 	at flash.display::NativeMenu/display()
: 	at flash.ui::ContextMenu/display()
: 	at flash.display::InteractiveObject/onContextMenuEvent()
:
: Click here to Report a Bug

UPDATE:  Changes in branch `features/issue-1221-selection-descrepancy-for-column-delete`

**Comment by feather812002** [comment]
@JoelProminic 
I fixed this , please check new branch features/issue-1221-selection-descrepancy-for-column-delete
I already commit this update to that branch.

**Comment by JoelProminic** [comment]
@feather812002 updated the logic to delete the column that is right-clicked (no prompt or selection change).   This feels intuitive to me, and the logic worked well in my tests

Test | Result
-- | --
Select a column, right-click > remove | Column removed
Select a column, right-click > remove a different columns | Column removed
Select a shared column, right-click > remove | Column removed
Select a shared column, right-click > remove a different columns | Column removed
First Column | Column removed
Last Column | Column removed
Right-click > Remove on placeholder column | BUG:  Column removed, throws error


    : Index '4' specified is out of bounds.
    : RangeError: Index '4' specified is out of bounds.
    : 	at mx.collections::ArrayList/removeItemAt()
    : 	at view::DominoViewMockVisualEditor/removeColumn()
    : 	at flash.display::NativeMenu/display()
    : 	at flash.ui::ContextMenu/display()
    : 	at flash.display::InteractiveObject/onContextMenuEvent()
    :
    : Click here to Report a Bug

**Comment by feather812002** [comment]
I fixed the remove the last empty column report error , test this on last update please,

Thanks.

**Comment by JoelProminic** [comment]
I confirmed this fix in my tests yesterday.
