### ISSUE TITLE
Default Value Missing in DXL

### ISSUE THREAD

**Issue by JoelProminic** [Moonshine-IDE/Moonshine-IDE#1223]
I have been noticing this issue while testing unrelated issues:
1. Create a new Form
2. Add a DateTime field
3. Set `@Now` as the Formula for defaultvalue
4. Save the form 
5. Build the database
6. Open the database in the Notes client and test the form.  BUG:  no default value is set
7. Open the DXL for the form.  BUG:  `@Now` is not found in the DXL.

We'll need to test this for other field types as well.

**Comment by feather812002** [comment]
Now, I let the default value work for all types on above format ,but maybe it will broken the ODP build.
I can't sure all types work on this format.
So, if you build fail with the default  value, let me know and post the correct dxl format from Designer, 
Then I will update it in next.

**Comment by feather812002** [comment]
![image](https://github.com/Moonshine-IDE/Moonshine-IDE/assets/8543391/d61e86f4-f7f5-401e-8061-a2c8d148ef52)
The client objects,contain 4 types, it look like not support for all object and type,
so , I think maybe we need more careful in here.

**Comment by JoelProminic** [comment]
To test, I built a form in Moonshine with default values for each of the core types.  The default values were populated as expected:
![image](https://github.com/Moonshine-IDE/Moonshine-IDE/assets/24532731/89f51069-1150-4a55-869b-922338ea9e38)

TODO:
- Test multivalue types
- Test more types
- Test the other Client Objects - this might be outside the scope of this issue.

**Comment by JoelProminic** [comment]
@feather812002, if you can run the missing test cases (and document your tests in the issue), that would be helpful.  You should be able to test like this:
1. Create a Form
2. Add a new field for each type, and set a default value
3. Save the Form
4. Build the database
5. Open the database in the local Notes client
6. Open the form, and check that the default values are populated.

If you are missing something you need to run these tests, let me know. I know you don't have access to Domino Designer, but that should not be required here.

**Comment by JoelProminic** [comment]
Testing from @feather812002

>09:11:33: I also test the default value , from my test, 
>most type should work fine
>![image](https://github.com/Moonshine-IDE/Moonshine-IDE/assets/24532731/4ef384e3-309a-4831-b2dd-c03b844cacd2)
>![image](https://github.com/Moonshine-IDE/Moonshine-IDE/assets/24532731/994af1ba-17ab-45bd-8d03-b1f19cf0c41a)
>
>09:12:10: I can open it with Designer and all default value show correct

**Comment by JoelProminic** [comment]
Here is a quick test of the each of primary field types in the Notes client.   I see the default values are showing like I expect, so this looks good:
![image](https://github.com/Moonshine-IDE/Moonshine-IDE/assets/24532731/1710b67e-c529-4d38-b1eb-26fdc45384d0)
