### ISSUE TITLE
Expand/Restore Editor Tab with Double-Click

### ISSUE THREAD

**Issue by JoelProminic** [Moonshine-IDE/Moonshine-IDE#1224]
@JustinProminic requested a behavior similar to Domino Designer and Eclipse to expand the editor tab on double click:
1. Double-click a tab
2. Collapse/hide the console and sidebar so that the editor tab fills the full window
3. Double-click a tab again
4. The console and sidebar are restored to the original size.

If it is easy, we would like to have a similar behavior for the Console or Problems tabs in the bottom section.  Double-click should hide/collapse the sidebar and editor window, and double-clicking again should restore them.

If Moonshine is restarted while an editor is in expanded mode, then the sidebar and console should be restored on startup.  This will give users a way to get back to the original layout if they accidentally double-click a tab and don't know how to get back.

UPDATE:
Branch:  features/issue_1224_fullscreen_tab_family
Build:  https://moonshine-ide.com/downloads/releases/dev/macos/branches/features/issue_1224_fullscreen_tab_family

**Comment by JoelProminic** [comment]
The base functionality for this is working consistently - I haven't seen it fail so far in my tests.   It should be fine to merge to master in this state.

However, the tabs can be slow to expand at times - I am noticing a 1-2 second delay in some cases.  This seems to get worse as I open more editor tabs.

**Comment by rat-moonshine** [comment]
This is now merged into `master`.

**Comment by JoelProminic** [comment]
After the update, I see:
1. Double click a tab
2. It expands after a short but noticeable delay
3. Click on another tab.  Nothing happens
4. Wait a second and try again.  The tab is selected

This makes sense with how the behavior is described above. I don't love this behavior, but it is less likely to trigger during normal usage, at least.   We'll see how this feels for in normal usage.

**Comment by rat-moonshine** [comment]
I'm aware of that delay on 4, and that's what I discussed in my [comment](https://github.com/Moonshine-IDE/Moonshine-IDE/issues/1224#issuecomment-1790486529) earlier - this may maybe noticeable. 

It's currently a problem to determine when the view actually updated on screen - using the known events.

Currently, known APIs returns their event as "display-updated" - when the actual display _on screen_ updated much later. It looks like the rendering engine of AIR doing something tricky behind, and the event APIs are not properly updates with the same. I'm still seeing for workaround to properly determine when the view _on screen_ - actually updates.

**Comment by JoelProminic** [comment]
This is working well in my latest tests.
