### ISSUE TITLE
Jump CMD+Click to specific framework class displays hash

### ISSUE THREAD

**Issue by piotrzarzycki21** [Moonshine-IDE/Moonshine-IDE#1233]
When I'm working with Apache Royale project and wanted to jump to some Royale class I'm getting hash instead source code. 
Moonshine version: **3.3.4 build 3131**
OS: **Mac OSX Sonoma 14.1.2**

https://github.com/Moonshine-IDE/moonshine-feathersui-text-editor/assets/24554795/83cf7279-3655-43dd-a260-7e4d38efc170

**Comment by joshtynjala** [comment]
Related to BowlerHatLLC/vscode-as3mxml@e6a7c4419c0bca4315b5bdeaaba4a3ca04fd2943. I can fix it soon.

Transferred to Moonshine-IDE repo, since it will be part of the AS3 language server manager rather than the TextEditor component.
