### ISSUE TITLE
Topicbox Integration

### ISSUE THREAD

**Issue by JoelProminic** [Moonshine-IDE/Moonshine-IDE#1237]
@JustinProminic created a Topicbox group for Moonshine-IDE.  He would like to get the Moonshine users involved in the group, so we would like to at least link this in Moonshine.   He would like to add this as part of the 3.3.5 release.

**Comment by JoelProminic** [comment]
The Moonshine TopicBox is here:  https://moonshine-ide.topicbox.com

We'd like to have a button for this on the Home page.  We want this button to stand out a little, but the Home page will need to be refactored before too long anyway.

We should point the users to the [Moonshine-discuss](https://moonshine-ide.topicbox.com/groups/ide) group.

**Comment by JoelProminic** [comment]
We would like a button in the Moonshine-IDE Home tab:
- Label:  View the Discussion
- URL:  https://moonshine-ide.topicbox.com/

**Comment by piotrzarzycki21** [comment]
This has been added as well.

**Comment by piotrzarzycki21** [comment]
Final labels: 

Moonshine.dev: "New web version features advanced Design View and AI at Moonshine.dev!"
TopicBox: "View the Moonshine user group discussion forum"
