### ISSUE TITLE
Workspace Dropdown Should Match Width of Control

### ISSUE THREAD

**Issue by JoelProminic** [Moonshine-IDE/Moonshine-IDE#1239]
We noticed this issue in the meeting today:
![image](https://github.com/Moonshine-IDE/Moonshine-IDE/assets/24532731/e0e903ac-cb42-446f-a177-5925ec691fd4)

The dropdown panel should match the width of the combobox control.  Since the control already expands to match the size of the sidebar, this would allow the user to make the list wider if needed.

**Comment by rat-moonshine** [comment]
So I see, we had a reason why we chose not to restrict the popup width based on its parent/drop-down list:

![image](https://github.com/Moonshine-IDE/Moonshine-IDE/assets/24370870/fca74549-2c33-4e4c-87d0-c2815207073c)

After today's update, it'll work conditionally:

When sidebar is small:

![image](https://github.com/Moonshine-IDE/Moonshine-IDE/assets/24370870/e3562e86-0a1e-4b3e-aab7-77c94e30f99e)

When sidebar has adequate width:

![image](https://github.com/Moonshine-IDE/Moonshine-IDE/assets/24370870/1be14987-e2d0-4ba7-afab-4bad674a4a02)

Please, check in latest build.

**Comment by JoelProminic** [comment]
Ah, it makes sense to have a minimum width for the panel.   Is this minimum width based on the longest workspace name?

![image](https://github.com/Moonshine-IDE/Moonshine-IDE/assets/24532731/7105187a-8fae-4572-8694-2e0f707c1d46)

I tested with different sidebar widths in today's build (on macOS), and this is working well
