### ISSUE TITLE
Deploy to Vagrant Server popup should have ability to edit launch url

### ISSUE THREAD

**Issue by piotrzarzycki21** [Moonshine-IDE/Moonshine-IDE#1242]
In **Deploy to Vagrant Server** popup we have **Example URL** link. User should have ability to change that link. 

<img width="608" alt="Screenshot 2024-01-29 at 14 18 41" src="https://github.com/Moonshine-IDE/Moonshine-IDE/assets/24554795/0bedafb9-86e6-4174-9cf3-54bd4b0450ad">

Link in **Example URL** is used to launch application once submission is successful. My proposition is to change that name to **Launch URL**

**Comment by Aszusz** [comment]
I tested it on macOS and it works

**Comment by JoelProminic** [comment]
FYI, I was planning on making improvements to `baseURL` in the Vagrant instance /info output so that this should be less necessary:  https://github.com/STARTcloud/hcl_roles/issues/1

**Comment by JoelProminic** [comment]
I did some tests, and I think this is a good feature even if I make improvements to `baseURL`. :
![image](https://github.com/Moonshine-IDE/Moonshine-IDE/assets/24532731/740ed094-a6e9-4bcd-9273-a002fe61bbb7)
![image](https://github.com/Moonshine-IDE/Moonshine-IDE/assets/24532731/eb8fb4df-d3d2-41c4-a178-b8977c2ad1ca)

I noticed that the application name is not populated in this case before js-debug.  Was this problem introduced with the change for this issue?

Some UI thoughts:
- Is the Change URL toggle necessary?  We could just give the user the URL as a text field and save a click
- If we do want to keep the "Change URL" button, I think the label should change when it is in edit mode.  Perhaps "Cancel" would make sense?
- The text field should expand to fit the panel, similar to Target Directory.

**Comment by piotrzarzycki21** [comment]
Good point @JoelProminic - I will remove "Change URL" - no need actually for additional steps.

**Comment by piotrzarzycki21** [comment]
I have committed following changes:
- "Change URL" has been removed
- Text field has been expanded to full width
- I have fixed lack of application name in default url

Next build should have all these changes.

**Comment by piotrzarzycki21** [comment]
@JoelProminic You can test this issue with newest build. Any additional improvements raise separate issue please.

**Comment by piotrzarzycki21** [comment]
This feature finally working. I'm closing it.

**Comment by JoelProminic** [comment]
This feature came up in #1217.   I see that it will automatically change the base URL to match automatically imported Vagrant instances, but manually created instances (i.e. "http://127.0.0.1:8095" for nsf-converter-portal) default to http://127.0.0.1:8080

Note that in the near future I hope to add a property to the `/info` page in the Vagrant instance that will supply a base URL, so we should be able to implement a more flexible solution with that.
