### ISSUE TITLE
Create full build process on GitHub Actions

### ISSUE THREAD

**Issue by Aszusz** [Moonshine-IDE/Moonshine-IDE#1250]

**Comment by JoelProminic** [comment]
For branch builds (mostly from @feather812002 and @rat-moonshine ), we would also need to use corresponding branches for the external projects, like MockupVisualEditor and VisualEditorConverterLib.  @Aszusz, do you have ideas on how to handle builds like this with GitHub actions?  We can discuss this more in the meetings next week if needed.

**Comment by JoelProminic** [comment]
In our last notarization attempt for Moonshine, we found that it [took about 13 minutes](https://github.com/Moonshine-IDE/Moonshine-IDE/issues/1251#issuecomment-1984095134).  I'm not sure if the current notarization code @Aszusz is using has a timeout.

**Comment by JoelProminic** [comment]
The Bamboo builds are blocked at the moment, so we will need to bump the priority for this.  See [this comment](https://github.com/Moonshine-IDE/Moonshine-IDE/issues/1254#issuecomment-2344596089) for more info.

I'm adding this to the next milestone

**Comment by Aszusz** [comment]
This is test ready:
https://github.com/Moonshine-IDE/Moonshine-IDE/releases/tag/untagged-3bb50060b68e5abe7686
