### ISSUE TITLE
Moonshine Notarization Problem for 3.3.4 Release

### ISSUE THREAD

**Issue by rat-moonshine** [Moonshine-IDE/Moonshine-IDE#1251]
Reported by @JoelProminic 

-----------------------------

I finally got the details. It looks like this is a problem with some unsigned files:

Moonshine_Signed_NonSandbox.pkg/com.moonshine-ide.pkg Contents/Payload/Applications/Moonshine.app/Contents/Resources/elements/tbls/node_modules/node-notifier/vendor/mac.noindex/terminal-notifier.app/Contents/MacOS/terminal-notifier

Moonshine_Signed_NonSandbox.pkg/com.moonshine-ide.pkg Contents/Payload/Applications/Moonshine.app/Contents/Resources/elements/tbls/node_modules/fsevents/fsevents.node

2024-03-06 15:08:54.415 altool[48690:1038534942] No errors getting notarization info.

   RequestUUID: 01814084-07bc-4148-af06-27dacc05bfb5
          Date: 2024-03-06 19:06:10 +0000
        Status: invalid
    LogFileURL: https://osxapps-ssl.itunes.apple.com/itunes-assets/Enigma122/v4/99/99/59/999959df-censored-737b09/developer_log.json?accessKey=1709-censored-%2BRF%2FXuINqYYsvhVTKNSd0%3D
   Status Code: 2
Status Message: Package Invalid

-----

```
{
  "logFormatVersion": 1,
  "jobId": "01814084-censored-27dacc05bfb5",
  "status": "Invalid",
  "statusSummary": "Archive contains critical validation errors",
  "statusCode": 4000,
  "archiveFilename": "Moonshine_Signed_NonSandbox.pkg",
  "uploadDate": "2024-03-06T19:06:10Z",
  "sha256": "195df006-censored-a23bdf738",
  "ticketContents": null,
  "issues": [
    {
      "severity": "error",
      "code": null,
      "path": "Moonshine_Signed_NonSandbox.pkg/com.moonshine-ide.pkg Contents/Payload/Applications/Moonshine.app/Contents/Resources/elements/tbls/node_modules/node-notifier/vendor/mac.noindex/terminal-notifier.app/Contents/MacOS/terminal-notifier",
      "message": "The binary is not signed.",
      "docUrl": "https://developer.apple.com/documentation/security/notarizing_macos_software_before_distribution/resolving_common_notarization_issues#3087721",
      "architecture": "x86_64"
    },
    {
      "severity": "error",
      "code": null,
      "path": "Moonshine_Signed_NonSandbox.pkg/com.moonshine-ide.pkg Contents/Payload/Applications/Moonshine.app/Contents/Resources/elements/tbls/node_modules/node-notifier/vendor/mac.noindex/terminal-notifier.app/Contents/MacOS/terminal-notifier",
      "message": "The signature does not include a secure timestamp.",
      "docUrl": "https://developer.apple.com/documentation/security/notarizing_macos_software_before_distribution/resolving_common_notarization_issues#3087733",
      "architecture": "x86_64"
    },
    {
      "severity": "error",
      "code": null,
      "path": "Moonshine_Signed_NonSandbox.pkg/com.moonshine-ide.pkg Contents/Payload/Applications/Moonshine.app/Contents/Resources/elements/tbls/node_modules/node-notifier/vendor/mac.noindex/terminal-notifier.app/Contents/MacOS/terminal-notifier",
      "message": "The executable does not have the hardened runtime enabled.",
      "docUrl": "https://developer.apple.com/documentation/security/notarizing_macos_software_before_distribution/resolving_common_notarization_issues#3087724",
      "architecture": "x86_64"
    },
    {
      "severity": "error",
      "code": null,
      "path": "Moonshine_Signed_NonSandbox.pkg/com.moonshine-ide.pkg Contents/Payload/Applications/Moonshine.app/Contents/Resources/elements/tbls/node_modules/fsevents/fsevents.node",
      "message": "The binary is not signed.",
      "docUrl": "https://developer.apple.com/documentation/security/notarizing_macos_software_before_distribution/resolving_common_notarization_issues#3087721",
      "architecture": "x86_64"
    },
    {
      "severity": "error",
      "code": null,
      "path": "Moonshine_Signed_NonSandbox.pkg/com.moonshine-ide.pkg Contents/Payload/Applications/Moonshine.app/Contents/Resources/elements/tbls/node_modules/fsevents/fsevents.node",
      "message": "The signature does not include a secure timestamp.",
      "docUrl": "https://developer.apple.com/documentation/security/notarizing_macos_software_before_distribution/resolving_common_notarization_issues#3087733",
      "architecture": "x86_64"
    },
    {
      "severity": "error",
      "code": null,
      "path": "Moonshine_Signed_NonSandbox.pkg/com.moonshine-ide.pkg Contents/Payload/Applications/Moonshine.app/Contents/Resources/elements/tbls/node_modules/fsevents/fsevents.node",
      "message": "The binary is not signed with a valid Developer ID certificate.",
      "docUrl": "https://developer.apple.com/documentation/security/notarizing_macos_software_before_distribution/resolving_common_notarization_issues#3087721",
      "architecture": "arm64"
    },
    {
      "severity": "error",
      "code": null,
      "path": "Moonshine_Signed_NonSandbox.pkg/com.moonshine-ide.pkg Contents/Payload/Applications/Moonshine.app/Contents/Resources/elements/tbls/node_modules/fsevents/fsevents.node",
      "message": "The signature does not include a secure timestamp.",
      "docUrl": "https://developer.apple.com/documentation/security/notarizing_macos_software_before_distribution/resolving_common_notarization_issues#3087733",
      "architecture": "arm64"
    }
  ]
}
```

[2024_03_06__notarization_log.json](https://github.com/Moonshine-IDE/Moonshine-IDE/files/14523108/2024_03_06__notarization_log.json)

**Comment by Aszusz** [comment]
> This tbls/node_modules seems to be new to Moonshine, and was not included in signing steps of Moonshine-IDE.

I did some git search and I think this commit:
https://github.com/Moonshine-IDE/Moonshine-IDE/commit/63a41ae21286feded4a760323fec531f4cdb06b7
touches all of the failing paths:
https://github.com/Moonshine-IDE/Moonshine-IDE/blob/master/ide/MoonshineSharedCore/src/elements/tbls/node_modules/node-notifier/vendor/mac.noindex/terminal-notifier.app/Contents/MacOS/terminal-notifier

But it was 8 months ago and I don't know why this is failing all of a sudden
@rat-moonshine let me know if I can help in any way

**Comment by rat-moonshine** [comment]
Usually we don't run notarization unless we prepare for an RC/release build. 

I see the last stable release is on Oct 18, 2022; So it makes sense that notarization process may haven't run for a long time.

**Comment by rat-moonshine** [comment]
For a comparison I gave a notarization test on MSDKI - and that went well. So this not an isolated server/host issue with Apple, or at Bamboo.

**Comment by JoelProminic** [comment]
As @Aszusz reported, these files seem to be related to @joshtynjala's work for Tibbo Basic (#1211).  If we don't have any particular concerns for these files, we should just sign them individually for now.

**Comment by JoelProminic** [comment]
@rat-moonshine cleared the notarization errors.  I also needed to [update the timeout](https://github.com/Moonshine-IDE/Apple-Notarization-Ant/blob/49beed19f7c45ae283318ee7258320ffe3ab2a5c/CheckNotarizationStatus.sh#L12) for the notarization script - it has been taking about 13 minutes for this build.   I'll continue with the release process.
