### ISSUE TITLE
moonshine.dev Link and Promotion

### ISSUE THREAD

**Issue by JoelProminic** [Moonshine-IDE/Moonshine-IDE#1254]
We would like to start promoting moonshine.dev from Moonshine
- "Try the new web version of Moonshine-IDE"
- Summary of the features
- Link to moonshine.dev home page

**Comment by piotrzarzycki21** [comment]
@JoelProminic I have added this to Moonshine. I had to change something in [MoonshineGUICore](https://github.com/Moonshine-IDE/Moonshine-IDE/tree/master/ide/MoonshineGUICore), but for some reason I cannot push MoonshineGUICore.swc to repository - Is that file being build on Bamboo ? Could you please take a look if build is working actually for Mac and Windows after my push. Thanks!

**Comment by piotrzarzycki21** [comment]
@JoelProminic I'm positive that Moonshine is failing on bamboo, because I didn't get any update on development version after my push. If you could take a look would be great.

**Comment by JoelProminic** [comment]
@piotrzarzycki21, I found that both the macOS and Windows remote agents were down.   I'm seeing other problems as well, so I'm working to fix this.

**Comment by JoelProminic** [comment]
Unfortunately, this is failing because of some network changes  that restrict outbound access for the Bamboo server.  I was able to work around this for the GitHub repositories, but now I'm running into trouble for haxelib

macOS:
```
09-Sep-2024 10:36:43 	InstallHaxeDependencies:
09-Sep-2024 10:36:43 	     [echo] Installing Haxe Libraries
09-Sep-2024 10:39:14 	     [exec] Error: Failed with error: Failed to connect on lib.haxe.org:443
```

Windows
```
11-Sep-2024 22:17:20 	InstallHaxeDependencies:
11-Sep-2024 22:17:20 	     [echo] Installing Haxe Libraries
11-Sep-2024 22:18:05 	     [exec] Error: Failed with error: Blockin
```

At this point, we want to focus on getting the GitHub actions working to get off of the legacy Bamboo builds.  If the GitHub actions are going to take a while, I could try to hack together a solution for Bamboo, but we don't want to invest more time in to the old build system.
