### ISSUE TITLE
Update Moonshine license to SSPL

### ISSUE THREAD

**Issue by piotrzarzycki21** [Moonshine-IDE/Moonshine-IDE#577]
We need to update Moonshine license to [SSPL](https://www.mongodb.com/licensing/server-side-public-license)

Each file should contains following header:

> /**
>  *    Copyright (C) 2016-present Prominic.NET, Inc.
>  *
>  *    This program is free software: you can redistribute it and/or modify
>  *    it under the terms of the Server Side Public License, version 1,
>  *    as published by MongoDB, Inc.
>  *
>  *    This program is distributed in the hope that it will be useful,
>  *    but WITHOUT ANY WARRANTY; without even the implied warranty of
>  *    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
>  *    Server Side Public License for more details.
>  *
>  *    You should have received a copy of the Server Side Public License
>  *    along with this program. If not, see
>  *    <http://www.mongodb.com/licensing/server-side-public-license>.
>  *
>  *    As a special exception, the copyright holders give permission to link the
>  *    code of portions of this program with the OpenSSL library under certain
>  *    conditions as described in each individual source file and distribute
>  *    linked combinations including the program with the OpenSSL library. You
>  *    must comply with the Server Side Public License in all respects for
>  *    all of the code used other than as permitted herein. If you modify file(s)
>  *    with this exception, you may extend this exception to your version of the
>  *    file(s), but you are not obligated to do so. If you do not wish to do so,
>  *    delete this exception statement from your version. If you delete this
>  *    exception statement from all source files in the program, then also delete
>  *    it in the license file.
>  */

As part of the issue we need to review each library which we are using and it is listed in the console during initial Moonshine launching.

**Comment by rat-moonshine** [comment]
Please make sure if we need this line:

> as published by MongoDB, Inc.

**Comment by piotrzarzycki21** [comment]
> Please make sure if we need this line, or we need to refer MondoDB to describe SSPL (although, I'm not sure if this license type is something intellectual to MondoDB or not):
> 
> > as published by MongoDB, Inc.

We need someone from Legal sight in Prominic to answer that question. I don't have knowledge towards such things.

**Comment by piotrzarzycki21** [comment]
I would like to briefly change license for upcoming release. Following question arise: 

1. What should I put in [LICENSE.MD](https://github.com/prominic/Moonshine-IDE/blob/master/LICENSE.MD) file ? 
2. In license we have mention MongoDB what should be done with that if any ?

**Comment by JoelProminic** [comment]
MongoDB, Inc publishes the SSPL license, so this reference should not change.

We need to update LICENSE.MD to reference the SSPL license.  There is a link in the description above.

Third-party code may have different licenses.  We need to preserve these licenses.

**Comment by Aszusz** [comment]
Here's the tool I made and used for this in case anyone else needs it:
https://github.com/Moonshine-IDE/FileFilter

**Comment by piotrzarzycki21** [comment]
We have decided move this to next release.

**Comment by JoelProminic** [comment]
@Aszusz, you should proceed with this now.  The big Haxe migration merge is completed, so this is a good time.

**Comment by JoelProminic** [comment]
@Aszusz is planning to update to the new license over the weekend.

**Comment by JoelProminic** [comment]
We discussed this with @Aszusz, and this is ready to be closed
