### ISSUE TITLE
Add "Close Others" to context menu on tabs

### ISSUE THREAD

**Issue by joshtynjala** [Moonshine-IDE/Moonshine-IDE#610]
Similar to "Close All", except that the tab where the context menu was triggered remains open, and all of the others close.

**Comment by rat-moonshine** [comment]
This ready on a branch. Can be tested using Moonshine branch build (macOS).

**Comment by rat-moonshine** [comment]
This issue now merged into `master` for everyone's test.

**Comment by piotrzarzycki21** [comment]
It works good for me. There are some additions to consider:
1. Context menu should open when we click on "Getting Started" or "Home" tabs
2. "Getting Started" and "Home" shouldn't be closed when we use options - I'm not sure if this is make sense.

**Comment by rat-moonshine** [comment]
Usually I think, when user chose "Close Others" s/he wants to concentrate on only tab by removing any others. I personally expects the behaviour works this way when I chose "Close Others", it can be a preferential matter, though.

**Comment by joshtynjala** [comment]
When I choose Close Others, I expect all tabs to close, regardless of content, including Home and Getting Started. I want one tab open only.

**Comment by rat-moonshine** [comment]
Context-menu should show to any non-editor tabs now.

**Comment by JoelProminic** [comment]
I agree that Close Others should also be able to close Home and Getting Started.   This is how Close All works currently, and it is the behavior I would expect as a user.  These tabs can be reopened with View > Home and Help > Getting Started.

I did some tests with Close Others on macOS.  I tested it on the first, last, middle, and only tab, and I didn't see problems in any of these cases.   @piotrzarzycki21 , if you are satisfied with our reasoning for Close Others, we can close this issue.

**Comment by piotrzarzycki21** [comment]
> I agree that Close Others should also be able to close Home and Getting Started. This is how Close All works currently, and it is the behavior I would expect as a user. These tabs can be reopened with View > Home and Help > Getting Started.
> 
> I did some tests with Close Others on macOS. I tested it on the first, last, middle, and only tab, and I didn't see problems in any of these cases. @piotrzarzycki21 , if you are satisfied with our reasoning for Close Others, we can close this issue.

@rat-moonshine please close the issue.
