### ISSUE TITLE
Language Server Errors with 3.0.0 Release Candidate

### ISSUE THREAD

**Issue by JoelProminic** [Moonshine-IDE/Moonshine-IDE#728]
While attempting to test #725 on Windows, I found that I was getting errors for the language server.

I am on Windows 10, and I am using only the SDKs installed from Moonshine SDK Installer (I ran this on Sep 14).

![image](https://user-images.githubusercontent.com/24532731/94721964-39e1d080-031c-11eb-899c-11de9703795b.png)

When I create a new Flex Desktop project, I get this error.  I see that the activity bar continues to show "Starting Actionscript and MXML code intelligence":

    : Sep 30, 2020 12:50:46 PM org.eclipse.lsp4j.jsonrpc.RemoteEndpoint fallbackResponseError
    : SEVERE: Internal error: java.lang.reflect.InvocationTargetException
    : java.lang.RuntimeException: java.lang.reflect.InvocationTargetException
    : 	at org.eclipse.lsp4j.jsonrpc.services.GenericEndpoint.lambda$null$0(GenericEndpoint.java:67)
    : 	at org.eclipse.lsp4j.jsonrpc.services.GenericEndpoint.request(GenericEndpoint.java:120)
    : 	at org.eclipse.lsp4j.jsonrpc.RemoteEndpoint.handleRequest(RemoteEndpoint.java:261)
    : 	at org.eclipse.lsp4j.jsonrpc.RemoteEndpoint.consume(RemoteEndpoint.java:190)
    : 	at org.eclipse.lsp4j.jsonrpc.json.StreamMessageProducer.handleMessage(StreamMessageProducer.java:194)
    : 	at org.eclipse.lsp4j.jsonrpc.json.StreamMessageProducer.listen(StreamMessageProducer.java:94)
    : 	at org.eclipse.lsp4j.jsonrpc.json.ConcurrentMessageProcessor.run(ConcurrentMessageProcessor.java:113)
    : 	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
    : 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
    : 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
    : 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
    : 	at java.lang.Thread.run(Thread.java:748)
    : Caused by: java.lang.reflect.InvocationTargetException
    : 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    : 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    : 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    : 	at java.lang.reflect.Method.invoke(Method.java:498)
    : 	at org.eclipse.lsp4j.jsonrpc.services.GenericEndpoint.lambda$null$0(GenericEndpoint.java:65)
    : 	... 11 more
    : Caused by: java.lang.NoSuchMethodError: org.eclipse.lsp4j.Diagnostic.getCode()Lorg/eclipse/lsp4j/jsonrpc/messages/Either;
    : 	at com.as3mxml.vscode.utils.LanguageServerCompilerUtils.getDiagnosticFromCompilerProblem(LanguageServerCompilerUtils.java:488)
    : 	at com.as3mxml.vscode.ActionScriptServices.addCompilerProblem(ActionScriptServices.java:1674)
    : 	at com.as3mxml.vscode.ActionScriptServices.publishDiagnosticsForProblemQuery(ActionScriptServices.java:2091)
    : 	at com.as3mxml.vscode.ActionScriptServices.getProject(ActionScriptServices.java:1968)
    : 	at com.as3mxml.vscode.ActionScriptServices.checkProjectForProblems(ActionScriptServices.java:2002)
    : 	at com.as3mxml.vscode.ActionScriptServices.addWorkspaceFolder(ActionScriptServices.java:263)
    : 	at com.as3mxml.vscode.ActionScriptLanguageServer.initialize(ActionScriptLanguageServer.java:107)
    : 	... 16 more

I closed the project and restarted Moonshine, then I created a new Actionscript Desktop project, I get this error.  I see that the activity bar continues to show "Starting Actionscript and MXML code intelligence":

    : Sep 30, 2020 12:45:56 PM org.eclipse.lsp4j.jsonrpc.RemoteEndpoint fallbackResponseError
    : SEVERE: Internal error: java.lang.reflect.InvocationTargetException
    : java.lang.RuntimeException: java.lang.reflect.InvocationTargetException
    : 	at org.eclipse.lsp4j.jsonrpc.services.GenericEndpoint.lambda$null$0(GenericEndpoint.java:67)
    : 	at org.eclipse.lsp4j.jsonrpc.services.GenericEndpoint.request(GenericEndpoint.java:120)
    : 	at org.eclipse.lsp4j.jsonrpc.RemoteEndpoint.handleRequest(RemoteEndpoint.java:261)
    : 	at org.eclipse.lsp4j.jsonrpc.RemoteEndpoint.consume(RemoteEndpoint.java:190)
    : 	at org.eclipse.lsp4j.jsonrpc.json.StreamMessageProducer.handleMessage(StreamMessageProducer.java:194)
    : 	at org.eclipse.lsp4j.jsonrpc.json.StreamMessageProducer.listen(StreamMessageProducer.java:94)
    : 	at org.eclipse.lsp4j.jsonrpc.json.ConcurrentMessageProcessor.run(ConcurrentMessageProcessor.java:113)
    : 	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
    : 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
    : 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
    : 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
    : 	at java.lang.Thread.run(Thread.java:748)
    : Caused by: java.lang.reflect.InvocationTargetException
    : 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    : 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    : 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    : 	at java.lang.reflect.Method.invoke(Method.java:498)
    : 	at org.eclipse.lsp4j.jsonrpc.services.GenericEndpoint.lambda$null$0(GenericEndpoint.java:65)
    : 	... 11 more
    : Caused by: java.lang.NoSuchMethodError: org.eclipse.lsp4j.Diagnostic.getCode()Lorg/eclipse/lsp4j/jsonrpc/messages/Either;
    : 	at com.as3mxml.vscode.utils.LanguageServerCompilerUtils.getDiagnosticFromCompilerProblem(LanguageServerCompilerUtils.java:488)
    : 	at com.as3mxml.vscode.ActionScriptServices.addCompilerProblem(ActionScriptServices.java:1674)
    : 	at com.as3mxml.vscode.ActionScriptServices.publishDiagnosticsForProblemQuery(ActionScriptServices.java:2091)
    : 	at com.as3mxml.vscode.ActionScriptServices.getProject(ActionScriptServices.java:1968)
    : 	at com.as3mxml.vscode.ActionScriptServices.checkProjectForProblems(ActionScriptServices.java:2002)
    : 	at com.as3mxml.vscode.ActionScriptServices.addWorkspaceFolder(ActionScriptServices.java:263)
    : 	at com.as3mxml.vscode.ActionScriptLanguageServer.initialize(ActionScriptLanguageServer.java:107)
    : 	... 16 more
    : 

Is anyone else seeing this problem?

**Comment by rat-moonshine** [comment]
So, I went ahead and downloaded the most latest build from Bamboo (which makes sense to the test) Build#235, and started tests on my Windows 10 system. 

@JoelProminic I see you have setup with "Apache Flex SDK 4.16.1 & AIR 27.0"; I wonder if this version you're using which installed by Moonshine SDK Installer may be some time back, as the last stable Moonshine SDK Installer installs AIR 28.0 as its default, and the nightly install AIR 32.0. 

But using AIR 27.0 is fine for this test anyway. 

I confirm I have the following Moonshine set up as of Joel's:
**Flex SDK:** Apache Flex SDK 4.16.1 & AIR 28.0
**JDK:** OpenJDK 1.8.0

1. Start Moonshine having no projects already opened to the sidebar
2. Create a new Flex Desktop Project, didn't throw any language-server error
3. Create a new ActionScript Desktop Project, didn't throw any language-server error
4. Deleted both the projects, exit Moonshine
5. Removed `JAVA_HOME` from the system environment variable - to test if language server has an explicit dependency on it besides the Moonshine provided Java path
6. Ensured running `java -version` throws an _unrecognized command_ on the command-line
7. Restarted Moonshine and re-do tests from 2-3
8. No language-server error throw this time either, I can see I able to use the Moonshine intellisence correctly

So far, I couldn't able to reproduce the problem in my tests on Windows.

**Comment by JoelProminic** [comment]
I realized that the AIR version mismatch was because the there was an error in my last SDK Installer test (already reported and fixed).  I installed a new version, but I still got the same errors.

When I downgraded to 2.6.0, this error stopped triggering for me.  However, when I upgraded to 3.0.0 again, I still didn't see the error!  I'm not sure how my installation could have gotten corrupted.

Also, this Windows machine is using a remote home directory through Active Directory.   I noticed that my test projects were being created in a UNC network path, but this didn't affect the error reported above.   I do have other issues with this, but I'll create a separate issue for that.

**Comment by piotrzarzycki21** [comment]
It is reproducible only on 1 machine so far. Moving to next version.

**Comment by rat-moonshine** [comment]
Since current LS requirement is JDK v11, we need to re-review necessity to open this issue. Also, if this issue is still producible in current Moonshine builds.

**Comment by piotrzarzycki21** [comment]
@JoelProminic please close this issue cause it seems to be irrelevant with Java 11.

**Comment by rat-moonshine** [comment]
> @JoelProminic please close this issue cause it seems to be irrelevant with Java 11.

Maybe not entirely, since JDK8 still has an usage in Moonshine:
![image](https://user-images.githubusercontent.com/24370870/140908836-ee9ab550-c9a2-4d31-b214-25d747ae09c1.png)

**Comment by rat-moonshine** [comment]
> @JoelProminic please close this issue cause it seems to be irrelevant with Java 11.

Maybe not entirely, since JDK8 still has an usage in Moonshine:
![image](https://user-images.githubusercontent.com/24370870/140908929-b715cc3d-49f3-421c-aac3-e8006bb25b0e.png)

**Comment by JoelProminic** [comment]
I retested this on a Vagrant VM ([Vagrantfile](https://github.com/Moonshine-IDE/Moonshine-IDE/files/7507040/Vagrantfile.zip)) with the default SDKs.  I recreated this VM relatively recently.

Testing with JDK 11, I get this error.  It looks like an an issue with java.policy or java.security:

    : WARNING: An illegal reflective access operation has occurred
    : WARNING: Illegal reflective access by org.dom4j.io.SAXContentHandler (file:/C:/Program%20Files/MoonshineDevelopment/elements/as3mxml-language-server/bin/dom4j-1.6.1.jar) to method com.sun.org.apache.xerces.internal.parsers.AbstractSAXParser$LocatorProxy.getEncoding()
    : WARNING: Please consider reporting this to the maintainers of org.dom4j.io.SAXContentHandler
    : WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
    : WARNING: All illegal access operations will be denied in a future release

I don't get this error with JDK 8, and I see the language server works without any errors.

Anyway, it is still unclear what caused the original errors, so I am fine with closing this issue.  I don't want to spend too much time on JDK8 support for Flex - for our core use cases, this is only needed for Domino Java and ODP projects.

**Comment by JoelProminic** [comment]
I moved the reflective access error discussion to #910.
