### ISSUE TITLE
[Windows] Compilation of Royale Project breaks when Apache Royale SDK path contains whitespaces

### ISSUE THREAD

**Issue by Aszusz** [Moonshine-IDE/Moonshine-IDE#741]
Test scenario:
1. Move Apache SDK to a location containing a whitespace, e.g.: `C:\Moonshine SDKs\Royale_SDK\apache-royale-0.9.8-bin-js`
2. Adjust the path in Moonshine IDE settings
3. After Build & Run Moonshine IDE fails with: `'C:\Moonshine' is not recognized as an internal or external command`

Content of the `C:\%USERNAME%\Roaming\com.moonshine-ide\Local Store\setLocalEnvironment.cmd`:

```
@echo off
set JAVA_HOME=C:\Program Files\OpenJDK\jdk-15
set ANT_HOME=C:\ProgramData\chocolatey\lib\ant\tools\apache-ant-1.10.8
set GIT_HOME=C:\Moonshine SDKs\Git\git-2.20.1
set ROYALE_HOME=C:\Moonshine SDKs\Royale_SDK\apache-royale-0.9.8-bin-js\royale-asjs
set PATH=%JAVA_HOME%\bin;%ANT_HOME%\bin;%ROYALE_HOME%\bin;%PATH%
"%GIT_HOME%\bin\git" config --global http.sslCAInfo "%GIT_HOME%\mingw64\ssl\cert.pem"
"C:\Program Files (x86)\HCL\Notes/nsd.exe" -version
```

This issue is related to: https://github.com/prominic/Moonshine-IDE/issues/739#issuecomment-706063869

**Comment by rat-moonshine** [comment]
This more like a Royale SDK/compiler problem than how Moonshine executes it. 

Consider the following tests:

**Without-space SDK path running on command-line**

```
C:\Users\Devsena>set ROYALE_HOME="C:\MoonshineSDKs\Royale_SDK\apache-royale-0.9.8-bin-js\royale-asjs"
C:\Users\Devsena>"C:\MoonshineSDKs\Royale_SDK\apache-royale-0.9.8-bin-js\royale-asjs\js\bin\mxmlc.bat"
Using Royale SDK: "C:\MoonshineSDKs\Royale_SDK\apache-royale-0.9.8-bin-js\royale-asjs"
Picked up _JAVA_OPTIONS: -Xmx1024M
MXMLJSC
-sdk-js-lib=C:\MoonshineSDKs\Royale_SDK\apache-royale-0.9.8-bin-js\royale-asjs\frameworks\js\Royale\generated-sources
Error: a target file must be specified.
```
(The above error is very obvious but remaining output tells the `mxmlc.bat` path is accessible at command-line)

**With-space SDK path running on command-line**
```
C:\Users\Devsena>set ROYALE_HOME="C:\Moonshine SDKs\Royale_SDK\apache-royale-0.9.8-bin-js\royale-asjs"
C:\Users\Devsena>"C:\Moonshine SDKs\Royale_SDK\apache-royale-0.9.8-bin-js\royale-asjs\js\bin\mxmlc.bat"
SDKs\Royale_SDK\apache-royale-0.9.8-bin-js\royale-asjs""=="x" was unexpected at this time.
```
I see similar error when running Royale project compilation command on command-line when SDK path has space. 

@piotrzarzycki21 please check if the SDK path with space is a known problem to Royale compiler.

**Comment by rat-moonshine** [comment]
We would like to test with Haxe `Process` as `NativeProcess` being unreliable in cases like this.

**Comment by rat-moonshine** [comment]
As I was looking into command-generation on Windows during #1066 , I decide to re-look into this issue as well. 

I noticed that MXMLCJ command that triggers the compilation and run process doesn't has its SDK or `mxmlc` path encoded. This doesn't has any connection with temporary environment generation logic (although, the command writes into the temp batch file to run as a bulk process), and runs as a separate command by IDE.

I fixed the command with proper encoding, I confirm I can run a Royale application with SDK contains whitespace. 

Please, check.

**Comment by piotrzarzycki21** [comment]
@Aszusz please test this one.

**Comment by Aszusz** [comment]
I can build and launch Royale Browser Project. I am closing this issue.
During this test, I discovered multiple rendering issues which I'll raise separately.
