### ISSUE TITLE
Git/Subversion: Messed up steps in setup on macOS

### ISSUE THREAD

**Issue by rat-moonshine** [Moonshine-IDE/Moonshine-IDE#749]
1. Rename the XCode.app (if exists)
2. _Clear_ any existing Git and SVN paths in Moonshine Settings and save
3. Restarts Moonshine
4. In the top-menu it now shows "Git/Subversion -> Grant Permission"
5. Clicking on the "Grant Permission" options opens the Manage Repositories window [Bug]
6. In the "Getting Started" section, it adds an exclamation icon next to Git and Subversion entries mentioning the feature is available, click the settings icon to configure
7. Clicking on the settings icon opens the following window as it expects:
![image](https://user-images.githubusercontent.com/24370870/97833627-cf95c480-1cfb-11eb-98c0-bcfddf13e84a.png)
8. Open Moonshine Settings, Git, and Subversion path already auto-setup pointing XCode.app even the app path is invalid and not explicitly permitted to use by the user [Bug]

**Comment by rat-moonshine** [comment]
Expected behaviours:

Situation | Current Behaviour | Expected Behaviour | Actual
-------------|--------------------|--------------------|----------
No previous setup | Notification in "Getting Started"<br/>Show "Grant Permission" in top-menu | Same as the current behaviour | Confirm
No previous setup | Moonshine Settings showing Xcode.app path auto-setup | No path auto-setup until user grants permission | -
No previous setup | Moonshine Settings shows invalid path auto-setup | Unless permission granted previously, an invalid path shouldn't auto-setup in the Settings | -
No previous setup | Clicking on "Grant Permission" from the top-menu shows Manage Repositories window | Clicking on "Grant Permission" should open Xcode or CommandLineTools (as appropriate) permission window | -
No Xcode or CommandLineTools available in system | Auto-setup invalid Xcode path | "Grant Permission" window need to suggest on installing appropriate tool ?? | -

**Comment by rat-moonshine** [comment]
We did important decoupling of setup ways for SVN and Git in https://github.com/Moonshine-IDE/Moonshine-IDE/issues/849, so not everything here could be same in newer builds now.

Giving a quick test with newer build to produce the original problem, I able to reproduce the following, although in next steps UI effectively notifies on a Git installation is needed. In case of SVN "Grant Permission" is no more needed.

> Clicking on the "Grant Permission" options opens the Manage Repositories window [Bug]

I couldn't able to reproduce the following part in newer build which is good (needs to make sure that Git path is nil in Settings before a testing):
6. In the "Getting Started" section, it adds an exclamation icon next to Git and Subversion entries mentioning the feature is available, click the settings icon to configure
7. Clicking on the settings icon opens the following window as it expects:
8. Open Moonshine Settings, Git, and Subversion path already auto-setup pointing XCode.app even the app path is invalid and not explicitly permitted to use by the user [Bug]

**Comment by rat-moonshine** [comment]
I have updated text describing "In order to use Git and SVN" in grant-permission window referencing to Git only.

If [above](https://github.com/Moonshine-IDE/Moonshine-IDE/issues/749#issuecomment-963828223) changes are Okay, then probably we're good with the original issue reported.

**Comment by JoelProminic** [comment]
The text updates look good:
![image](https://user-images.githubusercontent.com/24532731/141499600-3695c97e-fd93-426b-b372-6fd45cb4e4f4.png)

But I noticed another example on the Success prompt:
![image](https://user-images.githubusercontent.com/24532731/141499661-0df9077c-3841-4745-8f72-c622a7f41848.png)

**Comment by rat-moonshine** [comment]
Possibly all the reference to 'git and svn' now addressed. Please, check.

**Comment by JoelProminic** [comment]
The updated messages look good.
