### ISSUE TITLE
Notarize macOS Installers

### ISSUE THREAD

**Issue by JoelProminic** [Moonshine-IDE/Moonshine-IDE#774]
In order to clear errors on the downloaded macOS installers, we would like to notarize the installers.

**Comment by rat-moonshine** [comment]
Note to myself - I need to updated the signing process in the build-scripts.

**Comment by JoelProminic** [comment]
This is holding up the App Store release, but we could do a non-sandbox release earlier if desired.

**Comment by rat-moonshine** [comment]
I still see the error on a non-notarised non-sandbox build:
![image](https://user-images.githubusercontent.com/24370870/115662603-d6bd9700-a35c-11eb-862e-60f66ac83c8d.png)

I found a bit problematic myself on what was our last test-scenarios based on which we assume a non-sandbox build suppose not to create any install-warning/error on >Catalina.

**Comment by JoelProminic** [comment]
This error is expected for a non-notarized build, but we have been working around these errors for a while now.   I'd like to get this fixed, but my understanding was that resolving the notarization issues would be time consuming.  @rat-moonshine, do you have more details for this?

**Comment by rat-moonshine** [comment]
Currently, I only have the information that some .jar files inside different language-servers were not signed - as per the notarisation report we had earlier. I also seen that using the Apple certificates against them (as we use to sign everything in the .pkg for signing and notarisation) didn't worked either. 

I think we have a detail discussion on this somewhere, maybe in emails and chats (!)

**Comment by JoelProminic** [comment]
Yeah, we only had the errors listed in an email.   I reran the test, and attached the full error list:

[2021_04_23__Moonshine_Notarization_Errors.txt](https://github.com/prominic/Moonshine-IDE/files/6366797/2021_04_23__Moonshine_Notarization_Errors.txt)

These are all signing errors for either groovy-language-server or haslink-debug-adapter (deasync dependency).  Here is a list of files with errors:

    Moonshine_Signed_NonSandbox.pkg/com.moonshine-ide.pkg Contents/Payload/Applications/Moonshine.app/Contents/Resources/elements/groovy-language-server/groovy-language-server-all.jar/META-INF/native/osx/libjansi.jnilib
    Moonshine_Signed_NonSandbox.pkg/com.moonshine-ide.pkg Contents/Payload/Applications/Moonshine.app/Contents/Resources/elements/hashlink-debug-adapter/node_modules/deasync/bin/darwin-x64-node-0.10/deasync.node
    Moonshine_Signed_NonSandbox.pkg/com.moonshine-ide.pkg Contents/Payload/Applications/Moonshine.app/Contents/Resources/elements/hashlink-debug-adapter/node_modules/deasync/bin/darwin-x64-node-0.11/deasync.node
    Moonshine_Signed_NonSandbox.pkg/com.moonshine-ide.pkg Contents/Payload/Applications/Moonshine.app/Contents/Resources/elements/hashlink-debug-adapter/node_modules/deasync/bin/darwin-x64-node-0.12/deasync.node
    Moonshine_Signed_NonSandbox.pkg/com.moonshine-ide.pkg Contents/Payload/Applications/Moonshine.app/Contents/Resources/elements/hashlink-debug-adapter/node_modules/deasync/bin/darwin-x64-node-10/deasync.node
    Moonshine_Signed_NonSandbox.pkg/com.moonshine-ide.pkg Contents/Payload/Applications/Moonshine.app/Contents/Resources/elements/hashlink-debug-adapter/node_modules/deasync/bin/darwin-x64-node-11/deasync.node
    Moonshine_Signed_NonSandbox.pkg/com.moonshine-ide.pkg Contents/Payload/Applications/Moonshine.app/Contents/Resources/elements/hashlink-debug-adapter/node_modules/deasync/bin/darwin-x64-node-12/deasync.node
    Moonshine_Signed_NonSandbox.pkg/com.moonshine-ide.pkg Contents/Payload/Applications/Moonshine.app/Contents/Resources/elements/hashlink-debug-adapter/node_modules/deasync/bin/darwin-x64-node-4/deasync.node
    Moonshine_Signed_NonSandbox.pkg/com.moonshine-ide.pkg Contents/Payload/Applications/Moonshine.app/Contents/Resources/elements/hashlink-debug-adapter/node_modules/deasync/bin/darwin-x64-node-5/deasync.node
    Moonshine_Signed_NonSandbox.pkg/com.moonshine-ide.pkg Contents/Payload/Applications/Moonshine.app/Contents/Resources/elements/hashlink-debug-adapter/node_modules/deasync/bin/darwin-x64-node-6/deasync.node
    Moonshine_Signed_NonSandbox.pkg/com.moonshine-ide.pkg Contents/Payload/Applications/Moonshine.app/Contents/Resources/elements/hashlink-debug-adapter/node_modules/deasync/bin/darwin-x64-node-7/deasync.node
    Moonshine_Signed_NonSandbox.pkg/com.moonshine-ide.pkg Contents/Payload/Applications/Moonshine.app/Contents/Resources/elements/hashlink-debug-adapter/node_modules/deasync/bin/darwin-x64-node-8/deasync.node
    Moonshine_Signed_NonSandbox.pkg/com.moonshine-ide.pkg Contents/Payload/Applications/Moonshine.app/Contents/Resources/elements/hashlink-debug-adapter/node_modules/deasync/bin/darwin-x64-node-9/deasync.node

**Comment by piotrzarzycki21** [comment]
@JoelProminic @rat-moonshine We have found today that Nightly build of [Mac OS is very old](https://moonshine-ide.com/downloads/releases/dev/macos/). @Aszusz checked bamboo and we are seeing that due notarization problem build is failing, but there were also positive build not soe long ago. However non of them was correctly copied to mentioned [Nightly folder](https://moonshine-ide.com/downloads/releases/dev/macos/). Additionally failing build is copying "build_details_macos.json" despite of it's failure. Could you guys take a look into those problems ?

**Comment by JoelProminic** [comment]
Ah, I see deployment was broken since Feb 25.  Checking the Bamboo plan, I saw that the current logic was only SCPing the JSON file - this must have broken with some update we made.

I updated the deployment logic to make this more robust.  I confirmed that the artifacts were deployed with my latest test, but let me know if you see any more problems.

Currently, the Notarization process is a manual stage after the deployment runs.  So, this means that it won't prevent deployment, but the notarized build will not be deployed automatically (once we get it fixed).

**Comment by piotrzarzycki21** [comment]
@JoelProminic It looks like build is working now, but I would like to also see name changing for file. On Windows we are adding version to file name - maybe it's worth to have it for Mac as well.

**Comment by rat-moonshine** [comment]
I'm adding the suggestion from @joshtynjala to keep a note for myself:

> I have never released a macOS app that includes a .jar file, so I have no experience here.
> 
> It's possible that you'll need to extract the libjansi.jnilib file, sign it, and then add it back to the .jar file. That's my best guess from the "Not a directory" error, since a .jar file is not a directory. It's actually basically a .zip file with the .jar extension.

**Comment by rat-moonshine** [comment]
While I was experimenting `tar` as an unzip tool on macOS to be use during signing, I noticed a couple of size differences when zip the extracted directory back as `jar`. Following were my test commands and results:

```
// groovy-language-server-all.jar : Size: 17.7 MB

// i prefer to put the extracted files in a folder so I can delete directly
tar -xf groovy-language-server-all.jar -C groovy-language-server-all

// zip all the extracted files as a .jar this time
tar -cf groovy-language-server-all.jar -C groovy-language-server-all . 

// groovy-language-server-all.jar : Size: 46+ MB

// zip all the extracted files as .jar using gzip compression
tar -czf groovy-language-server-all.jar -C groovy-language-server-all . 

// groovy-language-server-all.jar : Size: 11.6 MB
```

With either compression types - there is a question on the validity of the re-packaged `jar` file now. Probably this will be clear only when be used in Moonshine.

**Comment by rat-moonshine** [comment]
```
spctl -vvv --assess --type exec ${debug_dir}/groovy-language-server-all/META-INF/native/osx/libjansi.jnilib

: [exec] bin-debug/groovy-language-server-all/META-INF/native/osx/libjansi.jnilib: rejected (the code is valid but does not seem to be an app)

---------------

spctl -vvv --assess --type open ${debug_dir}/groovy-language-server-all/META-INF/native/osx/libjansi.jnilib

: [exec] bin-debug/groovy-language-server-all/META-INF/native/osx/libjansi.jnilib: Not a directory

---------------

spctl -vvv --assess --type install ${debug_dir}/groovy-language-server-all/META-INF/native/osx/libjansi.jnilib

: [exec] bin-debug/groovy-language-server-all/META-INF/native/osx/libjansi.jnilib: Not a directory

-----------------

codesign -f -v -s "${certSignedDevIDKeychainName}" -deep bin-debug/groovy-language-server-all
codesign -f -v -s "${certSignedDevIDKeychainName}" -deep bin-debug/groovy-language-server-all.zip

[exec] bin-debug/groovy-language-server-all: bundle format unrecognized, invalid, or unsuitable
[exec] bin-debug/groovy-language-server-all.zip: bundle format unrecognized, invalid, or unsuitable

------------------

Signing checks on Sandbox APP: spctl -vvv --assess --type exec elements/hashlink-debug-adapter/node_modules/deasync/bin/darwin-x64-node-0.10/deasync.node

[exec] elements/hashlink-debug-adapter/node_modules/deasync/bin/darwin-x64-node-0.10/deasync.node: rejected (the code is valid but does not seem to be an app)

------------------
```

**Comment by JoelProminic** [comment]
To test the modified Groovy language server, you can use a Grails project like this:

1. Create Grails project
2. Open `grails-app/controllers/%project%/UrlMappings.groovy`.  This file should be sufficient to test tooltips
2. Project > Run Grails Command, `create-controller test.TestLS`
3. Open `grails-app/controllers/test/TestLSController.groovy`
4. This file should be appropriate for more testing, including completion

**Comment by rat-moonshine** [comment]
I continued tested with two separate files from different sections on signing and notarisation:

- bin-debug/groovy-language-server-all/META-INF/native/osx/libjansi.jnilib
- hashlink-debug-adapter/node_modules/deasync/bin/darwin-x64-node-0.10/deasync.node

**libjansi.jnilib**
This passed the test of signing and not in the notarisation error-report anymore.

**deasync.node**
Although, this do not has any signing-error marked in the notarisation error-report but this rejected with a different error now:

```
{
      "severity": "error",
      "code": null,
      "path": "Moonshine.pkg/com.moonshine-ide.pkg Contents/Payload/Applications/Moonshine.app/Contents/Resources/elements/hashlink-debug-adapter/node_modules/deasync/bin/darwin-x64-node-0.10/deasync.node",
      "message": "The binary uses an SDK older than the 10.9 SDK.",
      "docUrl": null,
      "architecture": "x86_64"
    }
```

**Additional**
Using the re-zipped `groovy-language-server-all.jar` doesn't seems to be working well in Moonshine. Following error shown in console and the language-support seems not work against `.groovy` file:
```
: Error: Unable to initialize main class moonshine.groovyls.Main
: Caused by: java.lang.NoClassDefFoundError: net/prominic/groovyls/config/ICompilationUnitFactory
: Groovy language server exited unexpectedly. Close the NewGrailsProject project and re-open it to enable code intelligence.
```

For reference, the .jar file re-zipped with `gzip` compression, we can try out with other zip-types:
`tar -czf elements/groovy-language-server/groovy-language-server-all.jar -C ${debug_dir}/groovy-language-server-all .`

**Comment by JoelProminic** [comment]
For the `groovy-language-server-all.jar` error, you should use `zip` instead of `tar`.   If that fails, we may need to use `jar` instead, but I think this will require more configuration.

There is an [ant task](https://ant.apache.org/manual/Tasks/zip.html) for zip, or you can use a command like this:

    zip -r groovy-language-server-all.jar groovy-language-server-all 


For the `deasync.node` error, it sounds like this is talking about the XCode version, but I didn't think that .node files had a dependency on XCode.  Do we have any other .node files?  If so, are they triggering the same error?

**Comment by rat-moonshine** [comment]
```
Load command 6
      cmd LC_VERSION_MIN_MACOSX
  cmdsize 16
  version 10.5
      sdk 10.8
```

**Comment by rat-moonshine** [comment]
I'm closing this issue as notarisation completes for Moonshine at Bamboo (https://bamboo.prominic.net/browse/MS-MGOSX-2037/log):

![image](https://user-images.githubusercontent.com/24370870/125409186-4631a880-e3d9-11eb-8886-6bd51eb4496c.png)

**Comment by JoelProminic** [comment]
I also ran a test with notarizing the AppStore build, and that was successful as well. 

I'll plan to update the Bamboo plan to
- Notarize both the NonSandbox and AppStore builds
- Deploy both builds to moonshine-ide.com

We'll need to do some testing on the AppStore build for the recent updates, but I'll create a separate issue for this.
