### ISSUE TITLE
File Associations Broken on Windows

### ISSUE THREAD

**Issue by JoelProminic** [Moonshine-IDE/Moonshine-IDE#800]
While testing #799, we noticed that Windows did not give the option to open .*proj or other files with Moonshine. 

![2021_03_29__FileAssociation_3_1_0](https://user-images.githubusercontent.com/24532731/112878074-20340280-908d-11eb-93ae-411df87c0936.png)

I can still open the files with Moonshine if I manually select Moonshine in the file chooser.

I installed the latest stable build (3.0.0), and found that it works fine.  So, it seems this bug was not introduced with the NSIS installer change.

![2021_03_29__FileAssociation_3_0_0](https://user-images.githubusercontent.com/24532731/112878098-275b1080-908d-11eb-93c2-9a50b6c4357b.png)

Could this bug be caused by the switch to Harman AIR (#773)?

**Comment by rat-moonshine** [comment]
Unfortunately, installing stable v3.0.0 on my Windows system didn't shown me any file-association either. 

I tried to build current branch build using Adobe AIR 30.0, that also didn't shown me any file-association sign. ;/

**Comment by JoelProminic** [comment]
I did some investigation for this with @rat-moonshine today.

I see that the commands for extensions are [assoc](https://docs.microsoft.com/en-us/windows-server/administration/windows-commands/assoc) and [ftype](https://docs.microsoft.com/en-us/windows-server/administration/windows-commands/ftype).  

    C:\Users\JAnderson>assoc .xml
    .xml=xmlfile

    C:\Users\JAnderson>ftype xmlfile
    xmlfile="C:\Program Files\Internet Explorer\iexplore.exe" %1

    C:\Users\JAnderson>assoc .as3proj
    .as3proj=Moonshine.Project.Configuration.File.1

    C:\Users\JAnderson>ftype Moonshine.Project.Configuration.File.1
    File type 'Moonshine.Project.Configuration.File.1' not found or no open command associated with it.


By my understanding, these mappings are defined by [registry keys](https://docs.microsoft.com/en-us/windows/win32/shell/how-to-register-a-file-type-for-a-new-application).  I see the "file type" registry entires, but not the "ProgID"

    C:\Users\JAnderson>reg query HKEY_CLASSES_ROOT /s /f "Moonshine"

    HKEY_CLASSES_ROOT\.as
        (Default)    REG_SZ    Moonshine.ActionScript.File

    HKEY_CLASSES_ROOT\.as3proj
        (Default)    REG_SZ    Moonshine.Project.Configuration.File.1

    HKEY_CLASSES_ROOT\.awd
        (Default)    REG_SZ    Moonshine.AwayBuilder.File

    HKEY_CLASSES_ROOT\.grailsproj
        (Default)    REG_SZ    Moonshine.Project.Configuration.File.4

    HKEY_CLASSES_ROOT\.javaproj
        (Default)    REG_SZ    Moonshine.Project.Configuration.File.3

    HKEY_CLASSES_ROOT\.mxml
        (Default)    REG_SZ    Moonshine.MXML.File

    HKEY_CLASSES_ROOT\.veditorproj
        (Default)    REG_SZ    Moonshine.Project.Configuration.File.2


After some testing, we confirmed that the registry keys are not updating when Moonshine is installed.   With a fresh Windows machine, no Moonshine registry keys are added.

Since we are using NSIS for the installer now, we probably need to have it manage the registry keys as well.  The API is [here](https://nsis.sourceforge.io/File_Association).

**Comment by piotrzarzycki21** [comment]
> File association on Windows now fixed with NSIS integration. This fix applied into master. Please, check.

Your changes may have been lost somehow due to some weird push from Bing to master. I have applied back what was on master before, but it looks like there is missing following commit https://github.com/prominic/Moonshine-IDE/commit/e532d4ff9b02ab005bd2c57101a738bc40c49b5a - You may have to apply it again.

**Comment by rat-moonshine** [comment]
I have re-committed my changes, should be good for a test now.

**Comment by JoelProminic** [comment]
I confirmed that the registry keys were updated:


    C:\Users\JAnderson>reg query HKEY_CLASSES_ROOT /s /f "Moonshine"

    HKEY_CLASSES_ROOT\.as
        (Default)    REG_SZ    Moonshine.ActionScript.File

    HKEY_CLASSES_ROOT\.as3proj
        (Default)    REG_SZ    Moonshine.Project.Configuration.File.1

    HKEY_CLASSES_ROOT\.awd
        (Default)    REG_SZ    Moonshine.AwayBuilder.File

    HKEY_CLASSES_ROOT\.css
        (Default)    REG_SZ    Moonshine.CSS.File

    HKEY_CLASSES_ROOT\.grailsproj
        (Default)    REG_SZ    Moonshine.Project.Configuration.File.4

    HKEY_CLASSES_ROOT\.htm
        (Default)    REG_SZ    Moonshine.HTML.File

    HKEY_CLASSES_ROOT\.html
        (Default)    REG_SZ    Moonshine.HTML.File.2
    
    ...
    
    HKEY_CLASSES_ROOT\Moonshine.ActionScript.File
        (Default)    REG_SZ    Moonshine.ActionScript.File

    HKEY_CLASSES_ROOT\Moonshine.ActionScript.File\DefaultIcon
        (Default)    REG_SZ    C:\Program Files\Moonshine\Moonshine.exe,0

    HKEY_CLASSES_ROOT\Moonshine.ActionScript.File\shell\edit
        (Default)    REG_SZ    Edit Moonshine.ActionScript.File

    HKEY_CLASSES_ROOT\Moonshine.ActionScript.File\shell\edit\command
        (Default)    REG_SZ    "C:\Program Files\Moonshine\Moonshine.exe" "%1"

    HKEY_CLASSES_ROOT\Moonshine.ActionScript.File\shell\open\command
        (Default)    REG_SZ    "C:\Program Files\Moonshine\Moonshine.exe" "%1"
    

I confirmed that the files opened automatically with Moonshine.

I'm a little concerned about setting Moonshine as the default for some common files (like .html).  However, in my tests I saw that .html files still opened with Firefox by default, so this seems to be fine.

However, I did notice that registry keys were not cleaned up when Moonshine was uninstalled.  For example, this means that .mxml files were still considered "Moonshine.MXML.File" even though Moonshine was no longer available.  Does NSIS have an API for this as well?

**Comment by rat-moonshine** [comment]
> However, I did notice that registry keys were not cleaned up when Moonshine was uninstalled. For example, this means that .mxml files were still considered "Moonshine.MXML.File" even though Moonshine was no longer available. Does NSIS have an API for this as well?

It probably does, I just didn't removed the association during an uninstallation. I shall add the cleanup, if it's helpful to some users.

**Comment by rat-moonshine** [comment]
I have added the unregistering steps for the Moonshine file-association during an uninstall on Windows. Please, check.

**Comment by rat-moonshine** [comment]
Recently @JoelProminic reported that even after the un-installation and file-type-disassociation, command-line still reports leftover descriptions in registry:

```
$reg query HKEY_CLASSES_ROOT /s /f "Moonshine"

HKEY_CLASSES_ROOT\.as
    (Default)    REG_SZ    Moonshine.ActionScript.File

HKEY_CLASSES_ROOT\.as3proj
    (Default)    REG_SZ    Moonshine.Project.Configuration.File.1

HKEY_CLASSES_ROOT\.awd
    (Default)    REG_SZ    Moonshine.AwayBuilder.File
```

Those leftover descriptions now being removed during an un-installation and should return no value when the command run.

**Comment by JoelProminic** [comment]
I confirmed that all the extension-related Moonshine registry keys were cleaned up when I uninstalled Moonshine.

**Comment by rat-moonshine** [comment]
@JoelProminic recently reported that double-clicking a project file from Explorer/Finder do focus Moonshine but nothing opens. I also confirm the similar behavior for known files. 

I have now commit a fix, a new build should be ready for a test.

**Comment by rat-moonshine** [comment]
Earlier freeze scenario is now fixed with newest build. Please, check.

**Comment by rat-moonshine** [comment]
I tested this today with latest build, and following are my test matrix. @JoelProminic please add, if any other point you may think. Else, I think we can close it. 
Description | Results
---------------|-----------------
Moonshine-IDE associated files can be double-clicked to open in Moonshine | Shows Moonshine icon on the files, double-clicking opens into Moonshine
Double-clicking a project file freeze the application | No
Uninstalling Moonshine removes files association | Double-clicking opens system prompt to open with application

**Comment by piotrzarzycki21** [comment]
I have tested this today with my Windows 10 Home machine. I did test with Flex, Royale and JavaGradleProjects everything works fine. I'm closing issue - let's reopen it or move to another milestone in case of problems.
