### ISSUE TITLE
Separate Auto-Update Configuration for Non-Sandbox, App Store, and Windows Builds

### ISSUE THREAD

**Issue by JoelProminic** [Moonshine-IDE/Moonshine-IDE#836]
We have not released Moonshine 3.0.0 and 3.1.0 to the App Store because of an issue with Notarization (#774).

However, I noticed that the App Store installation prompts the user to update, even though this is not available on the App Store.
![image](https://user-images.githubusercontent.com/24532731/120715823-c84db980-c48a-11eb-9835-20f9aa9859f8.png)

I think this is because we use the same configuration value in the updater XML file for both the App Store and Non-Sandbox builds.

We may want to release special builds for only one of the platforms in the future, so I'd like to see separate configuration values for each macOS build type and also for Windows.  If we update this, we'll need to keep the existing configuration value for a few releases to support the legacy builds.

We can discuss this further, but I'd like to have something added for this with the next App Store build (after resolving #774).

**Comment by rat-moonshine** [comment]
I have added separate check for App Store update in updater-xml (https://moonshine-ide.com/downloads/updater.xml) as `appStorePkg` tag.

Currently, this set to last released version v2.6.0.

**Comment by JoelProminic** [comment]
I updated appStore.version to 3.3.0, but I am not getting prompted to update the App Store build (nightly 2038).   Since the production Moonshine builds aren't using this, I left it with the updated value for now.

**Comment by rat-moonshine** [comment]
I have committed a fix on this.

**Comment by piotrzarzycki21** [comment]
> I have committed a fix on this.

Ok but in order to test that - you need to change for us remote file - Am I right ? Is it changed ? Should I get prompt ?

**Comment by rat-moonshine** [comment]
Based on current state of the remote file, here was my test-matrix:

Build Type | Current Version Value | Remote Version Value | Result
----------- | ------------------- | ------------------ | ---------------
App Store | < 3.1.1 | 3.3.0 | Message appears during startup suggesting to update using Mac App Store
Non Sandbox | 3.1.1 | 3.1.1 | No update message appears
Non Sandbox | 3.1.1 | 3.2.0 | Message appears to download an update

@piotrzarzycki21 If you want to test the App Store version only, you should get a prompt suggesting to update through Mac App Store at startup, the value at remote already set to 3.3.0.

**Comment by piotrzarzycki21** [comment]
I have just tested and I'm getting prompt on Mac OSX Big Sur. In my opinion everything is working correctly and you can close issue.

**Comment by JoelProminic** [comment]
![image](https://user-images.githubusercontent.com/24532731/125819750-f1a43f44-0b69-4cf6-9620-be4f54e8f68c.png)

This looks fine to me.  I reset the updater.xml file, and confirmed that the prompt does not show up in this case.
