### ISSUE TITLE
Haxe Library Version Issues for Ant  InstallHaxeDependencies Target

### ISSUE THREAD

**Issue by JoelProminic** [Moonshine-IDE/Moonshine-IDE#843]
When trying to build Moonshine from the Ant script today, I got errors on the Haxe libraries:

    InstallHaxeDependencies:
         [echo] Installing Haxe Libraries
         [exec] Downloading feathersui-1,0,0-beta,3.zip...
         [exec] Installing feathersui...
         [exec]   Current version is now 1.0.0-beta.3
         [exec] Done
         [exec] Installing dependency actuate 1.8.9
         [exec] You already have actuate version 1.8.9 installed
         [exec] Installing dependency hxargs 3.0.2
         [exec] You already have hxargs version 3.0.2 installed
         [exec] Installing dependency openfl 9.1.0
         [exec] You already have openfl version 9.1.0 installed
         [exec] Set openfl to version 9.1.0 [y/n/a] ? n
         [exec] You already have openfl version 9.1.0 installed
         [exec] Set openfl to version 9.1.0 [y/n/a] ? n
         [exec] You already have actuate version 1.8.9 installed
         [exec] You already have lime version 7.9.0 installed

    CompileGUICore:
         [echo] Compiling GUI Core SWC
         [exec] Warning: Lime version 7.9.0 may not be compatible with OpenFL 9.0.2 (expected version 7.7.*)
         [exec] Use <lime version="" /> before <haxelib name="openfl" /> to include a specific version
         [exec] /usr/local/lib/haxe/lib/openfl/9,0,2/packages/utils/src/openfl/utils/ByteArray.hx:750: characters 20-29 : openfl.utils.ByteArray should be haxe.io.Bytes
         ...

I see that the [current Ant commands](https://github.com/prominic/Moonshine-IDE/blob/4682b3721142a594755bb7af96703cd6773155b7/ide/MoonshineSharedCore/build/build-lib.xml#L836) do not have the --always flag, so they will automatically decline the prompt to switch to the latest version if it is already installed.

**Comment by JoelProminic** [comment]
I used an example from another Ant script to create a macro for this, and added the "--always" option.  This will always install the latest version of the libraries.

However, I'm not sure that this is the behavior we want for the Haxe libraries.  @joshtynjala, would it be better to:
- Define the specific library versions to use in this Ant script (or another configuration file).   The macro could easily be updated with a "version" parameter.  I have this code already present but commented out.   It would be possible, but messier, so make the version parameter optional in the macro, but I didn't want to spend more time on this for now. 
- Use whatever version is currently installed on the machine (and require developers to manually install and update the libraries)

For now, the code is in this branch only:  features/issue_843_InstallHaxeDependencies

**Comment by joshtynjala** [comment]
@JoelProminic To guarantee that the build would be more likely to complete successfully, defining specific library versions is probably the way to go. Always using the latest version would probably be a little less stable at times, but it would probably still be an improvement over just accepting whichever versions someone already has installed (which could be out of date or mismatching on compatibility).

**Comment by JoelProminic** [comment]
I thought this issue had triggered again, but it turned out to be a different issue.

I revisited my branch and did the following:
- merged master
- updated the Ant macro to use the button

However, I found that the logic to set HAXE_LIB_DIRECTORY does not work with Haxe installation from MoonshineSDKInstaller.   I may try to improve this logic, but we can set the path from a parameter like this:

    ant InstallHaxeDependencies -DHAXE_LIB_DIRECTORY=${HAXE_HOME}

**Comment by JoelProminic** [comment]
I merged this into master while I was looking into some missing Haxe dependencies.
