### ISSUE TITLE
Split File and Project Templates into separate sections

### ISSUE THREAD

**Issue by JoelProminic** [Moonshine-IDE/Moonshine-IDE#852]
From @JustinProminic

>
>2) we should not be mixing "Templating" into both "Files" and "Projects".  It is too confusing.
>
>There needs to be two separate top level items:
>
>Templates for Files
>
>
>Templates for Projects

>
>instead of all mixed together like this:

We may also be able to clarify this separation by having collapsible sections or another clear division, but I think the separate plugin entries in Settings make more sense.

**Comment by JoelProminic** [comment]
Another option would be to have radio buttons or tabs at the top of the interface to quickly switch between the File and Project templates.   This would probably be significantly easier and require less duplication than splitting the existing plugin.

**Comment by rat-moonshine** [comment]
This is ready for a test.

**Comment by JoelProminic** [comment]
The updated UI looks like this.  This seems to work, but I worry that the radio buttons will be too easy to miss, especially in fullscreen.

![image](https://user-images.githubusercontent.com/24532731/123990306-453b5880-d98f-11eb-82fe-5b34cc840df5.png)

The file templates are working fine, but I had trouble with the project templates on macOS 10.15.7.  This might be an unrelated issue:
1. Settings > Templating
2. Find the "Royale Browser Project Jewel" and click Modify.   Reset the project first if it was already modified
3. Add a new file to the base directory called Test.txt, and populate some simple text.
4. Close the template and save the settings
5. File > New > Royale Browser project.  Choose the Jewel type, and create the project
6. BUG:  the new project does not have the Test.txt file.

I saw the same behavior for the ActionScript Desktop Project and File > New > ActionScript Project > ActionScript Desktop Project, but I think this might be using a different template (I didn't see build_air in the resulting project).

**Comment by JoelProminic** [comment]
For the project template error, I checked the settings, and I see two templates folders:
- Local Store/templates
- Local Store/elements/templates

The updated templates are stored in elements/templates, while the templates directory is blank.

**Comment by rat-moonshine** [comment]
I have created a separate issue on above. I'm closing the original issue as fixed.
