### ISSUE TITLE
Remove NoteInfo from DXL Templates

### ISSUE THREAD

**Issue by JoelProminic** [Moonshine-IDE/Moonshine-IDE#853]
>The bigger issue here that I noticed, is we cannot have the following nodes in this:
>
>replicaid
>noteid
>unid
>
>In fact, I don't think the entire noteinfo section is supposed to be there at all.
>
>![image](https://user-images.githubusercontent.com/24532731/121744565-b7bfc380-cac8-11eb-98c8-4c46e436846c.png)
>
>
>all of this needs to be removed.
>
>```
>  <noteinfo noteid="2116" unid="27C118EDE31483CB86256C6900644875" sequence="8">
>    <created>
>      <datetime>Mon Aug 10 15:31:35 GMT+0300 2020</datetime>
>    </created>
>    
>    <modified>
>      <datetime>Mon Aug 10 15:31:35 GMT+0300 2020</datetime>
>    </modified>
>    
>    <revised dst="true">
>      <datetime>Mon Aug 10 15:31:35 GMT+0300 2020</datetime>
>    </revised>
>    <lastaccessed>
>      <datetime>Mon Aug 10 15:31:35 GMT+0300 2020</datetime>
>    </lastaccessed>
>    <lastaccessed>
>      <datetime>Mon Aug 10 15:31:35 GMT+0300 2020</datetime>
>    </lastaccessed>
>    <addedtofile>
>      <datetime>Mon Aug 10 15:31:35 GMT+0300 2020</datetime>
>    </addedtofile>
>  </noteinfo>
>```

This affects these templates (Moonshine > Settings > Templates):
- Files:
-- Domino Visual Editor Form.form.template
-- Form Builder DXL File.form.template
-- Visual Editor DXL File.dve.template
- Projects:
-- On Disk Project
-- Domino Visual Editor (I don't see this in the list, which may be a separate issue we need to address)

**Comment by JoelProminic** [comment]
@feather812002 updated this today in master.  We need to do some testing to make sure this worked fine.

**Comment by JoelProminic** [comment]
This is the commit for the updates to this issue:  https://github.com/prominic/Moonshine-IDE/commit/016eb0ac9c5c0531e7a3e88c1aa330f44c4920bc

**Comment by feather812002** [comment]
I to do some test and fix in today about this issue.
I confirm the noteinfo already remove  from "Domino Visual Editor" project.
The create a new "New onDiskProject" it also contain a "Greeting.form", this form also contain the noteinfo.
I can't make sure this form can be remove or not ?

**Comment by feather812002** [comment]
The "model"  look like already have value ,so the "model.javaPathForTypeAhead" maybe a null object/property , then it will throw the error.
So anyone have a chance check this in mins ?

**Comment by feather812002** [comment]
Other , when I build the new project (not contain the noteinfo) with the maven command in the terminal , it can success build.
So , after we fix this build bug ,I think we can close this issue.

**Comment by JoelProminic** [comment]
I tested the On Disk Project and Domino Visual Editor projects on macOS, and they seem to be working fine with the updates.   I confirmed that <noteinfo> has been removed from the generate .form files.

However, I still see noteinfo in other NSF files in the template.  We'd like to get these cleaned up, but please test and report if this breaks the projects.

On Disk Project:

    $ grep -r "noteinfo" .
    ./nsfs/nsf-moonshine/odp/Code/Agents/ExampleJavaAgent.ja:<noteinfo noteid='16e' unid='A634536F7DDD8A078625851C006FBC8C' sequence='4'>
    ./nsfs/nsf-moonshine/odp/Code/Agents/ExampleJavaAgent.ja:<addedtofile><datetime>20200310T133232,56-05</datetime></addedtofile></noteinfo>
    ./nsfs/nsf-moonshine/odp/Code/Agents/ExampleLotusScriptAgent.lsa:<noteinfo noteid='176' unid='334A581BE1833F428625851C0070002E' sequence='7'>
    ./nsfs/nsf-moonshine/odp/Code/Agents/ExampleLotusScriptAgent.lsa:<addedtofile><datetime>20200310T133232,58-05</datetime></addedtofile></noteinfo>
    ./nsfs/nsf-moonshine/odp/Code/actions/Shared Actions(1):<noteinfo noteid='196' unid='81A42834C769FBAE8625851C00712058' sequence='1'>
    ./nsfs/nsf-moonshine/odp/Code/actions/Shared Actions(1):<addedtofile><datetime>20200310T133232,74-05</datetime></addedtofile></noteinfo>
    ./nsfs/nsf-moonshine/odp/Code/actions/Shared Actions:<noteinfo noteid='192' unid='CF28A1C38EF220D08625851C00710F73' sequence='5'>
    ./nsfs/nsf-moonshine/odp/Code/actions/Shared Actions:<addedtofile><datetime>20200310T133232,72-05</datetime></addedtofile></noteinfo>
    ./nsfs/nsf-moonshine/odp/Code/ScriptLibraries/utils.ssjs.jss.metadata:<noteinfo noteid="1ba" sequence="2" unid="6115988D06DECEAC00258523004CE817">
    ./nsfs/nsf-moonshine/odp/Code/ScriptLibraries/utils.ssjs.jss.metadata:<addedtofile><datetime>20200310T133232,92-05</datetime></addedtofile></noteinfo>
    ./nsfs/nsf-moonshine/odp/AppProperties/database.properties:<noteinfo noteid='122' unid='22A8222D39A6451A8625851C006E1385' sequence='7'>
    ./nsfs/nsf-moonshine/odp/AppProperties/database.properties:<addedtofile><datetime>20200310T133232,24-05</datetime></addedtofile></noteinfo>
    ./nsfs/nsf-moonshine/odp/Forms/Greeting.form:<noteinfo noteid='14a' unid='A1246159B21013448625851C006E2D54' sequence='8'>
    ./nsfs/nsf-moonshine/odp/Forms/Greeting.form:<addedtofile><datetime>20200310T133232,44-05</datetime></addedtofile></noteinfo>
    ./nsfs/nsf-moonshine/odp/SharedElements/Fields/Comment.field:<noteinfo noteid='152' unid='8E9C9AA2A0528A0B8625851C006F1428' sequence='2'>
    ./nsfs/nsf-moonshine/odp/SharedElements/Fields/Comment.field:<addedtofile><datetime>20200310T133232,48-05</datetime></addedtofile></noteinfo>
    ./nsfs/nsf-moonshine/odp/SharedElements/Subforms/Footer.subform:<noteinfo noteid='156' unid='D1055C534A18B3F88625851C006F2DD3' sequence='2'>
    ./nsfs/nsf-moonshine/odp/SharedElements/Subforms/Footer.subform:<addedtofile><datetime>20200310T133232,50-05</datetime></addedtofile></noteinfo>
    ./nsfs/nsf-moonshine/odp/SharedElements/Columns/Last Updated.column:<noteinfo noteid='15a' unid='30EFDB8D0A8690A00625851C006F62EA' sequence='2'>
    ./nsfs/nsf-moonshine/odp/SharedElements/Columns/Last Updated.column:<addedtofile><datetime>20200310T133232,52-05</datetime></addedtofile></noteinfo>
    ./nsfs/nsf-moonshine/odp/Resources/IconNote:<noteinfo noteid='122' unid='22A8222D39A6451A8625851C006E1385' sequence='7'>
    ./nsfs/nsf-moonshine/odp/Resources/IconNote:<addedtofile><datetime>20200310T133232,24-05</datetime></addedtofile></noteinfo>
    ./nsfs/nsf-moonshine/odp/XPages/Greetings.xsp.metadata:<noteinfo noteid="1b2" sequence="90" unid="1A7C5AD43B48345B00258523004443B9">
    ./nsfs/nsf-moonshine/odp/XPages/Greetings.xsp.metadata:<addedtofile><datetime>20200310T133232,88-05</datetime></addedtofile></noteinfo>
    ./nsfs/nsf-moonshine/odp/XPages/Greeting.xsp.metadata:<noteinfo noteid="1a2" sequence="59" unid="036DFA5A40C3CF7200258523003F5303">
    ./nsfs/nsf-moonshine/odp/XPages/Greeting.xsp.metadata:<addedtofile><datetime>20200310T133232,80-05</datetime></addedtofile></noteinfo>
    ./nsfs/nsf-moonshine/odp/CustomControls/GreetingActionBar.xsp.metadata:<noteinfo noteid="1ae" sequence="64" unid="FA42CDDE28047C77002585230043ACB8">
    ./nsfs/nsf-moonshine/odp/CustomControls/GreetingActionBar.xsp.metadata:<addedtofile><datetime>20200310T133232,86-05</datetime></addedtofile></noteinfo>
    ./nsfs/nsf-moonshine/odp/CustomControls/GreetingsActionBar.xsp.metadata:<noteinfo noteid="1b6" sequence="56" unid="DBA74B5F00B8CC860025852300462F9D">
    ./nsfs/nsf-moonshine/odp/CustomControls/GreetingsActionBar.xsp.metadata:<addedtofile><datetime>20200310T133232,90-05</datetime></addedtofile></noteinfo>
    ./nsfs/nsf-moonshine/odp/CustomControls/Footer.xsp.metadata:<noteinfo noteid="1a6" sequence="38" unid="8E9248A06FCA9D6C0025852300433B9E">
    ./nsfs/nsf-moonshine/odp/CustomControls/Footer.xsp.metadata:<addedtofile><datetime>20200310T133232,82-05</datetime></addedtofile></noteinfo>
    ./nsfs/nsf-moonshine/odp/Pages/HelloWorld.page:<noteinfo noteid='15e' unid='A85F9604D99B61ED8625851C006F9D79' sequence='2'>
    ./nsfs/nsf-moonshine/odp/Pages/HelloWorld.page:<addedtofile><datetime>20200310T133232,54-05</datetime></addedtofile></noteinfo>
    ./nsfs/nsf-moonshine/odp/Views/All By UNID.view:<noteinfo noteid='182' unid='A4D7A061CC05A3BD8625851C007089A5' sequence='2'>
    ./nsfs/nsf-moonshine/odp/Views/All By UNID.view:<addedtofile><datetime>20200310T133232,64-05</datetime></addedtofile></noteinfo>
    ./nsfs/nsf-moonshine/odp/Views/All By UNID_5cBy Creation Date.view:<noteinfo noteid='186' unid='47898DA16B6ACAE78625851C007089A6' sequence='2'>
    ./nsfs/nsf-moonshine/odp/Views/All By UNID_5cBy Creation Date.view:<addedtofile><datetime>20200310T133232,66-05</datetime></addedtofile></noteinfo>
    ./nsfs/nsf-moonshine/odp/Views/Greetings.view:<noteinfo noteid='14e' unid='290445B60A324C128625851C006E8909' sequence='9'>
    ./nsfs/nsf-moonshine/odp/Views/Greetings.view:<addedtofile><datetime>20200310T133232,46-05</datetime></addedtofile></noteinfo>
    ./nsfs/nsf-moonshine/odp/Views/All By UNID_5cBy Form Used.view:<noteinfo noteid='18a' unid='166840A1ADDFA4148625851C007089A7' sequence='2'>
    ./nsfs/nsf-moonshine/odp/Views/All By UNID_5cBy Form Used.view:<addedtofile><datetime>20200310T133232,68-05</datetime></addedtofile></noteinfo>
    ./nsfs/nsf-moonshine/odp/Views/All By UNID_5cBy Last Modified.view:<noteinfo noteid='18e' unid='300F8324C7F108A28625851C007089A8' sequence='2'>
    ./nsfs/nsf-moonshine/odp/Views/All By UNID_5cBy Last Modified.view:<addedtofile><datetime>20200310T133232,70-05</datetime></addedtofile></noteinfo>

    # Forms
    $ grep -r "noteinfo" . | grep "\.form"
    ./nsfs/nsf-moonshine/odp/Forms/Greeting.form:<noteinfo noteid='14a' unid='A1246159B21013448625851C006E2D54' sequence='8'>
    ./nsfs/nsf-moonshine/odp/Forms/Greeting.form:<addedtofile><datetime>20200310T133232,44-05</datetime></addedtofile></noteinfo>


Domino Visual Editor:

    $ grep -r "noteinfo" .
    ./nsfs/nsf-moonshine/odp/Code/dbscript.lsdb:<noteinfo noteid='1e6' unid='FF5C59FBC8F213F68525846D004F6307' sequence='3'>
    ./nsfs/nsf-moonshine/odp/Code/dbscript.lsdb:<addedtofile><datetime dst='true'>20190906T102706,98-04</datetime></addedtofile></noteinfo>
    ./nsfs/nsf-moonshine/odp/AppProperties/$DBIcon:<noteinfo noteid='1b2' unid='61088A7D74BC85358525846D004D6230' sequence='1'>
    ./nsfs/nsf-moonshine/odp/AppProperties/$DBIcon:<addedtofile><datetime dst='true'>20190906T100514,13-04</datetime></addedtofile></noteinfo>
    ./nsfs/nsf-moonshine/odp/Resources/AboutDocument:<noteinfo noteid='1aa' unid='DAEA2AEE8C53C5D98525846D004D5520' sequence='2'>
    ./nsfs/nsf-moonshine/odp/Resources/AboutDocument:<addedtofile><datetime dst='true'>20190906T100440,83-04</datetime></addedtofile></noteinfo>
    ./nsfs/nsf-moonshine/odp/Resources/UsingDocument:<noteinfo noteid='1ae' unid='CBE3F4934D0ED2158525846D004D5743' sequence='2'>
    ./nsfs/nsf-moonshine/odp/Resources/UsingDocument:<addedtofile><datetime dst='true'>20190906T100446,15-04</datetime></addedtofile></noteinfo>
    ./nsfs/nsf-moonshine/odp/Views/Example View.view:<noteinfo noteid='1a2' unid='3F30E94182403E568525846B00645880' sequence='3'>
    ./nsfs/nsf-moonshine/odp/Views/Example View.view:<addedtofile><datetime dst='true'>20190904T141602,56-04</datetime></addedtofile></noteinfo>
    $ grep -r "noteinfo" . | grep "\.form"


I see you mentioned Greeting.form.  We want to keep this in the template as an example form.  We also have examples of other project types.

**Comment by JoelProminic** [comment]
@feather812002, please revisit this tomorrow.   If it is not a problem to clear the `noteinfo` for the other template files, I'd like to get this updated so that we can hopefully do a release soon.

**Comment by feather812002** [comment]
When I try to test this issue in today , I got the maven error again:

> TypeError: Error #1009: Cannot access a property or method of a null object reference.
> 	at actionScripts.plugins.maven::MavenBuildPlugin/start()[/Users/prominic2/work/Moonshine-
> IDE_fresh/ide/MoonshineDESKTOPevolved/src/actionScripts/plugins/maven/MavenBuildPlugin.as:170]

In my memory ,we already fix a similar issue on before , I don't know why it display again ?
The test version is :a0b5a710

**Comment by feather812002** [comment]
I try to create a new Domino Visual editor project and Domino On Disk project , I confirm the notesinfo already clear .
And can build success with "mvn install" command in the terminal .

So, I think after we fix the mvn build in the Moonshine IDE , we can close this issue.

**Comment by piotrzarzycki21** [comment]
> When I try to test this issue in today , I got the maven error again:
> 
> > TypeError: Error #1009: Cannot access a property or method of a null object reference.
> > at actionScripts.plugins.maven::MavenBuildPlugin/start()[/Users/prominic2/work/Moonshine-
> > IDE_fresh/ide/MoonshineDESKTOPevolved/src/actionScripts/plugins/maven/MavenBuildPlugin.as:170]
> 
> In my memory ,we already fix a similar issue on before , I don't know why it display again ?
> The test version is :a0b5a710

@feather812002 this should be fixed. If you try to get to the state where your java path are not set, you will get proper notification in console and Moonshine jump to settings.

**Comment by feather812002** [comment]
> > When I try to test this issue in today , I got the maven error again:
> > > TypeError: Error #1009: Cannot access a property or method of a null object reference.
> > > at actionScripts.plugins.maven::MavenBuildPlugin/start()[/Users/prominic2/work/Moonshine-
> > > IDE_fresh/ide/MoonshineDESKTOPevolved/src/actionScripts/plugins/maven/MavenBuildPlugin.as:170]
> > 
> > 
> > In my memory ,we already fix a similar issue on before , I don't know why it display again ?
> > The test version is :a0b5a710
> 
> @feather812002 this should be fixed. If you try to get to the state where your java path are not set, you will get proper notification in console and Moonshine jump to settings.

Yes, I test it ,it work fine at now .
Thanks.

**Comment by feather812002** [comment]
@JoelProminic 
Hello, Joel , I remove all the "noteinfo" from Moonshine-IDE.
And I can build it with maven command after I remove this .
But I found other issue.

If we setting the "maven setting" in project level for "~/Downloads/MoonshineSDK/Domino/setting.xml", the maven build will fail and report follow error:

> : [ERROR] Failed to execute goal org.openntf.maven:nsfodp-maven-plugin:3.4.0:compile (default-compile) on project nsf-moonshine-domino: Exception while compiling the NSF: Encountered exception while launching application: Notes plugins directory does not exist: /Users/prominic2/.m2/plugins -> [Help 1]

After I remove the project level setting , then runing the mvn build command from the Moonshine IDE , it work fine.

**Comment by feather812002** [comment]
I check the "~/Downloads/MoonshineSDK/Domino/setting.xml" into details :
`  <notes-platform>file:///Users/prominic2/.m2</notes-platform>`

So , this maybe have a error , why the "notes-platform" path in the "~/.m2", the correct way why not is "/Applications/HCL Notes.app/Contents/MacOS" ?

**Comment by feather812002** [comment]
Other issue , when I try to build with MockVisulEditor with ant command from terminal .
If I work with "Flex_4.16.1_AIR_33.1", I got follow error:

> 'Users/prominic2/Downloads/MoonshineSDKs/Flex_SDK/Flex_4.16.1_AIR_33.1/frameworks/flex-config.xml(85): Error: unable to open 'libs/player/33.1'

If I switch to "32.0" , it build success.

**Comment by piotrzarzycki21** [comment]
> Other issue , when I try to build with MockVisulEditor with ant command from terminal .
> If I work with "Flex_4.16.1_AIR_33.1", I got follow error:
> 
> > 'Users/prominic2/Downloads/MoonshineSDKs/Flex_SDK/Flex_4.16.1_AIR_33.1/frameworks/flex-config.xml(85): Error: unable to open 'libs/player/33.1'
> 
> If I switch to "32.0" , it build success.

Please make sure that you downloaded this SDK with Moonshine SDK Installer 3.9.0 - It just got release. It should have fix for this problem.

**Comment by feather812002** [comment]
> > Other issue , when I try to build with MockVisulEditor with ant command from terminal .
> > If I work with "Flex_4.16.1_AIR_33.1", I got follow error:
> > > 'Users/prominic2/Downloads/MoonshineSDKs/Flex_SDK/Flex_4.16.1_AIR_33.1/frameworks/flex-config.xml(85): Error: unable to open 'libs/player/33.1'
> > 
> > 
> > If I switch to "32.0" , it build success.
> 
> Please make sure that you downloaded this SDK with Moonshine SDK Installer 3.9.0 - It just got release. It should have fix for this problem.

Yeah, I try the Moonshine-SDK-Installer 3.9.0(build 293) , it work fine wit 33.1 version of Flex SDK.
Thanks.

**Comment by JoelProminic** [comment]
I tested the two project types, and I confirmed that all the <noteinfo> references are removed now.

However, for Domino On Disk Project, I see errors for the About and Using pages (under Help):
![image](https://user-images.githubusercontent.com/24532731/127017155-1631d202-c23b-4a28-8bce-2516be0566b6.png)

For the Domino Visual Editor project, these pages work fine.

`<notes-platform` should be set like this:

    <notes-platform>file:///Users/joelanderson/Downloads/MoonshineSDKs/Domino/UpdateSite</notes-platform>

The update site can be configured or generated in Moonshine > Settings > Domino.

**Comment by JoelProminic** [comment]
It looks like the About and Using pages were copied from the Domino Visual Editor template.   I thought that the original template for the On Disk Project had these files already, but after further review I see that the About and Using documents were not included in the original example database!  Anyway, the new documents work well, so this should be good.

Otherwise, the updated templates look good, and I confirmed that the other design elements work in the compiled database.
