### ISSUE TITLE
Copyright Information for NSF ODP Tooling

### ISSUE THREAD

**Issue by JoelProminic** [Moonshine-IDE/Moonshine-IDE#857]
From @JustinProminic 
>Are we bundling with Moonshine itself the NSF ODP tooling?
>
>https://github.com/OpenNTF/org.openntf.nsfodp
>
>
>I don't see it in the Moonshine SDK Installer, so I assume we must be bundling it.
>
>And that is probably what we should continue to do.
>
>
>However, we need to make sure we have proper copyright attributions in the Moonshine About dialog and on the startup console for any copyrighted software (including other ones I'm not thinking of at the moment).
>
>
>We need to be respectful of the work others have put in and don't want to make users assume that what we have done is all just Moonshine IDE authors.  I think that would really upset some people who have poured countless hours into projects like NSF ODP tooling.

**Comment by JoelProminic** [comment]
@JustinProminic suggested that we put something for this in 
- a "Special Thanks" section that should also mention the developers that have worked on this project
- A message on the console on startup

Another idea I had was to include it on the Settings > Domino page.

**Comment by JoelProminic** [comment]
For the special thanks section, we'll want to include:
- "Jesse Gallagher and the OpenNTF team"

**Comment by JoelProminic** [comment]
For now, I think what makes the most sense is to add a message in Settings > Domino below the "HCL Notes / Domino Integration" header:

> Based on [NSF ODP Tooling](https://github.com/OpenNTF/org.openntf.nsfodp) by Jesse Gallagher and the OpenNTF team.

This should be in italics so that it stands out from the header.  If it is a problem put this here, I am open to other suggestion.

I included a link to the main GitHub project for NSFODP.  Other option would be the documentation [here](https://frostillic.us/blog/posts/2019/7/8/f9643d0349dfd211852584310054b892), but I think the GitHub page is a better place to start.

**Comment by rat-moonshine** [comment]
> For now, I think what makes the most sense is to add a message in Settings > Domino below the "HCL Notes / Domino Integration" header:

It would be a bit tricky. The "HCL Notes / Domino Integration" is part of the header/title component showing as a description in plain text. Currently this doesn't has any special way to show but plain text and no link text.

Any followed by sections displays as a list of items separated with horizontal lines, so adding the NSF ODP Tooling message will make it a separate item only as this:
![image](https://user-images.githubusercontent.com/24370870/139788359-b5308c2e-3462-4c78-9039-c6485b07eb6f.png)

We can either think about someplace else to place the message, or if we still need the message to be underneath the title/description I'll need to modify the component behaviour.

**Comment by JoelProminic** [comment]
The updated message looks good, and I confirmed the link works.
