### ISSUE TITLE
About Page Fails with Error #1009

### ISSUE THREAD

**Issue by JoelProminic** [Moonshine-IDE/Moonshine-IDE#861]
Extracted from:  https://github.com/prominic/Moonshine-IDE/issues/841#issuecomment-861584133

> I noticed that @feather812002's screenshot showed that the SDK list on the About page was blank. 
>![image](https://user-images.githubusercontent.com/8543391/122064168-9b3dc700-cdf9-11eb-822f-92a24e83e560.png)
>
>I found I was able to reproduce the same error with build 1964 (Installed yesterday for @piotrzarzycki21's orginal fix). I see this error on the console:
> 
> ```
> : Error #1009
> : TypeError: Error #1009
> : 	at components.popup::SoftwareInformation/onSoftwareInfoCreationComplete()
> : 	at components.popup::SoftwareInformation/___SoftwareInformation_VGroup1_creationComplete()
> : 	at flash.events::EventDispatcher/dispatchEvent()
> : 	at mx.core::UIComponent/dispatchEvent()
> : 	at mx.core::UIComponent/set initialized()
> : 	at mx.managers::LayoutManager/doPhasedInstantiation()
> : 	at mx.managers::LayoutManager/doPhasedInstantiationCallback()
> :
> : Click here to Report a Bug
> ```
> 
> Is this related to the updates for this issue? Otherwise, we can move it to a new issue.

**Comment by rat-moonshine** [comment]
This issue is fixed and ready for a test.

**Comment by JoelProminic** [comment]
I confirmed this on my macOS workstation, and also on Windows.

**Comment by Aszusz** [comment]
Now, About page fails with error #2004
```
: Error #2004
: ArgumentError: Error #2004
: 	at mx.utils::ObjectUtil$/copy()
: 	at components.popup::SoftwareInformation/onSoftwareInfoCreationComplete()
: 	at components.popup::SoftwareInformation/___SoftwareInformation_VGroup1_creationComplete()
: 	at flash.events::EventDispatcher/dispatchEvent()
: 	at mx.core::UIComponent/dispatchEvent()
: 	at mx.core::UIComponent/set initialized()
: 	at mx.managers::LayoutManager/doPhasedInstantiation()
: 	at mx.managers::LayoutManager/doPhasedInstantiationCallback()
```
This is on both Mac and Windows. Yesterday there was no error.

**Comment by rat-moonshine** [comment]
The error should have fixed now. Please, check.

**Comment by piotrzarzycki21** [comment]
Yep everything is working just fine.

**Comment by Aszusz** [comment]
Works for me too, I'm closing the issue.
