### ISSUE TITLE
Getting Started Haxe UI Tuning

### ISSUE THREAD

**Issue by rat-moonshine** [Moonshine-IDE/Moonshine-IDE#863]
This originally reported by @JoelProminic at here - https://github.com/prominic/Moonshine-IDE/issues/782#issuecomment-860938290.

> I checked the new Getting Started interface:
> 
> ![image](https://user-images.githubusercontent.com/24532731/121948787-4cbafa80-cd1d-11eb-9878-5423aebd1427.png)
> 
> 
> Some problems I noticed:
> - The "Download Third-Party Software" button is too small.  This needs to stand out more, since want to make it easy and clear for "normal" users to just click this button to get their environment fully set up.
> - I see I have the option to choose between Nightly and Stable builds of Apache Royale.  If I choose nightly, some icon appears in the UI, but it is barely visible.  in the old Moonshine interface, this dropdown was not visible.
> - The License Agreement link for Apache Flex SDK is broken.  The Subversion and Git license agreements are also broken, but I'm not sure if we had license agreements for these.  All other license areement links seem fine.
> - The animation when clicking "Do no show this tab on startup" seems oddly slow.  The "Only show features that need setup checkbox is fast.
> - The title should be changed from "Getting Started Haxe" to "Getting Started" before release.

We can track the request status here as #782 being closed.

**Comment by rat-moonshine** [comment]
> The animation when clicking "Do no show this tab on startup" seems oddly slow. The "Only show features that need setup checkbox is fast.

I'm not sure if I can adjust this somehow, though.

**Comment by rat-moonshine** [comment]
> I see I have the option to choose between Nightly and Stable builds of Apache Royale. If I choose nightly, some icon appears in the UI, but it is barely visible. in the old Moonshine interface, this dropdown was not visible.

Fixed.

> The License Agreement link for Apache Flex SDK is broken. The Subversion and Git license agreements are also broken, but I'm not sure if we had license agreements for these. All other license areement links seem fine.

Looks like this is working in latest builds.

**Comment by JoelProminic** [comment]
The "License Agreement" link doesn't work for the Apache Flex SDK entries in By Software.  These links have special logic which was discussed in this issue: https://github.com/Moonshine-IDE/Moonshine-SDK-Installer/issues/58 .  Otherwise, the links look good.

I confirmed that the re-download button is not cut off for the Nightly Royale build now, but I noticed that the icon is different for the By Feature and By Software views.  I don't really like the "RE-DO" icon, so lets continue using the other icon.

![image](https://user-images.githubusercontent.com/24532731/123172520-e03dab00-d442-11eb-83f4-5f362e03d571.png)
![image](https://user-images.githubusercontent.com/24532731/123172533-e469c880-d442-11eb-9c46-26993d2104b2.png)

I see the Configure icon is visible now.

**Comment by rat-moonshine** [comment]
> The "License Agreement" link doesn't work for the Apache Flex SDK entries in By Software.

I realised you was pointing _when_ running inside Moonshine. I fixed it now. Based on legacy Getting Started, the license-agreement link is now hidden when running inside Moonshine but MSDKI.

**Comment by JoelProminic** [comment]
I confirmed that the License Agreement link is hidden now.

For the RE-DO button, we are using the Download icon instead for MSDKI, and this is fine for now.

**Comment by rat-moonshine** [comment]
Update status from this issue:

- [ ] Download 3rd-Party Software button is not highlighted enough (in-progress, having style-sheet conflicts)
- [x] Download icon cut-off the screen in case of Royale Nightly 
- [x] License Agreement links are broken for some items
- [x] "Do not show this tab on startup" checkbox animation is slow
- [x] Title should be changed from 'Getting Started Haxe' to 'Getting Started'
- [x] Change re-download button in "By Features" tab

**Comment by JoelProminic** [comment]
We still need to remove Help > Getting Started(Legacy) to fix this.

The "Do not show this tab on startup" checkbox still has a noticeable delay on macOS, but it is not a problem.  We don't need to spend more time on this.

Otherwise, the updates look good.

**Comment by rat-moonshine** [comment]
`Getting Started (Legacy)` link is now removed in Moonshine-IDE. However, the UI codes are still available in the source.

**Comment by piotrzarzycki21** [comment]
> `Getting Started (Legacy)` link is now removed in Moonshine-IDE. However, the UI codes are still available in the source.

If you are not going to remove old code, please raise issue so we can do that later on. This one should be closed.

**Comment by rat-moonshine** [comment]
I think this issue is fine to have closed. I just keep the old Flex UI for code references, however that can be done by comparing against archive source, as well. 

Let's close this.

**Comment by JoelProminic** [comment]
![image](https://user-images.githubusercontent.com/24532731/125819750-f1a43f44-0b69-4cf6-9620-be4f54e8f68c.png)

This looks fine to me.  I reset the updater.xml file, and confirmed that the prompt does not show up in this case.
