### ISSUE TITLE
Some projects has been reopen on Moonshine restart even when they were closed before 

### ISSUE THREAD

**Issue by piotrzarzycki21** [Moonshine-IDE/Moonshine-IDE#864]
I have found some edge case scenario where we have following project:

/Users/piotr/Dev/ExternalTest - name: "ExternalProject"

However over the road this project has changed the name to "ExternalTest". In some scenario for example when user manually (not in Moonshine) change name of the project it may stay in cookies as leftovers. Which causes in sometimes reopen for a project on startup, even if we closed it previously.

We are removing project based on:
- name 
- root folder path

I'm considering change that to remove project from cookie based only on path - Thougths ?

**Comment by JoelProminic** [comment]
@piotrzarzycki21, can you clarify what you changed here?   I'm not sure how to test this, or what else could be affected by this change.

**Comment by piotrzarzycki21** [comment]
@JoelProminic you don't need to go trough the case above. The only test is that, if you open couple of projects and later close some of them  - restart Moonshine - does projects reopen correctly ? You shouldn't see projects closed earlier.
