### ISSUE TITLE
Update References to Moonshine Projects to use Moonshine-IDE Organization

### ISSUE THREAD

**Issue by JoelProminic** [Moonshine-IDE/Moonshine-IDE#865]
We recently moved the Moonshine projects to the Moonshine-IDE organization.  The old URLs should redirect automatically, but I'd like to update any references we have.

For example, we need to update the default Git repositories:

![image](https://user-images.githubusercontent.com/24532731/123146238-487c9480-d423-11eb-8a7f-08a1c4f784d9.png)

And we also need to update the [moonshine-dependencies.xml](https://github.com/Moonshine-IDE/Moonshine-IDE/blob/bca63d93d5eebeb459b4d78263cb6c8a6070db8d/moonshine-dependencies.xml) files.  There may be additional moonshine-dependencies.xml files in the referenced projects.

Let me know if you find any other references that need to be updated.

**Comment by piotrzarzycki21** [comment]
Urls adjusted. @Aszusz test this on windows - make sure that nightly have latest commit.

**Comment by Aszusz** [comment]
The nagithly has the latest commit.
The URLs are updated:
![image](https://user-images.githubusercontent.com/7197014/127205821-d5ce530e-b625-4d19-8c76-dd011901165f.png)

However, I'm unable to clone them using default Moonshine's git installation. I'll investigate further and open another issue. This one can be closed.

**Comment by JoelProminic** [comment]
I confirmed that the updated links wok for macOS.  I also updated the moonshine-dependencies.xml file for XHTMLConverter.

The only remaining oddity I see is that if the user installed Moonshine before this version, they will have old prominic links that won't update:

![image](https://user-images.githubusercontent.com/24532731/127364867-6cff8863-8436-41ab-bb64-7346d969c9c9.png)

**Comment by piotrzarzycki21** [comment]
> I confirmed that the updated links wok for macOS. I also updated the moonshine-dependencies.xml file for XHTMLConverter.
> 
> The only remaining oddity I see is that if the user installed Moonshine before this version, they will have old prominic links that won't update:
> 
> ![image](https://user-images.githubusercontent.com/24532731/127364867-6cff8863-8436-41ab-bb64-7346d969c9c9.png)

I'm closing this one. Raise another issue if we wanted to have fix for that. However I think we should stay as is with this for now.
