### ISSUE TITLE
External JDK Path is Not Preserved Properly

### ISSUE THREAD

**Issue by JoelProminic** [Moonshine-IDE/Moonshine-IDE#866]
While testing #841 on macOS, I noticed this strange behavior:
1. Delete or rename ~/Downloads/MoonshineSDKs/Java/openjdk-11.0.10
2. Download and install AdoptOpenJDK from https://adoptopenjdk.net/ .  This should install to `/Library/Java/JavaVirtualMachines/adoptopenjdk-11.jdk/Contents/Home`
3. Restart Moonshine
4. Settings > Default SDK.  Note that Java Development Kit Root Path is Not Set
5. Set Java Development Kit Root Path to the JDK path from the installation above.  Use CMD-Shift-G to enter the path
6. Save the settings
7. Create a new Flex Desktop project
8. Project > Build & Run.  This runs successfully, so the JDK is valid
9. Restart Moonshine
10. Open Settings > Default SDK.  BUG:  Java Development Kit Root Path again shows "Not Set"
11. Run Project > Build & Run for the same project.   This again runs successfully, which makes me thing that Java Development Kit Root Path is still set somewhere in Moonshine.

I expect the external JDK to be preserved in this case.

@rat-moonshine can't reproduce this problem.  @piotrzarzycki21 , can you take a look when you have a chance?

**Comment by rat-moonshine** [comment]
I tested again today with latest nightly build.2009, I see the modified JDK path `/Library/Java/JavaVirtualMachines/adoptopenjdk-11.jdk/Contents/Home` persists properly even after a Moonshine restart.

**Comment by JoelProminic** [comment]
I retested this today, and I am also seeing that I can't reproduce the problem on my primary workstation (macOS 10.15.7):
1. Delete/Rename JDK 11 in ~/Downloads/MoonshineSDKs/Java
2. In Moonshine, set an external Java path
3. Restart Moonshine
4. Check the Java Path.  This is still set to the external path.


@feather812002 and I both saw this problem before when testing #841, though.  Could some other recent change have changed this behavior?  Maybe the settings were in an unusual state before, and this has been cleared by more testing.

**Comment by JoelProminic** [comment]
I should check this on my laptop, since I think this is where I had the problem originally.

**Comment by JoelProminic** [comment]
I can't reproduce this issue any more, so I am closing it and removing it from the milestone.  We can reopen it if we see it again.

**Comment by rat-moonshine** [comment]
I did some updates. Let me know if the following test-matrix looks good now.

JDK | JDK8 | JDK 11 Exists | JDK 8 Exists | Custom JDK | Description
------|------|--------------|------------|----------------|-------------
Nil | Nil | Yes | Yes | - | On restart, JDK set to v11, JDK8 set to v8
Nil | Nil | No | Yes | - | On restart, JDK not-set, JDK8 set to v8
Nil | 8 | No | Yes | - | On restart setting doesn't change
Nil | 8 | Yes | Yes | - | On restart, JDK set to v11, JDK8 doesn't change
11 | 8 | Yes | Yes | Set to v8 | On restart, settings doesn't change (JDK and JDK8 both has v8)
8 | 8 | Yes | Yes | - | On restart settings doesn't change
8 | 8 | Yes | Yes | Set to v17 | On restart settings doesn't change (JDK is v17, JDK8 is v8)

**Comment by JoelProminic** [comment]
The logic looks fine with the updated test matrix.  I retested the user stories with App Store build 2183:

Test | Result
-----|-------
Fresh Install | Works
Standard Install | Works
Custom Install (JDK 8) | Works
Custom Install (JDK 17) | Works
Upgrade to JDK 11 | Works

**Comment by JoelProminic** [comment]
@Aszusz reported similar problems on Windows.  In this case, the Java Development Kit was overwritten by the system JAVA_HOME environment variable.   We need to do a test for this case with the updated logic from the development build before the 3.2.0 release.

**Comment by Aszusz** [comment]
I tested this some more:
- on MoonshineDevelopment-3.2.0.exe I could still reproduce the issue
- on MoonshineDevelopment-installer.exe (build 643) the issue was gone

The other problem is I don't see a way to download JDK 11 through Moonshine. It ships with JDK 17 by default and JDK 11 is needed to make Java Gradle projects compile.

**Comment by JoelProminic** [comment]
I installed Temurin JDK 17 on Windows to do some tests.  I chose to set JAVA_HOME in the installer:

![image](https://user-images.githubusercontent.com/24532731/140192150-783c30ab-f279-4ff4-93c8-ab2cc6fa1297.png)

I did some tests with the 3.2.0 release candidate, build 646:

Test | Result
-----|-------
Fresh Install, JAVA_HOME only | JDK set to JAVA_HOME.  Note that I can't download JDK 11 through MSDKI in this case because Java is already considered installed.
Fresh Install, JAVA_HOME and v88 | Only JDK 8 is set
Fresh Install, JAVA_HOME, v8, v11 | Works, JDK is set with v11
Standard Install, JAVA_HOME set |  Works
Custom Install (JDK 8) | Works
Custom Install (JDK 17) | Works
Upgrade to JDK 11 | FAILED - JDK still set to v8

So, I see that the upgrade case is not working like I expect.  We may want to revisit the JAVA_HOME logic eventually, but this is fine for now.

I see @Aszusz's point on installing JDK 11.  If JAVA_HOME is set to a valid value, then OpenJDK will always be considered installed by MSDKI.  We may want a separate issue for this.

**Comment by rat-moonshine** [comment]
> Upgrade to JDK 11 | FAILED - JDK still set to v8

I'm little unclear about this scenario. Based on our earlier discussions if JDK is set to v8, Moonshine is suppose to use that only even a v11 exists in `MoonshineSDKs/Java` (or elsewhere). 

By saying "Upgrade to JDK  failed" did you meant following scenario where JDK suppose to be changed to v11?

1. JDK is v8, JDK8 is v8, user didn't has v11 installed at all
2. User installed v11 using MSDKI
3. If user restart Moonshine - based on [earlier](https://github.com/Moonshine-IDE/Moonshine-IDE/issues/866#issuecomment-956084635) logic set s/he continues to see JDK is v8 - no change in there
4. If user already has Moonshine opened during the v11 installation - Moonshine gets the notification and forcefully change JDK from v8 to v11 (?) - is this which is failed?

If above 4 is true, then what if JDK has >11 - will it need to need update the path anyway or does it requires a version comparison?

**Comment by JoelProminic** [comment]
We discussed this logic more today, but we couldn't prepare a quick solution for this.   For 3.2.0, we'll keep the current logic, and we can update this further in later milestones

**Comment by rat-moonshine** [comment]
I'm reopening this for 3.3.0 release as we wanted to do some more tuning which we skipped during v3.2.0 release.

**Comment by JoelProminic** [comment]
The only case that is failing here is the legacy update case, so I don't think it is worth spending more time on this for now.  If we do want to revisit this case, we should create a separate issue.

@rat-moonshine, if you had brainstormed any ideas for this already, feel free to record them in this issue for future reference.
