### ISSUE TITLE
Manage Repositories -> Browse All - Is Broken

### ISSUE THREAD

**Issue by rat-moonshine** [Moonshine-IDE/Moonshine-IDE#867]
Clicking on `Manage Repositories -> Browse All` throws TypeError#1009.

**Comment by rat-moonshine** [comment]
This issue fixed as part of #849 .

**Comment by piotrzarzycki21** [comment]
Can you close this? If you are working on it as part of #849 let's do not mix things and duplicate.

**Comment by JoelProminic** [comment]
Here is the behavior I saw for Browse All on macOS

Git Path | SVN Path | Git Repositories | SVN Repositories | XML Entries
---------|----------|------------------|------------------|------------
Set | Set | Included | Included | Included
Unset | Unset | Missing | Missing | Included
Unset | Set | Missing | Included | Included
Set | Unset | Included | Missing | Included

Also, if both Git and Subversion are not set, I see this message at the bottom of the Browse and Browse All screens:

> Git &amp; Subversion is unavailable.  Unable to Browse the related repositories.

Instead, this should be:

> Git and Subversion are unavailable.  Unable to Browse the related repositories.

**Comment by piotrzarzycki21** [comment]
> Also, if both Git and Subversion are not set, I see this message at the bottom of the Browse and Browse All screens:
> 
> > Git & Subversion is unavailable.  Unable to Browse the related repositories.
> 
> Instead, this should be:
> 
> > Git and Subversion are unavailable.  Unable to Browse the related repositories.

This has been corrected. Anything more with that issue ?

**Comment by JoelProminic** [comment]
I see that it is still using the "&" character, which is not showing up properly:
![image](https://user-images.githubusercontent.com/24532731/125658866-757888c9-1325-4eea-9b1b-f9178432fa07.png)

I'd like to just use "and" instead to avoid this.

**Comment by piotrzarzycki21** [comment]
Message is fixed. I'm closing this issue.
