### ISSUE TITLE
Missing JDK 11 Breaks Domino Visual Editor 

### ISSUE THREAD

**Issue by JoelProminic** [Moonshine-IDE/Moonshine-IDE#871]
@feather812002 [reported](https://github.com/Moonshine-IDE/Moonshine-IDE/issues/853#issuecomment-870601288) that he got this error when trying Project > Build Apache Maven for a Domino Visual Editor project on macOS:

    : Error #1009: Cannot access a property or method of a null object reference.
    : TypeError: Error #1009: Cannot access a property or method of a null object reference.
    : at actionScripts.plugins.maven::MavenBuildPlugin/start()[/Users/prominic2/work/Moonshine-IDE_fresh/ide/MoonshineDESKTOPevolved/src/actionScripts/plugins/maven/MavenBuildPlugin.as:170]
    : at actionScripts.plugins.maven::MavenBuildPlugin/prepareStart()[/Users/prominic2/work/Moonshine-IDE_fresh/ide/MoonshineDESKTOPevolved/src/actionScripts/plugins/maven/MavenBuildPlugin.as:244]
    : at actionScripts.plugins.maven::MavenBuildPlugin/startConsoleBuildHandler()[/Users/prominic2/work/Moonshine-IDE_fresh/ide/MoonshineDESKTOPevolved/src/actionScripts/plugins/maven/MavenBuildPlugin.as:258]
    : at flash.events::EventDispatcher/dispatchEventFunction()

I saw that he still did not have a value set for Java Development Kit Root Path, possibly because of #866.  However, Domino Visual Editor should only depend on JDK 8.  JDK 8 is required for compilation, and there is no language server.  I can reproduce the problem like this:
1. Move/Delete JDK 11 in ~/Downloads/MoonshineSDKs/Java
2. Clear Java Development Kit Root Path
3. Open/Create a new Domino Visual Editor projecjt:  File > New > Visual Editor Project, change type to "Domino NSF Database Visual Editor"
4. Project > Build with Apache Maven.  BUG:  I get the error below
5. Set an external JDK path for Java Development Kit Root Path
6. Project > Build with Apache Maven.  This works for me, but you may get errors if you have not setup your workstation for On Disk Project.

    : Error #1009
    : TypeError: Error #1009
    : 	at actionScripts.plugins.maven::MavenBuildPlugin/start()
    : 	at actionScripts.plugins.maven::MavenBuildPlugin/prepareStart()
    : 	at actionScripts.plugins.maven::MavenBuildPlugin/startConsoleBuildHandler()
    : 	at flash.events::EventDispatcher/dispatchEvent()
    : 	at actionScripts.utils::KeyboardShortcutManager/dispatch()
    : 	at actionScripts.utils::KeyboardShortcutManager/stopEvent()
    : 	at actionScripts.ui.menu::MenuPlugin/redispatch()
    :
    : Click here to Report a Bug

**Comment by JoelProminic** [comment]
@feather812002, please revisit this issue.   I have instructions in the description for how to update your environment to reproduce this.

**Comment by feather812002** [comment]
@JoelProminic I try test this ,this still have a issue, 
When open the latest version of Moonshine IDE, the "Java Development Kit 8 Root Path" can get the default JAVA SDK path from system .
But the "Jave Development Kit Root Path" still is keep empty .
And when I run the "build with maven " from Domino Visual project, I got a error.

![image](https://user-images.githubusercontent.com/8543391/126616706-0d74ecdf-ea59-4d1c-8f76-e4abb4214d56.png)

If I manual setting the "Jave Development Kit Root Path"  with system JAVA JDK path , it work fine again.

I think we still need fix this .

Or we should always remind user setting the "Jave Development Kit Root Path"  , if it is empty .

Thanks.

**Comment by JoelProminic** [comment]
@rat-moonshine, can you look into the remaining JDK 11 dependency here?   I have a test procedure in the description.

**Comment by rat-moonshine** [comment]
I did couple of fix per our discussion with @JoelProminic :

1. Domino Visual Editor project `Settings -> Java` now showing only JDK 8 option
![image](https://user-images.githubusercontent.com/24370870/126939658-c24ed308-2fd4-4155-b739-cf3fd774d4f4.png)
2. I have adjusted `MavenBuildPlugin` to look-for and use only JDK 8 during `Build with Apache Maven` in case of Domino Visual Editor project. This fix shouldn't anymore require to have `Java Development Kit Root Path` to be present

Please, check.

**Comment by JoelProminic** [comment]
I moved my JDK 11 install and tested a new Domino Visual Editor project, and this is working properly now.   I checked a new Domino On Disk Project as well (while testing another issue), and this works as well.
