### ISSUE TITLE
Java Project Fails to Open with .javaproj Name Mismatch

### ISSUE THREAD

**Issue by JoelProminic** [Moonshine-IDE/Moonshine-IDE#883]
1. Create a new Java Gradle project
2. Project opens properly
3. Close the project
4. Open the projet again from Project > Open/Import project
5. Close the project
6. Rename the project directory
7. Try to open the project again from Project > Open/Import project.  BUG:  This gives an error
8. Try to open th project again by double-clicking the .javaproj file in Finder.  BUG:  this gives an error

Error on Project > Open/Import Java Project

    : Error #1009
    : TypeError: Error #1009
    : 	at actionScripts.plugin.java.javaproject.importer::JavaImporter$/parse()
    : 	at actionScripts.impls::IJavaBridgeImpl/parseJava()
    : 	at actionScripts.plugin.actionscript.as3project::AS3ProjectPlugin/openProjectByDirectory()
    : 	at actionScripts.plugin.actionscript.as3project::AS3ProjectPlugin/loadOrReportOnRepositoryProjects()
    : 	at actionScripts.plugin.actionscript.as3project::AS3ProjectPlugin/onWorkerValueIncoming()
    : 	at flash.events::EventDispatcher/dispatchEvent()
    : 	at actionScripts.locator::IDEWorker/onWorkerToMain()
    :
    : Click here to Report a Bug

Error on opening .javaproj

    : Error #1009
    : TypeError: Error #1009
    : 	at actionScripts.plugin.java.javaproject.importer::JavaImporter$/parse()
    : 	at actionScripts.impls::IJavaBridgeImpl/parseJava()
    : 	at actionScripts.plugin.actionscript.as3project::AS3ProjectPlugin/openProjectByDirectory()
    : 	at actionScripts.plugin.actionscript.as3project::AS3ProjectPlugin/importProjectWithoutDialog()
    : 	at flash.events::EventDispatcher/dispatchEvent()
    : 	at actionScripts.plugins.nativeFiles::FileAssociationPlugin/openFilesByPath()
    : 	at actionScripts.plugins.nativeFiles::FileAssociationPlugin/onAppInvokeEvent()
    : 	at flash.events::EventDispatcher/dispatchEvent()
    : 	at flash.desktop::NativeApplication/dispatchEvent()
    :
    : Click here to Report a Bug

It looks like the problem is that JavaImporter will always [build the path](https://github.com/Moonshine-IDE/Moonshine-IDE/blob/39c11f6f99c5cd9d60403cfde6f9c217463122de/ide/MoonshineSharedCore/src/actionScripts/plugin/java/javaproject/importer/JavaImporter.as#L99) for the .javaproj file based on the project (directory) name.

I have been triggering this error while checking out additional copies of Java project from SVN.  I use a different directory name to avoid duplication, but the project never opens.

If this will be difficult to refactor, we can save it for a later release.

**Comment by rat-moonshine** [comment]
I see the scenario works for Flex projects (or `.as3proj` configurations). I brought the same import procedures to Java (`.javaproj` configuration), targeting the settings-file read instead of assuming directory name as project name.

I have tested following areas which worked correctly in my tests:

1. Create a new Java Gradle project
2. Project opens properly
3. Close the project
4. Rename the project directory 
5. Try to open the project again from `Project > Open/Import` project - worked
6. Try to open the project again by double-clicking the `.javaproj` file in Finder - worked
7. Try dragging the `.javaproj` file on Moonshine - worked

Note: Opening from recent-item may fail if attempted in step.5. It's because the project-object still holds the path before a rename.

Please, check.

**Comment by piotrzarzycki21** [comment]
@Aszusz when you have time please test this, so we could close it.

**Comment by Aszusz** [comment]
I tested this on Windows and in each scenario, the project opened for me correctly.
The recent item doesn't work, obviously, but this is normal for any IDE.
I think we can close this.

**Comment by JoelProminic** [comment]
I tested on macOS, and this seems to be working well.

Action | Java Maven | Java Gradle
-------|------------|------------
Open from .javaproj | Works | Works
Open from menu | Works | Works
Open from sidebar (updated name) | Works | Works
Renamed checkout from SVN | No example | Works
Renamed clone from Git | No example | No examlpe
Build & Run | Works | Works
Update settings |  | Use original .javaproj


I'll update if I find some good examples for the missing cases, but overall this looks good.

Are there other projects types that need to be updated for this?

**Comment by JoelProminic** [comment]
I think it is fine to close this for now.  We can create a separate issue if we find problems with other project types.
