### ISSUE TITLE
Selected SDK in main Settings has been reset to default after Moonshine restart

### ISSUE THREAD

**Issue by piotrzarzycki21** [Moonshine-IDE/Moonshine-IDE#884]
I've been observing this behavior for quite some time, but I didn't properly report it or debug. 

I have several SDKs on my list: 
<img width="382" alt="Screenshot 2021-08-03 at 14 09 56" src="https://user-images.githubusercontent.com/24554795/128013027-4823a13f-03e0-40e7-808c-d6a4aa02ecc2.png">

When I launch Moonshine Flex SDK is selected. Next I'm changing to any other sdk using menu main -> Settings -> Default SDK. After that change I'm restarting Moonshine and when I launch it again - Flex SDK is selected again, instead choosen one.

**Comment by piotrzarzycki21** [comment]
I've been trying to debug that and seems to me that [MXMLCPlugin](https://github.com/Moonshine-IDE/Moonshine-IDE/blob/master/ide/MoonshineDESKTOPevolved/src/actionScripts/plugins/as3project/mxmlc/MXMLCPlugin.as) should [save](https://github.com/Moonshine-IDE/Moonshine-IDE/blob/4e7f2a2088961cbf7027d9735aaef6bbf6ba8718/ide/MoonshineDESKTOPevolved/src/actionScripts/plugins/as3project/mxmlc/MXMLCPlugin.as#L249) choosen sdk?

**Comment by piotrzarzycki21** [comment]
It is on Mac OSX Big Sur

**Comment by rat-moonshine** [comment]
> I've been trying to debug that and seems to me that [MXMLCPlugin](https://github.com/Moonshine-IDE/Moonshine-IDE/blob/master/ide/MoonshineDESKTOPevolved/src/actionScripts/plugins/as3project/mxmlc/MXMLCPlugin.as) should [save](https://github.com/Moonshine-IDE/Moonshine-IDE/blob/4e7f2a2088961cbf7027d9735aaef6bbf6ba8718/ide/MoonshineDESKTOPevolved/src/actionScripts/plugins/as3project/mxmlc/MXMLCPlugin.as#L249) choosen sdk?

It was influencing the problem, but the problem was lying somewhere else. The `model.defaultSDK` was remain _null_ because of other non-available fields thus resulting `ProjectEvent.FLEX_SDK_UDPATED_OUTSIDE` event. 

I have fixed the issue, please give a test.

**Comment by piotrzarzycki21** [comment]
Working great! Thanks for fixing that. It was annoying.
