### ISSUE TITLE
Git status window cannot revert creation of untracked files

### ISSUE THREAD

**Issue by Aszusz** [Moonshine-IDE/Moonshine-IDE#889]
1. Work with Moonshine on a Git repository. Have a clean working tree.
2. Create a new file by any means (from Moonshine or manually)
3. Got to `Git > Status`. Moonshine lists the file as `N`
4. Select the file and click `Revert Selected`
5. Nothing happens

My guess is this is happening because behind the scene Moonshine might be using:
`git rm -f -- pathspec`
which cannot by itself remove untracked files.
The correct command to invoke would be:
`git rm -f -- pathspec || git clean -f -- pathspec`
as described here: 
https://github.com/Moonshine-IDE/Moonshine-IDE/wiki/Git-Integration-Guidelines#a3-restoring-files

**Comment by rat-moonshine** [comment]
I think, currently, Moonshine does nothing for an untracked file - https://github.com/Moonshine-IDE/Moonshine-IDE/blob/master/ide/MoonshineDESKTOPevolved/src/actionScripts/plugins/git/commands/RevertCommand.as#L48. But I'll give this a test to recall clearly.

**Comment by rat-moonshine** [comment]
Going against my earlier thought, Moonshine does something against new/untracked file; Here's the commands used in case of revert:

Modified, Deleted: `$pathToGit/git checkout $pathToFile`
New/untracked: `$pathToGit/git reset $pathToFile`

@Aszusz I see your command assumption was fairly different. The current commands were created based on my basic understanding at that time. Do you see the using commands are not entirely correct and we can improve them?

**Comment by Aszusz** [comment]
In the case of Modified and Deleted the command can stay as it is. The difference will be apparent only when a user makes use of Git's staging area outside of Moonshine.

In the case of New/untracked files `git reset` does nothing. We could use:
`$pathToGit/git clean --force -- $pathToFile` 
This is the default way of removing untracked files.
https://stackoverflow.com/questions/61212/how-to-remove-local-untracked-files-from-the-current-git-working-tree

**Comment by rat-moonshine** [comment]
Yeah, I agree running the command against untracked file does nothing. I shall plan to have the command updated per your suggestion.

**Comment by rat-moonshine** [comment]
I have updated the revert command for untracked/new file. Running the command I see the targeted file removes from the file-system. If this how the command is intend to work (remove with git-clean), you can try with a new build @Aszusz .

**Comment by Aszusz** [comment]
I tested the changes, they work great, I'm closing the issue.
