### ISSUE TITLE
Git New Branch not working

### ISSUE THREAD

**Issue by Aszusz** [Moonshine-IDE/Moonshine-IDE#893]
Steps to reproduce:

1. Open or clone a repository
2. Try to create a new branch via `Git > New Branch`
3. Process freezes on `Validating...` and the branch is not created

@rat-moonshine I wonder if it will be working for you

**Comment by rat-moonshine** [comment]
Was it a private repository or an open one?

**Comment by Aszusz** [comment]
> Was it a private repository or an open one?

Public repository so it may be different than #892

**Comment by rat-moonshine** [comment]
I think this is ready for your tests now. Please, check.

**Comment by rat-moonshine** [comment]
@Aszusz reported at https://github.com/Moonshine-IDE/Moonshine-IDE/issues/892#issuecomment-932217816 that he's unable to create a new branch:

> Besides that, Branch Name Availability is not working correctly. It will forbid you from creating a branch that exists on local or remote, but it freezes when trying to create a new legitimate branch.

During my test with a private or public repository (following one is private) I couldn't able to reproduce the problem, though.

**When a remote-branch is already exists**
![image](https://user-images.githubusercontent.com/24370870/135653405-205c91f1-0651-41d0-9976-b1962a46b4f0.png)

**When a new branch name provided**
![image](https://user-images.githubusercontent.com/24370870/135653489-14d9bf43-88fa-49ce-99d1-0194f3b59d2e.png)
![image](https://user-images.githubusercontent.com/24370870/135653578-398a3436-4f4e-4222-8a68-0971cfa9184e.png)

Can you provide some more details of your test-scenario @Aszusz ?

**Comment by rat-moonshine** [comment]
Sorry, I just discovered I wasn't testing this on the App Store build. I see the reported freeze during legitimate branch creation, too.

**Comment by rat-moonshine** [comment]
Branch creation should have fixed now in App Store build. Please, check.

**Comment by Aszusz** [comment]
OK, this works, but the downside is, it uses the user's credentials in a URL and prints them to the console.
I'm closing this issue because the original bug is fixed. We're going to work on the credentials inside the URL problem in #892.
