### ISSUE TITLE
Auto-Updates for Nightly Build

### ISSUE THREAD

**Issue by JoelProminic** [Moonshine-IDE/Moonshine-IDE#899]
We would like to have an auto-update feature for the nightly build so that it is easy to stay updated with the latest development changes.  

The update chain will need to be independent from the production updates (and we need to test before releases that the production build is using the correct update chain)

We will probably want to make this a "Moonshine Development" build, so that we can install it separately from the stable production build.

**Comment by rat-moonshine** [comment]
@JustinProminic @JoelProminic You can now download and install a Development version of Moonshine-IDE using the same Bamboo build-plans we use to distribute productions builds:

macOS: https://bamboo.prominic.net/browse/MS-MGOSX
Windows: https://bamboo.prominic.net/browse/MS-MGWS

Though, I was unsure if we wants to maintain two separate plans one for Production and one for Development - for now going by the Native/GBAuth-way, I chose to change the `development` flag and continue to use the same build-plans.

With the new Development installation, you shall see following things:

1. New executable `/Applications/MoonshineDevelopment.app`
2. Different application-id for Development build, so you can continue to have both production and development builds installed at same time
3. Different update notification URL (internal)
4. Auto-update is applicable for both App-Store and non-App-Store version in Development builds, for more information when the notification _with download-facility_ will shown please check following matrix

Scenario | Notification _with Download Facility_ 
----------|---------------------
<ul><li>Development = true</li><li>AppStore = true</li></ul> | Show
<ul><li>Development = true</li><li>AppStore = false</li></ul> | Show
<ul><li>Development = false</li><li>AppStore = true</li></ul> | Hide
<ul><li>Development = false</li><li>AppStore = false</li></ul> | Show

@Aszusz @piotrzarzycki21 You can probably see new Development installers on Moonshine website deployment area with following names:

MoonshineDevelopment.pkg/exe
MoonshineDevelopment_Signed_NonSandbox.pkg/exe

Let me know if you see any oddity. 

Note: We may need to decide on how the "Nightly" builds going to be distribute on Moonshine website (https://moonshine-ide.com/downloads/releases/dev/macos/) - _Development_ or non-Development build, although I think it'd be overkill if we wants to distribute both type of builds for "Nightly".

**Comment by JoelProminic** [comment]
The next step is to have Bamboo automatically modify the updater XML when deploying new builds.

To automatically generate new version numbers, I would like to append the build number to the version number (i.e. "3.2.0.2152").   If the current version checking logic can't handle this, this, we could replace the last number instead (i.e. "3.2.2152"), but this becomes a problem if we want quick-fix release like 3.2.1.

@rat-moonshine setup a new updater here:  https://moonshine-ide.com/downloads/updater-dev.xml
```
<?xml version="1.0" encoding="utf-8"?>
<update xmlns="http://ns.riaspace.com/air/framework/update/description/1.1">

        <!-- Mac update -->
        <pkg>
            <version>3.2.0</version>
            <url>https://moonshine-ide.com/downloads/releases/dev/macos/MoonshineDevelopment_Signed_NonSandbox.pkg</url>
            <description>
            <![CDATA[
                * This a Mac update
                ]]>
        	</description>
        </pkg>
        
        <appStorePkg>
            <version>3.2.0</version>
            <url>https://moonshine-ide.com/downloads/releases/dev/macos/MoonshineDevelopment.pkg</url>
            <description>
            <![CDATA[
                * This a Mac update
                ]]>
	        </description>
        </appStorePkg>

        <dmg>
            <version>3.2.0</version>
            <url>https://moonshine-ide.com/downloads/releases/dev/macos/MoonshineDevelopment_Signed_NonSandbox.pkg</url>
            <description>
                <![CDATA[
                    * This a Mac update
                    ]]>
        </description>
        </dmg>

        <!-- Win update -->
        <exe>
            <version>3.2.0</version>
            <url>https://moonshine-ide.com/downloads/releases/dev/windows/MoonshineDevelopment-3.2.0.exe</url>
            <description>
            <![CDATA[
                * This a Win update
                ]]>
	        </description>
        </exe>
</update>
```

I think we need to split this file in to Windows and macOS versions:
- This will avoid race conditions between the macOS and Windows builds
- This will simplify the commands to update or generate the files - it can just replace "<version>.*</version>" without worrying about the different version numbers for the two builds.

Production:  https://moonshine-ide.com/downloads/updater.xml
Dev, macOS:  https://moonshine-ide.com/downloads/updater-dev-macos.xml
Dev, Windows:  https://moonshine-ide.com/downloads/updater-dev-windows.xml

Production would only be updated manually.  The Dev files would only be updated by the Bamboo builds if the are running with "IsDevelopment
=true"

The Windows update could update both the EXE and the version number separately.

**Comment by rat-moonshine** [comment]
Message with link now updated for App Store Development version notification.

**Comment by JoelProminic** [comment]
The updated message should be good, and I confirmed that the download link works.

The macOS Development builds are updating like I expect:

Type | Initial Build | Latest Build | Update?
-----|---------------|--------------|--------
non-Sandbox | 2182 | 2183 | Auto-update works
non-Sandbox | 2183 | 2183 | No Update
App Store | 2182 | 2183 | Prompted to update with download link
App Store | 2183 | 2183 | No Update

I'd like to do some update tests once we have a release candidate, though, to make sure we didn't introduce a bug with these updates.

**Comment by JoelProminic** [comment]
I tested the production upgrade logic on the release candidates (2186 and 646) by temporarily updating the [production updater.xml](https://moonshine-ide.com/downloads/updater.xml).  I could probably test this with a local server instead, but I went with a quick test today.

OS | Local | updater.xml | Update Prompt?
---|-------|-------------|---------------
macOS | 3.2.0 | 3.1.1 | No
macOS | 3.2.0 | 3.2.0 | No
macOS | 3.2.0 | 3.3.0 | Yes
Windows | 3.2.0 | 3.1.1 | No
Windows | 3.2.0 | 3.2.0 | No
Windows | 3.2.0 | 3.3.0 | Yes

I checked the installation step as well on the 3.3.0 cases, and everything seems fine
