### ISSUE TITLE
Duplicated "Template Type" during ActionScript Project import

### ISSUE THREAD

**Issue by rat-moonshine** [Moonshine-IDE/Moonshine-IDE#902]
To test this:

1. Create a "New ActionScript Project"
2. Close the project (when created)
3. Delete the project-configuration file by going to the folder
4. Try to import the project in Moonshine
5. Moonshine will ask if want to import the directory as a _project_ since non-existence of any configuration file within it
6. Chose "Yes"
7. In opening project creation dialog, Moonshine shows duplicated "Template Types"
![image](https://user-images.githubusercontent.com/24370870/138637510-92222fa2-2cd3-4aa3-ac40-858ee088216e.png) [Bug]

In above scenario it was suppose to show either of the following:

1. Only "ActionScript Project" in first dropdown and the sub-types of ActionScript project in the second dropdown
2. Do not show second dropdown

**Comment by Aszusz** [comment]
> Is it possible that you have multiple MoonshineDevelopment.app exists in your system and somehow you're accessing any older one?

Even worse, I didn't know MoonshineDevelopment registers as a different executable and I was testing Moonshine all along. My apologies.

> It is surprising how your and @JoelProminic able to reproduce this using build 2164 but me

So naturally, I went back and tried 2164 again, this time for real. The issue is not present for me here. @JoelProminic  is there any chance you were also testing on `Moonshine.app` instead of `MoonshineDevelopment.app`?

**Comment by rat-moonshine** [comment]
We assumed it is a chance that you were testing with `Moonshine.app` instead of `MoonshineDevelopment.app` since the version number you've mentioned satisfies the same timeline from when we started building the Development version.

We mentioned the executable name update here https://github.com/Moonshine-IDE/Moonshine-IDE/issues/899#issuecomment-948326042 but it's possible to miss this between the updates. @piotrzarzycki21 also make sure you test with correct Development executable.

**Comment by JoelProminic** [comment]
Yeah, I think it is possible that I accidentally opened Moonshine instead of MoonshineDevelopment during one of my restart tests.  It will take a while to get used to opening the different application.  I may uninstall Moonshine.app so that I can't open it by accident...
