### ISSUE TITLE
[Domino Visual Editor] Page Mockup Editor

### ISSUE THREAD

**Issue by JoelProminic** [Moonshine-IDE/Moonshine-IDE#905]
Since we are almost done with the round-trip conversion (#812), @JustinProminic wants to move on to support for generating other Domino design features, in roughly this order:

> pages
> form actions
> views
> view actions
> java agent
> lotuscript agent
> java script library
> lotus script library
> the rest of an entire ODP scope

We will start with Pages (not XPages).  The Pages are defined in `nsfs/nsf-moonshine/odp/Pages/*.page`

Pages will be a subset of for the Form mockups which exclude the Field types.  We should be able to add these features:
- Label
- Table
- Div
- ComputedText
- Paragraph
- Section
- TabView
- Button?  This would have limited functionality at least

But not:
- Input
- Calendar

We will need additional intermediate XML files for the Pages.  This will required some refactoring, but we can use something like `visualeditor-src/main/webapp/pages/*.xml`.

@feather812002, let me know if there are any other major design decisions we need to discuss.   

We need to make these changes in a branch, since there could be some significant changes (and we hope to get the 3.2.0 release out soon).  Use the standard format for these branches (i.e. features/issue_905_domino_visual_editor_pages).  Let me know if you have any questions about this.

**Comment by JoelProminic** [comment]
@feather812002 reported that the basic page editor is working, but he didn't have a way to open the Page from the Notes client.

To resolve this, I created a Formula agent to open a page selected with a text prompt.  To use this, you need to add `Agents/OpenPage.fa` to `nsfs/nsf-moonshine/odp/Code`.  You can extract the zip below in the Code directory:
[Agents.zip](https://github.com/Moonshine-IDE/Moonshine-IDE/files/7499191/Agents.zip)

**Comment by JoelProminic** [comment]
I confirmed that I can create these elements in a Page:
- Label
- Tabs
- Table
- Buttons
- Div
- ComputedText
- Paragraph
- Section

![image](https://user-images.githubusercontent.com/24532731/140796754-7330453b-dd69-4c57-9d91-70b5ae217484.png)

@feather812002 reported errors for buttons.  Please investigate this in case there is a bug that needs to be fixed.  My Button configuration was very simple:

![image](https://user-images.githubusercontent.com/24532731/140796778-cbb07a2d-5b00-4fd9-a0c2-d10c33c93517.png)

Otherwise, I think the next step is to add a New > Domino Visual Editor Page menu item and template, and to make sure that these files are created in odp/Pages by default

**Comment by JoelProminic** [comment]
This is almost ready to be merged, so I moved it to 3.3.0.  I'd like to get this merged before the branch gets out of date.

**Comment by JoelProminic** [comment]
I can now create new pages from the context menu.  @feather812002 also resolved a bug with saving forms when a field is selected.

This is ready for a merge.  Please be careful with this so that we don't have problems like with #646.  
- Merge master in to this branch first
- Make sure to resolve any conflicts before committing the merge
- Check before you commit any changes to files not directly related to Domino Visual Editor
- Run some tests before merging into master.

Since this branch is less than a month old, it hopefully should be easier to merge.  Let me know if you run into any trouble with this.

**Comment by JoelProminic** [comment]
When I tested with the latest MoonshineDevelopment build, I found that my new page (Test2.page) showed up in Notes as a Form rather than a page:

![image](https://user-images.githubusercontent.com/24532731/142305750-cdfd2adf-99b0-4ab6-8744-bec3a0289c42.png)

Here is my test project:
[TestDominoVisualEditor_1117.zip](https://github.com/Moonshine-IDE/Moonshine-IDE/files/7558828/TestDominoVisualEditor_1117.zip)

**Comment by JoelProminic** [comment]
@feather812002, please review the issue I reported in my last comment.

**Comment by JoelProminic** [comment]
@feather812002, please revisit this now that #968 is done.

**Comment by feather812002** [comment]
@JoelProminic I work on this in today , I to do some test about the create& edit the page with Moonshine-IDE.
I fix some small bug ,and confirm it can build success to NSF database.
But I don't know how to open the page with Notes client , I only see some form name list from "Create" mean
Thanks.

**Comment by JoelProminic** [comment]
I created an agent to open pages here:  https://github.com/Moonshine-IDE/Moonshine-IDE/issues/905#issuecomment-963428662

Please add this OpenPage agent to the Domino Visual Editor template so that it is available for testing later.

Otherwise, the updates are looking good.

**Comment by JoelProminic** [comment]
I confirmed the OpenPage action is available and working.   This is ready for a merge along with #926.

**Comment by JoelProminic** [comment]
I missed that there were changes to the features/issue_905_page_mockup_editor branch in MockupVisualEditor as well.  I merged the branch in that project as well.
