### ISSUE TITLE
Build Moonshine with Harman AIR 33.1.1.633

### ISSUE THREAD

**Issue by JoelProminic** [Moonshine-IDE/Moonshine-IDE#907]
From @piotrzarzycki21

> Yesterday I upgrade my OS to newest version called Monterey. Editor and all text inputs start behave weird. When I’m trying to Enter letter „E” instead of a letter I get system Window with Emojis.  
There are also other behavior with popping up system windows. I will share tomorrow more details in issue. 

From @joshtynjala

> It's a bug in AIR when running on macOS Monterey. I found that HARMAN has fixed it in the latest AIR 33.1.1.633. 

I see this issue in the [33.1.1.633 release notes](https://airsdk.harman.com/api/versions/33.1.1.633/release-notes/Release_Notes_AIR_SDK_33.1.1.633.pdf):

> AIR-5060: Prevent Function accelerators triggering with normal keypresses on Monterey

**Comment by JoelProminic** [comment]
@rat-moonshine reported that the AIR version was updated as of Moonshine Development build 2180 (macOS) and 639 (Windows).  I confirmed I see the new version in the console when I install the latest build (2183), but I am running on High Sierra currently.

@piotrzarzycki21 reported that he still sees version 33.1.1.554 when installing the new builds on Monterey, though.   We are using the captive runtime for Moonshine, so it doesn't make sense that it would be a different version for some users.

**Comment by piotrzarzycki21** [comment]
@rat-moonshine @JoelProminic Today I have test everything again - It turns out that I have some kind of a mess with Moonshine installation. I cleaned up everything and all is good. I see proper version and issue on Mac OSX with editor is gone. Please proceed with updates in MSDKI.

**Comment by piotrzarzycki21** [comment]
I had yesterday national vacation in Poland, so sorry for the delay in response.

**Comment by piotrzarzycki21** [comment]
I have raised issue for MSDKI -> https://github.com/Moonshine-IDE/Moonshine-SDK-Installer/issues/75 - you can close this one.

**Comment by JoelProminic** [comment]
@piotrzarzycki21, is the "some kind of a mess with Moonshine installation" something that we should watch for as a potential bug, or just something that happened because we are installing a bunch of test builds?   Otherwise, I think we can close this issue.

**Comment by piotrzarzycki21** [comment]
This is something which I did and it's completely unrelated to the case of our work with release/dev build. We can definitely close this issue.
