### ISSUE TITLE
GitHub URL and Copyright Information Update

### ISSUE THREAD

**Issue by rat-moonshine** [Moonshine-IDE/Moonshine-IDE#912]
From @JustinProminic ,

> The GitHub URL in the console is wrong.  Please correct.
> Also, please change the copyright from Prominic.NET, Inc. to STARTcloud, Inc.
> 
> ![image](https://user-images.githubusercontent.com/24370870/141752570-20b30e25-7d6f-4799-b4a5-4044301a9fcf.png)

**Comment by rat-moonshine** [comment]
- All occurrence of Moonshine GitHub URL updated
- Occurrences of existing copyright information updated - please report if we still have old copyright information exists anywhere

**Comment by JoelProminic** [comment]
For macOS, I confirmed the updated URL, and the copyright was updated in:
- Console
- About Page

I'd like to do a quick check on Windows, but otherwise, this looks good.

**Comment by JoelProminic** [comment]
@JustinProminic also requested this update:

>It also needs to list Copyright (c) 2017-2021 and replace 2021 with whatever the current year is.   I think 2017 is about right for the start year on Moonshine IDE, but I don't remember.

I checked the old issues in JIRA, and the first issue I see is from 2015, so use this instead of 2017.

**Comment by rat-moonshine** [comment]
It is updated accordingly:

![image](https://user-images.githubusercontent.com/24370870/142137650-1ec7ba99-f5e8-45b3-ae30-d3ad48e767a3.png)
