### ISSUE TITLE
Can We Provide a Way to Easy Custom Path Input Instead of CMD+Shift+G on macOS?

### ISSUE THREAD

**Issue by rat-moonshine** [Moonshine-IDE/Moonshine-IDE#914]
Previously @JustinProminic faced trouble entering a path like `/opt/local/bin/svn` in opening file-browser window during his SVN setup in Moonshine Settings. Following his observation after the experience:

> I finally accomplished this by realizing even though there was no UI clue from MacOS that I could use Command-Control-Shift-G to specify a folder, and then type /opt/local/bin and finally select svn.
> 
> This is WAY too confusing.
> 
> While we still need to follow my earlier requests on this matter (display text location of all global Moonshine settings, make it so the user can type in the exact path in this case) we now *ALSO* should put a description here stating the Command-Control-Shift-G trick for accessing to specific folders on MacOS using the command line.
> 
> ![image](https://user-images.githubusercontent.com/24370870/141755250-8328fbf6-8375-42c4-8ec3-1b14684c1502.png)

EDIT:  Branch information
Branch:  features/issue_914_openhiddenpath
Build:  https://moonshine-ide.com/downloads/releases/dev/macos/branches/features/issue_914_openhiddenpath/

**Comment by rat-moonshine** [comment]
Some quick note on this,

- Using CMD+Shift+G standard macOS Finder way to open special directory starts with `/` where Finder do not provides a straight-forward access, this works in file-browser window too
- Due to directory bookmarking on macOS sandbox, a directory needs to be selected through a file-browser, an entered value not permitted acceptable

In light of the above, we can do something like:
1. User enter the special path to an input in Moonshine
2. User needs to validate that path by clicking on a button next
3. The validation button will open the file-browser to the entered path
4. User needs to accept that location by clicking on "Open" button in the file-browser

There are some extra steps involved here, but I think this an option.

**Comment by JoelProminic** [comment]
Another option is:
1. User clicks a new button called something like "Open Hidden"
2. Moonshine prompts for a path
3. Moonshine opens the filechooser to the entered path, and the user can browse from there.

Another options that @JustinProminic has suggested previously is adding a custom button in the FileChooser dialog (called something like "Open Path" or "Open Hidden" that will simulate the behavior of `CMD-Shift-G`.  The main problem with `CMD-Shift-G` is that it is an obscure macOS shortcut that most users won't be aware of.

**Comment by rat-moonshine** [comment]
I have added a new option on path-settings "Go to Folder" (keeping word similar to the Finder's option), this should be visible only on macOS:

![image](https://user-images.githubusercontent.com/24370870/175936117-56f647e6-5d7b-47b2-8390-500d9060c534.png)

User can chose to enter any arbitrary path in the opening popup, Moonshine will validate the enter and therefore opens a file browser to entered location.

However, I'm not sure if we wants to have the option available in path-list-settings interface (eg. in case of project's settings) where a path usually suppose to be selected from source code areas only (and not hidden). If we wants we can add there, as well.

![image](https://user-images.githubusercontent.com/24370870/175936567-4f375268-fea8-481f-9eba-7d4661bcf3a6.png)

I'm committing these changes to branch, can be tested with Bamboo macOS branch build.

**Comment by rat-moonshine** [comment]
From @JoelProminic 

---------------------------

Some notes from today's discussion:

- The current behavior failed for some of my test paths because some characters were restricted in the text input.  This filter should be removed so that we don't get problems on special cases, and we should validate the path only
- When the path was invalid (i.e. because of the filtered characters), the button was disabled, but I could still submit the form by hitting enter.  The behavior should be the same for the button and Enter.
- Rather than disabling the button on an invalid path, we should let the user submit the path, and then report an error if the path is invalid.   We may need to revisit this if the sandbox reports that non-bookmarked files do not exist.

**Comment by rat-moonshine** [comment]
Updates:

- Text input restrictions are now removed
- "Open" button is now always enabled
- `Enter` key or clicking on "Open" button now validates the entered path-value, and therefore opens the path to file-browser or show an error message - whichever is appropriate

Please, check.

**Comment by JoelProminic** [comment]
I tested the updates, and I don't see any obvious problems.   Go ahead and merge this, and we can briefly discuss the changes in the meeting tomorrow.

**Comment by rat-moonshine** [comment]
This branch is now merged into `master`.

**Comment by rat-moonshine** [comment]
During our tests earlier @JoelProminic reported that JDK-8 path do not validates upon set. This problem is now fixed.

![image](https://user-images.githubusercontent.com/24370870/176361373-eb0c05e3-60f9-4a5d-b6cb-fec93fb50790.png)

**Comment by JoelProminic** [comment]
I confirmed this is now available in the master build.  The validation for JDK8 in the settings page is also working.
