### ISSUE TITLE
Rename "Domino" in Moonshine Settings

### ISSUE THREAD

**Issue by rat-moonshine** [Moonshine-IDE/Moonshine-IDE#915]
From @JustinProminic 

> On the left hand side where it currently shows just "Domino" please rename it to "Domino and Notes Client"
>
> ![image](https://user-images.githubusercontent.com/24370870/141756790-cc299cec-26f4-430b-9985-8429b0d3e71e.png)

**Comment by JoelProminic** [comment]
I confirmed this was updated.
