### ISSUE TITLE
"Getting Started" Needs to Update Its UI When Everything Is Installed

### ISSUE THREAD

**Issue by rat-moonshine** [Moonshine-IDE/Moonshine-IDE#916]
From @JustinProminic ,

> Now that I finally have SVN installed and accessible using MacPorts and the Command-Control-Shift-G trick ....  I have everything installed.
> 
> BUT, our UI looks a bit underwhelming when this is the case.
> 
> Instead of congratulating the user, it returns ... nothing.
> 
> Which I understand makes sense from a programming perspective, but not from a user perspective.
> 
> Please when this case occurs, make a nice message that shows something like "Congratulations, you have all features installed!" with a smiley face or something happy to convey the accomplishment.   Then encourage the user: "Time to go coding!" 
> 
> ![image](https://user-images.githubusercontent.com/24370870/141757505-cc3f3988-4bd8-4f0f-936a-a132f5908148.png)
>

**Comment by rat-moonshine** [comment]
I think a flashy or very highlighted message may not suit here. Keeping the minimalist design approach as in Moonshine, I made this. Please, let me know if this is Okay.

![image](https://user-images.githubusercontent.com/24370870/141981858-6583e125-7d48-4d88-9be0-5fbdf9756c9e.png)

However, I noticed that "Getting Started" collection when "Only show features that need setup" is selected do not updates with an installation completes (with MSDKI). That means, the counting of items suppose to get reduced/removed when an installation completes from the list.

I need some time to fix this area.

**Comment by rat-moonshine** [comment]
I think this is now ready for tests.

**Comment by piotrzarzycki21** [comment]
@rat-moonshine I don't know what is happening but I just updated develop version and non of my Royale project is starting. I have in console something like that:

:```
 Error #3001,: Error: Error #3001,: at actionScripts.utils::FileUtils$/readFromFile(),: at actionScripts.plugins.startup::StartupHelperPlugin/onInvokeEventFired(),: at flash.events::EventDispatcher/dispatchEvent(),: at actionScripts.plugins.nativeFiles::FileAssociationPlugin/onAppInvokeEvent(),: at flash.events::EventDispatcher/dispatchEvent(),: at Function/(),: at Array/http://adobe.com/AS3/2006/builtin::forEach(),: at Function/(),: at flash.utils::Timer/tick() 
[object ParagraphElement] 
: Moonshine IDE™ 3.3.0
: Copyright © STARTcloud, Inc. 2015-2021. All rights reserved.
: Source code is under Apache License, Version 2.0
: https://github.com/Moonshine-IDE/Moonshine-IDE
: Uses as3abc (LGPL), as3swf (MIT), fzip (ZLIB), asblocks (Apache License 2.0), NativeApplicationUpdater (LGPL)
: Running on Adobe AIR 33.1.1.633
: Failed to load Java version. ActionScript & MXML code intelligence disabled for project: ProminicNativeWeb.
: Failed to load Java version. ActionScript & MXML code intelligence disabled for project: SignUpProminicNet.
: Failed to load Java version. ActionScript & MXML code intelligence disabled for project: RoyaleTabularCRUDTemplate.
: Error #3001
: Error: Error #3001
: 	at actionScripts.utils::FileUtils$/readFromFile()
: 	at actionScripts.plugins.startup::StartupHelperPlugin/onInvokeEventFired()
: 	at flash.events::EventDispatcher/dispatchEvent()
: 	at actionScripts.plugins.nativeFiles::FileAssociationPlugin/onAppInvokeEvent()
: 	at flash.events::EventDispatcher/dispatchEvent()
: 	at flash.desktop::NativeApplication/dispatchEvent()
:
: Click here to Report a Bug 
```

**Comment by piotrzarzycki21** [comment]
Ignore this. I have restarted my Mac and everything seems to be working fine now.

**Comment by JoelProminic** [comment]
It looks fine on macOS, but I'd like to see a test on Windows before we close this.

**Comment by Aszusz** [comment]
I tested it on Windows and it works.
I couldn't find it for a few good minutes. You need to check "by software" first and then "only show features that need setup". Probably not many people will see this.

**Comment by JoelProminic** [comment]
Thanks @Aszusz.   I had tried a test for this, but I didn't have HCL Notes installed on my test Windows VM so I couldn't get to this message.
