### ISSUE TITLE
Default Location For Emacs Is Wrong Under MacPorts

### ISSUE THREAD

**Issue by rat-moonshine** [Moonshine-IDE/Moonshine-IDE#917]
> From @JustinProminic 
> 
> The default location for Emacs is wrong, at least on MacPorts using:
> https://www.gnu.org/software/emacs/download.html#nonfree
> 
> Using MacPorts:
> `sudo port install emacs-app`
> 
> Currently we show the improper location by default:
> 
> ![image](https://user-images.githubusercontent.com/24370870/141757993-a207e414-a295-4bf4-9c26-f95d7432090c.png)
> 

UPDATE:  Justin reported that the path with a MacPorts installation was `/Applications/MacPorts/Emacs.app`

**Comment by rat-moonshine** [comment]
With the configuration currently it supports only path to an editor application. The listing of editors is simple and not doing any additional check/verification of any kind except validating the given path.

**Comment by JoelProminic** [comment]
To clarify, the default location for the Homebrew install was `/Applications/Emacs.app`.  Since we want to move to MacPorts, we need to update the default path to `/Applications/MacPorts/Emacs.app`.

**Comment by rat-moonshine** [comment]
Done.

**Comment by JoelProminic** [comment]
@rat-moonshine noticed this didn't update properly when editing the XML file, so this needs more investigation.

**Comment by rat-moonshine** [comment]
I see we had a problem with updating shared-objects with new external updates, that issue is resolved now https://github.com/Moonshine-IDE/Moonshine-IDE/issues/919#issuecomment-978865306.

However, @JoelProminic is seeing the Emacs path not changed because he already has a valid path! With the goodness of the update-sync design Moonshine will update the item's path only if the present path is not valid. So technically, if `/Applications/Emacs.app` is not valid in some user's case (i.e. @JustinProminic ) then the path should come updated with newer updates `/Applications/MacPorts/Emacs.app`. You really do not want the path get modified if your current path is already valid.

Please, check.

**Comment by JoelProminic** [comment]
I see that default path was updated without me resetting the settings.   I had uninstalled `/Applications/Emacs.app`, though, so I couldn't test if that part of the logic worked as expected.

**Comment by rat-moonshine** [comment]
Yeah, I have a valid `/Applications/Emacs.app` and I can confirm the editor-path updates to `/Applications/MacPorts/Emacs.app` if I remove Emac.app from `/Applications` folder.

**Comment by JoelProminic** [comment]
I confirmed the path is correct after I clear the settings.
