### ISSUE TITLE
Add New Editors In "Settings > External Editors" List

### ISSUE THREAD

**Issue by rat-moonshine** [Moonshine-IDE/Moonshine-IDE#919]
From @JustinProminic 

> - Please add CodeRunner for MacOS to the external editor list and corresponding right click menu: https://coderunnerapp.com
> - Please add Komodo Edit (which is free) for MacOS to the external editor list and corresponding right click menu: https://www.activestate.com/products/komodo-edit/
> - Please add Atom for MacOS to the external editor list and corresponding right click menu: https://atom.io

Coverage:
- [x] CodeRunner
- [x] Komodo IDE (not Edit - see [details](https://github.com/Moonshine-IDE/Moonshine-IDE/issues/919#issuecomment-968837323) for more)
- [x] Atom

**Comment by rat-moonshine** [comment]
Reading the description for Komodo Edit at https://www.activestate.com/products/komodo-edit/, it seems they providing Komodo IDE instead since it's became free. I couldn't found a link to Edit from the website. 

Are we going to support for Komodo IDE instead? Or, do we have any working download link to Komodo Edit?

For now I've added Komodo IDE, we can change this if requires. 

Note: Installed Komodo IDE from its .dmg throws following error:

![image](https://user-images.githubusercontent.com/24370870/141776615-5d7f50dc-6a83-44cf-ae2e-d7f2cdeb7564.png)

Also, Komodo IDE distributes with its version in its name, i.e. `Komodo IDE 12.app` - I'm not sure if we can manage this number in Moonshine when a new version comes out.

Other editors added:
- CodeRunner
- Atom

**Comment by JoelProminic** [comment]
I don't see the new editors in Settings > External Editors:

![image](https://user-images.githubusercontent.com/24532731/143287640-4474e14f-eb6f-46e2-88e4-99ae43c7d797.png)

**Comment by rat-moonshine** [comment]
It appears we already has shared-object sync logic with newer external-updates, with one incorrectness which was making Moonshine not seeing a new external-update is available.

The problem is now addressed, and you should see new items in your editors-list. Please, check.

**Comment by JoelProminic** [comment]
Yes, I see Atom and CodeRunner in the External Editors interface now.  

I don't have these editors installed, so there is more work to do for a proper test here.

**Comment by JoelProminic** [comment]
On Windows, I see that the default path for Atom is messed up - `C:` appears a second time in the middle - do you have a home directory reference here? I see a similar problem for Eclipse and Visualu Studio code, but not for Komodo Edit.

**Comment by rat-moonshine** [comment]
> On Windows, I see that the default path for Atom is messed up - `C:` appears a second time in the middle - do you have a home directory reference here? I see a similar problem for Eclipse and Visualu Studio code, but not for Komodo Edit.

This should be fixed now. Please, check.

**Comment by JoelProminic** [comment]
The paths look correct, now, but I don't have any of the applications installed on this test VMs.  I'd like to at least install and test the new editors before closing the issue.

**Comment by JoelProminic** [comment]
I did some tests after clearing the settings today.

### macOS

Editor | Path | Test
-------|------|-----
Atom | Correct | Works
CodeRunner | Correct | Works
Komodo Edit | Correct | Launches (requires login)

### Windows

Editor | Path | Test
-------|------|-----
Atom | Correct | Works, with console error
CodeRunner | N/A | N/A
Komodo Edit | On my machine, it installed under `Program Files (x86)` | Works, with console error

Here is the console error:

IMAGE

For the Komodo path, are you seeing it in Program Files on a 64-bit Windows machine?  If we are getting different results, then we can stay with your version.


One thing I noticed on both OSes was that the editors were not "enabled" by default (the checkbox in Seettings).  I need a reminder of the logic for this - are all editors supposed to be "enabled" byi default?

**Comment by rat-moonshine** [comment]
On 64-bit system, it is "Program Files (x86)" for me where Komodo Edit installed. 

I noticed the path-validation logic on Windows had a small but critical problem which was failing to validate the paths correctly. This fixed now. Komodo Edit's path should validate now with "(x86)" suffix. 

I also fixed the exception thrown on console during triggering an editor-application on Windows.

The _enabled_ checkbox in editors' settings are simply selects based on their path validation, by default. There is no extra handling we provides for a fresh installation.

**Comment by JoelProminic** [comment]
I confirmed the Komodo path is fixed.  

I would like to see the "enabled" checkbox behave more like this, but we should create a separate issue when we are ready to revisit it.
- All editors are "enabled" by default
- "disabled" editors do not appear at all in the context menu
- Improperly configured editors show as disabled in the context menu.  The user can click the "Configure Editors" menu item to fix this
