### ISSUE TITLE
Opens Duplicate Sections in Left Navigation

### ISSUE THREAD

**Issue by rat-moonshine** [Moonshine-IDE/Moonshine-IDE#922]
From @JustinProminic 

> When Useful links or Tour De Flex are already in the left navigator, they will be DUPLICATED and added again if the user selects them again from the Help menu.
> 
> Please fix this.  They should be greyed out from the Help menu if they are already present in the left navigator.
> 
> ![image](https://user-images.githubusercontent.com/24370870/141764018-91fd7789-9f3c-42f2-a1ce-85c8e291659a.png)
> 
> After the bug has been hit that allows more than one Tour De Flex to be opened, I can never fully get rid of Tour De Flex from the left navigator.
> 
> I cannot close them all.

**Comment by rat-moonshine** [comment]
A quick fix to this could be conditionally tested before opening to sidebar. 

Disable/enable in top-menu could require more effort.

**Comment by rat-moonshine** [comment]
Items those opens to sidebar and now prevents from opening duplicate - @JoelProminic @piotrzarzycki21 @Aszusz please update the list if you remember any other:

- [ ] Help > Userful Links
- [ ] Tour de Flex
- [x] View > Project View
- [x] View > Outline View

**Comment by rat-moonshine** [comment]
"Useful Links" and "Tour de Flex" menu options will work as toggle option same as `View > Outline View`.

**Comment by JoelProminic** [comment]
The menu toggling works well in my tests, and I think this resolves the duplicate section issue.
