### ISSUE TITLE
Default Directory Trouble for New Domino Page or Form

### ISSUE THREAD

**Issue by JoelProminic** [Moonshine-IDE/Moonshine-IDE#926]
While testing the merge for #905 today, I noticed this isseu

1. Create a new Domino Visual Editor project 
2. Expand the first level of the project only
3. Right-click on the project name and choose New > Page
4. BUG: the default directory is nsfs, which does not match either the selection or the desired directory
5. Expand nsfs/nsf-moonshine/odp
6. Right-click on the project name and choose New > Page
7. The default location is nsfs/nsf-moonshine/odp/Pages , as expected

I see the same problem for new Domino Forms.  

I think this is caused because the directories do not automatically expand (because of performance issues).  @rat-moonshine, do you remember if we had a similar problem for other projects?  This seems familiar, but I see that Flex and Java source files only prompt me to choose a source directory.

**Comment by rat-moonshine** [comment]
While I tried this with following build,
![image](https://user-images.githubusercontent.com/24370870/142355843-80d13070-21c5-431e-9209-d3691f2b954b.png)

I couldn't able to produce the problem with step.4 but step.7, so apparently yes I able to reproduce the problem:

![image](https://user-images.githubusercontent.com/24370870/142356027-435562b0-54d0-4b7c-babd-3b77a48f9033.png)

I don't remember now if we has this target-folder selection problem in new-file-creation popup, I can look into this.

**Comment by rat-moonshine** [comment]
I don't think the problem is related to our tree-management changes towards performance improvement. When I tested the behaviour with deep directory structure with a Haxe project, I couldn't found the problem. 

I also noticed that the popup tree logic do not opens any underneath folder unless it requires - in next tests in popup-tree it only opens until ----- when in sidebar the tree directory 

![image](https://user-images.githubusercontent.com/24370870/142357684-971ecca9-d2ca-4e1f-ab6e-71746593c119.png)

**Comment by rat-moonshine** [comment]
Okay. Doing some investigation it appeared that the target-folder information is modified by this [custom code](https://github.com/Moonshine-IDE/Moonshine-IDE/blob/master/ide/MoonshineSharedCore/src/components/popup/newFile/NewFilePopup.mxml#L193) written for Domino Visual Editor project.

In the said condition it changes the target location to "nsfs/nsf-moonshine" for me when I actually right-clicked and opened the file-creation dialog on "nsfs/nsf-moonshine/odp". If I remove this condition then tree-selection works correctly.

I assume this is the same problem that noticed by @JoelProminic . I don't know what underneath logic for this condition so I left this for @feather812002 .

**Comment by JoelProminic** [comment]
@feather812002, are you clear on @rat-moonshine's suggestion here?   This issue has been stuck for a while, so I'd like to get this cleaned up before you start on another large task.

**Comment by feather812002** [comment]
@JoelProminic , yeah , I working around this at now .
I will try to fix this at first ,then back to #905

**Comment by feather812002** [comment]
@rat-moonshine  thanks for your suggestion , I will follow your suggestion work around this.
Thanks.

**Comment by feather812002** [comment]
okay , I already done the File->New->Domino Visual Editor Form
I re-factory follow rat-moonshine's suggestion .
Now , it is work with https://github.com/Moonshine-IDE/Moonshine-IDE/blob/features/issue_905_page_mockup_editor/ide/MoonshineSharedCore/src/components/popup/newFile/NewDominoFormPopup.mxml

As you see, the new domino form work in same way as other new type files.
And from my test , the folder will update auto :
1. when you select in the project , it always will be limit into the "/nsfs/nsf-moonshine/odp/Forms" folder
2. the code will check above domino forms folder , it it not exist ,it will alert a waring message.
3. in the new Domino form file panel, it always be limit in the domino forms folder
![image](https://user-images.githubusercontent.com/8543391/157875773-04b299be-2bf6-4798-ac72-84e4b4fb254a.png)
4. after you create it done ,back to the Moonshine-IDE , the left tree will get into the Domino forms folder auto:
    
![image](https://user-images.githubusercontent.com/8543391/157876644-796a049f-d1e8-4b23-959c-44b5628b002d.png)

So, I not found the domino form default folder error at now .
I will try to do more test about this .

**Comment by JoelProminic** [comment]
The Bamboo plan failed with this error:

    build	15-Mar-2022 11:38:01	    [mxmlc] .../Moonshine-IDE/ide/MoonshineSharedCore/src/actionScripts/plugin/templating/TemplatingPlugin.as(1300): col: 190 Error: Access of undefined property File.
    build	15-Mar-2022 11:38:01	    [mxmlc] 
    build	15-Mar-2022 11:38:01	    [mxmlc] 				var dominoFormFolderStr:String=newDominoFormComponentPopup.wrapperBelongToProject.projectFolder.nativePath +  File.separator +"nsfs"+File.separator+"nsf-moonshine"+File.separator+"odp"+File.separator+"Forms";


@rat-moonshine reported that you should not use the desktop File API, since it breaks the Web build:  https://github.com/Moonshine-IDE/Moonshine-IDE/blob/b2f924925a816b08a17e3ca93cec7c889a4c5f50/ide/MoonshineSharedCore/src/actionScripts/plugin/templating/TemplatingPlugin.as#L94

Instead, you should use `model.fileCore.separator` to get the separator.  For example:  https://github.com/Moonshine-IDE/Moonshine-IDE/blob/b2f924925a816b08a17e3ca93cec7c889a4c5f50/ide/MoonshineSharedCore/src/actionScripts/plugin/templating/TemplatingPlugin.as#L149

**Comment by JoelProminic** [comment]
The Bamboo build errors have been resolved.  I tested with the latest build, and I see that the current logic works like this:
1. Right-click on project directory > New > Form
2. The prompt opens, and the default directory is nsfs/nsf-moonshine/odp/Forms
3. The user selects a different directory.
4. The selection reverts to Forms, and an error is displayed.

We discussed this in the Moonshine meeting today, and we'd prefer show an error and disable the submit button instead of resetting the position:
1. Right-click on project directory > New > Form
2. The prompt opens, and the default directory is nsfs/nsf-moonshine/odp/Forms
3. The user selects a different directory.
4. The selection is allowed, but an error is displayed.  The form can not be created

Updates for New > Page are still pending.

**Comment by JoelProminic** [comment]
The update is looking better, but I found this problem:
1. Right-click on project directory > New > Domino Page
2. The prompt opens, and the default directory is nsfs/nsf-moonshine/odp/Pages
3. Type a name for the page
4. The user selects a different directory.
5. The selection is allowed, but an error is displayed. The page can not be created
6. Select Pages directory again. BUG:  The error clears, but the Create button is not reenabled.  Also, the window scroll resets, so the selection is not visible without scrolling
7. Modify the name of the page.  BUG:  the Create button still does not enable
8. Clear the page name and re-type it.  Now the Create button is enabled again.

**Comment by JoelProminic** [comment]
I confirmed the behavior looks good for both pages and forms.   This is ready for a merge, but we need to be careful with it, since this is an old branch.

I merged master into this branch for the #1000 changes, so make sure you update before merging or making changes.

**Comment by JoelProminic** [comment]
I took care of the merge myself.  I didn't any problematic behavior, so this should be fine.
