### ISSUE TITLE
Find/Replace Window Throws an Exception When Replace Value is Null

### ISSUE THREAD

**Issue by rat-moonshine** [Moonshine-IDE/Moonshine-IDE#929]
@JustinProminic reported that,

> I try doing a basic find and it throws an exception....  see below.
> 
> ![image](https://user-images.githubusercontent.com/24370870/142817051-8ce1261f-071c-45ae-b37d-d5408963bb39.png)
> 

While looking into the error details it tries to call `addChangesForReplace()` which occurs during a find/replace, @JustinProminic later confirmed this in other email, additionally with following observation:

> Ok, the previous exception should still be handled more gracefully than it is, by not throwing an exception just because the user pressed "Replace/Find" without text being in the "replace".
> 
> I then actually READ the dialog and realized the "find" button is way over to the right.
> 
> I do not find this dialog intuitive given this information.
> 
> I think "Find" is the thing programmers do far more than 'Find/replace", so please redesign this dialog with the Find at the left.
> 
> ![image](https://user-images.githubusercontent.com/24370870/142817473-b3458f52-19c6-4d19-bdbb-16e10d0b5ef3.png)
>

**Comment by piotrzarzycki21** [comment]
@rat-moonshine As I expressed in the email I'm not sure if this is a good change. We can discuss it during the call. I would like to hear on what bases that change should happen.

**Comment by rat-moonshine** [comment]
We can have all three buttons in a sequence starts with "Find". I don't see any bad in that.

However, I wouldn't recommend custom handling in form focus when Tab key is pressed.

**Comment by piotrzarzycki21** [comment]
> We can have all three buttons in a sequence starts with "Find". I don't see any bad in that.
> 
> However, I wouldn't recommend custom handling in form focus when Tab key is pressed.

Do you mean starts from the very left "Find" ?

**Comment by JoelProminic** [comment]
When use this interface I generally just hit Enter after typing the search text, which triggers the Find action.  Trying to handle this with Tab-ing through the buttons seems like overkill.  I don't have a strong opinion about changing the button position.

**Comment by JoelProminic** [comment]
Checking the same project as @JustinProminic, I was able to reproduce this issue.  
1. Checkout a project
2. Use Edit > Find Resources to open the file
3. CMD-F
4. Enter some search text
5. (Optional) enter replace text.  I saw the same bug whether I entered this or not
6. Click Replace/Find. BUG:  this triggered the below error:

    : Nov 22, 2021, 3:25:04 PM Error while handling document change. URI: file:///Users/-user-/.../CheckDominoDesignEelmentExistForStatic.java
    : File not found: /USERS/-user-/.../CheckDominoDesignEelmentExistForStatic.java.
    : Java Model Exception: Core Exception [code 368] File not found: /USERS/-user-/.../CheckDominoDesignEelmentExistForStatic.java.

It looks to me like the problem is because USERS is capitalized.  My workstation is case-sensitive, so this fails for me, but may not fail for other users.

Is this a bug with converting a URI to a normal path?  Maybe the logic was intended for Windows?

This project is Prominic-internal, and I couldn't reproduce it on a simple project template.  I also notice it stops triggering for a while on the above file, so there seems to be something else happening here.   Please take a look for the capitalization error to see if that gives more context for the bug.  If you don't find anything, I'll do some more testing to see if I can track this down further.

**Comment by rat-moonshine** [comment]
The above bug looks interesting. I never seen such error before. The path to a file provides by the `File` API once the `File` object is generated to the editing file. We may or may not do [canonicalize](https://help.adobe.com/en_US/FlashPlatform/reference/actionscript/3/flash/filesystem/File.html#canonicalize()) during some handling of the file. Therefore the path used by `File.nativePath` way by Moonshine. 

We can try do a `canonicalize` when a path set to a `File` object, but I'm not sure whether this will fix the above particular problem, or may produce any unknown side-effect.

Beside this, I do able to produce the problem that @JustinProminic reported though,

1. Open any project
2. Open any text file
3. Enter a value in search field
4. Leave the replace field blank (optional)
5. Keep pressing `Tab`
6. Hit `Enter` on "Replace/Find" button
7. Moonshine throws following error during a replace/find activity [Bug]:
```
: Error #1009
: TypeError: Error #1009
: 	at moonshine.editor.text.managers::FindReplaceManager/addChangesForReplace()
: 	at moonshine.editor.text.managers::FindReplaceManager/replace()
: 	at moonshine.editor.text::TextEditor/replaceOne()
: 	at actionScripts.ui.editor::BasicTextEditor/searchReplace()
: 	at actionScripts.plugin.findreplace::FindReplacePlugin/dialogSearch()
: 	at flash.events::EventDispatcher/dispatchEvent()
: 	at feathers.controls::ScrollContainer/dispatchEvent()
: 	at moonshine.plugin.findreplace.view::FindReplaceView/replaceOne()
: 	at moonshine.plugin.findreplace.view::FindReplaceView/replaceOneButton_triggerHandler()
```

This error looks like a more general problem and can producible every time. We need to fix this.

**Comment by rat-moonshine** [comment]
> Do you mean starts from the very left "Find" ?

I'd prefer to keep all buttons at right in this case because with mouse this side faster reachable than at left.

**Comment by rat-moonshine** [comment]
It appears the original [exception](https://github.com/Moonshine-IDE/Moonshine-IDE/issues/929#issuecomment-976210467) reported is _possibly_ fixed by @joshtynjala in https://github.com/Moonshine-IDE/moonshine-feathersui-text-editor repo. I confirm I couldn't able to produce the exception anymore.

However I see another exception in my followed by tests:
1. Open any project and any file to editor
2. Open find/replace window
3. Enter some value in search field
4. Left the the replace value as it is (optional)
5. Click on "Replace/Find" button
6. Replace/find completes with no error
7. Hit the "Replace/Find" button again - [Bug] throws following exception:
```
: Error #1009: Cannot access a property or method of a null object reference.
: TypeError: Error #1009: Cannot access a property or method of a null object reference.
: 	at moonshine.editor.text.managers::FindReplaceManager/addChangesForReplace()[/Users/devsena/ProminicGITBranch/moonshine-feathersui-text-editor/src/moonshine/editor/text/managers/FindReplaceManager.hx:206]
: 	at moonshine.editor.text.managers::FindReplaceManager/replace()[/Users/devsena/ProminicGITBranch/moonshine-feathersui-text-editor/src/moonshine/editor/text/managers/FindReplaceManager.hx:112]
: 	at moonshine.editor.text::TextEditor/replaceOne()[/Users/devsena/ProminicGITBranch/moonshine-feathersui-text-editor/src/moonshine/editor/text/TextEditor.hx:944]
```

Upon investigation it appears that the tuple `result` is _null_ at [here](https://github.com/Moonshine-IDE/moonshine-feathersui-text-editor/blob/master/src/moonshine/editor/text/managers/FindReplaceManager.hx#L202). I could set a null check and terminate the process, but it's possible that @joshtynjala may have better idea why the `result` is null here and add more appropriate approach. Anyway, I don't have write access to this repository so I haven't commit anything. The problem left at is for now.

**Comment by rat-moonshine** [comment]
Keeping the basic priority of the find/replace window, I changed the button ordering in find/replace window in following priority:
1. Find
2. Replace/Find
3. Replace All

One can also start a basic search by either pressing the `Enter` key when remain in the search-input-field, when pressing `Enter` key by remain in replace-input-field shall trigger replace/find procedure. 

![image](https://user-images.githubusercontent.com/24370870/143003784-b9fa1e77-6dd3-4436-8d0e-6cef7dc2c720.png)

**Comment by piotrzarzycki21** [comment]
> Keeping the basic priority of the find/replace window, I changed the button ordering in find/replace window in following priority:
> 
> 1. Find
> 2. Replace/Find
> 3. Replace All
> 
> One can also start a basic search by either pressing the `Enter` key when remain in the search-input-field, when pressing `Enter` key by remain in replace-input-field shall trigger replace/find procedure.
> 
> ![image](https://user-images.githubusercontent.com/24370870/143003784-b9fa1e77-6dd3-4436-8d0e-6cef7dc2c720.png)

I don't like the idea. The main focused button should be Find without logic which allows trigger - Replace/Find/Replace All. There are super strong operation which may messed things up in your code. Please investigate other IDE how that windows works, revert code untill we discuss the changes and all agree for it. I have expressed that in above posts and email.

**Comment by rat-moonshine** [comment]
"Find" is suppose to be the first in ordered buttons, so it always get priority over "Replace/Find" and "Replace All". When a user moves by pressing `Tab` key, "Find" will be the normal first-in-order option as well.

Considering the earlier state, I don't see how you sees "Find" was the main focused option and now is not. If you meant by focused item is visually - then perhaps I'd suggest to keep "Find" far left but that wouldn't look good either and user may require to shift his mouse far to the left to reach the button. 

The earlier order of "Replace/Find", "Replace All" and "Find" can cause the trouble @JustinProminic reported. I don't recommend to break the field-in-focus by order in a form either. You can provide with more thoughts if you see some idea from elsewhere. We'll discuss on this in weekly meeting, anyway.

**Comment by piotrzarzycki21** [comment]
> "Find" is suppose to be the first in ordered buttons, so it always get priority over "Replace/Find" and "Replace All". When a user moves by pressing `Tab` key, "Find" will be the normal first-in-order option as well.
> 
> Considering the earlier state, I don't see how you sees "Find" was the main focused option and now is not. If you meant by focused item is visually - then perhaps I'd suggest to keep "Find" far left but that wouldn't look good either and users may require to shift their mouse far to the left to reach the button.
> 
> The earlier order of "Replace/Find", "Replace All" and "Find" can cause the trouble @JustinProminic reported. I don't recommend to break the field-in-focus by order in a form either. You can provide with more thoughts if you see some idea from elsewhere. We'll discuss on this in weekly meeting, anyway.

It looks like you didn't understand me again. Focus on find is mandatory. I don't like the order - Find in my opinion should be far right.

**Comment by JoelProminic** [comment]
I see that I get a console error on Replace/Find when there are no matches
1. Open a file
2. Enter a string that won't match anything in the file (i.e. "xxxxxx")
3. Click Replace/Find.  BUG:  error triggers - see below
4. Click Find.  BUG: Nothing happens and no error is displayed

    : Error #1009
    : TypeError: Error #1009
    : 	at moonshine.editor.text.managers::FindReplaceManager/addChangesForReplace()
    : 	at moonshine.editor.text.managers::FindReplaceManager/replace()
    : 	at moonshine.editor.text::TextEditor/replaceOne()
    : 	at actionScripts.ui.editor::BasicTextEditor/searchReplace()
    : 	at actionScripts.plugin.findreplace::FindReplacePlugin/dialogSearch()
    : 	at flash.events::EventDispatcher/dispatchEvent()
    : 	at feathers.controls::ScrollContainer/dispatchEvent()
    : 	at moonshine.plugin.findreplace.view::FindReplaceView/replaceOne()
    : 	at moonshine.plugin.findreplace.view::FindReplaceView/replaceOneButton_triggerHandler()
    : 	at flash.events::EventDispatcher/dispatchEvent()
    : 	at feathers.events::TriggerEvent$/dispatchFromMouseEvent()
    : 	at feathers.utils::PointerTrigger/pointerTrigger_target_clickHandler()
    :
    : Click here to Report a Bug


Instead, in both cases I would like to see it display a red error message next to the buttons or at the bottom of the panel.  A short message like "No matches" would be sufficient, and wouldn't use up to much horizontal space.

**Comment by joshtynjala** [comment]
I didn't change the Find/Replace code significantly when I translated to Haxe. It's probably a simple fix. I'll investigate.

**Comment by JoelProminic** [comment]
We discussed this in the meeting today, and we would like to move the buttons back to their original positions.

We would also like to consider better separation for the Find and Find/Replace logic, by simplifying the default find prompt.  This will need to be in a separate issue, though.

**Comment by JoelProminic** [comment]
I created a separate issue, #940, for the other Find interface updates.

**Comment by piotrzarzycki21** [comment]
@rat-moonshine can you make that update first thing on Monday ASAP ? This window just drives me...

**Comment by rat-moonshine** [comment]
You don't need to wait till Monday. I have restored the buttons ordering.

**Comment by JoelProminic** [comment]
I see the buttons are back in their original position, and Enter works as described above for each field.
