### ISSUE TITLE
JDK 8 Support for Ant

### ISSUE THREAD

**Issue by JoelProminic** [Moonshine-IDE/Moonshine-IDE#933]
While revisiting #668, I noticed that the `Run Ant File` action in the right-click menu is failing with Moonshine Development 3.3.0 on macOS Catalina.  After some investigation, I discovered this is because it was using JDK 11 instead of JDK 8.

I would like to have Ant respect the `Java Project > JDK > Use JDK 8` setting for a project.  This includes:
- `Run Ant File` 
- `Project > Build with Apache Ant` (if it is supported on the same project types as the above setting
- `Others > Build Apache Ant File`

Another solution would be to add a parameter to change JAVA_HOME in the form opened by some of the above interfaces, but I would like to avoid extra prompts on this.

**Comment by rat-moonshine** [comment]
A quick though, we may able to support running Ant with current set JDK against a project in following two options:
- Run Ant File
- Project > Build with Apache Ant (if it is supported on the same project types as the above setting

With `Others > Build Apache Ant File` user can trigger an arbitrary Ant file located somewhere which is not part of the project. We probably want to run with default-JDK in this case.

**Comment by rat-moonshine** [comment]
I made some changes in `AntBuildPlugin` to cover all three options mentioned in the original issue:

- Tries to determine if the given path has a corresponding project opened into Moonshine
- Checks if the project has multiple Java option (i.e. Java projects)
- Runs the Ant build setting the temporary environment variables accordingly

Following are my tests after having the changes:

Project Type | Default Java to Project | Ant Java Usage
------------|--------|--------|---------------
Non-Java | JDK | JDK
Non-Java | JDK | JDK (may Ant task fail with error reported)
Java | JDK | JDK
Java | JDK8 | JDK8

I tested above by adding Ant build file in projects having `<echo>${java.version}</echo>` in its content.

**Comment by JoelProminic** [comment]
I would like to setup the environment with the same script we use for other commands so that we can support other SDKs without custom logic.  See #938 for more discussion on this.

**Comment by rat-moonshine** [comment]
> I would like to setup the environment with the same script we use for other commands so that we can support other SDKs without custom logic. See #938 for more discussion on this.

I have separated this enhancement as https://github.com/Moonshine-IDE/Moonshine-IDE/issues/949 from the original issue here. For now, I keep this for v3.3.1. If I'd see this is ready before v3.3.0 we can move the issue in current milestone.
