### ISSUE TITLE
Broken Prompt on build.gradle or pom.xml Update

### ISSUE THREAD

**Issue by JoelProminic** [Moonshine-IDE/Moonshine-IDE#936]
@joshtynjala, I ran into some problems while editing build.gradle after your [file system watcher updates](https://github.com/Moonshine-IDE/Moonshine-IDE/issues/911#issuecomment-975808121)
1. Create a new Java Gradle project
2. Open build.gradle
3. Edit the file and save.  For my tests,  added the compatibility lines for Java 8 support.
4. A prompt opens showing "A build file was modified...".  BUG:  none of the buttons are clickable, and Moonshine is locked

![image](https://user-images.githubusercontent.com/24532731/143098810-45623e86-6f9a-4655-aeda-5c7d812f263c.png)

Example edit for build.gradle
```
// Required for Java 8 Language server support
sourceCompatibility = 1.8
targetCompatibility = 1.8
```

I can repeat the same bug with a Java Maven and pom.xml.  Even a whitespace update is enough to trigger the prompt.

I also have some concerns about the buttons:
- Never/Always.  Where is this stored?  Will it apply to all build scripts, or just the current one?  Does it persist across Moonshine restarts?
- Does it make sense to have a Skip button to ignore an update once?  This might be used when a user is still planning to make updates to the build script, but it doesn't take that long for the language server to restart.

**Comment by joshtynjala** [comment]
The Java language server sends a notification to Moonshine to display this prompt. We are simply showing the text and buttons that it requests, and clicking the buttons should result in Moonshine sending a response back to the language server.

I will fix the issue where button clicks are not working in this prompt.

**Comment by JoelProminic** [comment]
I confirmed that the "Now" button does not hang anymore.  I'd like to test the Never and Always buttons as well, but this may prevent me from doing other tests later.  @joshtynjala, are you aware of an option to reset this in the language server?

**Comment by joshtynjala** [comment]
Yes, the language server allows you to change this value after choosing Always/Never, but we don't currently expose a way for users to change it outside of this specific prompt. With the current implementation, a response of Always/Never should get saved for the current session only, and it will persist until you restart Moonshine. After you restart Moonshine, it will display this prompt again.

In VSCode, it also gets exposed as a setting/preference, which allows the response to be remembered permanently across sessions, while also allowing users to change it to a different value later. In an ideal implementation, this is probably what Moonshine should do too, but the once per session prompt is a good enough starting point for now.

**Comment by JoelProminic** [comment]
Thanks for the clarification.  I confirmed that:
- The selection lasts until Moonshine is restarted
- The prompt will trigger separately for different projects and language server instances.  This makes sense with your explanation above, but it may be confusing for users who are working with multiple projects for the same application.

Yeah, I think it would be better to have a global setting for this that would automatically respond to the language servers unless the Now option is selected (which would be the default).  It would probably be good to add a log message to the console for these cases so that we can tell what is happening, though.

That said, I agree that the current implementation is good enough for now.
