### ISSUE TITLE
Gradle Language Server Error on JAR Dependency

### ISSUE THREAD

**Issue by JoelProminic** [Moonshine-IDE/Moonshine-IDE#937]
@joshtynjala, I noticed that I started getting language server errors after your [recent updates](https://github.com/Moonshine-IDE/Moonshine-IDE/issues/911#issuecomment-975808121).  I'm not sure if they are directly related, but I was able to open projects like this on Monday morning with no errors.

After some investigation I found that if I add a `compile files` dependency, then the project shows the errors.  

```
dependencies {
    compile files('lib/TestJavaGradle_1123.jar')
}
```

Here is a minimal example based on the Java Gradle template: 

[TestJavaGradle_1123.zip](https://github.com/Moonshine-IDE/Moonshine-IDE/files/7591000/TestJavaGradle_1123.zip)

    : Nov 23, 2021, 2:48:36 PM Synchronize project TestJavaGradle_1123 failed due to an error in the referenced Gradle build.
    : Could not run phased build action using connection to Gradle distribution 'https://services.gradle.org/distributions/gradle-7.0-rc-1-bin.zip'.
    : org.gradle.tooling.BuildException: Could not run phased build action using connection to Gradle distribution 'https://services.gradle.org/distributions/gradle-7.0-rc-1-bin.zip'.
    ...
    : Caused by: org.gradle.internal.exceptions.LocationAwareException: Build file '/Users/-user-/Documents/Flex/temp_workspace/TestJavaGradle_1123/build.gradle' line: 9
    ...
    : Caused by: org.gradle.api.GradleScriptException: A problem occurred evaluating root project 'TestJavaGradle_1123'.
    ...
    : Caused by: org.gradle.internal.metaobject.AbstractDynamicObject$CustomMessageMissingMethodException: Could not find method compile() for arguments [file collection] on object of type org.gradle.api.internal.artifacts.dsl.dependencies.DefaultDependencyHandler.
    ...

I see this is is using Gradle 7.0 rc-1.  Was this changed recently?

I also noticed that the project had a strikethrough.  Does this indicate that the language server is not working properly?
![image](https://user-images.githubusercontent.com/24532731/143121352-2976e210-2173-47f7-bf66-061d6bc9f9bd.png)

**Comment by joshtynjala** [comment]
I updated the Java language server to the latest version yesterday in commit 5f9fda306ba174373de15de6361baae8f5f06bbe. I guess that this could affect which version of Gradle is used internally by the language server. According to [this StackOverflow answer](https://stackoverflow.com/a/66910991), `compile` was deprecated in Gradle 4.10 and replaced by `implementation`. `compile` was removed in Gradle 7, so it looks like you need to modify your Gradle file to use `implementation` instead.

I don't know what why a strikethrough style would be rendered in the file explorer. That is not an area of the code that I have worked on much.

**Comment by JoelProminic** [comment]
Thanks, that explains the error.  I remember hearing about the name changes before, but it hasn't been a problem until now.  

`implementation` works fine with the current Moonshine Gradle version, so I'll work on updating build.gradle on my projects. 

I see that new Grails projects in Moonshine have many `compile` entries.  However, I don't get an error in this case, just a warning that [seems to be unrelated](https://github.com/groovy/groovy-eclipse/issues/899)

    : WARNING: An illegal reflective access operation has occurred
    : WARNING: Illegal reflective access by org.codehaus.groovy.vmplugin.v7.Java7$1 (file:/Applications/MoonshineDevelopment.app/Contents/Resources/elements/groovy-language-server/groovy-language-server-all.jar) to constructor java.lang.invoke.MethodHandles$Lookup(java.lang.Class,int)
    : WARNING: Please consider reporting this to the maintainers of org.codehaus.groovy.vmplugin.v7.Java7$1
    : WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
    : WARNING: All illegal access operations will be denied in a future release

I'm seeing that Grails 3.10.0 uses Gradle 3.5, so it doesn't support `implementation`.  We may need to [update the Grails version for Moonshine](https://github.com/Moonshine-IDE/Moonshine-SDK-Installer/issues/43) if this becomes a problem.

For the strikethrough issue, @rat-moonshine thought this was a feature from Moonshine-Web.  We don't understand why it would be triggering in Moonshine Desktop suddenly, so thanks for clarify that it was not a change on your side.  We may create a separate issue for this.

I'm going to close this issue unless I find a template that requires updates, or some other required Moonshine change.
