### ISSUE TITLE
Tab Edited Status Does Not Update for JAVA and MXML

### ISSUE THREAD

**Issue by JoelProminic** [Moonshine-IDE/Moonshine-IDE#939]
While testing with the nightly build today (3.3.0 build 2233, on macOS Catalina), I noticed that .java and .mxml files do not properly show the edited status in the tab.  They also don't report unsaved changes when closing the tab, which is probably related to the first issue.

However, other files like build.gradle to show changes properly.

Here is a test procedure:
1. Create/Open a Java Gradle project
2. Add a space to the end of a line.  The tab shows a '*"
3. Close the tab without saving.  Moonshine shows an error
4. Open src/main/java/%project%.java
5. Add whitespace to the end of a line.  BUG:  the tab status does not change.

I also noticed the status did not update when doing a Find/Replace (see #929)

There may be other affected files.  I haven't done a full test yet.

**Comment by rat-moonshine** [comment]
Some debug/investigation on this if helps @joshtynjala to raise a fix, `BasicTextEditor` rely on `editor.TextEditorChangeEvent` to update the tab-label or flag an editor changed. 

During my tests I couldn't able to get the event from corresponding editor in case of:
- `.as`
- `.mxml`

But this works for:
- `.xml`

Here's the [listener](https://github.com/Moonshine-IDE/Moonshine-IDE/blob/master/ide/MoonshineSharedCore/src/actionScripts/ui/editor/BasicTextEditor.as#L268) that attache to the `editor`. If we ensure `editor` dispatches the text-change event tab should update accordingly.

**Comment by JoelProminic** [comment]
The flag seems to update properly now.   I tested with .java and .mxml files, and with normal editing and Find/Replace
