### ISSUE TITLE
Project Name With Strikethrough Text-style

### ISSUE THREAD

**Issue by rat-moonshine** [Moonshine-IDE/Moonshine-IDE#943]
We started noticing this following strikethrough text-style recently in sidebar. We don't yet know what causing this in a desktop build-run.

![image](https://user-images.githubusercontent.com/24370870/143809146-a57b1ceb-0c62-4ebe-b2ec-5b819c8c9098.png)

The strikethrough text-style once created particularly for the web-version of Moonshine run, [here's](https://github.com/Moonshine-IDE/Moonshine-IDE/issues/324#issuecomment-406159811) some details on the same.

**Comment by rat-moonshine** [comment]
If we unable to find a good way to reproduce this, I'll remove the strikethrough codes then. Anyway this style isn't using anymore which particularly created once for the web-build.

**Comment by piotrzarzycki21** [comment]
Try to delete some files from the project couple of times and see if it happen.

**Comment by JoelProminic** [comment]
This triggers frequently, but not consistently, for me when I have multiple Java Maven or Gradle projects open in my workspace.  I haven't found a good test procedure for this yet, but I have only noticed this on Java projects so far.

**Comment by rat-moonshine** [comment]
Okay. Currently, as I understand this triggers when `isDeleting` variable is changed (in `FileWrapper`). I remember I wrote `isDeleting` to notify the file is currently deleting on remote and does not uses any place else. The `isDeleting` sets during tree-refresh. It's hard to identify which process suddenly [triggers](https://github.com/Moonshine-IDE/Moonshine-IDE/blob/master/ide/MoonshineSharedCore/src/components/views/project/TreeView.mxml#L176) this variable to change unless we have a way to reproduce this each time. 

I don't want to spend time to find which process/steps triggers this. I'll check a few things to identify where it may cause, if not found and `isDeleting` not being used elsewhere I'm going to remove the strikethrough case.

**Comment by rat-moonshine** [comment]
Tried to look something more into this, it appears that `isDeleting=true` sets only during [DeleteFileCommand](https://github.com/Moonshine-IDE/Moonshine-IDE/blob/master/ide/MoonshineSharedCore/src/actionScripts/controllers/DeleteFileCommand.as). It is still unclear why suddenly a delete command-execution get called between tasks. Unless we identify a clear steps to reproduce this is hard to determine. I didn't found any reproducible steps during my tests. 

For now, I'm removing the UI style that generates the strikethrough text as it has no implication in a desktop run. I'm not removing `isDeleting` however. The strikethrough style remain available for legacy web-build.

**Comment by JoelProminic** [comment]
I haven't seen this bug again since @rat-moonshine's fix.  I'm a little worried that the isDeleting flag could cause trouble later, but this should be good enough for now.
