### ISSUE TITLE
Provide Minimal OS Information in About Dialog

### ISSUE THREAD

**Issue by rat-moonshine** [Moonshine-IDE/Moonshine-IDE#944]
From @JustinProminic 

> Please under the "Version 3.3.0..." line, have a new line that shows as much about the OS it is running on as you reasonably can.
> 
> ![image](https://user-images.githubusercontent.com/24370870/143810392-b73ba31c-d7f9-4009-8ed7-2f1db27046c3.png)
> 
> This would reduce the time it takes for me slightly when I'm sending the MacOS release separately.
> otherwise, I technically have to also send this screen shot:
> ![image](https://user-images.githubusercontent.com/24370870/143810409-9e6c513c-56ab-41ef-9a4a-802918a3efd3.png)
>

**Comment by rat-moonshine** [comment]
![image](https://user-images.githubusercontent.com/24370870/143813068-ce4a3ac3-39c7-4ef7-a348-e0d7ab15cfe9.png)

**Comment by JoelProminic** [comment]
I confirmed this is working for the non-Sandbox and Windows builds as well:

![image](https://user-images.githubusercontent.com/24532731/143959869-4674a78b-976c-4b43-9210-631e7224bf5a.png)
![image](https://user-images.githubusercontent.com/24532731/143959855-41c567e6-3d8e-4922-b818-b25e5f3b4d60.png)
