### ISSUE TITLE
File Creation Dialog Is Showing Path In Package Style

### ISSUE THREAD

**Issue by rat-moonshine** [Moonshine-IDE/Moonshine-IDE#945]
As @JustinProminic reported,

> I just noticed this oddity.
> 
> The source folder should be showing on Mac (and someday Linux):
> ExampleCommandLineAppAccessIMOS/src/main/java
> 
> and on Windows
> ExampleCommandLineAppAccessIMOS\src\main\java
> 
> The reason why we are using "." as the path separator escapes me.
> 
> We should not be confusing our users with quirks like this.  Lets give people what they expect to see please based upon their host OS.
> 
> ![image](https://user-images.githubusercontent.com/24370870/143836990-47461f4b-0de8-4d85-b40f-b277f033d63a.png)
>

**Comment by rat-moonshine** [comment]
Some note on the existing design - initially it was panned in Eclipse way where dotted syntax displays to point where the target file is creating. However, the label is misguiding in Moonshine certainly, where it was "Package" in Eclipse but "Source Path" in Moonshine. 

We can choose between either package or path way and have this adjusted:
1. Modify the label as "Package" and display `src.main.java` instead of `MyJavaProject.src.main.java`
2. Keep the label as "Source Path" and replace the dotted syntax with file-slash

**Comment by rat-moonshine** [comment]
I go by option.2 above which fits to our different use-cases. This now looks separated with file separator as suggested in the original issue:

![image](https://user-images.githubusercontent.com/24370870/143859712-12160bc8-dcf1-4fe7-a14a-270ccf890652.png)

I also noticed a problem in new-file type popups where the "Source Folder" opens ungenerated, until a node being selected in its folder tree. This being fixed now:

![image](https://user-images.githubusercontent.com/24370870/143860157-f995554b-5bb8-4b13-84a8-fe10c45c7a55.png)

**Comment by JoelProminic** [comment]
One problem I see with this solution is that directories need to be created manually (and not in the New Class prompt) for new packages.  Even a standard basic package has at least three directories (i.e. `com.company.project`) so this will quickly get tedious.  We could improve this by letting the user select or specify the package manually, and then creating the missing directories automatically.  This is beyond the scope of this issue, though.  We could consider implementing this as part of other package updates I discussed here:  https://github.com/Moonshine-IDE/Moonshine-IDE/issues/911#issuecomment-969285162

**Comment by JoelProminic** [comment]
I did a test with a new package in a Java Gradle project
1. Create a new directory for `src/main/net/prominic/test`.  (Note that the tree reset after each directory creation - we'll need to discuss this in #911
2. Right-click on the `test` folder and chose New > Java Class
3. Name the class Test and create it
4. BUG:  package is defined as `net/prominic/test` instead of `net.prominic.test`

```
package net/prominic/test;


public class Test  
{
	public Test()
	{
	}
}
```

I feel like we had a similar bug a while back, but I couldn't find an issue - did the update for that bug break the New > Java Class logic?

**Comment by rat-moonshine** [comment]
It appears that the earlier change affects far more than the initial scope I tested. I can see the package generation broken in other class-types, too:

AS3: directory - `src/subA/subB/subC/subD/TestFile.as`, package creates as: `package subA/subB/subC/subD`
Java: directory - `src/main/java/prominic/test/Test.java`, package creates as: `package prominic/test;`

After investigation I noticed that the same package building method (which earlier used with dotted syntax and now with file-slash) uses during generating different files by templating plugin. The new change thus affected all file types' generation   logic.

I have separated the path-reference from package-reference now. This should work now accordingly. I gave some tests generating different class-types between macOS and Windows.

Please, check.

**Comment by JoelProminic** [comment]
I did some testing, and I didn't see any problems.  I'm glad to see that Grails is working properly in the different source paths.

Type | File Dialog | Package
-----|-------------|--------
Java | Correct | Correct
Java (Grails) | Correct | Correct
Groovy (Grails) | Correct | Works with src/main/groovy, grails-app/services, grails-app/controllers 
AS3 Class | Correct | Correct
AS3 Interface | Correct | Correct
Haxe Class | Correct | Correct
Haxe Interface | Correct | Correct


Package | AS3 Result
--------|-------
None (directly in src) | "package " for AS3, no line for Java/Groovy/Haxe
net | "package net"
net.prominic | "package net.prominic"
net.prominic.test | package net.prominic.test
