### ISSUE TITLE
View > Problems View Should Be Open By Default

### ISSUE THREAD

**Issue by JoelProminic** [Moonshine-IDE/Moonshine-IDE#946]
@JustinProminic requested that we have the Problems tab (View > Problems View) open by default for Moonshine.  The Console tab should still be open by default, but the Problems tab should exist so that it is easier for new users to find.

I expect the open/closed state of the tab to be preserved on restart like it is currently, so this will only matter for fresh installations.

**Comment by JoelProminic** [comment]
I'm noticing that the Problems tab always has focus when I reopen Moonshine, even if I was on the Console tab before the restart.  If we don't save the active tabs, I'd like to make the Console tab have focus by default.

**Comment by rat-moonshine** [comment]
"Problems" is now a startup tab along with "Console", keeping "Console" is the highlighted one. Please, check.

**Comment by JoelProminic** [comment]
Testing this, I noticed this behavior:
1. Open Problems tab
2. Restart Moonshine
3. BUG: the Problems tab has focus on restart
4. BUG:  the Problems tab closes after about a second.

It seems that the new code opens the Problems view first, and then the saved Moonshine state tries to open the tab again and instead toggles it off.

In any case, we don't want to just reopen the Problems view on every restart - if the users don't want it, they should be able to close the tab and have it stay closed.  We just need to make sure that it opens initially for a fresh Moonshine install.

@rat-moonshine reported that the Problems tab has focus after a restart because it is the last tab added. We definitely want to have Console be the default tab for Moonshine on initial startup, so that the user can see any initial errors.  I would also like to keep the Console on the far left, so that it is in a consistent, priority position.

**Comment by rat-moonshine** [comment]
I have adjusted Problems panel display in following manner:

- Adds to display automatically in a fresh installation
- User close the Problems view intentionally
- Restarting Moonshine will not adds the view anymore automatically
- User adds the view intentionally
- Restarting Moonshine will re-add the view as was intended
- Keep the Console view always highlighted during a restart

Please, check.

**Comment by JoelProminic** [comment]
The Problem view updates look good for an existing installation.   I'll do a test with a fresh installation when I test some other issues that need this.

**Comment by JoelProminic** [comment]
Confirmed with cleared settings on macOS and Windows
