### ISSUE TITLE
Moonshine Closes When Update is Canceled

### ISSUE THREAD

**Issue by JoelProminic** [Moonshine-IDE/Moonshine-IDE#951]
I tried canceling a Moonshine update today when I saw there was a new build running, but I found that Moonshine closed and threw an error.
1. Open Moonshine
2. Update prompt appears.  Choose to update
3. Wait for the download to start, and then click Cancel.
4. BUG:  Moonshine closes, and throws a BUG:

![image](https://user-images.githubusercontent.com/24532731/144508707-13a9dfec-1ee3-40ae-9e4c-b88279f0dc5c.png)

It looks to me like Moonshine tried to continue the update process and run the installer, even though the download was canceled.

Instead, I would like to see Moonshine resume normal operation after the cancel.  This could be useful if the user's internet connection is unexpectedly slow, or they otherwise aren't willing to wait for the download to complete.

**Comment by rat-moonshine** [comment]
We probably need to re-visit the behaviour in other applications too, since mostly same code sharing.

**Comment by rat-moonshine** [comment]
I fixed a couple of issues:

Previously | Now
---------------|----------------------
Throwing error while cancelling a running download: ![image](https://user-images.githubusercontent.com/24532731/144508707-13a9dfec-1ee3-40ae-9e4c-b88279f0dc5c.png) | No error, download terminates, update-view disappears
Connection error while a download in-progress, throwing two different alerts: 
![image](https://user-images.githubusercontent.com/24370870/144580508-fee70a75-5469-4a0c-963f-56f68101d94a.png) | Throws only alert
Connection error while a download in-progress, left UI stuck: 
![image](https://user-images.githubusercontent.com/24370870/144580641-63b6a0a7-1a92-4265-b647-335bd2f5693e.png) | Restores the UI to initial state: 
![image](https://user-images.githubusercontent.com/24370870/144580808-0a8a6bb1-28ef-46e9-9be8-68c369b5dbd4.png)

**Comment by JoelProminic** [comment]
I confirmed that the original behavior was fixed.  However, I found that if I cancel a download and then wait a few minutes, Moonshine will close itself and show the downloaded installer.  It seems that the update process continues in the background.

The behavior for lost connections sounds good.  I'll add some notes once I have a change to test this.

**Comment by rat-moonshine** [comment]
> I confirmed that the original behavior was fixed. However, I found that if I cancel a download and then wait a few minutes, Moonshine will close itself and show the downloaded installer. It seems that the update process continues in the background.

I fixed this as part of other fixes in #923 . This can be tested with branch builds. If we see #923 is doing well then I shall plan a merge.

**Comment by JoelProminic** [comment]
I still need to test this with Windows.  I can do this once we have merged #923.

**Comment by JoelProminic** [comment]
This was merged to master, and I could not reproduce the problem on macOS or Windows.
