### ISSUE TITLE
I should be able copy to clipboard version of Moonshine from about section

### ISSUE THREAD

**Issue by piotrzarzycki21** [Moonshine-IDE/Moonshine-IDE#954]
In addition to issue #944 - field with version should be selectable and I should be able to easly copy it. If it's worth to have it - we can have button copy, but the minimum is having it selectable and ability to copy.

**Comment by rat-moonshine** [comment]
I usually think of 'copy to clipboard' option in functional cases, i.e. copying data. Providing ability to select/copy however is more suitable in this case. 

I made the About information selectable and copy.

**Comment by piotrzarzycki21** [comment]
Working nicely ;) Thanks!

**Comment by JoelProminic** [comment]
Yeah, it works for me as well. I can copy the macOS version as well, though the result only shows a single line:

> Version 3.3.0, Build 2287, Player: 33.1(Harman) Running On: Mac OS 10.15.7

![image](https://user-images.githubusercontent.com/24532731/146577519-ef9e819e-adaa-4f06-b9df-6d2982a4d29f.png)
