### ISSUE TITLE
File Ordering Incorrect After FileWatcher Update

### ISSUE THREAD

**Issue by JoelProminic** [Moonshine-IDE/Moonshine-IDE#955]
I noticed that the ordering of files in a project changes when I add a file outside of Moonshine:
1. Create/Open a project
2. Right-click > Copy Path
3. Open a Terminal and `cd` to the path
4. Create a new file with `touch test.txt`
5. Wait for Moonshine to update. BUG:  the files are reordered on the update, and it is no longer alphabetical
6. Refresh the project.  The files are ordered correctly.
![image](https://user-images.githubusercontent.com/24532731/145471027-d89aed33-6ab5-4023-bbb4-356158e60515.png)

This is not a critical bug, but it will be a distraction when it triggers.  We have had other problems with sorting on macOS before (see #650).

_Originally posted by @JoelProminic in https://github.com/Moonshine-IDE/Moonshine-IDE/issues/948#issuecomment-990223672_

We are planning to release Moonshine 3.3.0 tomorrow, so I moved this remaining issue from #948 to a separate issue

**Comment by joshtynjala** [comment]
With the latest changes, when the file system watcher worker causes the file tree to refresh a directory, its contents should now be sorted alphabetically. Additionally, I've figured out how to keep sub-directories open during a file system watcher worker refresh.
