### ISSUE TITLE
Encourage MacPorts Usage

### ISSUE THREAD

**Issue by Aszusz** [Moonshine-IDE/Moonshine-IDE#957]
Since we want to encourage Moonshine users to use MacPorts and we're making it a default part of our setup I'll gather here a couple of tiny improvements that came to my mind during the reconfiguration of my Mac and Moonshine IDE:

[SDK Installer]
1. Need to change the tooltip from homebrew to MacPorts:
![Screenshot 2021-12-28 at 21 18 11](https://user-images.githubusercontent.com/7197014/147604161-3d622cc4-8be7-46ac-a0c3-befcf90ffa21.png)

The command is: `sudo port install subversion`

[Moonshine IDE]
2. Default path for SVN when installed via MacPorts is `/opt/local/bin/svn`. This should be the new default.

[SDK Installer]
3. Even after I configure correct path in Moonshine IDE for SVN, Moonshine IDE installer insists it's not installed. Looks like it's hardcoded somewhere.

**Comment by rat-moonshine** [comment]
We'll probably need to create a corresponding issue in Moonshine SDK Installer repository as all the suggestion/problems are suppose to be MSDKI fix.

**Comment by JoelProminic** [comment]
I see that all of these issues are covered by https://github.com/Moonshine-IDE/Moonshine-SDK-Installer/issues/31
