### ISSUE TITLE
Directory Assistance Repository for Public GitHub Examples

### ISSUE THREAD

**Issue by JoelProminic** [Moonshine-IDE/Moonshine-IDE#958]
In today's meeting, @JustinProminic and I discussed adding a new Moonshine-IDE repository that will hold a moonshine-dependencies.xml file with various example projects that we have added recently.  For example:
- https://github.com/Moonshine-IDE/VagrantRoyaleExample
- https://github.com/Moonshine-IDE/ratpack-mongo-changestreams
- https://github.com/Moonshine-IDE/nodejs-mongo-backend
- Domino API example for #903
- DXL Importer example for #935 

I think this will then need to be added to the default repository list for Moonshine.

**Comment by piotrzarzycki21** [comment]
@JustinProminic  and @JoelProminic Why we are not using for all Royale examples this repository https://github.com/Moonshine-IDE/Royale-Examples ? 

There is so much repositories that this space starting to be a bit messy.

**Comment by JoelProminic** [comment]
Proposed repository name:  Moonshine-IDE-Examples-Directory-Assistance
I'm not really happy with this name, though, and I'd like to get a name we are satisfied with before we add it to the Moonshine repository list.

I looked through the Moonshine-IDE organization, and I didn't find may projects that were completely ready to be added to this repository.

Ready:
https://github.com/Moonshine-IDE/VagrantRoyaleExample
https://github.com/Moonshine-IDE/DominoAPILocalExample (Private)
https://github.com/Moonshine-IDE/Royale-Examples (already in Moonshine repositories list)


Needs project file:
Java:  https://github.com/Moonshine-IDE/ratpack-mongo-changestreams
Java:  https://github.com/Moonshine-IDE/ratpack-gradle-sse
Grails (private): https://github.com/Moonshine-IDE/captcha-server-2
Grails (private):  https://github.com/Moonshine-IDE/captcha-server

Unsupported language for Moonshine.  I could add fake Java or Actionscript/Flex code for these to allow them to open in Moonshine, but they won't have full integration
NodeJS:  https://github.com/Moonshine-IDE/nodejs-mongo-backend
Groovy:  https://github.com/Moonshine-IDE/ratpack-server
Pure HTML:  https://github.com/Moonshine-IDE/captcha-client

**Comment by JoelProminic** [comment]
I have created the initial version of the directory assistance project here:  https://github.com/Moonshine-IDE/Moonshine-IDE-Examples-Directory-Assistance

This needs to be added to the default repository list in Moonshine.

Unfortunately, I was not able to test this repository with the latest nightly build:
- Git is not working for me currently with macOS Moonshine.   I'll create a separate issue for this.
- When I opened the project locally, moonshine-dependencies.xml was not added as an XML entry in Manage Repositories.  Does this only trigger when cloning or checking out a project?

I added the "Ready" projects above, and we'll continue working on adding the remaining projects.

**Comment by rat-moonshine** [comment]
I have fixed #965 so you can continue with further testing on this (if any). Please, let me know when we're ready to have the new default-entry being added.

**Comment by JoelProminic** [comment]
For the Notes column, you can use:

> Moonshine-IDE example projects

This doesn't add much to the name, but I don't think we want to make this more complicated.

**Comment by rat-moonshine** [comment]
The new repository added to default-list in Manage Repositories. Additionally, I did some adjustment to support following things:

- Added handling to ensure Manage Repositories' default-list populates correctly with any new addition/updation
- Set default repositories non-editable/deletable

Please, check.

**Comment by JoelProminic** [comment]
The new entry looks good.  I confirmed it works with both an existing installation and a fresh installation.

I also tested a clone for each of the projects (and fixed a copy-paste error).   This is working fine.

I'm leaving this issue open for now so that we can discuss other projects to add, but the Moonshine side should be ready for the next release.

**Comment by JoelProminic** [comment]
I'm closing this issue for the release.  We can add more projects later.
