### ISSUE TITLE
TreeViewItemRenderer Error with feathersui 1.0.0-beta.8

### ISSUE THREAD

**Issue by JoelProminic** [Moonshine-IDE/Moonshine-IDE#959]
We started seeing the Moonshine fail today with this error:

    07-Jan-2022 04:51:13 	CompileGUICore:
    07-Jan-2022 04:51:13 	     [echo] Compiling GUI Core SWC
    07-Jan-2022 04:51:25 	     [exec] src/moonshine/theme/MoonshineTheme.hx:144: characters 74-105 : Class<feathers.controls.dataRenderers.TreeViewItemRenderer> has no field CHILD_VARIANT_DISCLOSURE_BUTTON
    07-Jan-2022 04:51:25 	
    07-Jan-2022 04:51:25 	BUILD FAILED
    07-Jan-2022 04:51:25 	/Users/.../Moonshine-IDE/ide/MoonshineSharedCore/build/build-lib.xml:241: The following error occurred while executing this line:
    07-Jan-2022 04:51:25 	/Users/.../Moonshine-IDE/ide/MoonshineSharedCore/build/build-lib.xml:952: exec returned: 1

Reviewing the logs, I see the feathersui library was updated to 1.0.0-beta.8:

    InstallHaxeDependencies:
    build	07-Jan-2022 01:48:12	     [echo] Installing Haxe Libraries
    build	07-Jan-2022 01:48:14	     [exec] Downloading feathersui-1,0,0-beta,8.zip...
    build	07-Jan-2022 01:48:16	     [exec] Installing feathersui...
    build	07-Jan-2022 01:48:17	     [exec]   Current version is now 1.0.0-beta.8
    build	07-Jan-2022 01:48:17	     [exec] Done

Checking the API, it looks like [TreeViewItemRenderer](https://api.feathersui.com/unstable/feathers/controls/dataRenderers/TreeViewItemRenderer.html) was deprecated:

>Deprecated: "TreeViewItemRenderer is deprecated. Use HierarchicalItemRenderer instead."

So it seems we need to switch to [HierarchicalItemRenderer](https://api.feathersui.com/v1.0.0-beta.8/feathers/controls/dataRenderers/HierarchicalItemRenderer.html) now.

For now, I cleared the error by downgrading the feathersui plugin.  This won't be reset by the Ant script - see #843.

haxelib install feathersui 1.0.0-beta.7

**Comment by rat-moonshine** [comment]
I tried to replace `TreeViewItemRenderer` with `HierarchicalItemRenderer` - in used item-renderer class and `MoonshineTheme.hx`. That didn't thrown any error during compilation, however when run it renders nothing. 

This might require some other handling than what exists now. I'd rather keep this for @joshtynjala to look into once.

**Comment by joshtynjala** [comment]
97aaadcaa77196c220663df980c7d1ed3e6b6dbb

**Comment by rat-moonshine** [comment]
The problem seems to be corrected. I'm closing this.

![image](https://user-images.githubusercontent.com/24370870/149092826-a6e4a316-9564-4050-8972-2980c729d4e1.png)
