### ISSUE TITLE
Updated Haxe Debug View

### ISSUE THREAD

**Issue by joshtynjala** [Moonshine-IDE/Moonshine-IDE#961]
Converting Moonshine's debug view to Haxe and Feathers UI.

This will require checking out the following Git repo:

git://github.com/Moonshine-IDE/moonshine-openfl-debug-adapter-client.git 

It should have the same parent directory as moonshine-openfl-language-client, and moonshine-feathersui-text-editor.

**Comment by joshtynjala** [comment]
@JoelProminic I have merged in the new debug view, which will require a change to the Bamboo plan, similar to when we added the new text editor. [(for reference)](https://github.com/Moonshine-IDE/Moonshine-IDE/issues/904#issuecomment-953255020)

This Git repo will need to be cloned:

git://github.com/Moonshine-IDE/moonshine-openfl-debug-adapter-client.git

**Comment by JoelProminic** [comment]
I updated the Bamboo builds, and I'll plan to do some testing for this tomorrow.

I added this to the 3.3.1 milestone.

**Comment by rat-moonshine** [comment]
I give this a try, it looks much more clear than the earlier UI:

![image](https://user-images.githubusercontent.com/24370870/149315267-ea6b4fa1-7852-4a51-9521-c5ae13cf1266.png)

I found the "Variables" listing prevent from any selection. I was wondering if this intentional.

**Comment by JoelProminic** [comment]
I tried the new interface with a simple Flex Desktop project.   Here are some screenshots for comparison:

Old Interface (Moonshine 3.3.0):
![image](https://user-images.githubusercontent.com/24532731/150233153-c5ac5d14-4c74-439a-924f-ca323ff337f8.png)

New Interface:  
![image](https://user-images.githubusercontent.com/24532731/150233172-a89e02c5-cfd4-4105-9a60-be009e3eae09.png)

Some things I noticed were missing from the new interface:
- The buttons on the left do not have tooltips.  Some of the icons are not familiar to me, like Step In and Step Out, so tooltips would be helpful
- The old interface had the same buttons in the Stack panel.  Do you remember these buttons had a special effect?   If they were the same effect, then I don't think we need to keep them in the new interface.


Some feature tests - everything seems fine:

Feature | Menu | Command | Button | Notes
--------|------|---------|--------|------
Build & Debug | Works | Works | N/A | 
Resume | Works | Works | Works | 
Pause | N/A | N/A | Works | 
Step Over | Works | Works | Works | 
Step In | Works | N/A | Works | 
Step Out | Works | N/A | Works | 
Stop | Works | Works | Works | 
Click row in Stack interface | N/A | N/A | Works | Jumps to line.  Steps are based on previous position

**Comment by joshtynjala** [comment]
> The buttons on the left do not have tooltips. Some of the icons are not familiar to me, like Step In and Step Out, so tooltips would be helpful

Okay, I will add tooltips to the buttons.

> The old interface had the same buttons in the Stack panel. Do you remember these buttons had a special effect? If they were the same effect, then I don't think we need to keep them in the new interface.

I forgot to add these buttons. Good catch! In projects with multiple threads/workers, the buttons allow control over each thread/worker individually. The main buttons don't specify a worker/thread, so it's up to the debug adapter to decide what to pause/resume/step/etc. (usually the main thread/worker, though).

**Comment by JoelProminic** [comment]
This is outside of the scope of this issue, but I was thinking about it after the discussion on variable selection.   I found it a little annoying that the variables tree closed after every step.  One common use case I have with debuggers is following the value of a specific variable, and it can be hard to find variables again with these classes.  However, I can see that keeping the tree expanded and focosed on a variable would be difficult as the user steps through the application with changing scopes.  The old interface behaved the same way.

That said, it might be better to find the variables in a different way:
- Search - this would probably have the same problems as variable selection, but it may be easier to find the variables originally
- Pinned expressions.  I have seen this in browser Javascript debuggers.  For a simple implementation, the user would provide a variable name (i.e. `aLocalVariable` or `this.aClassVariable`, and this would be updated (or marked as N/A) while stepping through the application.

If one of these ideas sounds easy and/or desirable, we can create a separate issue for this.

**Comment by joshtynjala** [comment]
> Search - this would probably have the same problems as variable selection, but it may be easier to find the variables originally

I'm not sure that this is possible because the variables are loaded on demand when you open branches in the tree. With circular references, it's potentially infinitely deep, so we probably couldn't load everything at once (but even if we could, that would probably have terrible performance).

> Pinned expressions. I have seen this in browser Javascript debuggers. For a simple implementation, the user would provide a variable name (i.e. aLocalVariable or this.aClassVariable, and this would be updated (or marked as N/A) while stepping through the application.

This is a feature that is available in some debug adapters, but it's not required by the protocol. Each debug adapter specifies which features they provide, so we could expose this when it's available.

**Comment by JoelProminic** [comment]
Ah, that is a good point about circular dependencies.  If we had classes/instances with references to each other, this could loop infinitely.

Thinking a bit more about what I described for the "expressions", I wonder if this would make more sense as a "pinned variable" instead:
1. The user right-clicks a variable and chooses "Pin"
2. An entry for the variable is added in a separate "Pinned" panel.  This would include the full path like `Locals.aLocalVariable` or `Locals.this.aClassVariable`
3. When the debugger steps or hits a new breakpoint, it tries to resolve the variable against the tree, retrieving children as needed.  If a tree node is missing, show N/A.
4. When the variable is no longer applicable, remove it with Right-click > Unpin

This is based on the tree rather than the scope, so it shouldn't require any special debugger functionality.  The tree lookup could be slow for complicated applications or objects, but it is limited at least.

**Comment by rat-moonshine** [comment]
> I found it a little annoying that the variables tree closed after every step.

This reminds me that I also noticed this during my tests earlier, I wonder if we had this behaviour in previous implementation, too. In a working situation, this a little annoying each time to manually expand nodes to a particular level after the tree refresh and closed all its nodes. 

Can we do something about it (?) (personally, I'm not very habituate to "pin" feature but looking through the list of nodes/properties.)

**Comment by joshtynjala** [comment]
I added the tool tips and the thread/worker debug controls.

One issue that I should mention that I'm already aware of: the grid column with the thread debug controls does not currently have alternating row background colors. The `alternateBackgroundSkin` style exists on the `ItemRenderer` class, but it seems that I never added it to the `LayoutGroupItemRenderer` class. I've added it to the next Feathers UI update, so I plan to come back later and enable the alternate background colors once that gets released. For now, it'll just need to be a minor cosmetic oddity.

**Comment by joshtynjala** [comment]
> ensure that grids update what they are displaying when removing all items

I found that, when clicking the resume/play button, the variables remained visible in the grid, but they should have been cleared until it was paused again.

> don't show branch controls on threads/stackframes grid if not paused

The triangle that indicates if a thread branch is opened or closed should be hidden when not paused, since there's no stack frames to show until paused. It should be revealed when paused (and the first branch will be expanded here too).

**Comment by JoelProminic** [comment]
Thanks for the clarification.  I confirmed these behaviors as well.  

@rat-moonshine, please try the updates.   If this is working well for your needs, we can close this issue.

**Comment by rat-moonshine** [comment]
I gave some tests after the updates, and this looks mostly better and easy to read. I see the selection in "Variables" column is working now:

![image](https://user-images.githubusercontent.com/24370870/151506767-bc0a6239-7457-4e61-81d8-04fb3977bf4e.png)

So far I not much tested with multiple threads (i.e. `worker`) in Moonshine-IDE, the additional thread-control seems to be handy, though. 

I still see nodes are collapsed on each breakpoint progress, although the root-node auto-expands this time. It'd be great if we can adjust the tree-nodes keep open during the breakpoint progress. 

I'd also wish Moonshine have some options in future, like "Skip All Breakpoints", or "Remove All Breakpoints", it'd be very handy in practice. But this wishes can refer as separate issues.

**Comment by rat-moonshine** [comment]
@joshtynjala do you have any other plan to update on this issue (?) Or, this one is ready for the milestone release, and we can close the issue for now.

**Comment by joshtynjala** [comment]
I don't have more plans at this time. Closing.
