### ISSUE TITLE
Null pointer exception in TreeView

### ISSUE THREAD

**Issue by piotrzarzycki21** [Moonshine-IDE/Moonshine-IDE#964]
Opening quite big project for one of our client I'm getting following error:

```
: Error #1009

: TypeError: Error #1009

:             at components.views.project::TreeView/sortChildren()

:             at components.views.project::TreeView/refresh()

:             at actionScripts.plugin.project::ProjectPlugin/handleWatchedFileDeletedEvent()

:             at flash.events::EventDispatcher/dispatchEvent()

:             at actionScripts.plugins.fswatcher::FSWatcherPlugin/onWorkerToMain()

:

: Click here to Report a Bug
```

Project is being opened, language server loaded and I don't do anything it's just occurs without any interaction. 

**OS: Windows 10
Moonshine Development version: 3.3.1 Build 774**

**Comment by rat-moonshine** [comment]
@joshtynjala pushed a fix https://github.com/Moonshine-IDE/Moonshine-IDE/commit/86fba851113ae7094bd11f9ef711fed7dd1dd5b4. @piotrzarzycki21 please give this a test.

**Comment by piotrzarzycki21** [comment]
It's working.
