### ISSUE TITLE
Git Integration Broken on macOS

### ISSUE THREAD

**Issue by JoelProminic** [Moonshine-IDE/Moonshine-IDE#965]
I tried to use Git in Moonshine today, and it was completely unusable because of Grant Permissions resrictions.  I tested with:
- MoonshineDevelopment:  Version 3.3.1, Build 2325, Player: 33.1(Harman)
- macOS 10.15.7 (Catalina)

I did a test with a fresh Moonshine settings folder, so that I could confirm that this was not caused by corrupt configuration:
1. Close MoonshineDevelopment
2. Rename or clear the settings in `~/Libraries/Application Support/com.moonshine-ide`
3. Open MoonshineDevelopment
4. Getting Started opens.  Scroll to the Git entry and click the configuration icon.
5. Click Allow Access and go through the Grant Permissions process
6. Open Moonshine > Settings > Git
7. BUG: interface reports `Invalid path:  path must contain usr/bin/git`
8. Click Change and set the path manually
9. BUG:  Moonshine still shows invalid path
10. Save the settings
11. Open Git > Manage Repositories.  BUG:  this is Git > Grant Permission instead
12. Try to clone Royale-Examples.  BUG:  Clone button doesn't work, with no visible error.
13. Close the panel.  BUG:  Allow Access opened behind the panel
14. Cancel the prompt and open Manage Repositories again.
15. Add a new repository (i.e. https://github.com/Moonshine-IDE/Moonshine-IDE-Examples-Directory-Assistance).  BUG:  interface shows "You need Git installed on your system"

**Comment by rat-moonshine** [comment]
All the problem mainly reasoned of broken Git path detection on macOS. I fixed it, following were test-results post the fix:

1. Close MoonshineDevelopment
2. Rename/delete the settings in ~/Libraries/Application Support/com.moonshine-ide
3. Open MoonshineDevelopment
4. Getting Started opens. Scroll to the Git entry and click the configuration icon.
5. Click Allow Access and go through the Grant Permissions process
6. Open Moonshine > Settings > Git
7. Git path sets correctly and no path-error [Fixed]
8. Click Change and set the path manually
9. Moonshine will report error if new path won't have `usr/bin/git` [Update/fix]
10. Open `Git > Manage Repositories` - no `Git > Grant Permission` this time
11. Try to clone Royale-Examples
12. Clone-window opens [Fixed]
13. Add a new repository (i.e. https://github.com/Moonshine-IDE/Moonshine-IDE-Examples-Directory-Assistance) - repository added without an error

Please, check.

**Comment by JoelProminic** [comment]
Going through the actions, I see that only Push and Pull are working properly:

Feature | Status
--------|-------
Add Repository | "You need Git installed on your system"
Clone | Won't trigger in Manage Repositories
Git > Pull | Works
Git > Push | Works
Git > Commit | Allow Access prompt
Git > Switch Branch | Allow Access prompt
Git > Status | Allow Acces prompt
Git > New Branch | Allow Acces prompt

**Comment by rat-moonshine** [comment]
You probably still needs to update the matrix since the fix, @JoelProminic (?)

**Comment by JoelProminic** [comment]
Sorry, I meant to update the matrix after the Bamboo build was fixed, but it looks like I forgot to post my updates:

Feature | Status
--------|-------
Add Repository | Works
Clone | Works
Git > Pull | Works
Git > Push | Works
Git > Commit | Works
Git > Switch Branch | TODO
Git > Status | Works
Git > New Branch | TODO

**Comment by rat-moonshine** [comment]
I think I'd need to re-visit to check if we still requires "Grant Permission" on non-sandbox build. But this may take some time and it's better not to include the task part of this issue.

**Comment by JoelProminic** [comment]
I haven't seen the "Grant Permission" issue lately.  I think it is probably a remaining bug, but I'll close this issue  until it becomes a problem, or we can reproduce it consistently.
