### ISSUE TITLE
Git Integration Broken for Windows

### ISSUE THREAD

**Issue by JoelProminic** [Moonshine-IDE/Moonshine-IDE#969]
I noticed today that Moonshine reports an "Invalid path" error for Git on Windows.  It looks like this is because of the difference in file separators.

![image](https://user-images.githubusercontent.com/24532731/153048853-16535f6b-9362-4f4a-8ae9-1686c8d7f0bb.png)

If I try Git > Manage Repositories, it opens the Git settings page.

I suspect this was related to the macOS fix for #965.

**Comment by rat-moonshine** [comment]
![image](https://user-images.githubusercontent.com/24370870/153132656-3d1cc27f-799e-4bfe-bad0-2323c2bde29e.png)

This should be fixed now.

I also confirm Git's regular functionalities working usually, and `Git > Manage Repositories` also opens its expected window. 

Please, check.

**Comment by JoelProminic** [comment]
I confirmed that the error is cleared in the settings, and that I can clone a project properly on Windows.  I don't see an error on macOS either.
