### ISSUE TITLE
Find/Replace Restrictions for Visual Editor

### ISSUE THREAD

**Issue by JoelProminic** [Moonshine-IDE/Moonshine-IDE#972]
I tried to edit pom.xml in a Domino Visual Editor today, and I found that Replace was disabled in the Find panel.  @rat-moonshine helped investigate, and he found that Replace was specifically disabled for Visual Editor:

https://github.com/Moonshine-IDE/Moonshine-IDE/blob/master/ide/MoonshineSharedCore/src/actionScripts/plugin/findreplace/FindReplacePlugin.as#L125
https://github.com/Moonshine-IDE/Moonshine-IDE/blob/master/ide/MoonshineGUICore/src/moonshine/plugin/findreplace/view/FindReplaceView.hx#L283

I think this was originally added to disable Replace on in the visual editor tab.  For these files, a replace could have unexpected behavior.

So, I'd like to keep Replace disabled for the editor files, but enable Replace for the other files.  We could consider disabling it for visualeditor-src files as well, but I think this would be overkill - those files are supposed to be hidden.

**Comment by JoelProminic** [comment]
I also found that Edit > Find and CMD-F are disabled for all files in projects based on the Domino On Disk Project template.

**Comment by rat-moonshine** [comment]
I have enabled `Edit > Find` in OnDisk project type.

I also enabled to appear replace-field in all editors except Visual Editor types, and Domino Form Builder (in case of `.dfb` I noticed it was set to not open Find window at all. The behaviour remains same):

Editor Type | Shows Replace Field
-------------|--------------------
Visual Editor Flex | No
Visual Editor PrimeFaces | No
Visual Editor Domino | No
Form Builder DXL | Find window disabled
Any other editors | Yes

**Comment by JoelProminic** [comment]
I did some tests on macOS

File | Template | Find | Replace
-----|----------|------|--------
pom.xml | Domino On Disk Project | Yes | Yes
project.ondiskproj | Domino On Disk Project | Yes | Yes
src/main/formbuilder/project.dfb | Domino On Disk Project | No | No
src/main/visualeditor/project.dve | Domino On Disk Project | No | No
nsfs/nsf-moonshine/odp/Forms/project.form (text editor) | Domino On Disk Project | Yes | Yes
pom.xml | Flex Visual Editor | Yes | Yes
project.veditorproj | Flex Visual Editor | Yes | Yes
src/project.mxml | Flex Visual Editor | Yes | No
pom.xml | PrimeFaces Visual Editor | Yes | Yes
project.veditorproj | PrimeFaces Visual Editor | Yes | Yes
src/main/webapp/project.xhtml | PrimeFaces Visual Editor | Yes | No
pom.xml | Domino Visual Editor | Yes | Yes
project.veditorproj | Domino Visual Editor | Yes | Yes
nsfs/nsf-moonshine/odp/Forms/project.form | Domino Visual Editor | Yes | No

This should be good.
