### ISSUE TITLE
Allow All Supported Characters for Haxe Library Names

### ISSUE THREAD

**Issue by JoelProminic** [Moonshine-IDE/Moonshine-IDE#975]
@Aszusz [reported](https://github.com/Moonshine-IDE/Moonshine-IDE/issues/967#issuecomment-1036488153) that Moonshine did not allow underscores in the library names for Haxe projects.  For example:
1. File > New > Haxe Project
2. Select the Neko platform and create the project
3. Right-Click > Setting > Paths
4. Click "Click to add" under Libraries, and try "tink_core".  BUG:  Can not type an underscore.

I see that the [allowed characters for haxelib packages](https://lib.haxe.org/documentation/creating-a-haxelib-package/) are:  `A-Za-z0-9_-.`   Of these, I see that `_` and `.` are not supported currently.  I don't think that Moonshine should enforce the length restriction on the name here.

**Comment by rat-moonshine** [comment]
The Haxe LS throws error if we use `-` or `.` in its project name:

![image](https://user-images.githubusercontent.com/24370870/159449978-3ea67308-992d-4086-a5bc-4487840ce910.png)

@joshtynjala please provide your opinion if we should use the said special characters in project naming. I assume this may need to adjust the current LS process.

**Comment by rat-moonshine** [comment]
I have added `_` and `.` in acceptable characters for Haxe libraries input field. 

I tried with "tink_core", and it installs properly to the project.

Please, check.

**Comment by Aszusz** [comment]
I tested it on macOS and it works.

**Comment by JoelProminic** [comment]
I also did a quick test of the pattern and confirmed that I can build a Haxe Neko project with a reference to `tink_core` (example from description). This looks good to me.
