### ISSUE TITLE
On Disk Project - Instructions for macOS Security

### ISSUE THREAD

**Issue by JoelProminic** [Moonshine-IDE/Moonshine-IDE#980]
Reviewing On Disk Project with Justin today, we saw this error again:  https://github.com/Moonshine-IDE/Moonshine-IDE/issues/646#issuecomment-790966713

We need to guide the user on how to set this up.  After retesting this it seems sufficient to grant Full Disk Access to Moonshine and Moonshine Development, so that will make this step simpler.

For now, I would like to add this documentation to the bottom of the page for Moonshine > Settings > Domino and Notes Client

>### macOS Security Configuration
>
>On macOS Catalina or higher, you will need to grant Moonshine "Full Disk Access" privileges, or you will get errors like this:
>
>    : [INFO] java.lang.Exception: Notes initialization failure - err 258
>
>1. Open System Preferences
>2. Navigate to Security & Privacy > Privacy > Full Disk Access
>3. Click the checkbox next to the Moonshine.app entry.  If you use MoonshineDevelopment, it will also need Full Disk Access
>
>![image](https://user-images.githubusercontent.com/24532731/156464720-cc24ffec-c58e-414a-a1e1-21201ba8fe97.png)

For reference, may also need to grant Full Disk Access to "java" processes as well.  I confirmed it wasn't needed for On Disk Project, but I have used it with DXL Importer (#668)

**Comment by rat-moonshine** [comment]
Done.

**Comment by rat-moonshine** [comment]
Updates:

- Title style changed to match other title styles in instruction
- Error details used with fixed-width font

**Comment by JoelProminic** [comment]
I think this is fine.  The header is a bit small, but it fits with the rest of the interface.  We can tweak the appearance more later if necessary.
