### ISSUE TITLE
Cannot edit file after using find feature

### ISSUE THREAD

**Issue by Aszusz** [Moonshine-IDE/Moonshine-IDE#988]
I was setting up an ODP project on Mac, I used find feature on pom.xml, when I found a match and closed the find window I couldn't edit the file. I replicated the issue on Windows using also ODP and a pom.xml file. For now, I couldn't replicate the issue with other files/file types, but it's possible that other files are affected.

**Scenario:**
1. Create a new ODP project
2. Open pom.xml file
3. Search (Edit -> Find) for 'nsfodp-maven-plugin'
4. When you find a match close the window and try editing pom.xml file

**Result:**
Cannot edit the file. When you scroll to the top you may find the caret "trapped" on the first line of the file.

**Comment by joshtynjala** [comment]
Between these two commits, this issue should be fixed.

Moonshine-IDE/moonshine-feathersui-text-editor@ea56152ae7915ce50c390b29baf28405208786da
Moonshine-IDE/moonshine-feathersui-text-editor@a426d5a1c261097825540dc66a61f8846a84e4fd
