### ISSUE TITLE
Short-Term Improvements for Monitoring Language Server Instances

### ISSUE THREAD

**Issue by JoelProminic** [Moonshine-IDE/Moonshine-IDE#994]
From @JustinProminic,

>Please investigate whether you can modify the Java process name that shows up in Activity Monitor to better reflect what it is doing.
>
>https://stackoverflow.com/questions/4217947/setting-process-name-on-mac-os-x-at-runtime
>
>
>Here is an example Moonshine screen shot that is only loading Moonshine itself to edit it.
>
>The %CPU calmed down by the time I took this screen shot -- after the 9 different Java processes consumed most resources on my computer for a couple of minutes.
>
> <img width="1785" alt="image" src="https://user-images.githubusercontent.com/24532731/158226945-100feaa1-4c32-49a0-a26a-536411da6d84.png">
>
>
>It would be wonderful to at least see what they are for in the Process Name column.
>
>Something like:
>
>java language server for project: MoonshineWorker

UPDATE 2022/04/13:  I am going to refocus this issue on creating a basic interface to track the language servers.  For the original request, see #992.

Some features that we can consider for this interface:
- List the active language servers
- List the corresponding process ID (for kill/review in Activity Monitor, etc).  Since can't get the process ID from NativeProcess, we'll need to find another way to do this.
- Show any "Abandoned" language server instances (Not associated with any of the language server instances currently maintained by Moonshine)
- Buttons to kill/restart the language servers?
- Memory/CPU statistics?  We may be better off using Activity Monitor/Process Monitor to track this.

**Comment by JoelProminic** [comment]
@JustinProminic,

From some quick research, I don't see how to make the process display more information in Activity Monitor.

You could try to use "htop", but the process arguments are very lengthy:  https://ports.macports.org/port/htop/
1. Open Terminal
2. Run `htop`
3. Press F4 to filter
4. Type `language-server` to show only java language servers

![image](https://user-images.githubusercontent.com/24532731/158227366-db3216aa-c77b-4359-a467-8f132861f414.png)

Another option would be to build something based on the commands I used for these scripts (if I update these or make Groovy scripts, I should move them to a GitHub project):  https://github.com/Moonshine-IDE/Moonshine-IDE/issues/947

And display process performance using the ps options suggested here:  https://apple.stackexchange.com/questions/162154/how-to-show-command-of-a-process-in-activity-monitor

**Comment by JoelProminic** [comment]
@JustinProminic's original request has a separate issue in #992.  If we have a way to implement this in Activity Monitor, we can close this issue.

**Comment by JoelProminic** [comment]
I created a quick script for this.  It was simpler than I expected, so I decided to just add it in a `scripts/` directory in this repository.  We can move it if we don't like this location:  https://github.com/Moonshine-IDE/Moonshine-IDE/blob/b4f70a321c6052986d04a605142298214046cf1d/scripts/LanguageServerStats.sh

Example output.  The indenting is not good, but I didn't want to spend to much time trying to make it look pretty in bash: 

    % sh LanguageServerStats.sh
    PROJECT			PID	%MEM	%CPU
    MoonshineSharedCore:  84361  0.2 132.1
    MoonshineSDKInstaller:  84363  0.2 136.3
    MoonshineDESKTOPevolved:  84369  0.2 135.7
    MoonshineWorker:  84377  0.2 131.2
    MockupVisualEditor:  84379  0.2 124.6
    VisualEditorConverterLib:  84381  0.2 127.4
    InstallerSharedCore:  84383  0.2 127.6

I see the high CPU utilization on project startup.  Once all the servers are started, the load becomes more reasonable:

    % sh LanguageServerStats.sh
    PROJECT			PID	%MEM	%CPU
    MoonshineSharedCore:  84361  1.7   0.0
    MoonshineSDKInstaller:  84363  0.8   0.1
    MoonshineDESKTOPevolved:  84369  2.0   0.0
    MoonshineWorker:  84377  0.4   0.0
    MockupVisualEditor:  84379  1.5   0.0
    VisualEditorConverterLib:  84381  0.8   0.0
    InstallerSharedCore:  84383  0.6   0.0
    MoonshineGUICore:  84623  0.1   0.0

**Comment by rat-moonshine** [comment]
Is the [script](https://github.com/Moonshine-IDE/Moonshine-IDE/issues/994#issuecomment-1067246669) is something you were thinking to be used by Moonshine, @JoelProminic ? If yes, how you envisioned this to be use. 

We may need Windows' scripts as well if we wants to standardise the usage in Moonshine.

**Comment by JoelProminic** [comment]
@rat-moonshine, I added some clarification for this in the description.  This is probably going to be a future task unless we have an easy solution.

**Comment by rat-moonshine** [comment]
I'm starting to look into this. My idea is to add a new menu under `Edit` to trigger a new tab to console panel area. This new tab to display a grid with LS instance information as [asked](https://github.com/Moonshine-IDE/Moonshine-IDE/issues/994#issue-1168689383) using the [file](https://github.com/Moonshine-IDE/Moonshine-IDE/issues/994#issuecomment-1067246669) that creates by @JoelProminic .

However, there could be some restrictions to this feature:
1. I'm not confident at this point if we can close a process without using administrator privilege
2. Running `.sh` file may not work in Sandbox build (App Store) since unavailability of necessary entitlement. In that case the feature may available only in non-Sandbox build
3. I don't know an equivalent script on Windows if we'll have available. Until then this feature will only avail on macOS platform
4. LS information grid shall show only information that returns by the `.sh` file - Project, PID, Memory, CPU

**Comment by rat-moonshine** [comment]
![image](https://user-images.githubusercontent.com/24370870/164025325-871abe18-17be-4ed4-8681-2641ef22d1ef.png)

This looks good so far. We need to decide on how we wants to refresh this - through a context-menu option, or auto-refresh with intervals.

**Comment by Igazine** [comment]
Any chance we can modify the language server wrapper Java source code? Java itself can query and print out the spawned process' id.

```
class Main {

    public static void main(String[] args) {

        long pid = ProcessHandle.current().pid();
        System.out.println(pid);

    }

}
```

This simple java code started with `java Main.java` in terminal printed the process id to stdout (but stderr also works with `System.err.println(pid);`).

**Comment by joshtynjala** [comment]
We run the Java language server without modifications.  The AS3 & MXML and Groovy language servers are also written in Java, so all three could potentially find a way to pass the process ID back to Moonshine.

The Haxe language server is written in Haxe and is compiled to run on Node.js.

**Comment by JustinProminic** [comment]
@joshtynjala It makes sense to me to modify the Java Language Server to do what we need, rather than go to a lot of extra steps to get the PID.  Moonshine absolutely needs to know the PID of the processes it is spawning.

**Comment by JoelProminic** [comment]
We spent some time today discussing my script and the [initial implementation](https://github.com/Moonshine-IDE/Moonshine-IDE/issues/994#issuecomment-1102716486) by @rat-moonshine.

If we want to match the language servers detected by my script with the NativeProcess instances, we could do something like this:
- Update the script to return the full project path.  We may need the language server type as well to uniquely identify the language server.
- Match the language server processes to the NativeProcess instances by the project path (and type?)
- Any processes that don't match a NativeProcess would be considered "abandoned" instances.  
- @JustinProminic recommended that, for the initial implemnetation, we focus on reporting the process ID, and leave the CPU/Memory status to external tools.

Some problems:
- If there are multiple language server processes that match the same NativeProcess instance, Moonshine wouldn't know which one was active without more information (like the start time)
- We'll need to make a versio of the script for Windows.  I think we can use powershell for this
- This script may not work with the Apple Sandbox build.

**Comment by JoelProminic** [comment]
We discussed this issue in the Wednesday meeting last week, and agreed to use [the solution](https://github.com/Moonshine-IDE/Moonshine-IDE/issues/994#issuecomment-1104401417) proposed by @Igazine.  @Igazine started on these updates, and you can see the changes tagged above.

For Haxe, we see the language server [here](https://github.com/vshaxe/haxe-language-server).  I was expecting that we would need to clone the language servers to the Moonshine-IDE organization and make the small modification to the main class, but @Igazine seems hopefully that we can do this with a quick wrapper instead.

**Comment by Igazine** [comment]
The language servers with the printed PID are working with all the available language server types (Haxe, Java, Groovy and AS3MXML)

The newly printed PIDs are displayed in the Language Servers tab, so running the shell script is no longer needed (consequently it's working on Windows as well)

The previously on-demand query of language servers (and PIDs) are now event-based. New processes will show up, closed processes will be removed from the list.

Before pushing the changes, I have to ask @joshtynjala a question about the compiled server.js size to make sure nothing's missing.

**Comment by JoelProminic** [comment]
I updated the Bamboo branch builds to run on this branch:  `features/issue_994_language_server_monitor`

The builds are running now, but they should appear here.  The Windows build hasn't been used in a while, so I may need to do some cleanup:

Windows:  https://moonshine-ide.com/downloads/releases/dev/windows/branches/features/issue_994_language_server_monitor
macOS:  https://moonshine-ide.com/downloads/releases/dev/macos/branches/features/issue_994_language_server_monitor

**Comment by piotrzarzycki21** [comment]
> I updated the Bamboo branch builds to run on this branch: `features/issue_994_language_server_monitor`
> 
> The builds are running now, but they should appear here. The Windows build hasn't been used in a while, so I may need to do some cleanup:
> 
> Windows: https://moonshine-ide.com/downloads/releases/dev/windows/branches/features/issue_994_language_server_monitor macOS: https://moonshine-ide.com/downloads/releases/dev/macos/branches/features/issue_994_language_server_monitor

@JoelProminic both links doesn't work for me.

**Comment by piotrzarzycki21** [comment]
I don't mind merging that stuff to master and have proper development build which we all using.

**Comment by piotrzarzycki21** [comment]
Actually we should probably wait till upcoming release.

**Comment by rat-moonshine** [comment]
I would like to have this merged if soon possible since the updated interface will have a terminate button. Currently, I need to go into Activity Monitory to terminated unreleased servers each time during debugs (mainly).

**Comment by JoelProminic** [comment]
The macOS Bamboo plan wasn't updated to the correct branch.  I fixed this and triggered the build again.

Windows is failing with some strange error on an SVN project with some build scripts.   I'll need more time to debug this.

**Comment by piotrzarzycki21** [comment]
@Igazine merge master to that branch so I would have fresh build.

**Comment by Igazine** [comment]
master has been merged into issue_994_language_server_monitor

**Comment by piotrzarzycki21** [comment]
> ![image](https://user-images.githubusercontent.com/24370870/164025325-871abe18-17be-4ed4-8681-2641ef22d1ef.png)
> 
> This looks good so far. We need to decide on how we wants to refresh this - through a context-menu option, or auto-refresh with intervals.
> 
> Note: Conditions yet to be added to display the monitor option based on [above](https://github.com/Moonshine-IDE/Moonshine-IDE/issues/994#issuecomment-1102193907) criteria.
> 
> I also copied the `.sh` file location from `/Moonshine-IDE/scripts/LanguageServerStats.sh` to `/Moonshine-IDE/ide/MoonshineDESKTOPevolved/src/macOScripts`. We can delete the former.

@Igazine I have installed Moonshine from Joel's link and I don't see options to launch that tab with LS. Can you check ?

**Comment by piotrzarzycki21** [comment]
I'm installing this -> MoonshineDevelopment_Signed_NonSandbox.pkg

**Comment by Igazine** [comment]
Checking.

In the meantime please note that Memory and CPU tabs should be removed entirely from this tab, so there must be an issue with your build, it still uses the old shell script based solution, as there's no way to get memory consumption and CPU usage programmatically from Java and/or NodeJS. So those columns have been commented out entirely. (and 'PID' has been changed to 'Process ID')

<img width="1029" alt="image" src="https://user-images.githubusercontent.com/2218406/169987760-224519da-5502-4b61-97f5-216eab5d9ba9.png">

**Comment by piotrzarzycki21** [comment]
I had to remove Development version and than install this one - It has lower version number than the one build out of master.

**Comment by piotrzarzycki21** [comment]
@Igazine This branch contains also changes from Haxe conversion branch ?

**Comment by Igazine** [comment]
@piotrzarzycki21 one additional Haxe class has been added, which means CompileGUICore ant task must be executed during the regular compilation of the project.  This branch contains no other Haxe modifications from that separate branch

**Comment by JoelProminic** [comment]
The Windows build completed properly after the most recent update.   It is now available at the URLs above.  I didn't need to make any changes to the Ant command in Bamboo.

**Comment by JoelProminic** [comment]
I did some tests on macOS:

Test | Result
-----|-------
Actionscript Desktop Project | Works
Flex Desktop Project | Works
Java Maven Project | ERROR:  not reported
Java Gradle Project | ERROR:  not reported
Grails Project (Groovy - and Java?) | Groovy language server starts
Haxe Project | Works
Language servers from other/old Moonshine instances | Not displayed (not relevant with this implementation)
Gradle wrapper | Not displayed (not relevant with this implementation)

To clarify the Java case:
1. Create a new project with:  File > New > Java Gradle Project
2. Project opens, but no new entry shows up in Language Servers
3. Check `LanguageServerStats.sh`.  This shows that the language server is running
4. Open `src/main/java/<project>.java`.  BUG:  There are no tooltips for the language server - it seems the instance is not connected properly.

**Comment by Igazine** [comment]
An Eclipse-based JAR file has been updated in SharedCore, now it properly displays process ids for all the processes that have been started with this Java plugin

<img width="1032" alt="image" src="https://user-images.githubusercontent.com/2218406/170204913-cb43df8b-f28e-459c-8b0e-eb5c7c3f9633.png">

Currently the Jar (binary) has been updated in the repo, I'll commit the source files as well once I've created a proper Ant buildfile, so compiling this Java class can be added to the main buildfile if it's needed.

The source files are slightly modified versions of Eclipse's relevant classes and packages:
https://git.eclipse.org/c/equinox/rt.equinox.framework.git/tree/bundles/org.eclipse.equinox.launcher/src/org/eclipse

**Comment by Igazine** [comment]
Language servers after closing NewGrailsProject

<img width="1031" alt="image" src="https://user-images.githubusercontent.com/2218406/170209753-429ff8b5-4822-4a18-a49a-6196b970850b.png">

**Comment by Igazine** [comment]
**_[This is probably unrelated to this specific issue as it occurs in the current development build as well]_**

Creating a Java Domino project also starts the language server, but it looks like issue #937 is back in the following specific circumstances:

* Grandle has been installed by MoonshineSDKInstaller (Gradle version 5.4.1)
* OpenJDK v 11.0.10 installed by MoonshineSDKInstaller and selected as JavaSDK
* OpenJDK v 1.8.0u201 installed by MoonshineSDKInstaller and selected as Java8SDK

```
May 25, 2022, 10:08:17 AM Synchronize project NewJavaDominoProject failed due to an error connecting to the Gradle build.
Could not run phased build action using connection to Gradle installation '/Users/tamasimac/Downloads/MoonshineSDKs/Gradle/gradle-5.4.1-bin'.
org.gradle.tooling.GradleConnectionException: Could not run phased build action using connection to Gradle installation '/Users/tamasimac/Downloads/MoonshineSDKs/Gradle/gradle-5.4.1-bin'.
	at org.gradle.tooling.internal.consumer.ExceptionTransformer.transform(ExceptionTransformer.java:55)
```

Additionally there's an error displayed in Problems tab

<img width="740" alt="image" src="https://user-images.githubusercontent.com/2218406/170216931-a0f19f47-ced2-4008-8b48-69c81a47ea61.png">

**Note: I have multiple Java versions installed, so it may be a local error of how Gradle is trying to access Java, and it's possible it doesn't occur in other environments with default Moonshine configuration.**

**Comment by joshtynjala** [comment]
> Moonshine-IDE/Moonshine-IDE@2541819d8564063054071a35bcff90783b348fec

I notice that you seem to have modified one of the .jar files from eclipse.jdt.ls. We should try very hard to avoid that. Right now, if there's a new release of any language server that we use in Moonshine, I can copy/paste the binaries in, and nothing generally needs to be rebuilt.

Can you implement your modifications to the eclipse.jdt.ls in a separate wrapper .jar that delegates to the eclipse.jdt.ls .jar file?

**Comment by joshtynjala** [comment]
If needed, we can modify how files get copied to the application storage. We should probably keep the logic for copying the third party eclipse.jdt.ls files the same. I recall that I made Moonshine avoid copying these files every time the app launches because copying them all is indeed slow. However, copying the new wrapper (and any related files) could probably happen more frequently because they should be much smaller. We could potentially compare the file modification dates, if we want to ensure it doesn't happen too frequently.

**Comment by Igazine** [comment]
@JoelProminic please hold on with the tests until proper wrappers are in place. thank you

**Comment by piotrzarzycki21** [comment]
> @JoelProminic please hold on with the tests until proper wrappers are in place. thank you

How is going with this ? Will it be able to fix this before the meeting ? I don't remember if we wanted to have it merged to master for this release ?

**Comment by Igazine** [comment]
It's not ready to be merged yet, I have to create proper wrappers for Java and NodeJS. I'll update the issue today or tomorrow.

**Comment by Igazine** [comment]
### Java Language Server Wrapper

The wrapper prints the process id and starts the language server.

How to build: see [readme.md](https://github.com/Moonshine-IDE/Moonshine-IDE/tree/c43cc9425497852408b12a6a7fa4ae329b0fb05c/language-server-wrappers/moonshine-jdt). The  pre-built JAR file has been added to the repo, build only if it's necessary. 

### Haxe Language Server Wrapper

Haxe-based, the NodeJS process creates a child process with server.js. The child process' stdin, stdout and stderr will be inherited from the parent.

How to build: see [readme.md](https://github.com/Moonshine-IDE/Moonshine-IDE/tree/7fe12096e29a7e7696badb72a6369716922aee3f/language-server-wrappers/moonshine-haxe). The pre-built JS file has been added to the repo, build only if necessary. Update Haxe Language Server normally if there's an update available.

### Screenshot of working language servers and tooltip

<img width="1027" alt="image" src="https://user-images.githubusercontent.com/2218406/171061551-52100c5a-e962-41a7-8bd7-7af540a3bdcc.png">

**Comment by Igazine** [comment]
This branch has been merged into master
