### ISSUE TITLE
Avail Options to Create More File Types in OnDisk Project

### ISSUE THREAD

**Issue by rat-moonshine** [Moonshine-IDE/Moonshine-IDE#995]
From @JustinProminic ,

-----------------------

I'm working in a Domino Form Builder project.

I would like to be able to add everything to this one project.

That means from this project, I need to be able to create these file types:

- File
- Java class
- XML file
- CSS file
- Grovvy class

But these are all prevented -- please enable these to work in ANY project type since you never know when users want to combine technologies into one project / repository.

![image](https://user-images.githubusercontent.com/24370870/158318388-0bc4df0f-158d-46ee-83cc-90932c8e4a48.png)

**Comment by rat-moonshine** [comment]
I'm not so sure if we still wants to avail Groovy and Java class creations in project like AS3. However, one can create such files using `File` option.

For now, I'm availing file-types in following project-types conditions. We can discuss more on this if we wants a change.  

File Type | Availability in project type(s)
-----------|--------------------------
CSS, XML, File | Any
Groovy, Java | Grails, Java, OnDisk, Visual Editor Domino

**Comment by JoelProminic** [comment]
For now, just enable Java and Groovy files for the Domino On Disk Project.  Don't worry about language server support (we may revisit this later).

I created a separate issue (#999) for a separate idea I had for this but we agreed in the meeting today to stick with a simple update for now.

**Comment by rat-moonshine** [comment]
Then I assume this issue is complete based on the [changes](https://github.com/Moonshine-IDE/Moonshine-IDE/issues/995#issuecomment-1068804221) (?)

**Comment by rat-moonshine** [comment]
This should be fixed now. Please, check with newer builds.

**Comment by JoelProminic** [comment]
I confirmed on macOS Catalina that these projects have all the above types enabled:

Project | File > New | Right-click > New
--------|------------|------------------
Domino Visual Editor | Confirmed | Confirmed
On Disk Project | Confirmed | Confirmed
Grails | Confirmed | Confirmed
Java Domino | Confirmed | Confirmed
Java Gradle | Confirmed | Confirmed
Java Maven | Confirmed | Confirmed

I confirmed that these projects have entrys for File, XML, and CSS, but not Java and Groovy files.  I limited this to a few projects to keep the testing reasonable.

Project | File > New | Right-click > New
--------|------------|------------------
Haxe Neko | Confirmed | Confirmed
Flex Desktop | Confirmed | Confirmed
Away3D | Confirmed | Confirmed
