### ISSUE TITLE
Run Known Binary Files Without Prompting

### ISSUE THREAD

**Issue by rat-moonshine** [Moonshine-IDE/Moonshine-IDE#996]
Currently, double-clicking or opening any binary type of file from Moonshine follows this confirmation prompt:

![image](https://user-images.githubusercontent.com/24370870/158393895-b930b87d-1803-4907-a805-1f088c7e1a03.png)

We want to improve the usability by not triggering any confirmation prompt but open directly, for known binary file types.

Following are a few known file types that do not requires the prompt, we can update the list with more items:
- nsf
- png
- jpg
- jpeg

**Comment by rat-moonshine** [comment]
@JoelProminic

**Comment by JoelProminic** [comment]
@rat-moonshine, thanks for testing multiple file selection - I forgot that this was a feature in Moonshine.

I did some more tests.  I tried to test Windows an a Vagrant/VirtualBox VM.  However, running Moonshine and Notes at the same time hung the VM.  @Aszusz, could you finish the Windows test when you have a chance?

Extension | macOS | Windows
----------|-------|--------
.nsf | No prompt | 
.png | No prompt | 
.jpg | No prompt | 
.jpeg | No prompt | 
.bmp | Prompt | 
.class | Prompt | Prompt
.jar | Prompt | Prompt

**Comment by Aszusz** [comment]
@JoelProminic @rat-moonshine 
I finished the tests. It looks like the extension recognition is case sensitive so `.png` opens without a prompt but `.PNG` will prompt you.

**Comment by rat-moonshine** [comment]
This should be fixed now. Please, check.

**Comment by Aszusz** [comment]
I confirm this works for both lowercase and uppercase extensions.
