### ISSUE TITLE
Hang when Closing Moonshine

### ISSUE THREAD

**Issue by JoelProminic** [Moonshine-IDE/Moonshine-IDE#998]
@JesseProminic reported that MoonshineDevelopment has been consistently hanging when closing on macOS Monterey:

![image](https://user-images.githubusercontent.com/24532731/158682766-600d0a2c-9880-4589-a2df-fb0c526a9195.png)

I can't reproduce this on macOS Catalina.  @rat-moonshine, do you have any ideas about what could cause this?

The "SecurityScopeBookmark" reference makes me think this is an AppStore build.  I did a quick test with the AppStore build on macOS Catalina, but I couldn't reproduce the error.   If it is an AppStore build issue, then we probably won't fix this issue until we revisit the AppStore release, but this may be a new macOS limitation we need to investigate.

**Comment by rat-moonshine** [comment]
From Adobe documentation (https://help.adobe.com/en_US/FlashPlatform/reference/actionscript/3/runtimeErrors.html):
**Error#3500** - The extension context does not have a method with the name %1.

However, this doesn't fit correctly with my understanding to the codes what we have: https://github.com/Moonshine-IDE/Moonshine-IDE/blob/master/nativeExtension/SSB/obj-c/SecurityScopeBookmark/SecurityScopeBookmark.m#L120.

Furthermore, if this triggers only in certain OS, this trouble me. 

I need some more information before building any thought. 

"SecurityScropeBookmark" may calls in non-AppStore build as well during Moonshine exit. So @JesseProminic can you please share using Moonshine's version details by going into `Help > About`. As an example,
![image](https://user-images.githubusercontent.com/24370870/158741889-7bee843f-cbf4-4aa7-b1b5-f02875604a03.png)

If the version information states "(App Store Version)", then please go to `File > Access Manager > Revoke All Access` - and let me know if this throws you any error to console on macOS Monterey. **Note:** if this executes without any error then you may clear-out all previously accessed paths to your system folders from Moonshine, you may need to re-browse your project directories using file-browser again.

**Comment by JesseProminic** [comment]
This is what I have currently. 

<img width="909" alt="Screen Shot 2022-03-17 at 10 49 05 AM" src="https://user-images.githubusercontent.com/96078188/158839248-a2c76d5c-edfc-4ec8-bf2c-5d6ef559b108.png">

**Comment by rat-moonshine** [comment]
Thank you @JesseProminic . If you please provide information to this part as well:

> If the version information states "(App Store Version)", then please go to File > Access Manager > Revoke All Access - and let me know if this throws you any error to console on macOS Monterey. Note: if this executes without any error then you may clear-out all previously accessed paths to your system folders from Moonshine, you may need to re-browse your project directories using file-browser again.

**Comment by JesseProminic** [comment]
@rat-moonshine 

>If the version information states "(App Store Version)", then please go to File > Access Manager > Revoke All Access - and let me know if this throws you any error to console on macOS Monterey. Note: if this executes without any error then you may clear-out all previously accessed paths to your system folders from Moonshine, you may need to re-browse your project directories using file-browser again.

I followed your direction and the App Store version is not throwing any errors. Also I am able (Monterey 12.3) to close the App Store Version with no problem.

**Comment by rat-moonshine** [comment]
@JesseProminic please give a test with newer Development build version >=2445.

**Comment by JoelProminic** [comment]
@JesseProminic reported a similar error on startup.  This may be a separate issue, though:

![image](https://user-images.githubusercontent.com/24532731/159747365-aec364b2-7055-473c-b4a9-df9fede2c64b.png)

**Comment by rat-moonshine** [comment]
Some updates on this. 
I see a few ways forward:

1. Modify Ant build process to ensure that `CONFIG::OSX` never triggers unless a sandbox run. But this also will introduce a lot of process additions and managing at Ant side. I'm not very keen to go by this path at this moment
2. Doing more investigation in the ANE codes. I don't want to mess with the existing codes either at this point neither I have Monterey to test, so can't go by guesswork
3. Try to understand and see if this triggers for every Monterey users

At this point, I feel 3 is the best option to go for. I don't found a strong reason why the startup error starts suddenly for @JesseProminic when there were no changes in startup process recently. That makes me think we need more test results on this.

I requested @Aszusz and others to test the scenario on Monterey if they has. @Aszusz confirmed that he's not seeing any error in his Monterey tests during startup or shutdown. 

I don't have a strong opinion why this could trigger in certain system.

**Comment by JesseProminic** [comment]
<img width="1434" alt="Screen Shot 2022-03-30 at 11 04 41 AM" src="https://user-images.githubusercontent.com/96078188/160880529-d740d766-33d1-4327-8d90-4ab38f946ee7.png">


After I updated it, the window came up like this, which happens occasionally. When I readjusted the window size, it returned to the standard view.

**Comment by JoelProminic** [comment]
I moved the remaining error to #1011 so that I could close the updates for the 3.3.2 release.
